### ISSUE TITLE
Crouch Jumping

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#100]
I always wanted to disable crouch jumping as it often leads to all those jumps, that you'd then just have to wall off with invisible walls. If crouch-jumping was disabled, it'd basically make railings actually block you from jumping over, just like general Zombies map design (to prevent shortcuts everywhere, make it more close-quater). You see this everywhere in CoD zombies maps. But the question I've always wondered would be how would it work?

Should I make it impossible to crouch while in the air, or should I change the crouch hull (collision size) to be lower than you if in midair? The first one can potentially break some wanted jumps (although zombies can't crouch, so maybe not?), while the second will make you land on a little "bump" as you land crouched, since your collision is lower (it just feels wierd), and you can also get stuck in the ground (can probably be prevented).
And should this be a config map setting? A convar that defaults to on? Or maybe even a permanent feature (possibly able to be stopped with map scripting if absolutely needed)? Or maybe I shouldn't even disable it at all?

What's you guys' take on this?

**Comment by minin43** [comment]
Just decrease jump height? Or would that not work?

**Comment by Zet0rz** [comment]
I tried that and lowering to the point where crouch jumping is as high as normal jumping just makes normal jumping look like you're jumping 5-10 cm in real life lol

**Comment by func-octo** [comment]
why not disable jumping altogether like in WAW?

**Comment by Zet0rz** [comment]
> why not disable jumping altogether like in WAW?

There's jumping in WaW? And I can't disable it alltogether, that would both be annoying in-game and also disable a few needed areas and generally lower map compatibility.

**Comment by func-octo** [comment]
Well I meant that there isn't, but there's a mod for it. Completely gamebreaking as you might imagine. And to your second statement, that would be true. I would still add 'Disable Jumping' as a setting though.

**Comment by func-octo** [comment]
P.S. I have an open pull request :) :pager:

**Comment by lolleko** [comment]
Maybe a cvar, but honestly such a feature would break more than it would fix lol. Zombies can make almost any jump a player can make if the navmesh is edited good enough.

**Comment by Zet0rz** [comment]
It's not so much that zombies can't follow, it's more to avoid the annoying work to invisible-wall off almost all railings in a map. Even though zombies could jump over them too (although it takes a hell of a time of you wanted to place navmeshes on top of all of them so they know they have to jump and not just drop through), this would make maps more open and much easier to train them, removing a lot of the difficulty in surviving high up.

**Comment by minin43** [comment]
> this would make maps more open and much easier to train them, removing a lot of the difficulty in surviving high up.

Can confirm, you have to wall off just about everything, or players will jump on top of absolutely anything they can find.

**Comment by Alig96** [comment]
Its why I made the invisible wall tool in the first place. If it doesn't fix the problem, then there is a fundamental problem to the invisible wall tool itself.

**Comment by Zet0rz** [comment]
@Alig96 Invisible walls are still highly useful for all sorts of other stuff, this is just a general annoyance to have to go through all the time, so it could be disabled it'd save a lot of work.

**Comment by minin43** [comment]
@Alig96 I don't feel like there is a fundamental problem with anything, it's just that eliminating player's ability to crouch-jump is a nice shortcut

**Comment by Alig96** [comment]
I'm on mobile which is why I'm not quoteing correctly.

What else are they useful for? They are there to stop players going where they're not intended to go, what else? What im saying is if its annoying to use the tool, make it easier maybe mark an area of a bounding box bottom left corner and top right corner of the area you want to block and have a small system work out how many blockers to put inbetween

**Comment by minin43** [comment]
@Zet0rz Is suggesting we find a way to eliminate crouch-jumping to undesirable places entirely, that way we don't even have to touch the invisible wall tool. Yea it has it's uses, and I'm grateful it exists, but finding a workaround would save a LOT of time (especially on really big maps).

**Comment by Alig96** [comment]
And what me and lolleko are suggesting is that the zombies can make the same crouch jumps, the problem is where the players are allowed to do it. If I'm understanding lolleko then they can crouch jump to areas too, which in theory is fine. The problem is where the players are allowed to. Now i understand what you're saying that it makes it easier not to have to do it all, but there's what im saying the problem is. The wall blocker isn't doing its job properly.

**Comment by Alig96** [comment]
The change im suggesting is similar to how this is displayed https://steamcommunity.com/sharedfiles/filedetails/?id=268191276

See how he clicks 3 areas and the area is selected and shown how big it is? Something similar should be done for the blocker tool so it only takes a second to block off an area a player shouldn't be allowed to get to.

**Comment by minin43** [comment]
Many, MANY places players can crouch-jump to don't have any nav stuff there. There aren't any of the boxes connected to one another on this areas because they were never generated. If your response to that is:

> Well make them yourself

Why do that, when blocking the area off takes even less time then that? Especially considering the fact that nextbot AI is buggy and shitty.

But then you can take that even further by finding a workaround so that you don't even need to block those areas off, and then you see we're back to where we are now.

**Comment by Zet0rz** [comment]
@Alig96 @minin43 Both of you have very valid points. Yes, the fact that this solution is desired _does_ mean that the Invisible Wall tool isn't doing everything perfectly. But the thing that is bad about it isn't so much the time it takes, but more the accuracy it does. If two invisible walls are placed just 1 single unit further in or out from each other, you can get stuck on those edges. Moreso, a single unit offset from the railing it's covering can make you able to jump on that railing or get stuck under it, depending on which way it is offset. Oh, and then it takes **an awful** lot of time.

I'm gonna give a shot at an improved Invisible Wall Tool v2 which would work where you shoot corners and generate invisible walls of any dimension. If that doesn't work, I might look into an easy way to align the walls with each other. And finally, if none of them work properly, probably disable crouching when in midair along with a convar.

**Comment by Zet0rz** [comment]
This problem should be virtually fixed with the new Invisible Wall tool. The only places this won't make a quick deal of it is on diagonal areas. Those few areas can be solved with normal invis blocks, so it's fine.
