### ISSUE TITLE
Wunderfizz Machine(?)

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#101]
Just reading what all the perks do on the wiki, but noticed an extra perk named the Wunderfizz Machine.

http://nazizombies.wikia.com/wiki/Perk-a-Cola

Doesn't seem to be included

**Comment by minin43** [comment]
It's not a bad idea to add it in, but it is a map-specific machine.

I also see a lot of other unused perk machines that could also be used, but I guess I don't know what resources @Zet0rz has access to.

**Comment by Zet0rz** [comment]
I am definitely aware of Der Wunderfizz, but as @minin43 said, I only have access to WaW content and what's on the workshop already. However I have seen Der Wunderfizz in a WaW custom map and I think I found someone made a download with it for WaW which may contain the models. I just haven't checked yet as I felt the other models had priority. Right after the Bowie I want to look into this. 

> I also see a lot of other unused perk machines

The only one I am aware of other than this that I am missing is Widows Wine. I haven't seen it anywhere though, but I may look into seeing if I can get it after Der Wunderfizz.

**Comment by minin43** [comment]
@Zet0rz Look at the wiki link, at the bottom. There were some perks that had never been implemented.

**Comment by Zet0rz** [comment]
@minin43 Yeah won't implement them. Both because they don't even have models, also because they were scrapped because they were OP or just didn't work.

**Comment by func-octo** [comment]
My friend has bo2 origins dlc, he is trying to move it off his xbox onto a flash drive and onto a computer to see if it is the correct files. Within the week I might have results.

**Comment by Alig96** [comment]
Just because I'm interested, what is the widows' wine?

**Comment by Zet0rz** [comment]
@Alig96 http://callofduty.wikia.com/wiki/Widow's_Wine

**Comment by Alig96** [comment]
Interesting... I can't help but think that perk is a little... uhh.. strange. Also from the wiki again, I remember seeing the jingles any plans to implement them? However i don't remember hearing the jingles past the first dlc map for waw

**Comment by Zet0rz** [comment]
> I remember seeing the jingles any plans to implement them?

The jingles are all already there. Although only the on-buy versions. I don't think I will be bringing the full jingles in the official gamemode, as they just play randomly anyway and you rarely notice them, plus it's extra files which are each a minute or two long.

Someone could easily create an extension that does this though, just running a Think hook to loop through all perk machines if their `perk.NextJingleTime` is less than `CurTime()` and play it and then set a random `NextJingleTime`.

**Comment by Zet0rz** [comment]
Collecting all missing model parts into one issue #130
