### ISSUE TITLE
Accurate Perk Cost

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#102]
So taking a look at a previous issue which was just opened up, I see that Deadshot Daiquiri costs more than it actually does. Can we switch around the cost of the machine to the correct value, 1,000? Here's the link: http://nazizombies.wikia.com/wiki/Perk-a-Cola

**Comment by Zet0rz** [comment]
I am aware it costs 1000 on PC but that is because PC doesn't have an aim assist so the entire main point "aiming at the head" is removed. I coded in a sort of aim assist, so I felt 1500 was most appropriate. However it is only run once when aiming, so it may be less powerful and would justify 1000 (since you don't get hip fire or ADS speed either). That's some balancing questions we'll need to playtest for.

**Comment by minin43** [comment]
It's hard to find good spots to use this though. It takes a bit of falling before taking damage. I feel like 1k is appropriate for how little it does in gmod.

**Comment by Zet0rz** [comment]
@minin43 I think you're talking about PhD? Deadshot gives you aim assist, not fall damage related explosions. But I can change the falldamage function to damage a bit more, it's a bit forgiving atm.

**Comment by minin43** [comment]
Derp.

Yea, I meant deadshot.

But that doesn't sound like that bad of an idea, either. PhD is really useless.

**Comment by lolleko** [comment]
Maybe let the map script creator set the price of a perk machine, I think that would be cool.

**Comment by Zet0rz** [comment]
> Maybe let the map script creator set the price of a perk machine, I think that would be cool.

I actually added that functionality together with the Solo Quick Revive thing, it's what sets it to 500 and updates back to 1500 if another player drops in. You can do `perk:SetPrice( int )`. I also changed the system to this internally anyway.

**Comment by lolleko** [comment]
Oh lol didn't notice. Is it also implemented in the tool menu & context menu.? Also can you have multiple perk machines of the same type with different prices? (I know it does work like that in cod, but I have some scenarios in mind where this could be useful)

**Comment by Zet0rz** [comment]
> Is it also implemented in the tool menu & context menu.?

No and I won't do this as I don't want to encourage things that aren't like in CoD, that includes price on Random box as well. However if you really want to, you can create a map script with it. I keep stuff like that to scripting so it is only done by those who reaaally want to.
