### ISSUE TITLE
Server console being spammed with messages

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#106]
![untitled](https://cloud.githubusercontent.com/assets/7705215/14369323/b15b1dda-fce9-11e5-9076-ec2716228e84.png)

The server also crashed when I got downed. Damn.

**Comment by minin43** [comment]
I played some more with a friend and the game didn't crash when we all went down.

I think it might have had something to do with solo quick revive.

**Comment by lolleko** [comment]
Okay, do you have anymore info on how to recreate this issue?

**Comment by Zet0rz** [comment]
I know there's another short circuit in the zombie AI, I came across it when I spawned a Hellhound on the side of one of the buildings in gm_construct very high up. As to the spam, that was a debug line I didn't comment out. I already did on my end, just didn't update it.

**Comment by minin43** [comment]
I couldn't find anything, as console was being spammed with those messages.

Once the fix to that is pushed, I'll do more testing. I've got quite a few maps lined up.

**Comment by Zet0rz** [comment]
> Once the fix to that is pushed, I'll do more testing.

See commit 81ececf58b144cda2ef29321ded2f7aab76b4349 for the message spam. See commit 448ed2ed1c00502602d81b82c74ed3f6d59e1742 for the short circuit fix.
