### ISSUE TITLE
Add Zombie NAV_JUMP awareness back.

### ISSUE THREAD

**Issue by lolleko** [Zet0rz/nzombies#108]
In a very early state the zombies would jump if entering a navmesh with the NAV_JUMP flag set. This should be added back. With this zombies could make very difficult jumps, with proper nav editing.

**Comment by minin43** [comment]
PLEASE.

I NEED THIS.

NAV FILE GENERATION SUCKS ASSSS

**Comment by Zet0rz** [comment]
> NAV FILE GENERATION SUCKS ASSSS

This has nothing to do with nav generation, in fact to benefit of this it requires you to edit it. I don't think the generator ever adds NAV_JUMP flags. Correct me if I am wrong though.

**Comment by minin43** [comment]
I mean: a simple nav_generate command does a poor job. In lots of cases, you have to do HEAVY editing to the nav file before it functions as you would want it to.

**Comment by Alig96** [comment]
I would be glad that nav generate does what it does, would hate to not have the generator and have to do it ALL instead of just editing

**Comment by minin43** [comment]
@Alig96 Of course, doing it all by hand would be a total bitch, and for that I am grateful. But the command ain't perfect, either.

**Comment by Zet0rz** [comment]
> PLEASE.
> 
> I NEED THIS.
> 
> NAV FILE GENERATION SUCKS ASSSS

What I meant was that no, this feature won't help you with nav generation, so I think you misunderstood what this feature would actually do xD

**Comment by minin43** [comment]
ebhgaerherherr

I understand that!

I'm saying: nav generation sucks! Without editing, zombies get stuck everywhere!

If this command does as I'm thinking it does, then this'd be useful for telling zombies when they need to jump, and that would be extremely useful, because the jump thinking is bad.

**Comment by lolleko** [comment]
> because the jump thinking is bad

lol thanks :D You can use the `nav_jump` and `nav_no_jump` commands to set this flag while in nav_edit mode, but as of now it doesn't do anything. Jump areas must/should only have 2 adjacent nav areas, so that the jump area serves as connection between the low and high area (https://developer.valvesoftware.com/w/images/e/e5/MaximumJumpCrouch.jpg). I will probably make a advanced nav editing tutorial at some point for stuff like this.

**Comment by minin43** [comment]
I'm experienced with nav editing, but I don't know everything. I'd appreciate it.

**Comment by lolleko** [comment]
Added in #117 see https://github.com/Zet0rz/nzombies/wiki/Advanced-Navmesh-Editing#jumping for a quick guide.

**Comment by lolleko** [comment]
I will keep this issue open for now, since there is still a bug in the zombie jumping, where zombies will jump "down" areas they should only jump "up".
