### ISSUE TITLE
Invisible Wall Tool v2

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#109]
A new invisible wall tool that works by shooting the positions you want the walls to be in.
They need to be physgun'able to be rotated.

**Comment by minin43** [comment]
You'll want it to be a 3-click thing. 
Once for starting position
Once for horizontal stretch
Once for vertical stretch

**Comment by Zet0rz** [comment]
![](http://i.imgur.com/qHaXFfV.jpg)

Picture of the thing right now. It is a 3-click process, one for origin, one for x and y (flat), and one for height. It is very easy to fill out an entire area with no edges like this.

**Comment by minin43** [comment]
Please keep the old ones in as well

**Comment by func-octo** [comment]
Yes, I agree. Keep the old ones as well :)

**Comment by Zet0rz** [comment]
Looks like rotating won't work really well. The physics box it generates is aligned to the world. The old invis tool will definitely stay because of this, but if it gets fixed I may replace them (only if this one can rotate the boxes like any other box).

In the case that happens, I will try to add backwards compatibility by loading all the models' sizes in and generating these based on that.

**Comment by Zet0rz** [comment]
Added in commit baae3c45e14e02826371043aeb688e0a9678afc1. Should definitely make blocking off large railings and/or areas much easier. Most map parts are world-aligned anyway. If I can get this working with rotation, I will add that functionality, but that would be later. For now use the old invis tool for those diagonal ones.
