### ISSUE TITLE
@Zet0rz - An nZombies 'flyer'

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#110]
For the home page on the wiki I was thinking of coding some html, taking a screenshot, and you could make it the home page. Here's what I have so far if you are interested. 

A little fact about me:  I know a lot of HTML and CSS and have started redesigning www.falconkits.com, but have only just started learning LUA

Either download and open or use Editey (Not recommended)
https://drive.google.com/file/d/0B1xHaGAsFiwgaUZMVXEtMnVjRnM/view?usp=sharing

**Comment by Zet0rz** [comment]
I don't really think a garry's mod gamemode needs a website unless it's hosting things, I'm not entirely sure what you want to do with this :/

**Comment by func-octo** [comment]
Lol, I could see how you think that. What I mean is I'd like to make graphic for the wiki home as a png, but I'll use HTML to make it because it's much more precise than photoshop. I just need you to write the body of it where it explains what it is and such.
