### ISSUE TITLE
Drawing Wallbuys (Enhancement)

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#113]
Like in buried in BO2, you can get chalk drawings of items then draw it on the ?. It rewards you with 1000 and if you draw the final one, you get 2000 points.

**Comment by Zet0rz** [comment]
Should be fairly easy to make, but I'll probably put it low priority, maybe not even before workshop release.

**Comment by lmao5677** [comment]
Ok, if that's up to you then.
