### ISSUE TITLE
More Zombie Types?

### ISSUE THREAD

**Issue by Omnipotiontated** [Zet0rz/nzombies#115]
So far theres the Zombie, Napalm Zombie, and Hellhound
Are we going to see others like a Crawler Zombie, Zombie Monkey, Shrieker Zombie, etc.
And maybe even bosses such as The Panzer and George Romero?

**Comment by minin43** [comment]
@Zet0rz doesn't have access to those models, so if someone has BO/BO2, they can probably give him the resources.

**Comment by func-octo** [comment]
I recommend a zombine-type zombie with a chance to hold a live grenade and suicide when it explodes.

**Comment by minin43** [comment]
@ScriptnLua The zombies that explode when you kill them are already close enough to that, no?

If anything, I'd like to see a bit more of a focus on difficulty increase when the power turns on.

**Comment by Zet0rz** [comment]
I definitely want to do this and I might be able to get the resources for WaW because a lot of people are converting stuff back down to that game for custom maps. I'm just not sure how to implement them. Like how do you define how often they appear or what type of specials will appear? The only real way I can see is with map scripts. Thoughts?

**Comment by minin43** [comment]
I have BO3, do you need any resources from BO3?

**Comment by Zet0rz** [comment]
> I have BO3, do you need any resources from BO3?

Hmm, I'm not sure. I didn't really like the aliens from Shadows of Evil, so probably not any of them. Things we need atm are Der Wunderfizz on/off/away, all perks after WaW's off models, death machine weapon and viewmodel, fire sale model, Widows Wine if possible. After that, there's of course models that we don't need but would be cool like the newer Hellhounds or Zombies from Der Eisendrache.

Are you able to extract any of these models? I am currently using WaW's map editor to try and get community-ported extensions that include all these perks and the death machine and so on, so I'll probably be able to get them myself if you can't :)

**Comment by minin43** [comment]
@Zet0rz If you can point me in the right direction I'll see what I can do. I just don't know where to look for an extraction tool.

**Comment by Zet0rz** [comment]
I've got no clue on BO3 either. The best I can point you out is to google it lol

**Comment by func-octo** [comment]
I use Lime or Lemon to extract models. It doesn't support BO3 though :\
http://tom-crowley.co.uk/downloads/
