### ISSUE TITLE
Zombie Crawlers?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#120]
In the CoD games, you could use grenades to blow out a zombie's feet, leaving only a torso and arms, creating a zombie crawler.

Is this functionality available to us to make use of as well? The HL2 headcrab zombies had this functionality

**Comment by Zet0rz** [comment]
Not in the base models, but I am able to extract and rig the crawler models and their animations, then manually change their models when they get blown up to that of crawlers. It will take some time though and I will only do it after all the other models I have to work on, if at all before workshop.
