### ISSUE TITLE
Nav Editor Tool

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#121]
An actual tool that will make it possible to edit the navmesh in-game. It'd need a fancy GUI in the Q-menu, including seperating "nav_save" and other permanent commands into a "dangerous" area. This tool needs to be able to do almost all nav_ commands. It should only be available in singleplayer games.

**Comment by Omnipotiontated** [comment]
There is already a Navigation Mesh Editor on the workshop, I use it in sandbox to edit the Navigation and it works great. I'm sure its created by Robotboy

**Comment by Alig96** [comment]
Yes, the but this is to add it natively to nzombies so you dont have to go to sandbox.

**Comment by Zet0rz** [comment]
> There is already a Navigation Mesh Editor on the workshop, I use it in sandbox to edit the Navigation and it works great. I'm sure its created by Robotboy

That is the one we're trying to replicate the functionality of. It would be really helpful to be able to do it in-game as you can see the props you placed in the gamemode here. Otherwise you'd have to go into sandbox and try and remember where the props were and how big they were.

**Comment by lolleko** [comment]
To be honest the fastest way to edit a navmesh is a bind config not a tool.

> bind "MOUSE1" "nav_begin_area"
> bind "MOUSE2" "nav_end_area"
> bind "r" "nav_delete"
> bind "o" "nav_connect"
> bind "p" "nav_disconnect"
> bind "k" "nav_splice"
> bind "m" "nav_merge"
> bind "u" "nav_split"
> bind "c" "nav_simplify_selected"
> bind "l" "incrementvar nav_snap_to_grid 0 2 1"
> bind "j" "nav_jump"
> bind "h" "nav_no_jump"
> bind "n" "nav_flood_select; nav_toggle_selected_set"

**Comment by Zet0rz** [comment]
Probably, but a tool is much more nice, you don't have to unbind everything or be scared that you accidentally do stuff (the only undo is reload), and you also don't have to mess with game configs.

We should make the tool regardless.

**Comment by minin43** [comment]
I don't want to rebind everything

**Comment by lolleko** [comment]
Yes I agree a tool is defiantly better for newbies. But if you are somewhat good at nav editing and want to be efficient, a config is definitely the best. I use a modified version of this https://developer.valvesoftware.com/wiki/Nav_mode.cfg (so if you are advanced check it out). If not the tool will be included soon.

@minin43 you won't have to rebind anything if you set it up correctly. Regardless i understand your concern.

**Comment by lolleko** [comment]
Added in #132. Could still have some minor issues. Please report any issue here.

**Comment by Zet0rz** [comment]
If there are issues with the Nav Editor tool, post them in a new issue.
