### ISSUE TITLE
The official nav meshs don't load.

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#122]
Title. They don't load from the folder they;re in at the moment, you have to move them to your maps folder manually which is a small issue.

**Comment by Zet0rz** [comment]
I think it is a gmod bug that was fixed in the March Update which was then reverted. See https://github.com/Facepunch/garrysmod-issues/issues/1455. Not sure when we'll get this fix in the live branch

**Comment by minin43** [comment]
I read through that link, and the OP updated with this:

> Update: I have found that packing the nav mesh into the map file using VIDE or similar will work, as long as the map is only packed once. Packing more than once will apparently corrupt the map file somehow - obviously not the fault of Garry's Mod. This explains why my previous attempts to pack were unsuccessful - I had packed custom content earlier, then added the nav file later. Still, the nav file does not load if packed on its own into a .gma, so I will leave this thread up as it appears to be the only entry concerning this issue on this database.

**Comment by Zet0rz** [comment]
I'm sure I've seen it on the changelog for the March Update, but it's now gone.

**Comment by lolleko** [comment]
http://wiki.garrysmod.com/changelist/

> FIX Navigation meshes can now be loaded from within addons

**Comment by minin43** [comment]
Sweet
