### ISSUE TITLE
Electric Cherry doesn't work

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#123]
[ERROR] addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/function_override/sh_meta.lua:108: attempt to index field 'Effects' (a nil value)
1. v - addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/function_override/sh_meta.lua:108
   1. unknown - lua/includes/modules/hook.lua:84
   2. SetAnimation - [C]:-1
      1. unknown - workshop/lua/weapons/fas2_base/shared.lua:450

**Comment by Zet0rz** [comment]
Lolle updated the effects module to use a single table but didn't change it in the places it was used. Done quickly in 47cc8137a642e7ee8b0b2624d0399f79a3f9cd1c
