### ISSUE TITLE
Creative Functionality Improvements

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#125]
Rather than Creative Mode being applied automatically to all Superadmins upon entering that mode, it should be individually set for each player. E.g. an admin going to Creative mode should not bring all other admins in, only himself. Every admin will then be able to drop in and out individually. 

We'll also want admins to be able to give other non-admins creative mode, as well as a "Trusted" status which acts as a sort of permission to do more "dangerous" stuff such as cleaning, saving, loading. Alternatively the Trusted status could be required to do anything at all; leaving non-trusted players only able to run around the map.

**Comment by Alig96** [comment]
You should just make some basic permission hooks. Then the server owner can choose their own admin system and just hook it up. I.e

OnChangeMode( ... )
if player is admin then

OnDropInCreative

**Comment by Zet0rz** [comment]
Stuff like `if hook.Call("nzPlayerCanGoCreative", nil, ply) then` could work. We could also use `PlayerCanUseTool` but we'd need networking for that to make it update client-side in the Q-menu.

But what I was thinking was just a simple trust system with 1 or 2 levels of trust, where each gives permission to do certain things. Since Creative Mode is more often used in single player or passworded lobbies, while public servers would want to stay in Survival Mode, it's not really necessary to add too many hooks that determine permissions. 

Hooks like `OnPlayerCreative` and `OnModeChange` however are some useful hooks we can add.

**Comment by Zet0rz** [comment]
The upcoming update changes how creative mode is handled. Players are individually put in creative, and the first to join or the last to go will toggle the round state. The toolbar has got Creative button at the top, and the previous button has been replaced with a way to toggle creative on any player (if the player is admin)

Screenshot:
![](http://i.imgur.com/DDTkhAn.png)

**Comment by Zet0rz** [comment]
Added in commit 2341c9d712ad612d2c18e16821a71bc701b71115
