### ISSUE TITLE
Zombies don't despawn

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#126]
Zombies don't despawn when fully submerged in water (or sewage, in my case). Whatever's been implemented doesn't work for me.

**Comment by lolleko** [comment]
It's probably map related. Maybe the water level was not setup correctly by the map creator.

**Comment by minin43** [comment]
Well it isn't water, it's damaging sewage. Is that treated differently?

**Comment by lolleko** [comment]
I guess so at least its not `CONTENT_WATER`, which is used to test if a zombie is underwater (http://wiki.garrysmod.com/page/Enums/CONTENTS). Maybe its slime? Idk whats the map's name maybe i can figure it out and make them despawn in there aswell.

**Comment by minin43** [comment]
zs_sludge

**Comment by lolleko** [comment]
Can you look at the sewage and execute `lua_run print(bit.band(util.PointContents(Entity(1):GetEyeTrace().HitPos),CONTENTS_SLIME))` and tell me what it prints?

EDIT: I tested it myself, it is actually flagged as CONTENT_SLIME not CONTENT_WATER I will enable zombies to despawn in slime aswell very soon.

**Comment by lolleko** [comment]
Added in #133. Zombies should now despawn in slime/sludge. Needs testing tho.
