### ISSUE TITLE
Major Easter Egg System

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#128]
A system that would make handling Easter Eggs easier in Map Scripts. Instead of tons of booleans and checks, the system would run in a **Step-based** system. In map scripts you would create these steps and what they do when achieved. The system would then auto-increment the current step to allow the next to be completed. The system would auto-block CompleteStep functions for steps that we currently aren't on, meaning you won't have to do a whole lot of boolean checks to check whether it is even valid.

Functions would be like these:
`EasterEgg:AddStep(func OnComplete)`
`EasterEgg:SetStep(int step, func OnComplete)`

Using it in a map script would then be fairly simple. Say, you have a button that when pressed completes Step 3. You'd do something like:
`button.OnUsed = function()
    EasterEgg:CompleteStep(3)
end`
This would complete the step, but only if the current step is already 3, meaning you won't have to check any conditions in the script. If the current step was 2, this would do nothing.

Because it's map script exclusive, this would be cleared on Mapping:CleanConfig() as well as Mapping:ScriptUnload(), which means it's safe to add without having to do the cleanup yourself.

**Comment by minin43** [comment]
Can we get it so that we can use different props for Easter eggs?

**Comment by Zet0rz** [comment]
> Can we get it so that we can use different props for Easter eggs?

Props, buttons, triggerzones (stuff you can buy/use by standing inside, similar to teleporters where you buy them just by standing in them, no need to look at them), soul catchers. Those are the entities so far planned to be available in Map Scripting. Any entity can have a OnUsed function set (including map-based ones), this is how I got the Gas Cans to register being picked up. All of these entities though are not part of the Easter Egg system, just the Map Scripting one. The Easter Egg system will utilize these props though. You'll likely assign `EasterEgg:CompleteStep(x)` to all the buttons/props/keys you place in your map for the easter egg.

**Comment by Zet0rz** [comment]
Buttons will likely not be available anyway, as any entity can be given an OnUse function (which you can check for a price, then subtract it), as well as text when you look at them, effectively making all entities able to become buttons. You'll probably wanna use `nz_script_prop` for this.
