### ISSUE TITLE
When trying to change a wall buys with the c key

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#129]
[ERROR] addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/interfaces/sh_int_weps.lua:20: attempt to call method 'GetEntName' (a nil value)
1. unknown - addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/interfaces/sh_int_weps.lua:20
   1. func - addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/interfaces/sh_sync.lua:37
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by Zet0rz** [comment]
Commit 614c4e3c8af72e3fecfa8826df90283783b19af1 fixes this
