### ISSUE TITLE
Content Pack (Remaining Models)

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#130]
Here's a little to-do list (mainly for myself) of the remaining stuff before a content pack can be made:
- ~~Hellhounds updated to have smaller hitbox (get stuck in doors right now)~~
- ~~Der Wunderfizz~~
- ~~Off models for all perks we don't already have them for~~
- ~~Fire Sale drop~~
- Death Machine drop + weapon (?)
- The Wunderwaffe-DG2 (?)
- Potentially Widows Wine models and possibly ~~upcoming perks from Zetsubou no Shima~~ (no new perks)
- Crawler Zombies (?)
- ~~Zombie Barricade Jump Animation remakes~~
- ~~Zombie Blood~~
- ~~Blood Money~~
- ~~Random Apocalyptic models from Origins~~
- Panzersoldat

I think that's it. If you guys come up with more that needs to be packed in before the release, put them below. **Note:** Extra zombies like Napalm might be added, but as a post-release Addon Update. Therefore they aren't required to finish this pack (but would still be nice to have if I can)

**Comment by lolleko** [comment]
I really hope that all is not pre workshop lol :D

**Comment by Zet0rz** [comment]
Hellhound fix, off models, Der Wunderfizz are (if possible). The rest are depending on how much time I have before Workshop release in terms of other features still needed.

**Comment by minin43** [comment]
You can probably find the Death Machine model on the workshop

**Comment by Zet0rz** [comment]
Turns out the Hellhound collisions are not due to their models, but rather code. Sadly, the only fix is by lowering their CollisionBounds which makes you unable to shoot them in the head or tail :(

**Comment by Zet0rz** [comment]
I have posted a thread on Facepunch about getting these, and people have told me of a way I can get the models directly from memory while the game is running. They also offered to get them for me (from the original games, I can only try via WaW Custom Maps) if I couldn't. So these are gonna be here in not-too-long :D

**Comment by minin43** [comment]
Some people are fantastic :D Try to get as much from the games as possible. They don't have to be used for the gamemode launch, but if you can get some stuff for future updates, that'd be awesome.

**Comment by Zet0rz** [comment]
All perk machines' off models was added in commit f56105a29daaab9e241cf626edb3e6a1bf373b11. I did those myself by taking the same models and removing the self-illumination on the textures.

I got the Wunderfizz from a friend with Origins, as well as many other cool props from there (The Panzer Soldat, the 115 generators, dead bodies on stakes and much more scenery). Those will be converted and implemented soon. We're nearing guys :D

**Comment by Zet0rz** [comment]
Update on Der Wunderfizz:
![](http://i.imgur.com/j6ZBaCE.png)

Now I just gotta figure out why it isn't animating at all lol

**Comment by func-octo** [comment]
Dials need a bit of cleaning though... xD

**Comment by Zet0rz** [comment]
That's as good as it gets with the resources I have.

**Comment by func-octo** [comment]
It's fine. Nobody can tell the difference =)

**Comment by Zet0rz** [comment]
Commit d7cfaff158836cb25829ae27b875e91a10078e7e adds Der Wunderfizz. Let me know how it works, only put it through a random set of scenarios.

**Comment by func-octo** [comment]
Can you check out #163 for me? I need some help with that game-breaking bug.

**Comment by Zet0rz** [comment]
Update on Zombie Climb Animations:
![](http://i.imgur.com/1d09bJ6.png)
They fit much better with props directly under the barricade. They will also ignore any props with their traces (although with much smaller trace distances), so you can theoretically block an entire door up so you can't walk through them, but the zombies would still be able to climb.

**Comment by func-octo** [comment]
Looks awesome. I would let it detect the prop, then calculate when it should do the animation so it matches with were the prop is placed.

**Comment by Zet0rz** [comment]
> I would let it detect the prop, then calculate when it should do the animation so it matches with were the prop is placed.

We can't really do that, as we can't offset animation positions. If we instead offset the zombie itself's position, then we risk it getting stuck in the wall or other props as it teleports back. For now, you'll just have to place props that fit the size of their animation. And we can't really avoid the clipping they do, otherwise they'd get stuck.

**Comment by minin43** [comment]
What props are available, and can we get an invisible prop, for nazi zombie recreation maps?

**Comment by Zet0rz** [comment]
It doesn't use any props, you place those down yourself. You just get an option whether it should trigger the animation or not.

**Comment by Zet0rz** [comment]
Barricade Jump animations should be fully implemented in commit fab7900f75615b0c6d1d60cb736c48fd4cb033af. Give it a few shots. It also allows you to disable the planks on the barricades, making you able to make blocks zombies can jump over but players cannot. Note that **zombies will nocollide with everything while doing their jump animation**, meaning you can safely put down props and invisible walls to block players completely :)

**Comment by Zet0rz** [comment]
That should actually complete the content pack if we aren't making the ones with question mark. Just gotta model and add the Zombie Blood and Blood Money drops I also got from the friend who got me the origins models :)

**Comment by Zet0rz** [comment]
Commit 8d449ea414d620ed5c1a52275e8a7f9aedfae858 adds both Zombie Blood and Blood Money models to the game, as well as Zombie Blood being fully functional. Let me know if there's any bugs with the update!

**Comment by minin43** [comment]
What does Blood Money do?

**Comment by Zet0rz** [comment]
Update on some random apocalyptic models from Origins:
![](http://i.imgur.com/xLffrCr.jpg)
They will be added soon. I'm missing the textures for the generators found in that map, so they aren't here. After that, we'll only need the Panzersoldat, which I have the model and textures for, and the Workbench to be able to script buildables.

**Comment by func-octo** [comment]
Looks awesome. Atmosphere +1000%

**Comment by Zet0rz** [comment]
Commit bb05d52cab878251fbb83166d70e418d3298dbc0 adds these models. Now we only need the Panzersoldat.

**Comment by Zet0rz** [comment]
It's Panzersoldat day today. Here's a nice little preview:
![](http://i.imgur.com/GAvV4ZX.png)

**Comment by func-octo** [comment]
Anything but that guy! I didn't know he could be any worse (trying to fight him, anyway), but he found our true weakness: MISSING TEXTURES!

**Comment by Zet0rz** [comment]
Imagine him spawning in front of you with [this animation](http://i.imgur.com/mI5M4q0.gifv) :O

**Comment by minin43** [comment]
Daaaaamn sooonnnnn.

That's pretty fuckin' A.

**Comment by Zet0rz** [comment]
![](http://i.imgur.com/wDGo07f.png)
A bit too rusty? I feel like he's a bit too rusty in the texture. Origins also had these textures, but it had blue-tinted color correction to fix that, we don't have that here. Should I tint the textures more blue-steel-ish?

**Comment by minin43** [comment]
Can we see both, so as to make a side-by-side comparison?

**Comment by func-octo** [comment]
I don't think so. Post back with a picture like this, but in the start room of kosovos. Then we'll see :)

**Comment by Zet0rz** [comment]
I did try him in zs_blitzkreig_v2, the most Origins-like map I've seen, but I haven't tried Kosovos. I'm gonna put a few screenshots when I get time to mess around with him more :)

**Comment by func-octo** [comment]
Cool :) No better way to test looks than to just put him in a stance in an appropriate part of the map that he'll spawn in :) (Apparently :) is the new .)

**Comment by func-octo** [comment]
Could you add a setting so that hl2 zombines could be used as well on special rounds? (The ones that have a chance to pull out a live grenade and suicide bomb you, or just rush at you, they are tough enemies.)

**Comment by func-octo** [comment]
Back to the zombie climb animation, I would make a new tab of props called 'Barricade'. This tab would contain all props that match the animation height (like that cabinet in that picture you posted.). This way map makers can easily tell which props should be used in barricades. Either that or you could add a setting in the barricade tool  to add a prop like it was in that picture you posted. It would bing up a menu with all available props, then just spawn it in right inside the barricade like that pic you posted.

**Comment by Zet0rz** [comment]
Not putting props into the tool itself, it would either limit the selection too much (if only with reasonably many props) or be too complicated if a GUI (if all props). The Apocalyptic tab already has most barricades I found. After that, it's literally any prop of the right height that can be used. And all props can be moved. The cabinet in the picture was actually too tall, so I moved it into the ground.

**Comment by minin43** [comment]
@Zet0rz Most of those props were errors for me

**Comment by Zet0rz** [comment]
> Most of those props were errors for me

Noticed that on my laptop. I'm not sure if it is because of a game's content I only have installed on my desktop, but I think it's the ones from props_fortification. It's gonna be immensely difficult if I can only use default gmod props, there aren't many good ones of those.

**Comment by func-octo** [comment]
Death Machine
https://steamcommunity.com/sharedfiles/filedetails/?id=449046988

When the round starts: http://www.tf2sounds.com/1822#q%3Dwhat%26w%3DHeavy

**Comment by func-octo** [comment]
Also dont forget to add a light to Panzer's helmet and torso light areas!

**Comment by Zet0rz** [comment]
You mean this? ![](http://i.imgur.com/RtgRyTd.png)

**Comment by minin43** [comment]
Terrifying

**Comment by func-octo** [comment]
Yes, but also the lamps outside his suit. Want to eat some Divinium for dinner?

**Comment by func-octo** [comment]
See earlier post for death machine!

**Comment by Zet0rz** [comment]
I can't take models and stuff off of another game's mod, and not without permission either. Death machine is likely to not appear, and if at all, post-workshop.

**Comment by func-octo** [comment]
Ok. I'll search around for a non-copyright(?) model then.

**Comment by func-octo** [comment]
Also on the topic of **Crawler Zombies**. You could cut the zombie model in half and then spawn that in where the zombie used to be. Also spawn the legs as a ragdoll next to it and let the explosion fling them somewhere. Phases of spawning: Zombie has grenade situation, create a cloud of green gass, remove the zombie, spawn in the crawler zombie with no entrance animation, spawn legs as ragdoll (like in hl2), let cloud of smoke fade quickly after spawning. This way you don't have to be neat while spawning it, just create a smokescreen to cover it up.

**Comment by func-octo** [comment]
Could just use an addon for Wunderwaffle dg-2: https://steamcommunity.com/sharedfiles/filedetails/?id=304625393

**Comment by lolleko** [comment]
You can jsut add the wunderwaffe yourself if  you want to use it!

**Comment by func-octo** [comment]
Lol, true. I think I will. Actually I'm feeling in the mood for this as a starter weapon xD Gonna see how that works out today!

**Comment by Zet0rz** [comment]
Tried all those Wunderwaffes, they're quite terrible to be honest xD

**Comment by Zet0rz** [comment]
> Also on the topic of Crawler Zombies ...

Well I mean I can't just cut a model in half and expect it to work. If I make crawler zombies, they'd be their own model with their own animations.

> Ok. I'll search around for a non-copyright(?) model then.

When and if I'm gonna try and get a Death Machine, I'll probably just ask a friend with Black Ops to extract it from his game. But one of the main reason I can't really do this is because I have no idea of how to animate the thirdperson model onto a player and have it still work with leg movements. I don't even think it's possible to modify player animations.

**Comment by Zet0rz** [comment]
This is one big content pack; 222MB uncompressed, 128MB compressed. And that's even removing some of our unused sounds.

**Comment by Zet0rz** [comment]
Content pack is now uploaded. I will go through some tests to see that nothing is missing, then remove the content from the newly created branch: `master-workshop` (No capital letters, fixes that too). After closing this issue, you guys should switch to the master-workshop branch which will only contain the code and a few select resources, and subscribe to the content pack on the workshop. Don't do it yet though, I need to test it first and potentially update if it's misssing something.

**Comment by func-octo** [comment]
It's quite small compared to prop Hunt with all of it's expansions. Prop Hunt's winner calculation is quite broken as well. Congrats on **500 commits** :)

**Comment by Zet0rz** [comment]
Content pack complete! Get it here: http://steamcommunity.com/sharedfiles/filedetails/?id=675138912
You can get the newly repacked branch here: https://github.com/Zet0rz/nzombies/tree/master-workshop
This branch will become the main once a bit more testing has happened, and Master-Changes will be discontinued. It also renames the gamemode itself from nzombies3 to nzombies, so there may be some bugs here and there. Let me know if it works for you :D

**Comment by minin43** [comment]
Will the game mode itself not be available for workshop? Or are you seperating the content and the gamemode?

**Comment by func-octo** [comment]
is master-workshop the new default branch? If so, make it the default branch in settings.

**Comment by Zet0rz** [comment]
> Will the game mode itself not be available for workshop?

The gamemode will be its seperate workshop item when it's ready for it.

> is master-workshop the new default branch? If so, make it the default branch in settings.

Read:

> This branch will become the main once a bit more testing has happened,

**Comment by func-octo** [comment]
Oh. I didn't see that the first time :P

**Comment by func-octo** [comment]
On crawler zombies again. When I said cut the model in half, I meant go into blender or something and separate the model at the waist, make the legs invisible, and have an animation that looks like he's crawling. Then save just legs as a separate model to be used as a ragdoll that soawn after creating the crawler zombie.

**Comment by Zet0rz** [comment]
I am able to extract the crawlers and their animations. I just haven't. I don't feel like it is as important as the other features I intend to add, and it would also make it much harder to get other models to work (you wanted to be able to use TF2 models right?)

That being said, the content pack is complete, so this issue is done :D

**Comment by func-octo** [comment]
Ok. I agree. 63 flippin' comments is enough.
