### ISSUE TITLE
Rounds and Money

### ISSUE THREAD

**Issue by DANJ16** [Zet0rz/nzombies#134]
Every time I start Play Mode it never goes past Round 1.
Money is not earned when killing zombies or hellhounds as well.

**Comment by lolleko** [comment]
Can you provide additional info? Which config/map do you use? Could you possible have any other addons that interfere with this gamemode? Did you copy this repo into the addons or into the game modes folder?

**Comment by Zet0rz** [comment]
If you upgraded from Alig's version, you _need_ to completely delete the old one and drop the new one in. It also goes to `garrysmod/addons` rather than `garrysmod/gamemodes`.

**Comment by DANJ16** [comment]
What is al info exactly?

I've used the gmemode on a few maps such as gm_flatgrass and 2Fort:
Invasion.

Maybe, I don't have many add ons on my Garry's Mod at the moment. I'll try
disabling them all at once and see if it solves the problem.

I have not done anything else except throwing the entire folder in my
addons folder. (As the instructions tell me)

I have never used any other version of this gamemode except the newest
version.

**Comment by Zet0rz** [comment]
Check your config file: `addons/[your nzombies folder]/gamemodes/nzombies3/gamemode/config/sh_constructor.lua`. Look at the ValidEnemies table (started at line 30) and see it has `nz_zombie_walker`, `nz_zombie_special_burning` and `nz_zombie_special_dog` in it. This is the table it uses to determine which entities give points. 

But honestly, the fact that your rounds don't progress suggests to me you installed it wrongly, or another addon is overwriting the Round table (but then you'd get errors?). Do you get any errors?

**Comment by DANJ16** [comment]
Alright I'll check it out.

Yes I do get a lot of errors in to console menu.

**Comment by DANJ16** [comment]
Alright I'll check it out.

Yes I do get a lot of errors popping up in the console menu.

If I somehow did not install it correctly, then how do you install the
gamemode correctly?

**Comment by Zet0rz** [comment]
Download the zip of the Master-Changes branch, open it. Drag that folder inside into `garrysmod/garrysmod/addons`. It should only appear in the gamemode list on the bottom right if you installed it correctly. For it to do this, this path has to be valid: `garrysmod/garrysmod/addons/[any name]/gamemodes/nzombies3/nzombies3.txt`

**Comment by DANJ16** [comment]
Yeup. That is the way I installed it. It does show up in the bottom right.

**Comment by Zet0rz** [comment]
Give us some errors and we can look into it.

**Comment by DANJ16** [comment]
Alright

**Comment by DANJ16** [comment]
I found what was causing the problem. One one of my older addons was
causing the errors which was screwing up the entire gamemode. So I simply
deleted it and now the gamemode works fine. cheers! ^^

**Comment by DANJ16** [comment]
I found what was causing the problem. One one of my older addons was
causing the errors which was screwing up the entire gamemode. So I simply
deleted it and now the gamemode works fine. Thanks for the help! ^^
