### ISSUE TITLE
Spawn Radius?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#135]
Is there a convar to increase the spawn radius of zombies? Or is there some way we can lock parts of the nav mesh to allow/disallow zombie spawning? Some maps are fairly big, and very often zombies further away just wont spawn.

**Comment by Zet0rz** [comment]
The radiusses are hard-coded, but we can change them internally. Zombies will only ever spawn on spawnpoints, if they aren't spawning, you need to place some more.

**Comment by minin43** [comment]
No, I mean I'm too far away from the spawn location for them to spawn. For some maps, the spawn radius needs to be increased.

**Comment by Zet0rz** [comment]
We can probably make it a convar.

**Comment by minin43** [comment]
If could comment in some predefined values (short, mid, far) that'd be nice.

**Comment by lolleko** [comment]
I don't know if a convar would be a good idea, since some configs could break if the convar is set to a value the config wasn't crated with. Maybe a map setting. Although we could probably increase the default amount, right now its 2000 which really isn't much.

**Comment by Zet0rz** [comment]
I don't think any configs are, or should, be built upon distance to spawnpoints, they are purely handled by whether their room so open or not, so nothing should break. In case people _really_ want to dynamically open and close these, they'd need to modify the `Doors.OpenedLinks` table via a map script. Same script could also change the convar.

**Comment by minin43** [comment]
> they are purely handled by whether their room so open or not, so nothing should break

There are definitely spots in some maps were zombies don't spawn because you're too far away.

**Comment by Zet0rz** [comment]
> There are definitely spots in some maps were zombies don't spawn because you're too far away.

But there are no maps built based on the fact that they don't spawn; it's unintentional. (Just saying that it won't break any configs as no config should depend on the distance being lower or higher, it would just lower the spawn rate)

**Comment by minin43** [comment]
Right, it's unintentional. Can we change that, then?

**Comment by Zet0rz** [comment]
Commit 614c4e3c8af72e3fecfa8826df90283783b19af1 increases this from 1500 to 2500. Let us know how it plays.

**Comment by func-octo** [comment]
If you do decide to make it a convar, could it be `nz_zedSpawnRadius (Int Value)`?

**Comment by Zet0rz** [comment]
I keep seeing "Zed" but isn't it "Zombies"? I'd rather make it `nz_zombiespawnradius`

**Comment by minin43** [comment]
Zed is essentially the Euro/British way of saying Zombie. It's also British for Z (us Americans say "zee" and the British say "zed")

**Comment by lolleko** [comment]
I am working on a more dynamic spawn system, that doesn't depend on a radius. So there will be no convar. I will keep you posted.

**Comment by minin43** [comment]
yay

**Comment by lolleko** [comment]
Fixed with #151.
