### ISSUE TITLE
Loading Configs

### ISSUE THREAD

**Issue by Worset** [Zet0rz/nzombies#136]
I have tried to load up a config I made, but when it opens, the console produces this error:
[ERROR] addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/interfaces/sh_int_configloader.lua:112: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
   1. unknown - addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/interfaces/sh_int_configloader.lua:112
   2. func - addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/interfaces/sh_sync.lua:37
      1. unknown - lua/includes/extensions/net.lua:32

The config menu itself doesn't look right either:
![image](https://cloud.githubusercontent.com/assets/18449391/14506467/d5297cc2-01b5-11e6-83fb-ec045cfb740d.png)

Nothing happens when I select the config I wish to load. Any help?

**Comment by Zet0rz** [comment]
Hopefully your configloader should look like this:
![](http://i.imgur.com/n3Pip9l.png)
If it doesn't, did you perhaps install this version on top of Alig's?

**Comment by Worset** [comment]
No, just tried installing again and nothing has changed.
Which is strange because a few updates ago, it worked just fine.
I think it was around when the 'Workshop Config Support' update came out where it stopped working for me.

**Comment by Zet0rz** [comment]
Alright found the bug. It seems to happen if the table isn't valid. Pushed a fix with commit 120842402358ca44d4115f617fb22c7730a04ac8
