### ISSUE TITLE
Hellhounds aren't spawning in the correct spots

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#138]
Titles describes the issue. I have experienced time and time again hellhounds spawning behind barricaded areas, where the regular zombie spawns are. Dunno why, but it really needs to be fixed.

**Comment by Zet0rz** [comment]
It is likely due to the normal spawnpoints being included in the table of valid spawnpoints for the hellhounds.

**Comment by Zet0rz** [comment]
Turns out it's the respawning that doesn't take their type into account. It was fixed in commit 614c4e3c8af72e3fecfa8826df90283783b19af1
