### ISSUE TITLE
Limiting PaP Attachments

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#139]
I'm creating a Pull Request tied to this, but is there a way we can force certain attachments on some weapons?

The AK-74 has the "74U" attachment to it, and having the PaPed version of the AK-74 being titled the AK-74U with the "74U" attachment ALWAYS equipped is nice for consistency reasons. If this could be made so map creators such as myself, or at the very least server owners, have control over this, it'd be greatly appreciated. 

For example, the SCAR-H has multiple variants, but with a certain set of attachments, it actually mirrors the IRL version of. But, since attachments are always randomized, you can't name it the actual, IRL variant, because you won't always get those same attachments (obviously avoiding setting EVERY attachment to be the same EVERY time). Get what I'm saying?

**Comment by minin43** [comment]
Yea I can't figure out how the fuck github desktop works. It's so confusing it's legit pissing me the hell off. Really wanna explode in anger right now, but I'm gonna try not to. I need help with this.

**Comment by Zet0rz** [comment]
This is gonna be a rather complicated thing to implement, but should be possible. I'd have to put a table which contains banned (or whitelisted instead?) attachments for any weapon, but you'd have to modify that server-side and it wouldn't carry over with your configs to other players.

To use Github, all you have to do is make it register your nzombies installation, then just modify its code like you want locally. Then Github will list them under the Changes button, click there, verify your changes, click Commit, click Sync. Then it'll be in your own version of this gamemode. Then you can create a pull request with all the differences between your version and this one.

**Comment by minin43** [comment]
Desktop Github and availability to map creators/server owners aside, can this just be done for the default guns? As a server owner, it isn't hard to just delete the attachments from the gun itself and limit it that way, and map creators can probably just do something through map scripts.

**Comment by Zet0rz** [comment]
If I do this, it'd be through a table which lists either banned or whitelisted attachments. It'd probably come with some functions so people can do it in map scripts (similarly to PaP names), but it really is too much of a special case for me to do it normally. It will _only_ be available through file modification, and by extension, _only_ apply to the server it was modified on. But that should be good for you right?

**Comment by minin43** [comment]
I can just delete the attachments from the guns, and limit it that way. But the server we play on is just run off my dekstop, it won't be up much more than it is now; when I want to play with others online.

**Comment by minin43** [comment]
If you aren't up for doing this, or at least anytime in the near future, go ahead and close this.
