### ISSUE TITLE
Would anyone like resources from BO/BO2/BO3?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#142]
I have BO3 and buying BO/BO2 here soon (Activision Publisher Weekend sale on Steam). Does anyone need any models from the games?

**Comment by Zet0rz** [comment]
Can you extract from BO3? I'm not sure there's any tools for that yet. But there is the list of needed models, if you could get some of those, then that'd be perfect! Just something raw that I can load into Maya, then I can handle the animating and rigging and compiling.
Also didn't list it, but I really want to get the Gersch Device, I just love that weapon xD
