### ISSUE TITLE
Update the remaining modules to the "new" system.

### ISSUE THREAD

**Issue by lolleko** [Zet0rz/nzombies#143]
We should update the remaining modules, to keep everything clean and uniform.
Here is a list of modules left that still use the "old" format, I will try to keep it updated.
- ~~Config~~ (#153)
- ~~Curves~~ (#153)
- ~~Easter Eggs~~ (a23509f)
- ~~Misc~~ (#153)
- ~~Navigation~~ (74fab22068764468b23fd6d1a108883365ef7051)
- Notifications
- ~~Perks~~ (e1adc4221647e3426beada126eaace510b9d78bc)
- ~~Powerups~~ (8d449ea414d620ed5c1a52275e8a7f9aedfae858)
- ~~Weapons~~ (3c6bd74661057e624cea8a493067711a67dcf5e1)
- ~~Enemies~~ (#151)
- ~~Tools~~ (8bf12f084253620ae03d11eb680e19edea4976dc)

**Comment by Zet0rz** [comment]
Easter Eggs just done with commit a23509fb93fa650e563a8df93aea8fb4e3c08d68

**Comment by lolleko** [comment]
Enemies done in #151.

**Comment by lolleko** [comment]
Config, Curves, Misc done in #153.

**Comment by Zet0rz** [comment]
I'll do Powerups and Perks when I add permaperks (easter egg reward) and the remaining powerups (perk bottle, blood money, zombie blood).

**Comment by Zet0rz** [comment]
Commit 8d449ea414d620ed5c1a52275e8a7f9aedfae858 updates the Powerups Module to this system.

**Comment by func-octo** [comment]
what does blood money do?

**Comment by Zet0rz** [comment]
Commit 74fab22068764468b23fd6d1a108883365ef7051 updates Nav module.

**Comment by jaxjaxk** [comment]
it would be nice if we could add stuff like traps in. just a thought, stuff like press a button and it activates turrets or electric arcs.

**Comment by func-octo** [comment]
Sorta like those BO3 easter eggs that spawn mass amounts of zombies from nowhere?

**Comment by Zet0rz** [comment]
Commit 3c6bd74661057e624cea8a493067711a67dcf5e1 rewrites the Weapons Module.

**Comment by Zet0rz** [comment]
Commit e1adc4221647e3426beada126eaace510b9d78bc updates Perks module.

**Comment by Zet0rz** [comment]
All done
