### ISSUE TITLE
Server console being spammed with unnecessary information

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#146]
This was only starting the round, letting the 5 zombies spawn, and then dieing.

> Locked door   Entity [140][prop_buys]
> Locked door     Entity [141][prop_buys]
> Locked door     Entity [142][prop_buys]
> Locked door     Entity [144][prop_buys]
> Locked door     Entity [145][prop_buys]
> Locked door     Entity [146][prop_buys]
> Locked door     Entity [147][prop_buys]
> Locked door     Entity [148][prop_buys]
> Locked door     Entity [149][prop_buys]
> Locked door     Entity [150][prop_buys]
> Locked door     Entity [151][prop_buys]
> Locked door     Entity [165][prop_buys]
> Locked door     Entity [166][prop_buys]
> Locked door     Entity [167][prop_buys]
> Locked door     Entity [168][prop_buys]
> Locked door     Entity [169][prop_buys]
> Locked  Entity [36][prop_door_rotating]
> Locked door     Entity [36][prop_door_rotating]
> Locked  Entity [59][prop_door_rotating]
> Locked door     Entity [59][prop_door_rotating]
> Locked  Entity [60][prop_door_rotating]
> Locked door     Entity [60][prop_door_rotating]
> Locked  Entity [61][prop_door_rotating]
> Locked door     Entity [61][prop_door_rotating]
> Locked  Entity [62][prop_door_rotating]
> Locked door     Entity [62][prop_door_rotating]
> Added lock output to    Entity [98][prop_dynamic]
> Added lock output to    Entity [99][prop_dynamic]
> Locked  Entity [157][prop_door_rotating]
> Locked door     Entity [157][prop_door_rotating]
> Locked  Entity [158][prop_door_rotating]
> Locked door     Entity [158][prop_door_rotating]
> Locked  Entity [159][prop_door_rotating]
> Locked door     Entity [159][prop_door_rotating]
> Locked  Entity [160][prop_door_rotating]
> Locked door     Entity [160][prop_door_rotating]
> Added lock output to    Entity [194][prop_dynamic]
> Added lock output to    Entity [195][prop_dynamic]
> Added lock output to    Entity [196][prop_dynamic]
> Locked  Entity [289][prop_door_rotating]
> Locked door     Entity [289][prop_door_rotating]
> Added lock output to    Entity [330][prop_dynamic]
> Added lock output to    Entity [331][prop_dynamic]
> Added lock output to    Entity [332][prop_dynamic]
> Added lock output to    Entity [333][prop_dynamic]
> Added lock output to    Entity [336][prop_dynamic]
> Added lock output to    Entity [371][prop_dynamic]
> Added lock output to    Entity [404][prop_dynamic]
> Added lock output to    Entity [405][prop_dynamic]
> Added lock output to    Entity [417][prop_dynamic]
> Locked  Entity [474][prop_dynamic]
> Locked door     Entity [474][prop_dynamic]
> TriggerProximity - Missing measure target or measure target with no origin!
> Locked  Entity [59][prop_door_rotating]
> Locked  Entity [160][prop_door_rotating]
> Locked  Entity [289][prop_door_rotating]
> Locked  Entity [36][prop_door_rotating]
> Locked  Entity [62][prop_door_rotating]
> Locked  Entity [158][prop_door_rotating]
> Locked  Entity [474][prop_dynamic]
> Locked  Entity [61][prop_door_rotating]
> Locked  Entity [159][prop_door_rotating]
> Locked  Entity [157][prop_door_rotating]
> Locked  Entity [60][prop_door_rotating]
> Locked door     Entity [140][prop_buys]
> Locked door     Entity [141][prop_buys]
> Locked door     Entity [142][prop_buys]
> Locked door     Entity [144][prop_buys]
> Locked door     Entity [145][prop_buys]
> Locked door     Entity [146][prop_buys]
> Locked door     Entity [147][prop_buys]
> Locked door     Entity [148][prop_buys]
> Locked door     Entity [149][prop_buys]
> Locked door     Entity [150][prop_buys]
> Locked door     Entity [151][prop_buys]
> Locked door     Entity [165][prop_buys]
> Locked door     Entity [166][prop_buys]
> Locked door     Entity [167][prop_buys]
> Locked door     Entity [168][prop_buys]
> Locked door     Entity [169][prop_buys]
> Locked  Entity [36][prop_door_rotating]
> Locked door     Entity [36][prop_door_rotating]
> Locked  Entity [59][prop_door_rotating]
> Locked door     Entity [59][prop_door_rotating]
> Locked  Entity [60][prop_door_rotating]
> Locked door     Entity [60][prop_door_rotating]
> Locked  Entity [61][prop_door_rotating]
> Locked door     Entity [61][prop_door_rotating]
> Locked  Entity [62][prop_door_rotating]
> Locked door     Entity [62][prop_door_rotating]
> Added lock output to    Entity [98][prop_dynamic]
> Added lock output to    Entity [99][prop_dynamic]
> Locked  Entity [157][prop_door_rotating]
> Locked door     Entity [157][prop_door_rotating]
> Locked  Entity [158][prop_door_rotating]
> Locked door     Entity [158][prop_door_rotating]
> Locked  Entity [159][prop_door_rotating]
> Locked door     Entity [159][prop_door_rotating]
> Locked  Entity [160][prop_door_rotating]
> Locked door     Entity [160][prop_door_rotating]
> Added lock output to    Entity [194][prop_dynamic]
> Added lock output to    Entity [195][prop_dynamic]
> Added lock output to    Entity [196][prop_dynamic]
> Locked  Entity [289][prop_door_rotating]
> Locked door     Entity [289][prop_door_rotating]
> Added lock output to    Entity [330][prop_dynamic]
> Added lock output to    Entity [331][prop_dynamic]
> Added lock output to    Entity [332][prop_dynamic]
> Added lock output to    Entity [333][prop_dynamic]
> Added lock output to    Entity [336][prop_dynamic]
> Added lock output to    Entity [371][prop_dynamic]
> Added lock output to    Entity [404][prop_dynamic]
> Added lock output to    Entity [405][prop_dynamic]
> Added lock output to    Entity [417][prop_dynamic]
> Locked  Entity [474][prop_dynamic]
> Locked door     Entity [474][prop_dynamic]
> Unlocking door  Entity [62][prop_door_rotating]
> 62  Entity [62][prop_door_rotating]
> 0
> 0
> Generating round speeds with steps of 10...
> Weapon [426][nz_quickknife_crowbar] Weapon [NULL]
> Weapon [427][nz_grenade]    Weapon [NULL]
> nz_zombie_walker
> 1   =   Entity [12][zed_spawns]
> 2   =   Entity [13][zed_spawns]
> 3   =   Entity [14][zed_spawns]
> 4   =   Entity [15][zed_spawns]
> 5   =   Entity [22][zed_spawns]
> Spawning Enemy: 1/5
> nz_zombie_walker
> 1   =   Entity [12][zed_spawns]
> 2   =   Entity [13][zed_spawns]
> 3   =   Entity [14][zed_spawns]
> 4   =   Entity [15][zed_spawns]
> 5   =   Entity [22][zed_spawns]
> Spawning Enemy: 2/5
> nz_zombie_walker
> 1   =   Entity [12][zed_spawns]
> 2   =   Entity [13][zed_spawns]
> 3   =   Entity [14][zed_spawns]
> 4   =   Entity [15][zed_spawns]
> 5   =   Entity [22][zed_spawns]
> nz_zombie_walker
> 1   =   Entity [12][zed_spawns]
> 2   =   Entity [13][zed_spawns]
> 3   =   Entity [14][zed_spawns]
> 4   =   Entity [15][zed_spawns]
> 5   =   Entity [22][zed_spawns]
> Spawning Enemy: 3/5
> nz_zombie_walker
> 1   =   Entity [12][zed_spawns]
> 2   =   Entity [13][zed_spawns]
> 3   =   Entity [14][zed_spawns]
> 4   =   Entity [15][zed_spawns]
> 5   =   Entity [22][zed_spawns]
> Spawning Enemy: 4/5
> nz_zombie_walker
> 1   =   Entity [12][zed_spawns]
> 2   =   Entity [13][zed_spawns]
> 3   =   Entity [14][zed_spawns]
> 4   =   Entity [15][zed_spawns]
> 5   =   Entity [22][zed_spawns]
> Spawning Enemy: 5/5
> nil Allowed or not
> Swagalf The Pink got downed!
> Locked door     Entity [140][prop_buys]
> Locked door     Entity [141][prop_buys]
> Locked door     Entity [142][prop_buys]
> Locked door     Entity [144][prop_buys]
> Locked door     Entity [145][prop_buys]
> Locked door     Entity [146][prop_buys]
> Locked door     Entity [147][prop_buys]
> Locked door     Entity [148][prop_buys]
> Locked door     Entity [149][prop_buys]
> Locked door     Entity [150][prop_buys]
> Locked door     Entity [151][prop_buys]
> Locked door     Entity [165][prop_buys]
> Locked door     Entity [166][prop_buys]
> Locked door     Entity [167][prop_buys]
> Locked door     Entity [168][prop_buys]
> Locked door     Entity [169][prop_buys]
> Locked  Entity [36][prop_door_rotating]
> Locked door     Entity [36][prop_door_rotating]
> Locked  Entity [59][prop_door_rotating]
> Locked door     Entity [59][prop_door_rotating]
> Locked  Entity [60][prop_door_rotating]
> Locked door     Entity [60][prop_door_rotating]
> Locked  Entity [61][prop_door_rotating]
> Locked door     Entity [61][prop_door_rotating]
> Locked  Entity [62][prop_door_rotating]
> Locked door     Entity [62][prop_door_rotating]
> Added lock output to    Entity [98][prop_dynamic]
> Added lock output to    Entity [99][prop_dynamic]
> Locked  Entity [157][prop_door_rotating]
> Locked door     Entity [157][prop_door_rotating]
> Locked  Entity [158][prop_door_rotating]
> Locked door     Entity [158][prop_door_rotating]
> Locked  Entity [159][prop_door_rotating]
> Locked door     Entity [159][prop_door_rotating]
> Locked  Entity [160][prop_door_rotating]
> Locked door     Entity [160][prop_door_rotating]
> Added lock output to    Entity [194][prop_dynamic]
> Added lock output to    Entity [195][prop_dynamic]
> Added lock output to    Entity [196][prop_dynamic]
> Locked  Entity [289][prop_door_rotating]
> Locked door     Entity [289][prop_door_rotating]
> Added lock output to    Entity [330][prop_dynamic]
> Added lock output to    Entity [331][prop_dynamic]
> Added lock output to    Entity [332][prop_dynamic]
> Added lock output to    Entity [333][prop_dynamic]
> Added lock output to    Entity [336][prop_dynamic]
> Added lock output to    Entity [371][prop_dynamic]
> Added lock output to    Entity [404][prop_dynamic]
> Added lock output to    Entity [405][prop_dynamic]
> Added lock output to    Entity [417][prop_dynamic]
> Locked  Entity [474][prop_dynamic]
> Locked door     Entity [474][prop_dynamic]
> Dropped Swagalf The Pink from server (Disconnect by user.)

I deleted messages that were map-specific.

**Comment by Zet0rz** [comment]
I was sure I removed the entity spawnpoint list? Anyway, Lolle is remaking that so it will likely be gone by then. As to the rest of it, those are mainly debug/status messages. They will probably stay here until the end of beta and then be removed at the final cleanup update before workshop release.

**Comment by lolleko** [comment]
Added DebugPrint function and loglevel, but keep expecting "unnecessary information".
