### ISSUE TITLE
New Config Structure? (Metadata, Workshop)

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#154]
So we've been discussing the idea of metadata and stuff to load with configs for the load interface. We've been discussing some potential solutions, but we'd like you to give your opinions on the things we came up with:

**Addons in Addons:**

Every config would be structured like their own small addons. This means it'd look like this:
![](http://i.imgur.com/ACpUuch.png)

In this, all files related to the config would be in a folder inside `/lua/nz/` which is named the same as your config. The loader would then load for folders instead, and then use the files inside this folder as its resources. Meta would contain information about the map that'd be sent to clients loading and this will likely appear in a window that appears if you hover over a config. **The downside is** that it'll take some more work on packing it into a workshop addon, and if you're making a map script, it would be in a seperate folder to begin with only to be moved together in the end. It will also cost _a lot_ of networking and time spent reading files depending on how much metadata there is.

**Workshop ID Link:**

This one would not change much, other than but a string of numbers at the end of your config file. It would use this to determine which workshop addon it belongs to. It'd look like this:
![](http://i.imgur.com/hxWBVBD.png)

Any and all metadata would then be set on the Workshop page, and the label Workshop would link to the page. This is good because it would dynamically update your info as you change it on the workshop page, and you can add much more such as pictures and videos, as well as links to used mods and your other configs. We could possibly even load some information into the loader interface with http.Fetch to use as metadata without loading any local file from the server, which means no slowdowns serverside. **The downside is** that you'd have to upload the addon once to get your ID before you can update and add it.

**Metadata in Map Settings:**

This would limit your options slightly and you can only set the information the fields allow you (Don't worry, we'll give you as many as you will realistically need). This is good because you don't have to modify any files; uploading to the workshop is as easy as before. **The downside is** that the server would have to load _all_ (or just current map if set) files just to grab the metadata from them. It wouldn't lag since it isn't creating entities, but it'd take a lot of networking and surely be slower than it is now.

**Do nothing.**

Yah, that's an option.

**Comment by Zet0rz** [comment]
I'm kinda hanging to the Workshop ID myself, I think it'd be cool if we could use http.Fetch to create a window on hover that lists the creators _current_ name, and then some information if we create a description structure template the http.Fetch could use to seperate information.

**Comment by lolleko** [comment]
While i think the "add ons in add on thing" would be the coolest. "Do nothing" sounds like it would involve the least work lol, that sounds really good aswell.

**Comment by Alig96** [comment]
> but it'd take a lot of networking and surely be slower than it is now.

The problem to this is that we don't know _how_ slow it makes it. If its slow enough to notice a major slow down then obviously not worth it, but if its a little network lag for a few seconds, is it really that bad? Think about everything else that is networked, this would be fractional compared to all that. You could also only request the meta data when the user has the file highlighted in the menu. Have the starting data all say "Loading" then swap out the data when its been networked. That way you're only networking 1 at a time. You could also cache the data so when the user clicks off the highlighted, and back it loads it from cache rather than re-request it from the server.

**Comment by lolleko** [comment]
We could also addcsluafile the meta.lua file automatically, so there won't be any need for networking right?

Edit: Even if we need to network the information it should barely be noticeable if at all.

**Comment by Zet0rz** [comment]
That's probably true, I'm just so used to micro-optimizations xD
But it is a lot of data if you have a fair few configs that all have long descriptions, creators name, player count, difficulty, and whatever else we add. I'm more worried about the slowdown of having to read all of them with all their files despite only needing to load 1 when you need to.

**Comment by minin43** [comment]
I like the most user-friendly option out there. As the Simpsons put it: "WHY WON'T ANYONE THINK OF THE CHILDREN?!"

**Comment by Zet0rz** [comment]
> I like the most user-friendly option out there. As the Simpsons put it: "WHY WON'T ANYONE THINK OF THE CHILDREN?!"

Tell us which one that is. Because the way I see it is that doing nothing is the most user friendly; where making a config can be fully done by the gamemode itself, and packing for the workshop requires nothing but a drag'n'drop and a file extension rename. But this negates any type of metadata except the workshop ID solution.

**Comment by minin43** [comment]
The suggestion you like. It'll take more work for people like us who know what they're doing (in this regard), but at the end of the day, for the average (12 year old) player, it'll be nice to have all the information available.

**Comment by Zet0rz** [comment]
> The suggestion you like.

So the workshop ID one?

**Comment by minin43** [comment]
Yes

**Comment by lolleko** [comment]
Idk if the average 12 year old is even capable of creating a config we would even want on the workshop lol. But the workshop id is a good compromise. And if we do that we gonna have to make the link more visible than the screenshot version above, because  90% probably won't even notice it.

**Comment by Zet0rz** [comment]
I was thinking of using http.Fetch to get info from the workshop when you hover over the icon of a config for a second. If we make this standard, then a lot of people would do it by themselves which would reveal whether it has a workshop or not. 

But when I think about, the only way to get configs is through the workshop, so you'll _need_ to go through there anyway, meaning metadata isn't actually needed at all as you would read all of it before even deciding whether to subscribe in the first place. Just like your map browsers, you know what it is just by their name and icon. 

That being said, it would be a cool feature to make it link to the workshop, especially if you join another server so you can see their configs and subscribe yourself.

**Comment by func-octo** [comment]
This might be a stupid question. What is Metadata? And will this change how we upload to the workshop?

**Comment by Zet0rz** [comment]
@ScriptnLua Metadata is data about the config that is outside the config itself. It's the creators name, descriptions, thumbnails, and other info you would put on it (basically what you would put on a workshop page).

And depending on the solution we decide to use, then yes, it will make it take some more work to upload to the workshop as this stuff can't be done in-game. Basically this is what would change:
If we go **Addon in Addon** you'd have to make new .lua file seperate and fill it like a table with the info you want, and then pack it into a folder structure like the picture. _(Applies to all)_
If we go **Workshop ID** you'd have to upload your addon once, go to its workshop page to get its ID, edit the filename of your config to add `;[Workshop ID]` at the end, then update the workshop immediately. _(Applies only to those who want)_
If we go **Map Settings** you'd have to do nothing but set your info in a tab in the Map Settings tool, but it'd potentially slow down loading. _(Applies to all)_
If we go **Nothing** then it'd be like it is now, and all the metadata you want your players to know, you'd have to add to the Workshop page (like any other addon).

**Comment by func-octo** [comment]
@Zet0rz Do't forget we can get temp banned for uploading more than one thing to the workshop in a day...

**Comment by Zet0rz** [comment]
@ScriptnLua You're not uploading 2 addons, you're updating the first one. That won't get you suspended. (Do you even get suspended for 2 addons in a day?)

**Comment by lolleko** [comment]
You can get suspended for multiple addons per day although I am not sureif  the maximum per day is 2.

**Comment by func-octo** [comment]
IDK, last time I checked it was, but that was 2009.

**Comment by Alig96** [comment]
Its to reduce spam. Also addons in addons, just make them fill out a table. If the user can't fill out the table then they shouldn't be uploading a config

**Comment by minin43** [comment]
I've uploaded/editted ~3-4 addons in one afternoon before and suffered no consequences. Dunno if something's changed or not.

**Comment by Zet0rz** [comment]
Workshop ID it is then. It will be completely optional, and if it doesn't exist, the workshop label will not be a link and the config won't have a popup. It should be fairly fast to update as a script is only a few kilobytes, so you can just pack the addon and upload, then get the ID and add it to the filename manually, and run the same .bats to update the addon.

**Comment by Zet0rz** [comment]
I made a bit of work on a draft that does this. Here's how it looks in-game (Used Packs is a scroll panel):
![](http://i.imgur.com/QDzbM5u.png)
And here's what was put on the Workshop page to make this appear:
![](http://i.imgur.com/uh0NgMq.png)

The Description fills out the text above the line. Config name and map icon, as well as map name is defined by the file like normal.
Creator is your name, Map ID is a Workshop ID to the map (then it will become a link and you can click it), Pack Name is the name of your config collection (e.g. World at War Configs), Used packs is a table where you can link to used weapon packs or addons that add perks etc., the first value is the name and the second the Workshop ID to link to. Finally the {end} marks the end of the data. You can have more sets of data on a single page if your addon contains more configs.

**Now the question is:** What more info should it display? There's 1 free slot under the pack name, and we can also replace some if needed.

**Comment by minin43** [comment]
Maximum player count + recommended player count.

**Comment by Zet0rz** [comment]
> Maximum player count + recommended player count.

I'd like to know your reasoning behind it. In my head, max players should always be 10+ for well-designed configs and you can always hop in Creative and place a few more yourself if needed, there is really no max. And recommended players is always gonna be 4-5 due to the fundamental gameplay; the fact that any map would have a different count would be a flaw in map design, it needs to be big and open for that and that isn't good Zombies map design.

**Comment by minin43** [comment]
de_cherno. It's small, shouldn't be played with by more than 4 people, and I would like to notify the people who are choosing to play on it that it's meant for 4 people. Because it will be going up on the workshop (along with my other maps) once the gamemode's released.

**Comment by Zet0rz** [comment]
Hmm, fair enough, will make that the thing so far, but it is the first thing to be replaced if we get something better.

Or maybe just make it a "Note" and you can put whatever you want like "Not recommended for 4+" or something. Probably not enough space for that though lol

**Comment by Zet0rz** [comment]
Some progress have been made! It includes the addition of an optional note. It looks pretty good: ![](http://i.imgur.com/swwXdOX.png)
Also the map, pack name, and used packs all have tooltips that display the full name, should it be cut off like it is here.

**Comment by func-octo** [comment]
That's pretty neat! Where would the Creator, map, etc go for when we upload a config? Would it be a lua file or json file?

**Comment by Zet0rz** [comment]
As discussed before, it will be on the workshop page. The one for Breakout is here:
http://steamcommunity.com/sharedfiles/filedetails/?id=675138912

**Comment by func-octo** [comment]
Oh, right .-. 

Also the first two words in the note are Not Recommended, which the user then assumes a slightly negative feeling. If it were Recommended for 1-4 players, the user wouldn't have this feeling, inclining them to play more/longer. But it's a personal preference :P

**Comment by Zet0rz** [comment]
Commit bb547999bfca9f6974bc185654c3e1246e97f043 adds this feature.

**Comment by func-octo** [comment]
> Commit bb54799 adds this feature.

😄
