### ISSUE TITLE
Soul Collecting Doors

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#155]
Would it be possible to add a setting for doors for the number of souls (souls collected by zombies being killed within a certain radius of it) it must collect before opening? This would help with those special maps with extra areas.

If you do, there is usually a short particle trail that comes from the newly dead zombie and travels to the door.

**Comment by Zet0rz** [comment]
See the [Soul Catcher](https://github.com/Zet0rz/nzombies/tree/Master-Changes/lua/entities/nz_script_soulcatcher) Entity available to be used in Map Scripts. Code it to open a door once filled and set its position to be on the door so the souls fly there.
