### ISSUE TITLE
Can Zombies Be Killed By Fast-Moving Entities?

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#157]
If for some reason a map maker intends to have a drivable vehicle in their map, or some sort of smashy trap, would it kill the zombies like it would a player if crushed or run over?

**Comment by Alig96** [comment]
Fairly sure the zombies can take physics dmg, but might need Lolle to confirm

**Comment by Zet0rz** [comment]
I think entities can by default and that we haven't done anything specific to prevent it. But there's only one way to try! lol

**Comment by lolleko** [comment]
I am pretty sure nexbots dont take physics damage (they dont take fall damage aswell), at least not by fast moving props. Most of the times the prop just glitches through a bot. I guess I could code something in to mimic default physics damage, but i am not sure if I should.

**Comment by func-octo** [comment]
Sure you should! Just make it a module for map scripts so they can go into the map script and type something like `ent:TakesEntityDamage(true)` or something like that. :question:

**Comment by Zet0rz** [comment]
Fall damage needs to be off though, zombies don't take fall damage.

**Comment by minin43** [comment]
> Zombies don't take fall damage

That would be the thing to look out for.
