### ISSUE TITLE
More Chat Commands (Mark as enhancement and suggestion)

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#158]
Take a look at https://github.com/Splerge/nzombies for ideas on chat commands. Just something to look at. The last commit has the details.

**Comment by Zet0rz** [comment]
We already have `/givepoints`. We want to make buttons for admins to drop other players into Creative Mode, so that accounts for `/createall`. We have a console command to change round (and this one works fully) called `nz_forceround`, and you can even decide a specific round by doing `nz_forceround 1000`. We have `/giveperk`, but not one for all. `/respawnbox` is pointless in our case, as we have actual move logic. We could make a `/movebox` command though. `/respawn` would be quite handy actually.

**Comment by func-octo** [comment]
Your welcome, ut I didn't come up with those. Splerge did :) Feel free to send him a thank you. :+1:

**Comment by func-octo** [comment]
I will keep putting things here though so keep it open :D

**Comment by func-octo** [comment]
- [ ] /unstuck
  - teleports the player to the nearest player spawn point without killing them in case they get stuck somehow.
- [ ] /setPlayerMaxHealth
  - Allows the player to set their health if Admin
- [ ] /takePoints
  - Allows a SuperAdmin to take points from players for penalties or something (just a concept at this point)
- [ ] /killAllnz
  - Kills all monsters in the map in case you just can't find that last zombie that got stuck in a weird place
- [ ] /killRadius <radius>
  - allows Admins to kill all monsters in a certain radius of them. Good for removing swarms.

P.S. If you have a credits page when uploading to the workshop could you add me as "helped with commands", or something like that? Nothing big if you don't want to :)

**Comment by lolleko** [comment]
/unstuck would be a pretty big cheat.

/setHealth (/heal) is a cool idea I did plan on adding it

/takePoints can be added aswell, although i am not sure what this is good for.

/killAllnz sure, although zombies wont get perma stuck if you setup your map/config correctly.

/killRadius sure why not.

**Comment by Zet0rz** [comment]
> /setHealth (/heal) is a cool idea I did plan on adding it

With health regen being almost faster than typing that, isn't that a bit unecessary? lol

**Comment by lolleko** [comment]
I think what he means is Entity:SetMaxHealth() so you can give a player 1000hp for example.

**Comment by func-octo** [comment]
@lolleko Exactly :) I also see what you mean with **/unstuck**. players would then abuse it during hordes. I would just make it so they teleport to ground level (if possible. If not, have a cooldown of 3 minutes or so on it.)

**Comment by ScriptnLua** [comment]
- /getUp
 - What are you doing on the ground? get up!

**Comment by func-octo** [comment]
Here are more commands
- `/spawn (type)`
  - Ex: /spawn zombie_fast (Types include: hound, zombie_fast, zombie_normal, zombie_special) Used for testing purposes. **Creative mode only!** Mainly for testing navmeshes.
- `/unstuck_zombies`
  - Respawns all zombies that aren't currently moving. Useful for respawning that zombie that got stuck in a weird place (TZTGSIAWP for short)

# Server-Side Commands

(Used in scripts on servers, but can also be on client)
- `/buff_weapons`
  - Doubles the damage of weapons (if not possible, half the health of all current zombies) for 10 seconds in case a server wants to have "random crits." Also used for testing purposes.
- `/debuff_weapons`
  - Halves the damage of weapons (if not possible, double the health of all current zombies) for 10 seconds in case a server wants to have a "hardcore" event. Also used for testing purposes.
- `/permbuff_weapons`
  - A quick command used to make it easier for newer players (same as `buff_weapons`, but is active until `/buff_weapons` or `/permbuff_weapons` is called again.)
- `/permdebuff_weapons`
  - A quick command used to make it harder for those 'hardcore' players (same as `debuff_weapons`, but is active until `/debuff_weapons` or `/permdebuff_weapons` is called again.)
- `/setNextRound (type)` (Types include: normal, special_zombieonly, special_houndonly, and special_normal)
  - Allows SuperAdmins to set what type the next round is

Hope you like them :) If you see any loopholes or repetitiveness, let me know :+1:

**Comment by Zet0rz** [comment]
`/spawn` has its very own tool lol
`/setnexteround type` will not work for as long as we don't have types; we only have special and non-special, and the ones defined in the config. 
The buff commands are for what exactly? I don't see the practical use of these commands really. 
`/unstuckzombies` might actually be helpful in games where they get stuck. Or just `/respawnzombies`

**Comment by func-octo** [comment]
I just added the buff/debuff commands to easily make it harder or easier to play the gamemode without restarting the server after changing the config (it also only lasts as long as the server and isn't saved to the config. It can also be disabled at any time.). But yeah, we really do need something like `/unstuckzombies` or `/respawnzombies` xD

Could you assign me to this issue? Thanks!

**Comment by lolleko** [comment]
`/unstuckzombies` ... zombies will respawn by themself if stuck.

**Comment by func-octo** [comment]
They will? I didn't know that lol

**Comment by func-octo** [comment]
- `/forceout <player>`
  - This forces a player to drop out of a round and into the unready state, and can drop in the next round. Good for removing unwanted players (6 year old mic spammers and whatnot, Useful on Servers)
- `/forcein <player>`
  - This forces a player to join a round instead of dropping into the next one. Useful for that one guy who joined a little late.
