### ISSUE TITLE
Content pack: Create a new git repo

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#159]
When the pack is finalised, put it into its own repo. 

This  makes it easier for dedicated server installs also include a resource.Add lua file just in a auto run

**Comment by func-octo** [comment]
What?

**Comment by Alig96** [comment]
Wrote this while walking home from Uni, couldn't put many details, but basically;

Separate the content (models/textures/sounds/fonts) into its own git repository. It makes it easier for players to download and update the game mode since when Zet0r pushes an update at the moment, you have to re-download all of these files again even for small update so it bloats the gamemode download. Zet0r you gotta separate it eventually, but if you could do it now that would be the better. It will also be ready to package to the workshop too. Its win-win

**Comment by func-octo** [comment]
He could just make a release in the release tab :P
For major updates and such along the way.

**Comment by Alig96** [comment]
Fairly sure the releases feature packages the whole repository IIRC. With its own repository he can add more content without it affecting the gamemode

**Comment by minin43** [comment]
It's going to be uploaded to the workshop, no? Everything finalized gets put into that?

**Comment by minin43** [comment]
Well it's going to be uploaded to the workshop, no? Just throw everything in that, and then use the GitHub repository for feature testing. I don't think we need an entirely separate repository for it.

**Comment by Alig96** [comment]
Correct. The problem with that, with dedicated servers, you would have to download it from the workshop locally, then extract it from the workshop package, repackage it as a zip (or equivalent) then upload to the server. Where as with the repo, you can just download it directly ( wget https://github.com/Zet0rz/nzombies-content/archive/master.zip ) and it done. I know what you're saying is that it will be finalized and it won't be needed to be changed, so it doesn't need a repo but, saying it will _never_ needs to be changed is quite the statement. How about if some sort of new perk or power up or anything comes out in the new COD and Zet0r wants to implement it?

**Comment by lolleko** [comment]
A server admin could just use `git fetch origin` or `git pull` instead of redownloading the whole repo again (via zip).

**Comment by minin43** [comment]
> with dedicated servers, you would have to download it from the workshop locally, then extract it from the workshop package, repackage it as a zip (or equivalent) then upload to the server

As someone who ran multiple servers for over a year, you do not need to repackage it in a zip, you can upload the addon in it's legacy format directly into the addons folder and it'll work just the same.

As for updates, you will have to download the newest update no matter what you use. But if you use workshop, the gamemode will auto-update when you load gmod. You'll never know when the GitHub repository version updates unless you get told or check on your own. It's honestly not much work to just re-extract the gamemode from gmod.

Not to mention you can't use resource.AddWorkshop("workshopID") to download the files if it's on GitHub, you have to pretend GitHub is a FastDL server, and if the server using this gamemode already has one, then you screw things up.

Please just keep it on the workshop.

**Comment by Zet0rz** [comment]
Wouldn't it be more compact and nice to create a seperate branch rather than a full new repo?
And I'm only missing the last few things before the workshop version, so the next time it's gonna be updated is likely going to be the one seperating them.

**Comment by Zet0rz** [comment]
> How about if some sort of new perk or power up or anything comes out in the new COD and Zet0r wants to implement it?

When that happens, I'll just update the content pack :P

**Comment by lolleko** [comment]
Dont create seperate a repo/branche for the same project!? Github is not a download server it's for organizing/edditng the source and putting files that belong together in different repos would be pretty shitty imo. Server owners can use the workshop (it automatically updates without redownlaoding everything) or if they really want to use github, they can use `fetch` or `pull` instead of "Download .zip".

**Comment by Zet0rz** [comment]
Discuss the Content Pack on the Remaining Models issue.
