### ISSUE TITLE
Tool Finalizing

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#162]
A list of tool-related todo things before the release on the Workshop:
- ~~The Random Box Tool should have _Possible Start_ option~~
- ~~The Zombie Spawn tools should have _Spawnable_ and _Respawnable_ fully removed~~
- ~~The Door Locker tool should have everything _Navgroup_ removed~~
- ~~Barricade Creator should have _Planks_ and _Trigger Jump_ options (when jump animations are finished)~~
- ~~Map Settings tool should have _Metadata_ tab (if chosen to have so)~~ (Going with Workshop ID solution)
- ~~Map Settings tool should have _Number of Guns_ removed~~
- Special Zombie Spawns should be required to play a config (since Hellhounds were made default)
- ~~Nav Grouping tool should be completely removed (New Zombie AI can do this by themselves)~~

Any other tool changes you guys think we should implement?

**Comment by lolleko** [comment]
The tool menu should also scale with the display resolution or should be resizable.

**Comment by ScriptnLua** [comment]
@lolleko I agree.
Also, @Zet0rz are you using Linux to make this? If you are, that might be why I can't use doors/cheats.

**Comment by minin43** [comment]
Why would that matter @ScriptnLua 

Lua language is Lua. I'm on W7 and everything seems  to be working fine.

**Comment by ScriptnLua** [comment]
Do the doors/cheats work on kosovos for you? They don't for me (Although you already know that).

**Comment by minin43** [comment]
They do.

**Comment by ScriptnLua** [comment]
Would you have any idea on how to fix my problem? I will reinstall when I get home and see if that helps.

**Comment by minin43** [comment]
You haven't provided any bugs, so it's either a bad installation, corrupt config, or addon confliction

**Comment by ScriptnLua** [comment]
Ok. I'll experiment. I'll get back to you once I fix it. If it's addons, I'll tell you which addon(s) if possible.

**Comment by func-octo** [comment]
Should be able to access the Mismatch menu more than once (as long as no round in progress) to be able to change what happens to the mismatched gun.

**Comment by Zet0rz** [comment]
Commit 74fab22068764468b23fd6d1a108883365ef7051 adds random box start location(s), removes leftover zombie spawn data, and removes everything Nav Groups.
