### ISSUE TITLE
Icons For GUI (Config Loader)

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#164]
Here are some icons. They are explained below.
![awsnap_file](https://cloud.githubusercontent.com/assets/10675391/14711896/1b1373c0-07a9-11e6-8edb-ef5ae907d69b.PNG)
Could be used if map script is not present. "Could not locate Map Script file" with the image above it.

![awsnap](https://cloud.githubusercontent.com/assets/10675391/14711937/3e773ae0-07a9-11e6-9a63-e8caf2135111.PNG)
Could be used as an error if the nz data folder is missing. "Critical error: garrysmod/data/nz does not exist!" Then image above it

Keep in mind that they can be resized infinitely without resolution/quality loss.

**Comment by minin43** [comment]
Better these than the missing texture picture we have now

**Comment by func-octo** [comment]
For what? I have never seen missing textures in the GUI. Or do you mean gMod in general?

**Comment by Zet0rz** [comment]
There is no reason to add these. Map scripts will by default not load, and if you say yes to it and it doesn't exist, the warning text in chat is sufficient. Icons like these should be used in browsing interfaces, which the map script loader is not. 

As to the other, the folder can not ever not exist. If it doesn't exist, it will simply be created the first time you save. It is not a critical error at all.

**Comment by minin43** [comment]
I was thinking about the pictures when you try to load a config, not the script file, my bad.

**Comment by func-octo** [comment]
Ohhhh... Yeah, that'd look WAY neater.

**Comment by func-octo** [comment]
@Zet0rz Hope you heard @minin43  :)
