### ISSUE TITLE
Zombies to be Lag Compensated

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#165]
Should be fairly easy, but I keep forgetting it, this is more of a reminder to myself or Lolle for the next time we update it xD
It'd be solved by just putting `self:SetLagCompensated(true)` in the zombie baseclass Initialize.

**Comment by func-octo** [comment]
What would this do?

**Comment by Zet0rz** [comment]
If you have higher ping, zombies will be teleported back the time based on your ping when you shoot, so you still hit them if they are under your crosshairs even with a high ping.

**Comment by lolleko** [comment]
But this will also drastically increase the server load with many zombies alive at once. And because zombies are moved to a prior state this will cause some weird behaviours and chaos, like shooting "around" corners etc... . Tbh I don't think lag compensation is really needed in a PVE environment.

**Comment by Zet0rz** [comment]
It really is, it is very hard to get hits even at just 150 ping. Although I'm not sure how much server strain it would cause, but we can always make it a convar.

**Comment by lolleko** [comment]
<50 zombies it shouldn't really matter. I doubt the lag compensation will be more expensive then the rest of the zombie stuff (the bathing especially).

**Comment by Zet0rz** [comment]
Commit e4c3491d1c2b571be01851930885cac099939daa adds this along with a convar to control it.
