### ISSUE TITLE
Errors and pixels everywhere except for props.

### ISSUE THREAD

**Issue by LoomDesires** [Zet0rz/nzombies#167]
there has been errors and pixels on my hud and errors  zombies, perks. how do i fix that? ive been trying to figure out if i placed the files properly. here's a picture of the issue. thank you!
![20160424044859_1](https://cloud.githubusercontent.com/assets/18642496/14767353/3de1795c-09d8-11e6-9602-c879786ff046.jpg)

**Comment by Zet0rz** [comment]
Are you playing on a dedicated server? If so, you _need_ to install the gamemode in your client as well. The models and textures are all in the addon, so your client will not have them if you did not install them.
