### ISSUE TITLE
Mode doesn't count players that didn't ready as alive

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#168]
I'm not sure if you have noticed but if let's say 10 people join and 3 are ready when only the 3 die or go down the game mode acts as if everyone died and ends the game. the good news is i found the cause. 

short version: in rounds/sv_round the function player.GetAllNonSpecs(),
you want "if ply:IsValid() and ply:IsReady()" replaced with "if ply:IsValid() and ply:Team() != TEAM_SPECTATOR then"

long version: 7 players in the given example were not marked as ready. because of this they are not included in player.GetAllPlaying() there for they are not included in player.GetAllPlayingAndAlive(). as you know player.GetAllPlayingAndAlive() is used to count how many players are alive and active and if the list is empty then the gamemode knows to end the game.

**Comment by Zet0rz** [comment]
This is actually a really good call. We haven't put it through public server style testing, so we haven't come across this. Thanks!

**Comment by lolleko** [comment]
That is how it's intended lol, what you are suggesting is that every player will be forced to play once enough players are ready, we don't want it that way. We only want the players to play that are actually ready. So in your example if you have 10 ppl on your server and 3 press ready and the game starts, those 3 will be set to playing, the other 7 can either drops in or spectate... that's exactly how we want it to be. A player in this gm is only considered "alive" if he is ready/playing and alive, you can't be alive without being ready first.

**Comment by Zet0rz** [comment]
That's probably true. The way I read it though is that 3 players readied up and everyone dropped in, but only the 3 original ready ones counted towards staying alive. @jaxjaxk mind clarifying what exactly happened?

**Comment by lolleko** [comment]
Droppins will set a players state to "Playing" aswell (I hope lol).

**Comment by func-octo** [comment]
if you read this, you should make a new milestone called 500 Commits to celebrate how far you've come :) You're almost there already!

**Comment by jaxjaxk** [comment]
i finally got it fixed. ignore the fix i proposed. instead make sure you set the team they are on and that they are ready when they spawn IE the spawn function. ( setteam and setplaying)

what happens is when anyone presses ready everyone spawns in, ready or not. only if they are ready does the code set them to playing. so any player that did not select ready is counted as not playing ( isplaying)
