### ISSUE TITLE
Mysterybox error

### ISSUE THREAD

**Issue by LoomDesires** [Zet0rz/nzombies#169]
mystery box appearance is good, but i am unable to use it. it keeps saying "something is creating errors" :(

**Comment by Zet0rz** [comment]
Check through the commits listed on this page: https://github.com/Zet0rz/nzombies/commits/Master-Changes
You will see that I already did some point and powerup hotfixes, including this box. Or are you on the latest version? (Panzersoldat models)

**Comment by lolleko** [comment]
I fixed this issue in #176 , sometimes the box tried to show invalid guns during windup which caused script errors.

**Comment by Zet0rz** [comment]
I think he referred to the constant script errors related to the Powerups module rewrite but where I forgot to change the firesale check on the random box. That bug was fixed in 244bf1a5950769f121fd2667ad11cf440b244b59. Either way, it works fine now.
