### ISSUE TITLE
nZombies Invade Sandbox?

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#170]
Since the title probably makes no sense, here is my idea.
@Zet0rz Could you please make it possible to spawn in all zombies/hounds/panzerzoldat inside of the sandbox gamemode (NPC/SNPC/Nextbot)? This would be really fun to have as your friend could be building, and you could spawn in a panzerzoldat behind him/her xD. Other than that it would be really great for posing for backgrounds for the gamemode.

**Comment by Zet0rz** [comment]
Possibly after workshop release as an update, the NPCs should be somewhat simple to make independent of the gamemode.

**Comment by func-octo** [comment]
Cool. I'd enjoy having 10 panzersoldats chasing my brother around xD

**Comment by func-octo** [comment]
Also take a look at be_office from Greenlight item Codename CURE for another official map.

**Comment by func-octo** [comment]
@Zet0rz I would actually wait on backgrounds until workshop release since then we might be able to use ragdolls and pose them for background shots
