### ISSUE TITLE
not compatable with PS2

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#172]
in class\sh_constructor their is a function "class". PS2 has a function like this as well and causes problem with the game. TBH naming a function class is kind of a bad idea because it can easily be used in other addons and cause problems. i suggest you change the function name to something like "classA" ( the only place i have seen this function being used is in enemies/sv_spawner.lua)

**Comment by Zet0rz** [comment]
Yeah that makes sense. I will look into it soon if Lolle does not change it before then. I think putting nz in front would do good, nzClass().

**Comment by lolleko** [comment]
Naming something "class" is actually pretty normal, i had contflicts with PS2 before and honestly for a 40$ addon its the creators responsibility to make it compatible with all addons! But sure we can put an ugly prefix in front of it.

**Comment by func-octo** [comment]
I would add nz to the front of any obvious 'calls' to prevent conflicts with other addons.

**Comment by Zet0rz** [comment]
Commit e4c3491d1c2b571be01851930885cac099939daa changes the name of this function to nzClass. Should have fixed the issue. Reopen this if it still conflicts and tell me further errors.
