### ISSUE TITLE
Server always crashes in the middle of the rounds or when it's game over :(

### ISSUE THREAD

**Issue by LoomDesires** [Zet0rz/nzombies#173]
Is there a way to fix this issue. it always auto diisconnects my friends and i from the server. and i have to restart it

**Comment by jaxjaxk** [comment]
i do not have this issue, could it be an addon?

**Comment by Zet0rz** [comment]
We've seen short-circuit bugs in the gamemode, but I thought we fixed them all. Check your addons? If you believe it is nZombies, here's wha you can do to find out where it short-circuits:
1) Make Garry's Mod write a console log (put -condebug as launch option)
2) Start nZombies with the console command `nz_zombie_debug` to 1
3) Make it crash and find the console.txt file in `garrysmod/garrysmod`
4) Scroll down to where it should infinitely repeat a certain loop of debug messages related to the zombie

That loop tells us which functions the zombies AI loops through when it short-circuits. Tell us what it is.

**Comment by Zet0rz** [comment]
Also make sure you're using the latest version. We've had these before but fixed them, could be it is an old bug.

**Comment by lolleko** [comment]
This either was introduced in 8d449ea (onnotarget changes), or you are indeed using a old version of the gm. Also i removed the debug lines it was pretty annoying, if you worked on something else zombie related and tried to debug that.
