### ISSUE TITLE
Improved Perk Icons (Illustrator)

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#174]
I have reopened this because  am trying a new technique. There is also more of a likelihood that you'll see this. Here is whoswho.png redone by hand in Illustrator. No longer uses the blur method xD

2535 x 2483
https://cloud.githubusercontent.com/assets/10675391/14886770/8a71d60e-0d20-11e6-9995-c68c2cc65408.png

72x73
https://cloud.githubusercontent.com/assets/10675391/14886917/5f859970-0d21-11e6-9166-8e614cb13066.png

I used Bicubic Sharper for the reduction.

**Comment by Zet0rz** [comment]
I'm honestly not sure if we wanna remake them that badly, if they get too "clean" it will look out-of-place in-game. I'd probably just stick with what we have tbh, maybe with the exception of Double Tap 1 :/

**Comment by func-octo** [comment]
OK. Just let me know if you want anything art-related then :)
