### ISSUE TITLE
Lightning From Hound Spawns Create Glitches [needs test]

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#178]
Every time a hound spawn in the lightning leaves a white bar with a black outline around it. This lasts until either the lightning stops or the hound that spawned died. The bar stays where it is like a billboard gui, facing the player while it's on-screen.

**Comment by lolleko** [comment]
graphics settings?

**Comment by func-octo** [comment]
Do you mean my game settings? If so, I can't until about 2:00 today.
Also what do you think of this icon i just finished for Zet0rz (made for christmas, if he celebrates that?)
https://drive.google.com/file/d/0B1xHaGAsFiwgeVZkOHY4eGdfUkE/view?usp=sharing

**Comment by lolleko** [comment]
looks allright but its quite some time till christmas :D Maybe that bug is game graphic dependent, but its more likely we messed soemthing up.

**Comment by func-octo** [comment]
Lol, a little late on that. But you know more than I do about this since you made it. I'll upload a screenshot of my settings and mayb one of those bars if I can get a shot without being killed. If I were you, I'd sift through the files to see if something is making it happen. If you cant fix it, just see if you can move it down really far so we can't see it :) Good luck!

P.S. Any progress on the downed appearance of players? It looks derpy to revive hem sitting in a chair with their legs through th ground xD Maybe you could have a pose/one frame animation to make it look like they are on the floor. Also make the chair transparent xD

**Comment by Zet0rz** [comment]
I don't get any wierd graphical bugs with the lightning effects. Also, you say 

> until either the lightning stops or the hound that spawned died

but the lightning will always be done before the hound has spawned. Does it stay longer than the spawnanimation for them?

> P.S. Any progress on the downed appearance of players?

I can't really modify player animations since they use a shared skeleton that is built directly into gmod. I did think of using the backwards swimming animation though.

**Comment by func-octo** [comment]
That would work. Could you freeze the animation?

Also yes, the bar thing stays there until the hound dies.

**Comment by Zet0rz** [comment]
Get us a screenshot so we know what you're talking about. As to me, I'm currently focusing on finishing the content pack, I won't be working on much code before that's done.

**Comment by func-octo** [comment]
I will as soon as I can.

**Comment by func-octo** [comment]
Seems to be fixed in master-workshop. Hasn't happened yet.

**Comment by Zet0rz** [comment]
Huh, that's weird. Maybe a simple redownload fixed it. Let us know if it happens again, otherwise we'll close this in a day or so.

**Comment by func-octo** [comment]
OK. Also the prices for things like 'Press E to buy for 500 Points' and 'The Electricity Must Be On!' doesn't show up. But I can still buy them with enough points. The Main HUD on the left works fine though. Same error as before with Display.

**Comment by Zet0rz** [comment]
Give us the error, you never did in the first place. And many mods that replace HUD block other HUDs from running so that you don't get overlapping HUDs. Make sure you don't have one of these blocking the target drawing hook.

**Comment by func-octo** [comment]
I do not have a HUD addon. I am getting the error as you read this.

**Comment by func-octo** [comment]
This issue has been fixed in `master-workshop`.
