### ISSUE TITLE
Boss System

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#179]
This is the system we're going to be using together with the Panzersoldat. It is a system that should spawn in these boss zombies depending on how they're registered. It should also allow people to register their own bosses by calling a simple function with some data. E.g:
`nzBossSystem:Register(classname, displayname, health calculation function, counted in round, affected by instakill, affected by nuke, damage function)`
Classname is the entity we're registering, displayname is the name showing up in Map Settings, health calculation function gets called to determine its health, counted in round means it'll need to be killed to progress the round and will count for 1 zombie spawned, instakill and nuke determine whether they will harm this, damage function can be used to give points (as they will otherwise not). Possibly also settings for Spawnpoint Type, or a condition function that can block it from spawning (say, require power).

The map settings tool should then have a tab that allows you to set which boss spawns, and how frequently. There should also be functions for this for map scripts so they can change stuff about the boss in there.

**Comment by minin43** [comment]
Isn't the boss supposed to be the replacement for round 6/12/18/etc special zombies (or dogs)? It is, at least, for Origins, which is where you got Panzersoldat from.

**Comment by Zet0rz** [comment]
It is not a replacement, although in the maps these bosses appear, they do replace special rounds. But take Der Eisendrache where the Panzer does appear while the map has Hellhound rounds. Also, they run completely differently, where the Special Round system completely replace normal rounds, the boss just appears alongside them.

**Comment by func-octo** [comment]
So for instance this?
`nzBossSystem:Register("panzer", "Panzersoldat", healthcalcfunc(), true, false, true, dmgfunc())`

how about a parameter `spawnConditions` (like you said) that could be `requirePower` ,`normal`, `special`, or `onElecActivated`? `onElecActivated` would be nice to play with.

**Comment by lolleko** [comment]
We should maybe use the existing system, adding a boss spawner instance to the round system and a boss spawnpoint entity, so you can just add a boss to round to nzConfig.RoundData. Maybe make an interface for round data in the tool menu. (We should probably do this regardless if we add the bosses to this system). For that we would nee to move the roundData to the config tho, but I think this should be done anyways aswell.

EDIT: If someone would want to spawn a boss without that system via a mapscript/objective he could just spawn the ent in his map script.

**Comment by func-octo** [comment]
I think I like Zet0rz idea better. It'd be easier to add bosses and easily change the settings.

**Comment by lolleko** [comment]
It would just be the same just work a little bit different internally lol. We could still have this Register helper in addition to the RoundData.

**Comment by Zet0rz** [comment]
We could use the same spawnsystem, but this is meant to make it possible to select which one from a dropdown of registered bosses. People can upload their own workshop packs with new zombie types and register these so they work as a sort of extension to the gamemode. It'd be easier to handle in its own Map Settings table anyway, since we only really need to lookup frequency and spawn it, then call its health function and done.

**Comment by lolleko** [comment]
You could still have that dropdown, I am just saying we shouldn't create another spawn system, since we already have one!

**Comment by Zet0rz** [comment]
Wouldn't wanna make special boss spawnpoints though, special spawnpoints are pretty much universal in-map checkpoints that we can use for all sorts of stuff. Bosses should just spawn on these so you don't have to place boss spawnpoints all the same places. But the system doesn't allow more spawners on any spawnpoint type, plus our system is built for mass-spawning, this is just a single ents.Create call every few rounds.

**Comment by lolleko** [comment]
The system is object orientated you can easily derive from the Spawner class and fix all the issues you mentioned: 
That way you could easily create spawner instances that would work on special spawns aswell without fucking up the normal special spawns. The only reason you cant apply multiple spawner instances to the same spawn type is because of the ZombiesToSpawn field in the spawn point entity, a boss wouldn't need that field so you could add a BossSpawner Instance that doesn't update the the zombriestospawn value on spawners to use special spawn points for bosses aswell.
You could also create custom weight functions or remove that completely.

So you could just do 

```
nz.RoundData[n] = {
  normalTypes....
  specialTypes...
  bossTypes = {
    ["panzer"] = {
      name...
      healthfunc.
      onspawn(optional)...
      periodically  = 5 //(this would add the same boss type to the n + 5 round)
     ......
    }
  }
}
```

This would give way more possibilities to advanced user. And you can still create that register spawn function & dropdown for normal users/map settings, that would basically be a helper to insert something into the round data.

In practice this will do exactly the same you are planing, but it will keep all spawning consistent.

**Comment by Zet0rz** [comment]
I'll look into making it as consistent as possible, probably will add another data table like the SpecialRoundData (specialTypes), using the same way of delaying and checking.

**Comment by func-octo** [comment]
Also for noobs could you make a gui that we could use in maybe map settings that'll let us define what monsters to spawn. So we could easily replace zombies and such.

**Comment by lolleko** [comment]
If @Zet0rz isn't working on this yet, I would make the boss system and gun for zombieRoundData. This would take some days tho because what i have in mind is a lot of work.

**Comment by Zet0rz** [comment]
> Also for noobs could you make a gui that we could use in maybe map settings that'll let us define what monsters to spawn. So we could easily replace zombies and such.

With any of this you will need to create some sort of register function that works similarly to how the ValidEnemies table does. It's what gives you points when you shoot them and what kills them with nukes and such. I will look into making these register functions when I make the boss system.

> This would take some days tho because what i have in mind is a lot of work.

I was just going to replicate the Special Round system we have already which works the exact same way; marking a round as being special and then setting the next one, except just doing it with a boss variable instead. I have already begun preparations for this on my end.

**Comment by Alig96** [comment]
Instead of a long function could I suggest:

local tbl = {}
tbl.className = "fcnbsdkjjf"
tbl.displayName= "fcnbsdkjjf"

nzBossSystem:Register(tbl)

Then you could have defaults when the function.

**Comment by Zet0rz** [comment]
Finally added in commit 2341c9d712ad612d2c18e16821a71bc701b71115. Comes with a few things to set:
- Class

The class to spawn
- Special Spawn

Whether to spawn at special spawnpoints or not
- Init function

Function is run when the game begins with this boss set. Use to set the intial round to encounter the boss.
- Spawn function

Run when the boss spawns. Used to set health, speed, etc. First argument is the boss spawned.
- Death function

Run when the boss dies. Used to set next time he will appear (as it only counts from deaths normally). This can also give points. Arguments are `(boss, attacker, dmginfo, hitgroup)`
- On Hit function

Run whenever the boss is damaged. Can be used to give points to players. Not run on death. Arguments are `(boss, attacker, dmginfo, hitgroup)`
