### ISSUE TITLE
Grenades Not Exploding In `master-workshop`

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#180]
Grenades work as they should, being thrown and such, but then it says that fas20 is creating errors and the grenade never explodes. Retrieving the error some time today...

**Comment by Zet0rz** [comment]
Are you using FAS2's grenades? Because they don't work.

**Comment by func-octo** [comment]
I am. They work fine in sandbox though.

**Comment by Zet0rz** [comment]
I don't know why they wouldn't work, haven't looked into it really, but you should be using the in-game grenades (they will be improved later).
