### ISSUE TITLE
Be Notified Upon Cheating

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#182]
I think it would be a good idea to 'whisper' to a person that they have received a cheat from someone.

Examples:
`You have received 500 points from Zet0rz` - `("You have received " .. pointamnt .. " from " .. cheater)`
Or if you are the server owner:
`Notice! lolleko has just given 500 points to Zet0rz!` - `("Notice! " .. cheater .. " has just given " .. pointamnt .. " points to " .. cheated)`

Yes, you could compile all messages of thhis type into one or two methods such as determing the type of cheat and then put a custom string Ex: `("Notice! " .. cheater .. " has " .. cheatstring .. " to " .. cheated)`

**Comment by Zet0rz** [comment]
Commit e4c3491d1c2b571be01851930885cac099939daa does this, but only server-side and in a less fancy way. It just says "NZ [Player][EntIndex][Name] used cheat /cheat with arguments argument1 argument2".

**Comment by func-octo** [comment]
Gotta keep it fancy man, handlebar mustaches xD

**Comment by func-octo** [comment]
Also I found this. It is very similar to die rise except of the precarious upside down building wedged between them. Use this while I work on my version :)
http://steamcommunity.com/sharedfiles/filedetails/?id=147132515

> - Creepy abandon part of hotel

**Comment by func-octo** [comment]
@Zet0rz Would you like me to make the cheater notifying fancier (my idea)? I really need something to do since I can't finish Die Rise for a long time due to access errors.

Since cheats don't work for me, please post a screenshot of what the chat says after giving a cheat (Screenshots of all command outputs would be great)
