### ISSUE TITLE
What's Being Done About Map Script Tutorials?

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#183]
I would just like to say that many of us want to make map scripts, but we do not know where to start (some of you may, but I am clueless). Can someone please start on doing the Map Script wiki pages so we even know where to start with this?

**Comment by Zet0rz** [comment]
Nothing at the moment. It will be a thing later, you'd probably agree that getting the Panzersoldat to work is more important than the wiki page lol. Keep discussions of already open issues to their issue please. We already have #98

**Comment by func-octo** [comment]
Oh, right #98, forgot about that one xD. I'm sure you've got a lot on your plate, so I'll leave you alone for now.
