### ISSUE TITLE
Saving Create Map

### ISSUE THREAD

**Issue by Hayden152** [Zet0rz/nzombies#184]
I'm not sure if this is a big issue for most people, but I have been creating sets on nZombies before playing on my create save. The problem is I don't know how to save it, load it, or anything like that. Is there anyway I can save it properly?

**Comment by lolleko** [comment]
You can use the drop down in the f1 menu or the `/save` and `/load` chat commands. Your map config gets stored in `garrysmod/data`.

**Comment by func-octo** [comment]
Be sure to generate a navmesh. You can do this using `nav_generate` in the console by pressing `Shift + ~`. After this is done, you must load your config again, and you will be ready to play :)

Feel free to share you configs with your friends. If you do not want to use the workshop, grab your config text file, as loll said, and your `.nav` file for the map you're on (in `addons` or `data` folder), and email (whatever method you use) to give it to someone.
