### ISSUE TITLE
Creation of BO3 Maps

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#185]
I plan to create some BO3 zombies maps for gmod. They will look rough for a while as I fancy it up a little, but will be playable to some extent. As of now, I am working on bo3_exodus, next is bo3_aquarium.

If you want to see a BO3 Map in nZombies, just tell what the name of it is, and I'll find a way to make it!

**Comment by Zet0rz** [comment]
We can only assign owners and collaborators to an issue, so only me or Lolle. I'd be interested to see Splash or Gauntlet. Remember that if you're making it for Zombies, be sure to put smart spawn areas for them. That means make small corridors you can put a spawnpoint in and barricade off, allow them to walk on the roofs and drop down, or make bushes/foliage PLAYER_CLIP brushes so zombies can spawn in there and walk out but players cannot. Of cours don't do this if you aim for an actual recreation.

**Comment by func-octo** [comment]
Lol, I didn't know that. But yeah, since I am making them, I can manipulate them to our needs. That'd be funny seeing zombies come out of a bush xD. But yeah, I can make holes in walls and such so they can drop down and such things. It'll take a while for each map, and expect them to look bare for a while since it's for testing atm.

**Comment by Zet0rz** [comment]
Don't ask for tags, especially when your issue doesn't really have anything to do with the gamemode. Whatever you make is completely seperate.

**Comment by func-octo** [comment]
@Zet0rz Ok.

  I will try my best to post regular progress updates in this issue, usually every 3 days I will post a new screenshot here.

**Comment by func-octo** [comment]
![Map Layout](https://cloud.githubusercontent.com/assets/10675391/15044455/beecd60e-12a2-11e6-8017-d7c189d3e78f.jpg)

Green areas are planned zombie spawns. Props will be added to make the map more close quarters.
The black web are all areas the will be able to explore. More layout designs might be made in the future as the buildings have no set zombie spawns inside them.

**Comment by Zet0rz** [comment]
You'll need a lot of zombie spawns per room (room as in areas to open), these green ones alone won't be enough. But good progress on it

**Comment by func-octo** [comment]
Thanks :) At this point, the skies the limit. In the longrun, the thing to think about is where you want the player to go, spacing (intelligent placing of debris/props), difficulty, where perks should go, where randombox should go, where pap should go, and clever spawn areas.

**Comment by func-octo** [comment]
Until I finish, here are some maps to take a look at from zombie survival.
https://steamcommunity.com/sharedfiles/filedetails/?id=157384458

**Comment by Zet0rz** [comment]
I kinda wanna try making the Zombie Survival entities so that ZS Objective (__obj__) maps would work natively as a sort of easter egg. Would be pretty cool right?

**Comment by func-octo** [comment]
That would be awesome actually :D I'm really excited now! Would that work as a side mission, or would it be the main mission to complete in order to end the map?

**Comment by Zet0rz** [comment]
I'm looking over the entities in Zombie Survival. Do you think we'd need any other than Win/Lose and World Hints? Spawnpoints should be placed by the tools anyway. Maybe we'll want entities on Zombie Survival spawnpoints that open a certain link when enabled (so map-based door events can enable spawnpoints by simulating a door link opening)?

**Comment by func-octo** [comment]
I don't think we need any others. I would do that map-based door opening event system. Sound like it could work :)
