### ISSUE TITLE
Powerup chance to be Pseudo Random instead of True Random

### ISSUE THREAD

**Issue by lolleko** [Zet0rz/nzombies#188]
The title says it all. Basically right now you could play 100 rounds without getting a powerup once. Instead of a true random chance we should use a pseudo random chance. The PR would takes into account when the last powerup dropped, and increase the chance of the next drop the more zombies where killed without dropping a powerup.

**Comment by ScriptnLua** [comment]
Happened to me before. I set myself to god mode and just changed the config so headshots did 1000x more damage per hit. Didn't get a powerup until round 97 xD

**Comment by Zet0rz** [comment]
Yeah sounds good.

**Comment by func-octo** [comment]
That's the way they did it in BOZ

**Comment by lolleko** [comment]
Added in #199.
