### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#190]
There are some gamers out there that play pc games with a controller (using a program like joy-to-key). Are there any controller supported features we could add, say a Controller Mode option so that we would have a beginning for controller support?

**Comment by lolleko** [comment]
As far as i know gmod has no real controller support. So I think its not even possible. But even if it would be possible i don't think its worth spending so much time adding "controller support" for the 3 people that play a pc fps wit a controller. 

EDIT:
I think steam controllers should be supported since you can bind them in big picture, but this configuration has to be done manually by the user.

**Comment by func-octo** [comment]
It's very easy to use a controller in gmod using joytokey. But I forgot about steam controllers.

**Comment by lolleko** [comment]
Well you can use your program than to bind all the keys you need, we don't use any special keys. If you bind WASD, MOUSE, F1, 1, 2, 3.... it should work.

**Comment by Zet0rz** [comment]
I think the main problem with gmod and controller support is that gmod covers sooo many control styles; some gamemodes are controlled completely differently and use more binds than you have buttons on a controller. And the biggest problem is probably the overlay controls, such as the Spawn Menu in Sandbox. And we have that with Q and C in nZombies as well. It'll take a drastic recoding to get those menues working for controllers. I don't think it's worth building into the gamemode itself.

**Comment by lolleko** [comment]
I checked it is not even possible to do that. We have no way of knowing someone is using a controller, nor do we have access to controller specific functions or IN_ENUMS.

**Comment by func-octo** [comment]
Ok. Well even though it won't be in the gamemode, I am going to make one massive profile in Joy-To-Key and test it. Once I finish that, would it be ok for me to add a "Adding Controller Support" page to the wiki? I realize there aren't enough buttons, but I have a clever workaround that I know works and requires no coding.

**Comment by Zet0rz** [comment]
Depends on how well you can write it. If the wiki page is relevant (not just to way too few people) and is well written, then sure.

**Comment by func-octo** [comment]
What do the number keys do?

**Comment by lolleko** [comment]
1,2,3 are for switching weapons not sure about the rest, probably nothing to relevant.

**Comment by func-octo** [comment]
Oh. I just have it set to scroll the mouse wheel when a button gets pressed.

**Comment by func-octo** [comment]
The buttons above the triggers throw grenades.
