### ISSUE TITLE
Rebuilding barricades doesn't work

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#192]
`[ERROR] addons/nzombies/lua/entities/nz_zombiebase.lua:741: attempt to index field 'Nav' (a nil value)
1. unknown - addons/nzombies/lua/entities/nz_zombiebase.lua:741
   1. Compute - [C]:-1
   2. ChaseTargetPath - addons/nzombies/lua/entities/nz_zombiebase.lua:731
      1. ChaseTarget - addons/nzombies/lua/entities/nz_zombiebase.lua:635
      2. RunBehaviour - addons/nzombies/lua/entities/nz_zombiebase.lua:328
      3. unknown - gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua:10

Path generation failed!
Killed Enemy: 5/5
Generating round speeds with steps of 10...`

This has nothing to do with the barricade, but somehow is preventing it.

**Comment by lolleko** [comment]
You are on the wrong version, you are either not using master-workshop or you didn't delete the old branch. Especially `lua/entities` this folder does not exist anymore.

**Comment by func-octo** [comment]
Oh. I forgot to delete the stuff before installing this one. Thanks!
