### ISSUE TITLE
primary clip size for paped weapons.

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#194]
location:gamemode\weapons\sv_weps.lua
function: nz.Weps.Functions.ApplyPaP(ply,wep)

the code you have made lets people customize how a weapon gets paped ( wep.OnPap function)
the problem is that not too much further down in the code you change the clip size. this keeps you from altering the clip size by the custom function ( wep.OnPaped) because only a moment later it changes it again. i suggest after line 248 (    if wep:IsCW2() then)
replacing the next two lines with 

```
            if not wep.OnPaP then
                wep.Primary.ClipSize_Orig = newammo
                wep.Primary.ClipSize_ORIG_REAL = newammo
            end
```

or perhaps get the primary clip size before the custom pap function ( if wep.OnPaP then wep:OnPaP() end) and getting the clip size after and if they are the same then run what you already have.

ill post an example of the second proposed idea below as a full function

**Comment by jaxjaxk** [comment]
here is the first dozen lines of the proposed alterations of the code for the function nz.Weps.Functions.ApplyPaP

function nz.Weps.Functions.ApplyPaP( ply, wep )
    if wep.pap != true then
        print("Applying PaP to: " .. wep.ClassName)
        --wep:SetMaterial("models/XQM/LightLineRed_tool.vtf")
        local ammbefore = wep.Primary.ClipSize or 0
        //Call OnPaP function for specially coded weapons
        if wep.OnPaP then wep:OnPaP() end
        local ammafter = wep.Primary.ClipSize or 0
        local data = {}
        data.wepdata = {}
        data.primarydata = {}
        //Attach the weapon to the data
        data["wep"] = wep
        wep["pap"] = true
        data.wepdata["pap"] = true

```
    if wep.Primary and wep.Primary.ClipSize > 0 then
    local newammo = wep.Primary.ClipSize
        if ammbefore == ammafter then
            newammo = wep.Primary.ClipSize + (wep.Primary.ClipSize*0.5)
            newammo = math.Round(newammo/5)*5
            if newammo <= 0 then newammo = 2 end
            wep.Primary.ClipSize = newammo
            data.primarydata = {}
            data.primarydata.ClipSize = newammo
            wep:SetClip1(newammo)
        end

        if wep:IsCW2() then
                wep.Primary.ClipSize_Orig = newammo
                wep.Primary.ClipSize_ORIG_REAL = newammo

            -- Random attachments
            if GetConVar("nz_papattachments"):GetBool() and wep.Attachments then
                for k,v in pairs(wep.Attachments) do
                    if string.lower(v.header) != "magazine" and string.lower(v.header) != "mag" then -- Mag can't be edited
                        local atts = {}
                        for k2,v2 in pairs(v.atts) do -- List all missing attachments
                            if !CustomizableWeaponry:hasAttachment(wep.Owner, v2) then
                                table.insert(atts, v2)
                            end
                        end
```

sidenote: this is just an example, i have not tested it yet.

what this should do is if the custom pap changes the clip size then it will not alter it further. otherwise it will alter it as you have shown here. i think you should try to do something similar to the damage function because right now all weapons just do double damage when paped no matter what. is is a bit disappointing.

**Comment by Zet0rz** [comment]
Yeah makes sense. To be honest, the weapon should just do nothing at all if the OnPaP function exists, that should then do it all. I have an idea in my head of how I could rewrite the perk/weapon modifications to save some networking, so I'll probably do that when I rewrite it. 

Also, we can't reliably do anything other than double damage and mag size increase for all weapons, so that won't change. Weapons that will be made specifically for nZombies should just have a OnPaP function.

**Comment by Zet0rz** [comment]
Commit 3c6bd74661057e624cea8a493067711a67dcf5e1 allows the OnPaP function to return true and block the rest of the behaviour on the weapon. If you want to manually change ammo and not have the gamemode do it, put `return true` at the end of the function. Remember that doing this will also block any other behaviour **including setting wep.pap!** This means it won't display a PaP name, won't play laser sounds, and won't do double damage to zombies. You can put `self.pap = true` into the function to do this though, or you can manually set your sounds or Display Name in the weapon itself.
