### ISSUE TITLE
max ammo

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#195]
location:gamemode\weapons\sv_ammo.lua
function: nz.Weps.Functions.CalculateMaxAmmo(class,pap)

i believe this is an ineffective way to calculate maxammo as it does not allow for any kind of custom weapons as all it does is multiply the clip size by 10 and some function for paped weapons.

i suggest replacing the function with this

```
local wep = weapons.Get(class)
local clip = wep.Primary.DefaultClip

if pap then
    return math.Round(clip * 2)
else
    return clip 
end
```

what this does is lets the coder specify how much maxammo is for any weapon be setting defaultclip to whatever a player should get for max ammo and twice as much if the weapon is paped. the only down side is players get maxammo when they get a new weapon.

**Comment by lolleko** [comment]
Could you make a pull request for code suggestion its much easier for us to review and we can implement it immediately if it works.

**Comment by Zet0rz** [comment]
A lot of the DefaultClip values are only 1 magazine, some are even 0. If we use this number, a max ammo would only give you a single spare mag. Multiplying it would also break those weapons that _do_ use a higher DefaultClip, then you'd get 10x that much. I don't think we can reliably use any other value than the magazine size :/

**Comment by jaxjaxk** [comment]
@Zet0rz 
TBH people are heartless if they don't already modify the weapons for the gamemode because one clip given when you buy a weapon off the wall, that's just mean. further more the damage output for most weapons straight from an addon is just week. bottom line, they already have to change the weapons so why not have them change this too? my proposal i believe is better because the maxammo for the pistol should be higher than the maxammo for a sniper yet they are about the same.

**Comment by func-octo** [comment]
@jaxjaxk I agree partially. While this is true, some ammo could still be low on a high-use weapon. Say a machine gun only comes with one extra clip (50 or so). That's only 100 bullets before they run out, so it's too expensive.

**Comment by Zet0rz** [comment]
@jaxjaxk 

> they already have to change the weapons

People won't remake their weapons for this gamemode. That just won't happen. Both because the gamemode isn't popular enough to get people to develop solely for that, but also because making a generic weapon pack ensures compatibility with everything else, that will always be more desirable. We are working based on the principle of _every weapon compatible_ which means we **cannot** require modified weapons to be balanced. Also we can't just say it's their fault and be done with it, ultimately players will get a bad experience with it.

> further more the damage output for most weapons straight from an addon is just week

While no weapons are specifically balanced for nZombies, most weapons are balanced relative to themselves. That means that no weapon would be OP compared to others of the same pack. Just lower the zombie health curve if you think the damage is too weak, and that'll effectively be a global damage buff.

Something to remember is that we only have the values that the weapon gives us. We cannot judge them by their viewmodels or weapon types in the code as we can with our eyes and minds.

**Comment by Zet0rz** [comment]
If you guys can come up with a good algoritm/mathematical function to calculate a balanced max ammo, let me know here and I can look into it. Otherwise, I'm gonna close this after a few days.

**Comment by ScriptnLua** [comment]
Got one. I'm on a phone so I'll put it here around 7 PM EST

**Comment by func-octo** [comment]
Here you go. It's rudimentary, but it'll do.
Some foreword - This involves finding the current weapons clip size so it evens things out a bit later on. The multiplier is very flexible, and if needed (if you use a float/decimal like 2.34) could be rounded. Also I know the variables are not needed but it makes it easier to understand in this issue.
`clipSize = nz.findClipSize() //A function that is not yet implemented, but I don't know what kind of impact a function has on performance, if any`
`multiplier = 3 //The variables are able to go inside the config though...`
`maxAmmoAmount = math.round(clipSize * multiplier)`

This way we can make it even in only 3-5 lines of Lua. If you'd like to spice it up a bit, you could do a math.random() between two number for the multiplier. Heck you could even modify the clipSize variable with a math.random() between 0 and 2 to make it vary randomly each time.

**Comment by Zet0rz** [comment]
@ScriptnLua That there is no different to what we already do, unless your `nz.findClipSize()` does something fancy that you didn't tell us. I didn't mean for a way to code it (I know how to code), I meant a sort of calculation for how much ammo to give. Something like `mag size * (round(15 * cos(magsize/1000 * pi/2)) + 2)`
That's probably a bit extreme, but what I'm trying to say is come up with some algorithm that uses a curve (like the cosine curve) or something more complex than just magsize \* x, to result in less relative ammo for larger guns. Or maybe something fancy that takes note of the ammo type, giving x mags based on what ammo type it uses.

**Comment by func-octo** [comment]
> Something like `mag size * (round(15 * cos(magsize/1000 * pi/2)) + 2)`

That's more than a bit extreme xD. I will come up with some sort of formula that will be really over-complicated for no reason. Such as `magSize * (ceiling((magSize*400000/12)/3.14159 + sin(tan(MagSize * 12000))))`

**Comment by lolleko** [comment]
Periodic functions in a scaling function lul, sounds like a good idea! Please deliver! :D

**Comment by func-octo** [comment]
If my last equation ha magSize = 12, max ammo would give 1527882!

**Comment by Alig96** [comment]
I'm confused, what is the problem here? Are you suggesting 10 full clips of ammo is not enough or too much?

**Comment by Zet0rz** [comment]
I think he's suggesting that it should not depend on just the mag size. For an example, a sniper with a 10-bullet mag should get less ammo than a pistol with 10 bullets in the mag. Basically use the already-set DefaultClip value instead (which for way too many guns is just 1 mag).

**Comment by func-octo** [comment]
Is there any way to find out the type of weapon? Maybe you could look for official supprted guns (cw_...) and just use a standard equation for every other gun? Sure it may not be efficient, but heck does it work. Ex. cw_glock20 - maxammo = 14 \* 10 while cw_snipergunname - maxammo = 10*3.
In this example, gunType is the variable that cntains the name of the currently held weapon (Does maxammo give ammo to all guns or just the current one? Also periods are whitespacing xD).

`if gunType == cw_sniper1 or gunType == cw_sniper2 or gunType == cw_sniper3 then`
`....maxammo = 30 (Could be 20 I guess)`
`elseif gunType == cw_smg1 or gunType == cw_smg2 or gunType == cw_smg3 then`
`....maxammo = 170`
`else`
`....maxammo = 150`
`end` 

This could continue through all types. It would work, but it'd probably use more resources than necesarry. Then again, we could just run through the check when the person picks up the max ammo (Like we're already doing...). I say we try it, but it's up to you, **Zet0r**.

**Comment by minin43** [comment]
CW2.0 doesn't inherently support something like that, I don't think. I know by SWEP standards that you can look up ClassName, Category, and Base, but I don't think either 3 of those will be the solution to the issue.

And not to mention, if a server decides to add in their own, non-official guns, they'll run into the same "problem" there is now.

**Comment by func-octo** [comment]
> And not to mention, if a server decides to add in their own, non-official guns, they'll run into the same "problem" there is now.

True.

> CW2.0 doesn't inherently support something like that, I don't think.

What I meant is that it gets the name of the player's currently held gun.

> I know by SWEP standards that you can look up ClassName, **Category**, and Base

I am hoping that **Category** would work because then it would be universal.

@Zet0rz I am done with the xbox 360 controller config, trying to get my ps3 controller to work, but it hates windows...

**Comment by minin43** [comment]
Category is client-side only, and will be different from gun to gun (or addon to addon, in this instance). It's the "folder" the guns are shown in, in the sandbox q-menu. It won't server you any more than Base would.

**Comment by Zet0rz** [comment]
We can't use really long if/elseif-statements, but we can use lookup tables for the same result. I just don't want to add specific support and suddenly limit to a small range of weapons working properly. Probably the best variable to look at to judge what type of weapon it is would be _holdtype_. But again, it won't always be accurate. I really don't think there's any better solution to this than magsize \* x.

**Comment by Zet0rz** [comment]
Also, a note to a feature I'm making which will work for custom weapons is the addition of the function `SWEP:NZMaxAmmo()`. It is called upon a weapon when max ammo is being applied to it (whether it'd be via getting it off the wall, from the box, buying ammo off the wall, or Max Ammo drop), and will prevent the default ammo stuff from being run on that weapon. If you make your own weapon, make this function restore the correct amount of ammo. 

> Does maxammo give ammo to all guns or just the current one?

Gives all your guns max ammo.

**Comment by minin43** [comment]
> Probably the best variable to look at to judge what type of weapon it is would be holdtype. But again, it won't always be accurate

^^ exactly this

**Comment by func-octo** [comment]
We can't be perfect all the time. We should implement this now, but work on it after WS release.

**Comment by minin43** [comment]
> We should implement this now, but work on it after WS release.

_cough cough_

> I really don't think there's any better solution to this than magsize \* x.

**Comment by Zet0rz** [comment]
Closing this. The addition of [the Max Ammo function](https://github.com/Zet0rz/nzombies/wiki/Weapon-Modifications-&-Attributes#max-ammo-function) will cover for this, especially if you thought developers had to edit their weapon for it anyway.
