### ISSUE TITLE
Zombie Animations Not Working Properly

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#198]
So every so often (half the time) a zombie gets stuck in either it's falling animation or just a random frame in it's walking animation. They still move towards you so they aren't stuck, but something is breaking the animation cycle.

**Comment by Zet0rz** [comment]
Yep, aware of this. I don't know what it is though, it looks to me like the BodyUpdate isn't being called as often as it should, and that's a gmod bug. But it may be something to do with how we handle ActStages.

**Comment by func-octo** [comment]
Ok. You might want to put bugs that you are aware of in the readme so people don't open duplicate topics.

**Comment by Zet0rz** [comment]
It doesn't have a duplicate issue. It's fine to have one as that in itself marks that we know of it. Also works like a todo list.

**Comment by ScriptnLua** [comment]
Can you give the path to the perk icons? I can't find them, and would like to redo dTap1

**Comment by func-octo** [comment]
Where are the perk icons in `master-workshop`? I have redone dtap1, but don't know where to put it to open a pull request.

**Comment by func-octo** [comment]
Here are the 2 different versions:
![dtap](https://cloud.githubusercontent.com/assets/10675391/15329888/6e88b216-1c28-11e6-96e3-f6b5475b850f.png)

And No. 2
![dtap](https://cloud.githubusercontent.com/assets/10675391/15329899/77d06f44-1c28-11e6-8772-5a7cd2963cde.png)

**Comment by Zet0rz** [comment]
All materials were removed with the release of the content pack. They are instead in there. Those icons are actually pretty good looking, I'll have to remember them when I update the content. I'd rather update it in bigger updates because it takes ages to upload lol

**Comment by func-octo** [comment]
Lol ok. It's about time I did something useful xD
Just let me know which one you like more, and what I could do to make it better. I can guarantee there are improvements I could make since I did those in 10 minutes. 📦

**Comment by func-octo** [comment]
Here is a side-by-side preview of the 2 dtaps.
![dtap](https://cloud.githubusercontent.com/assets/10675391/15340499/d1656bde-1c57-11e6-8ad8-da48bb1c9a02.png)
![6e88b216-1c28-11e6-96e3-f6b5475b850f](https://cloud.githubusercontent.com/assets/10675391/15340503/d360fe1c-1c57-11e6-9179-11708f20b833.png)

**Comment by minin43** [comment]
Obviously the newer one looks nicer, but I liked the bullets colored as they are above.

**Comment by func-octo** [comment]
The images won't load for me atm. Do you mean the cream-ish color?

@Zet0rz Sould this be added to the milestone? It seems sorta game-breaking (Well, not really, but I don't have another word for it).

**Comment by minin43** [comment]
@ScriptnLua yes

**Comment by func-octo** [comment]
Here is the final version then :)
![dtap](https://cloud.githubusercontent.com/assets/10675391/15391753/122dd7a2-1d91-11e6-9a34-b4104963ad08.png)

**Comment by func-octo** [comment]
Just let me know if I can do anything else. :)

**Comment by func-octo** [comment]
_Bump_

**Comment by Zet0rz** [comment]
Zombie animations frozen should be fixed in commit 41bf9b5b313cbf6e62c7ecb63eabf1dc66af6e87. It happens after a barricade breaking where zombie:IsAttacking() didn't reset, causing it to not run any walk animations (which it shouldn't when attacking). It now properly resets, making it resume its walking animation after attacking the barricade.
