### ISSUE TITLE
NPC Unkillable.

### ISSUE THREAD

**Issue by Terrible1337** [Zet0rz/nzombies#201]
http://images.akamai.steamusercontent.com/ugc/279599570099395124/B78B8DB89059F1ED4957B33C00D233B836F93B06/

any idea?

**Comment by func-octo** [comment]
Unfortunately, we do not know what causes this bug, but we do know fairly well that it exists, and has about a 1/150 chance of happening.

**Comment by Terrible1337** [comment]
Well, we did happen 8 times so sadly.

**Comment by Zet0rz** [comment]
Let us know in what connection it happened. I am well aware of the bug, but I can't find the cause of it and it doesn't happen to us at all :/
If you encounter it again, try putting this into console:
`lua_run local e = Entity(1):GetEyeTrace().Entity print("Health:", e:Health(), "Block Attack:", e:GetBlockAttack(), "Timeout:", e:GetTimedOut(), "Attack:", e:GetAttacking(), "Climb:", e:GetClimbing(), "Jump:", e:GetJumping(), "Stop:", e:GetStop())`

Player 1 must be looking at the invulnerable zombie. Replace `Entity(1)` with another number to make it use players view.

Until this is fixed, you can use console command `nz_forceround` to progress the round if it keeps you from completing it.

**Comment by Terrible1337** [comment]
Thanks Zet0rz, i will check out this code when its happens ^^

**Comment by Terrible1337** [comment]
In the console says: "CCommand::Tokenize: Encountered command which overflows the argument buffer.. Clamped!"

http://images.akamai.steamusercontent.com/ugc/279599570111218543/26196EF68D95BFFE82969A204476ABCC00C6A9A2/

**Comment by Zet0rz** [comment]
Doesn't look like a Lua error, more like an engine error. It may be unrelated, at least I don't know of any of our Lua functions that take too long arguments. I don't think that is related. Did you run the code on the zombie?

**Comment by Terrible1337** [comment]
Yes I ran the code on the zombie.

**Comment by Zet0rz** [comment]
And that was what gave you the CCommand thingy? If that's the case, you should try and print the things one by one. Remove all the things in the print parenthesis except the "e:" parts, but only one of them at a time. Use arrow up to make the console go to the previous command, then edit the print to the next e: call.

**Comment by Terrible1337** [comment]
Ok, i will try again when its happens.

**Comment by Terrible1337** [comment]
Well not works :/ but i got command is works for remove the NPC.

here code: 

lua_run for k,v in pairs(ents.FindByClass('nz_zombie_walker')) do v:Remove() end

lua_run for k,v in pairs(ents.FindByClass('nz_zombie_special_dog')) do v:Remove() end

lua_run for k,v in pairs(ents.FindByClass('nz_zombie_special_burning')) do v:Remove() end

**Comment by Zet0rz** [comment]
`nz_forceround x`
Kills all zombies and proceeds to round x. Replace x with the same as the current to restart the round. Otherwise, the functions above will remove all zombies without counting them as dead, meaning they just respawn so that works mid-round.

**Comment by lmao5677** [comment]
(Sorry for the necrobump or whatever) This bug also can happen when the weapon damage is too high. It happened to me once before, the zombies hp went over negative health, and no matter how many times you would try to kill him, he would never die.
Btw, I don't want to sound like I'm going off topic, but what cw2.0 addon is that?

**Comment by Zet0rz** [comment]
Fixed in 1af80034dc69ff94c99ddd6c17ce85698ecb7f2b
