### ISSUE TITLE
Zombie Collision.

### ISSUE THREAD

**Issue by Terrible1337** [Zet0rz/nzombies#205]
For some small the maps, the zombie can't be a stack in way can be make server is getting lag.

**Comment by func-octo** [comment]
So you're saying that on small maps zombies get stuck in groups and can't move, thus causing you lag from all the physics iterations?

**Comment by Terrible1337** [comment]
Yes,

Like this happens since 46 rounds.
http://images.akamai.steamusercontent.com/ugc/279599570115095758/6C453F2371F38A59ED1947A74D7D2C2067CEEC7D/

**Comment by Zet0rz** [comment]
This looks more like a problem with the max zombies limit not seemingly taking effect. Did you increase the max zombie limit? It will always lag if there's too many. Try reducing it to 2 or 3 and see if more than 2 or 3 zombies spawn, to confirm that it may be completely broken.

**Comment by func-octo** [comment]
First off, that's a LOT of zombies. That is what's causing your lag, not the stuck ones. I recommend setting maximum zombies at 30 and going up by 5 or 10 until it starts lagging.

**Comment by Zet0rz** [comment]
Waaayy too many. Also if you can just make it to round 51 and 30-ish that easily, maybe you should make your configs a bit more close quarter. General good difficulty is if you can make it somewhere in the rounds 10-20 on average.

**Comment by Terrible1337** [comment]
Well, COD Zombie games has the zombie collision.

My config code is: "nz_difficulty_zombie_amount_base", 20, any idea why its many the zombies?

and nz_difficulty_max_zombies_alive is 20 too.

**Comment by Zet0rz** [comment]
> nz_difficulty_zombie_amount_base

That command is related to the curve that decides how many zombies spawn in each wave. It is calculate with `nz_difficulty_zombie_amount_base * round^nz_difficulty_zombie_amount_scale`. With 20 that would mean 20 zombies on round 1. Set that lower. The default is 5.

**Comment by Zet0rz** [comment]
`nz_difficulty_max_zombies_alive` confirmed broken. Will fix with next update.

**Comment by Zet0rz** [comment]
Commit 288ec9da64e47223ba8307ec8787f853f620298c fixes broken max zombies convar. This was most likely the cause of your lag. It defaults to 35.
