### ISSUE TITLE
Weapon Problems Round 2

### ISSUE THREAD

**Issue by DammitStella** [Zet0rz/nzombies#206]
So im back. Sorry, but i took some vacation ^^
Same Setup as in #193 
Now i've managed to find 2 Bugs withit.
Firstly: The MaxAmmo Display on the HUD is now showing 0, but i've still got the ammo. So purely visual. I can't give any hint to why currently.
Secondly (and more important imo):
The Swep order is again mixed. So basicly im again running into the problem, that instead of my current swep, the slot 2 swep gets replaced.

I'm gonna debug it again and will edit the logs into it. Incase live question are needed again, just hit me up on steam.

> Generating round speeds with steps of 10...
> Weapon [808][nz_quickknife_crowbar]     Weapon [NULL]
> lua_run for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end
> for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end...
> 1
> 0
> lua_run for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end
> for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end...
> 1
> 0
> 2
> NZ Player [1][MEME.DADDY] used command /givepoints with arguments 20000
> lua_run for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end
> for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end...
> 0
> 2
> 1
> Killed Enemy: 1/5
> Killed Enemy: 2/5
> Killed Enemy: 3/5
> Unlocking door  Entity [93][func_door]
> 93      Entity [93][func_door]
> lua_run for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end
> for k,v in pairs(player.GetByID(1):GetWeapons()) do print(v:GetNWInt("SwitchSlot")) end...
> 1
> 0
> 2
> Killed Enemy: 4/5

**Comment by Zet0rz** [comment]
So basically no matter what, always the weapon in slot 2 gets replaced? Have you tried with Mule Kick? Is it then always gun 3 or still 2?

**Comment by Terrible1337** [comment]
I've tried with Mule Kick its same issue gun still 2.

**Comment by Zet0rz** [comment]
Good to know. Will look into it when I get time.

**Comment by DammitStella** [comment]
No way. If i see it correctly, you added the same bug as in #193 
currently im setting some prints up, gonna edit them in

**Comment by Terrible1337** [comment]
2 things bug:
Firstly, when you dont have ammo and you can't melee it because of 0 ammo.

Secondly, when you dont have ammo then receive the player then you get grenade hand glitch and crowbar glitch too.

Oh, wait there more:
Bought Bowie Knife then you can't use melee.
+grenade2 is issue can't ever use monkey.

Another one,
First reload then switch to your 1st gun then back to 2nd gun looks so fastest reload time.

**Comment by DammitStella** [comment]
Yes, just tested it out. The slot is wrong. I gonna fix this issue tommorow.

**Comment by Zet0rz** [comment]
> Secondary, when you dont have ammo then receive the player then you get grenade hand glitch and crowbar glitch too.

What?

> Yes, just tested it out. The slot is wrong. I gonna fix this issue tommorow.

I will definitely be able to use your findings to fix it, but watch out you don't make a fix that only works in certain situations. E.g. your previous relied on the last weapon variable which is only set on random box or wall buy; that would break if you get a weapon from anything else such as lua code. I am probably more likely to make the fix myself using your findings.

**Comment by Zet0rz** [comment]
Did the issue get fixed/was something other than nZombies? You shouldn't close it if it isn't fixed. I also meant what I said as in your help is very much appreciated; it's what I base my fixes on :)

> I will definitely be able to use your findings to fix it

**Comment by Terrible1337** [comment]
http://images.akamai.steamusercontent.com/ugc/279599570123618449/FC589057D39235A05747FEE702A2CB6F7CC06A26/

when you have 0 ammo and you will have the hand glitch ^^

**Comment by Zet0rz** [comment]
Those freaking grenades! xD
It's because CW2 uses a seperate viewmodel entity, and it apparently works somewhat when changing, but the default gmod viewmodel doesn't change on 0 ammo.

**Comment by func-octo** [comment]
> Those freaking grenades! xD

Gotta love that 'perfect' technology xD

**Comment by Terrible1337** [comment]
Lol, when will be update this gamemode? ^^

**Comment by Zet0rz** [comment]
I'm currently going through exam periods, which drastically slow down development. On top of that, I still have to edit videos for my channel regularly and I am also getting a drivers license. It might be a bit, the time I get to work is very fragmented. 

That being said, I quickly tested the priority weapon slots, and it works perfectly for me. Might be because I'm running singleplayer, might need to try out multiplayer.

**Comment by Terrible1337** [comment]
Ok, you should try out the multiplayer.

**Comment by Terrible1337** [comment]
Also problem with receive when you're receive then you can use other gun than pistol or raygun.

**Comment by Zet0rz** [comment]
Nope, works fully with multiplayer as well for me. I will assume this is fixed until someone else can confirm the bug. Won't be able to find a fix unless someone can tell me how they got it so I can try to reproduce it.

**Comment by Terrible1337** [comment]
Hmm, when i bought bowie knife then use the knife then happens. 

http://steamcommunity.com/profiles/76561198068336183/screenshot/279600193857618970

**Comment by Terrible1337** [comment]
Also, replace the gun is not works since this update.

**Comment by Zet0rz** [comment]
I haven't been able to fix anything related to it, so if it didn't work before it still doesn't. I just can't reproduce it. I even joined your server and played for a bit and it worked perfectly fine there too. Are you using a certain weapon pack? Maybe an addon that does it? It could also be an addon using a function of the same name. I can try renaming it (or making it a function on the player metatable).

Did you throw a grenade before that bowie knife glitch? The grenades are known to make all viewmodels invisible except the hands themselves.

**Comment by Terrible1337** [comment]
Yes, my server but i used Tomelyr's code for fix replace the weapons only.

I did throw the grenade still same issue when 0 ammo then can't melee it.

Im using addons pack from http://steamcommunity.com/workshop/filedetails/?id=673266588
