### ISSUE TITLE
attempt to call method 'SetUsingSpecialWeapon'

### ISSUE THREAD

**Issue by Terrible1337** [Zet0rz/nzombies#209]
[ERROR] gamemodes/nzombies/entities/weapons/nz_perk_bottle/shared.lua:151: attempt to call method 'SetUsingSpecialWeapon' (a nil value)
1. unknown - gamemodes/nzombies/entities/weapons/nz_perk_bottle/shared.lua:151

that errors on server multiplayer for the perk, PaP, bowie Knife, monkey bomb and revive morphine.

**Comment by Terrible1337** [comment]
When you're in solo the game that you can't see the error but if its 2 players and more will have error so sigh.

**Comment by Zet0rz** [comment]
Check if it still happens in version 3d0510cc1f97772cb5152d79bf40ad1733be18bf

**Comment by Terrible1337** [comment]
Well, still error.

http://imgur.com/oEe67px

**Comment by Zet0rz** [comment]
This is something I'll look into when I remake the special weapons system.

**Comment by Terrible1337** [comment]
also http://imgur.com/iW0fEoU

**Comment by Terrible1337** [comment]
yeah need remake the special weapons system.

**Comment by Zet0rz** [comment]
And I did. It's on the dev branch atm, but will be merged to main soon. Open a new issue if the problem still exists in the new version.
