### ISSUE TITLE
Map switch system

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#211]
There needs to be a map-switch system in place, where at the end of every game, players can vote to either play the map again or choose another one.

Any map-changing addons you'll find on the workshop or elsewhere won't work with this gamemode's round system, or it'll at least require some manual tinkering

**Comment by func-octo** [comment]
I recommend taking a look at Deathrun's GitHub page for this @Zet0rz, if you so choose to add this.

https://github.com/Arizard/deathrun/tree/master/gamemode/mapvote

**Comment by Zet0rz** [comment]
It's probably something we want to work on towards the end, we can probably do something fancy with the already-existent config loader. There is the problem of the Lua state being destroyed as the server shuts down or changes map, but we can probably get around that by saving a temporary .txt with the config to load.

**Comment by minin43** [comment]
No, I don't necessarily mean picking the map's config before you join it, I mean you either A) choose to play the map again, or B) Choose a different map to load

**Comment by func-octo** [comment]
Yes, then all the server host has to do is a load up a config. Which I assume would automagically open when the next map loaded along with any necessary mismatch screen.

**Comment by Zet0rz** [comment]
I don't think mismatch will work for dedicated servers, it only appears for the player loading the config. But it was built for players subscribing to configs on the workshop which may use stuff not installed. Dedicated servers should verify their configs beforehand, you don't really "hotload" new configs on a server :P

**Comment by jaxjaxk** [comment]
for now it might not be a bad idea to set up a basic system with a hook called when the map should switch. that way you can use any votemap system out there by just adding in one line or adding a hook. i have one set up for my server that uses hook instead of changing the gamemode so it it not too hard.

**Comment by minin43** [comment]
Any update to this?

**Comment by lolleko** [comment]
I did start the implementation of a vote system. But i am pretty busy studying right now and probably will be for another few weeks. I will get back to the vote system and traps once i have the time!

**Comment by minin43** [comment]
I feel as the gamemode becomes more popular (and more servers start running it 24/7) a dedicated config vote tool should become a priority. People will lose interest if they have only 1 map to play on (per server - since there isn't always an admin on)

**Comment by lolleko** [comment]
I understand but priority for me right now is getting through the math exams so i never have to see math again :D Maybe @Zet0rz has the time to implement a vote system.

And out of curiosity how many server are there actually? is it really that popular already?

**Comment by minin43** [comment]
I didn't mean to force you, @lolleko I meant that more towards @Zet0rz 

And I see about 6 servers with it running 24/7, one of which is a part of a community I'm apart of.

**Comment by lolleko** [comment]
That's not bad for new game modes in gmod nowadays, especially since this is still in development. Let me see maybe I will have some time tonight, no promises tho.

**Comment by minin43** [comment]
It could honestly run off ULX right now. Just something would be nice

**Comment by Zet0rz** [comment]
You should very easily be able to make it in ULX right? Actually maybe not, after changing the map it'll need to autoload the config.

I already have in my head how I want the voting system to use, which would just be a bool sent in the net message that opens the config loader, which will tell the client to set it up as a vote rather than load menu. Then just limit what configs show up, make a vote counter, and make it send and receive the appropriate net messages. I should be able to do it fairly easily if you want me to prioritize it over the other changes.

**Comment by Zet0rz** [comment]
Something like this is what I had in mind:
![](http://i.imgur.com/tef1YPC.png)
The green fills up as more people vote, the highest voted being fully filled and the rest relative to it. I just gotta put an actual vote counter somewhere, I'm thinking under the map name in the middle, bumping it  up.

**Comment by lolleko** [comment]
I really like the idea of reusing the config loader. But i think its a bad idea to show the result before the vote is over. Because seeing those bars will influence your own vote. There is not really a reason to show how many voted for what until everyone voted (or the time is over). But showing this bars after the vote would be sick!

**Comment by Zet0rz** [comment]
For now they show them live as that's pretty much what every map voter I've ever seen does, so I think people will be used to it. But it should be possible to make them hidden until the vote is finished. I could probably also make the Cast Vote button be filled up as time goes on to represent the time left? Or should I just put that as a number in the frame's title?

**Comment by lolleko** [comment]
Yeah just because everyone does it it doesn't have to be good lol. I mean it looks cool but thats really the only upside. I mean fucking arcana vote(dota) was rigged af at the beginning, because they showed the results all the time.

Probably both counter and bar 👍

**Comment by Zet0rz** [comment]
Counter and bar will both be there (might make hidden an option for servers to set). I'm thinking about the time left, should that be represented as a bar that fills up the vote button or should it just be a number on the vote button/frame's text?

**Comment by Zet0rz** [comment]
![](http://i.imgur.com/SDCVNJR.png)
The button now gets filled up depending on the time left (which can be set in the argument of the server function). Pressing F1 will also reopen it if it was closed during a vote (gets hidden instead of recreated, as opposed to normal config loading).

**Comment by minin43** [comment]
This is perfect! This looks super functional and I like how it re-uses the same interface. 2 things: can we get some functionality where we can black-list specific configs, and can we get a re-vote system once a game is finished? Either for a new config, for a replay, or for a new map (which might be a bit challenging- users might need to set this). Maybe only allow map voting for maps that have a config installed?

But yes, I would appreciate it if this were a high priority.

**Comment by Zet0rz** [comment]
It's going to be 100% customizable which configs show up! It'll read from a text file you can save to your server which configs are going to be sent to the client for voting. 
![](http://i.imgur.com/k3KcM0a.png)
As you can see, I just temporarily reused the table from the normal config load data, it's going to be read from a file instead (and auto-mark them as local/official/workshop so it can't be manipulated).

I am currently working on nzMapping:LoadConfig to be able to change map _and then autoload_ the config when the map is loaded, so map changing will work. 

I have yet to make any system for _when_ the vote starts, but it's easy to call with just `nzInterfaces.StartVote( time )`. I can quickly add it to the end of each game, after X games, or in hooks. Servers can also easily call this function in an autorun to run it whenever they want.

**Comment by minin43** [comment]
Another functionality idea: 3 same-map config limit (So 3 total on a specific map)

**Comment by Zet0rz** [comment]
There will be no limit. If you want certain X configs on a map, you just only add those X configs into the text file with maps your server will run.

**Comment by Zet0rz** [comment]
Map switching now works and the normal config loader will also utilize this. This means that if you vote/load a config on a different map, it will first change map then load the config after 3 seconds of having loaded fully.
![](http://i.imgur.com/khCQd7D.png)

**Comment by Zet0rz** [comment]
Commit 6c86a0ca4baefd928524491f79c8694df156d0db on the development branch has the vote system in it now. It isn't called at any time yet as it is not completely finished, but should work. You can give it some tests if you want. When should it be called? With !rtv commands, on game over, or when?

**Comment by lolleko** [comment]
Maybe with a  time limit. So you have one map at least 60min (configurable) and once those 60min are over the map vote will trigger, once the active round (if active) is over.

And an /rtv command in addition.

**Comment by Zet0rz** [comment]
The vote now automatically start after X time has passed. When this time has passed, the vote will begin next time the game enters Waiting state (after 10 second game over screen). The X time can be set with ConVar "nz_rtv_time" (in minutes). Set to 0 to disable auto-vote. Also added /rtv chatcommand which will cause the end of the end of the current game to start a vote if half of all players have voted.

In commit c627d15b81b2961ee3b118ed39cb8128f83caa56.

**Comment by func-octo** [comment]
:D :+1:  :tada:

**Comment by minin43** [comment]
We got a time for this to hit the live version?

**Comment by Zet0rz** [comment]
> We got a time for this to hit the live version?

The thing is, I don't think I can merge only a few changes from the dev branch into the live one, only all of them. And most of the changes are half-broken ones that I haven't finished, so I can't merge the entire thing either. If I could, it could go live right now, but otherwise it'll have to wait until all the other things are done. And there's a lot to be done.

**Comment by minin43** [comment]
Could you upload the files to a temporary copied main branch and then merge the two that way?

**Comment by tylerpadgett** [comment]
Maybe make the change on a separate branch, a copy of the main as minin said, and only add the completed code in? (You might have to code it in manually, and you probably don't want to, but sometimes it helps find other, more efficient ways to do things.)

**Comment by tylerpadgett** [comment]
http://stackoverflow.com/questions/6372044/how-do-i-merge-a-specific-commit-from-one-branch-into-another-in-git

It's possible!

**Comment by Zet0rz** [comment]
RTV fully working on dev branch, along with a .txt file in /garrysmod/data/nz/server_autoload.txt in which you can define what configs to load automatically on a per-map basis. RTV will currently get all configs available on the server, remove the ones you don't want to be able to change to (develop your configs locally).
