### ISSUE TITLE
New Feature Todo List

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#213]
This is mainly a list so we can keep track of what new things we need to make both before, and as possible post-workshop release.
### Workshop Release
- ~~Boss System (#179)~~ (2341c9d712ad612d2c18e16821a71bc701b71115)
- ~~Panzersoldat~~ (2341c9d712ad612d2c18e16821a71bc701b71115)
- ~~Workshop ID metadata (#154)~~ (bb547999bfca9f6974bc185654c3e1246e97f043)
- Hammer .fgd _(With "Map Config" if needed, similar to Gamemode Extensions)_
- Map/Config Switch system (for dedicated servers)
- ~~Custom Spawnlist tabs (similar to Sandbox)~~ (baf22e1d759e35640c110dee741f56b91b5a868e)
- ~~Special Round selection system (similar to boss)~~ (39aea56d62f02be82af9203c88d092d4c25a0135)
- New Special Weapons hooks (Likely use [PlayerButtonDown](http://wiki.garrysmod.com/page/GM/PlayerButtonDown) which is predicted)

**Comment by func-octo** [comment]
When do you estimate we'll see Panzer?

**Comment by func-octo** [comment]
> Map/Config Switch system (for dedicated servers) 

Is there any way to have this in the command line since it's a dedicated server?

**Comment by Zet0rz** [comment]
There'd probably be console commands to switch configs. Probably one to call a vote as well. Voting would use the config loader, but it needs players anyway so that's no problem.

**Comment by func-octo** [comment]
It would also be nice if you enabled the gravity gun and the normal toolgun into creative mode so we can make ropes and such for aesthetics and or hanging objects. Would also be nice if you made a ragdoll zombie corpse so we could pose it any way we like :)

**Comment by Zet0rz** [comment]
What would you need gravity gun for? And we can't implement the normal gmod tools as they are exclusive to sandbox, at least from what I've seen. And we won't add physics constraints like ropes, it'd be too much CPU. Ropes may appear as purely aesthetic entities though.

**Comment by func-octo** [comment]
The gravity gun can be better than the physgun for smaller objects. Also great for throwing things. Say you want to have a convincing pile of paint cans that have fallen over. All you have to do is build a stack, shoot a paint can into it, then freeze all the cans :) But the ragdoll would also be neat.

**Comment by Zet0rz** [comment]
Commit 39aea56d62f02be82af9203c88d092d4c25a0135 adds special round selection. It may be a bit buggy or unoptimized, but it should work for now.

**Comment by Zet0rz** [comment]
Started working on spawnmenu category editing. Already got .txt reading working, and the default spawnmenu is just a .txt now. Working on making it possible to add and edit categories. Here's a sneak peek:
![](http://i.imgur.com/c1T40nW.png)

**Comment by func-octo** [comment]
Awesome :) :+1:

**Comment by Zet0rz** [comment]
Here's some new things.
- Utilities and Spawnlist are now seperate into two tabs

![](http://i.imgur.com/PbWusDD.png)
- Right-click items in Search or Map Props and you can add them to any category or create a new one

![](http://i.imgur.com/r95NLIu.png)
- Right-click a category to be able to edit it, change the order, or remove it entirely

![](http://i.imgur.com/cqsG1bQ.png)
- New categories now has Tooltip field, and they show placeholder text when empty. The name box also flashes red with already taken names or no name.

![](http://i.imgur.com/Gi2B3uE.png)

Every time any changes have been made, the spawnlist will update and re-create itself in real time, however no changes will be made to your spawnlist txt. This means any changes are temporary until you press Save, which will save your changes to the .txt so it loads like this next time.

**Comment by Zet0rz** [comment]
Spawnmenu upgrade along with a few other fixes and stuff added in commit baf22e1d759e35640c110dee741f56b91b5a868e!

**Comment by Zet0rz** [comment]
Working on the predicted special weapons system now. Got the knives working, it works pretty well the way I made it. Grenades are a bit more tricky though. Conversion to HL2 grenade coming with it, as well as fixes to the invisible weapons and the morphine bug.

**Comment by minin43** [comment]
How are you so talented at coding...
