### ISSUE TITLE
(Question) Custom Melees

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#214]
Is there any command that allows you to create a knife, so when you press v, it can will let you attack with it.

**Comment by Zet0rz** [comment]
Yes it it is possible, the system was made specifically so you can register your own stuff, that goes for all special weapons (like grenades). Look at the Bowie Knife's code:
https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/entities/weapons/nz_bowie_knife.lua#L176-L191

I do have plans to change the way this is registered though, but it'll be more simple. Basically the function would be optional, and if it doesn't exist, it just deploys the weapon, calls PrimaryAttack on it and then holsters it again after the delay set by SetNextPrimaryFire. So in the future it'd basically be:
`nzSpecialWeapons:AddWeapon( "your_knife_class", "knife")`

**Comment by lmao5677** [comment]
I don't mean to sound silly, but how would you use this? Would I have to create my own lua file? Or do a certain action.

**Comment by Zet0rz** [comment]
Anywhere it's run. Lua/autorun, in an existing script, in the gamemode itself's files, in the weapon file, whatever. As long as the function `nzSpecialWeapons:AddWeapon` gets called, it'll register. If you're scripting a custom weapon, I suggest you put it in there, but if you're using another weapon you'll need to put it somewhere else.
