### ISSUE TITLE
Bugged PAP Weapons

### ISSUE THREAD

**Issue by Worset** [Zet0rz/nzombies#215]
[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/display/cl_hud.lua:117: attempt to index field 'Display_PaPNames' (a nil value)
1. v - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/display/cl_hud.lua:117
   1. unknown - lua/includes/modules/hook.lua:84

Right now it seems to only be with custom PaP names (I did them manually through the "cl_papnames" file - part of the issue?), but it causes the ammo counter, perk icons and onscreen prompts to vanish as well.

**Comment by Zet0rz** [comment]
Could be you made a syntax error causing the file to not load; check to make sure you have all the necessary commas and brackets.

**Comment by Worset** [comment]
No, went through and looked at everything I could, but it still doesn't work. Although, looking at the code it look more like it is related to the "cl_hud" file.

Heres the code it seems to be slipping up on: (**"cl_hud", line 117**)

_if wep.pap then

```
name = nz.Display_PaPNames[wep:GetClass()] or nz.Display_PaPNames[name] or "Upgraded "..name
```

end_

EDIT: Default PaP weapon names are affected as well. (It was the AR-15 I tried, but that didn't work either) I didn't touch them when I was making other names.

**Comment by Zet0rz** [comment]
Yeah that'd be the line. But there's nothing wrong with it, it says it's trying to get the `Display_PaPNames` subtable under the `nz` table, but it doesn't exist which means there's a syntax error in the file it's defined. Even if you missed a single comma, it will affect the entire file. Start a new server or singleplayer game and look for errors while you're loading. Scroll up in the console to find errors that appeared together with the long blue or yellow loading list.

**Comment by Worset** [comment]
Found it. I was fine with the commas, but after looking again I found I had put -'s where I should have put ='s. Whoops.

**Comment by Zet0rz** [comment]
Awesome, you solved it. Also, notice the function at the bottom of the file. You can use that instead of adding to the table manually. That way you can do it in any lua file and it also won't get deleted or replaced when you update your gamemode.
