### ISSUE TITLE
(Suggestion) Tesla Trap

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#217]
Like in Der Riese and Verrukt, you have a laser trap that you need the power to turn on. The way I thought of this out is that you could have a tesla object that can be flagged and a telsa activator that can also be flagged. The activator triggers the ones with the same flag number. Whoever turns the trap on gets the points.

**Comment by Zet0rz** [comment]
I did have this planned, but as a post-release feature together with stuff like Widows Wine, Death Machine, possibly GobbleGums as well. I also have an idea how it'd work. Basically you create a wall similar to the invisible walls or invisible blocks, and any zombie touching them will die instantly while the wall is "on" from a switch you link it to. That way we don't have to tie the killing to the effects and we can easily replace the effects with other things like flamethrowers. You give it a link, a price, a cooldown, and a duration.

Also traps don't give points in Zombies.

**Comment by lmao5677** [comment]
> Also traps don't give points in Zombies.
> Oh, alright. I like your idea of the concept too.

**Comment by func-octo** [comment]
@Zet0rz 

> I also have an idea how it'd work.

**Short Answer**
Trigger blocks.

**Long Answer**
Well it's sorta like you put it. I would adda trigger block (nocollide) that shouts an event when triggered by zombies (or whatever entity) that would then trigger lightning effects and all zombies in a range to the trigger block (in hammer units, say 64) take constant damage until they die or get too far away from the trap. The End :P I recommend using the cherry cola death effect for tesla.

**Comment by jaxjaxk** [comment]
don't forget to add turrets as well. because gmod does not have a lot of maps like black ops it would be nice to have standard traps that are easy to add.

**Comment by func-octo** [comment]
Maybe even a trap too? Even though it's busy right now, you could work on this post-workshop and have 2 or 3 default traps like fire, turrets, or tesla. That way people can easily make traps and others could make their own.

**Comment by jaxjaxk** [comment]
@OctothorpeObelus 

i actually recommend buttons for the traps. a simple button placement with a flag and a simple trap with the same flag to be activated when the button is pushed.

**Comment by lolleko** [comment]
Closed see: https://github.com/Zet0rz/nzombies/issues/308

**Comment by func-octo** [comment]
For turret traps would it be possible to modify the combine turrets code?
