### ISSUE TITLE
(Question for Permission for Experimentation) Easter Egg Model

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#218]
I was wondering if I could experiment with making Easter egg models the teddy bear model you'd get from the random box. Just to see how it turns out :)

**Comment by Zet0rz** [comment]
You don't need out permission to experiment locally, but I'm we're keeping the hula dolls as they fit the gmod theme, similar to how the EEs are prison-themed in Mob of the Dead and so on

**Comment by func-octo** [comment]
Ok
