### ISSUE TITLE
Addition To The Mismatch System

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#219]
Is there any way to detect if a weapon will show up as an error (the big annoying thing that flashes)? If there is, would it be possible to add those weapons to the mismatch system so that there are no ERRORs floating around in the random box.

**Comment by Zet0rz** [comment]
The mismatch system already covers wall buys and random box list, but it only checks if the weapon doesn't exist at all (not installed). You could make it also check if the model is invalid, but the fact that the model is invalid yet the weapon is valid means that the addon was poorly coded (or it failed to load for some reason), so I don't think I will make that a mismatch function.

However the mismatch system, just like many of the other modules, is completely modular so you can very easily make your own mismatch check by defining a function that checks for the mismatches, a function that creates the panel client-side, and the function that corrects the mismatches with the data from the client.
https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/gamemode/mapping/sh_mismatch.lua#L97-L108

This will be documented on the wiki under some "Scripting nZombies Extensions" or something like that later.

**Comment by func-octo** [comment]
> This will be documented on the wiki under some "Scripting nZombies Extensions" or something like that later.

Cool. I like the sound of that :)
