### ISSUE TITLE
Invincible zombies, glitched workshop configs & wall/box buys still taking the wrong gun.

### ISSUE THREAD

**Issue by shanzenos** [Zet0rz/nzombies#220]
Okay, sorry to bombard you with bugs, but some more: For one, the first issue below some people seem to still be having an issue with when they subscribe to the configs. For two, the wall  weapons and box still seem to trade the wrong weapons at times, albeit a bit rarer now. And also, the invincible (and sometimes invisible) zombie glitch I recorded here: https://www.youtube.com/watch?v=x1fvJcxSt7I&feature=youtu.be

**Comment by Zet0rz** [comment]
Already aware of all the bugs but the first one, but they're something I can quite find the cause of as they're not consistently happening. As to the first bug, is it the one that causes doors to not be openable? Or what does it cause?

**Comment by shanzenos** [comment]
Yeah sorry I forgot I copy pasted it verbatim from the steam report I had typed up. Yeah it seems for some people doors are not openable when they subscribe to one of the map configs. As for the latest released I actually switched back to an older version of the game-mode because the newest one here seems to cause me more issues. I'll open another issue about those soon however. Again, great work as always, just reporting back whatever I find that breaks.

**Comment by Zet0rz** [comment]
Just tried setting my weapon's damage to 100000000000000 but it did not make the zombie go invulnerable, it just died instantly.

**Comment by func-octo** [comment]
> 100000000000000

Little bit off-topic but what if it were like that admin gun that spray everywhere xD

**Comment by Zet0rz** [comment]
Invincible zombies fixed in 1af80034dc69ff94c99ddd6c17ce85698ecb7f2b
