### ISSUE TITLE
Timer Failed for Grenade Spam

### ISSUE THREAD

**Issue by Terrible1337** [Zet0rz/nzombies#221]
http://imgur.com/CZwZP0K

Any idea?

**Comment by Zet0rz** [comment]
Seems like someone clicked the grenade button but the grenade wasn't equipped. Tbh I'd just completely disable the grenade for now, it's kinda broken and not even balanced.

This is something we'll be fixing with the grenade remake.

**Comment by func-octo** [comment]
Yes. It bouces way too much. Even if it were one of those Super Boucy Balls from Five Below.

**Comment by Terrible1337** [comment]
its been 1 month and still not fix the grenade? hm?
