### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by sethworkman1624** [Zet0rz/nzombies#230]
Stupid question but how do you get rid of the menu sorry for bugging

**Comment by func-octo** [comment]
F1 by default :)

**Comment by func-octo** [comment]
@sethworkman1624 if you would like to change this button, open the console (~ or Shift + ~. Enable through advanced keyboard settings.) and type `bind key nz_settings` where key = to any key on the keyboard. For Numpads use KP then a key. Ex: KPUP
