### ISSUE TITLE
Pressing shift in ready screen

### ISSUE THREAD

**Issue by djrefor** [Zet0rz/nzombies#232]
When pressing shift while there is no game started yet, will result in this error:

[ERROR] addons/nzombies/gamemodes/nzombies/gamemode/player_class/sv_sprint.lua:6
8: bad argument #1 to 'SetRunSpeed' (number expected, got nil)
1. SetRunSpeed - [C]:-1
   1. fn - addons/nzombies/gamemodes/nzombies/gamemode/player_class/sv_sprint.lu
      a:68

**Comment by Zet0rz** [comment]
Good call! Should be fairly simple to fix but I'm quite busy so don't expect it too soon :P

**Comment by func-octo** [comment]
Wow. I didn't even think that would happen. Kinda funny actually.

> Should be fairly simple to fix but I'm quite busy so don't expect it too soon :P

Would you like to see If I could fix it?
