### ISSUE TITLE
Error spamming console after some games

### ISSUE THREAD

**Issue by djrefor** [Zet0rz/nzombies#235]
[ERROR] addons/nzombies/gamemodes/nzombies/entities/entities/random_box/shared.l
ua:178: attempt to call method 'GetOpen' (a nil value)
1. fn - addons/nzombies/gamemodes/nzombies/entities/entities/random_box/shared
   .lua:178
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**Comment by Zet0rz** [comment]
Should hopefully be fixed in 3d0510cc1f97772cb5152d79bf40ad1733be18bf. Haven't been able to recreate it, but from what it looks like this will fix it.
