### ISSUE TITLE
Spawning breaks dynamic lights

### ISSUE THREAD

**Issue by Worset** [Zet0rz/nzombies#237]
I set up some dynamic lighting on a new config, and they save just fine. However, when I spawn in-game (creative mode or otherwise), they disappear - not as in they just don't activate, their entity vanishes completely. Loading the config after I have spawned brings them back, but going out of and back into the game again makes them vanish again. 

**Config loaded before spawn:**
![20160618181209_1](https://cloud.githubusercontent.com/assets/18449391/16172406/55243ad6-3580-11e6-95f4-d2b9c4a680aa.jpg)

**Config loaded after spawn (a few seconds later):**
![20160618181223_1](https://cloud.githubusercontent.com/assets/18449391/16172409/650965fc-3580-11e6-86a1-100eb63e9af2.jpg)

**Comment by Zet0rz** [comment]
Thanks, edit_dynlight wasn't added to the exclusion list in the map cleanup function! This has been fixed in the update I will be pushing later today! :D

**Comment by Worset** [comment]
Awesome. Thanks for the quick response :D

**Comment by Zet0rz** [comment]
Fixed in 3d0510cc1f97772cb5152d79bf40ad1733be18bf
