### ISSUE TITLE
new zombie count

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#239]
let's be honest. the way the number of zombies is calculated is not very good....
if i recall the workshop uses something like 

> return math.Round(GetConVar("nz_difficulty_zombie_amount_base"):GetInt()*math.pow(round,GetConVar("nz_difficulty_zombie_amount_scale"):GetFloat()))

i use something like 

> return math.Round(((.089125_math.pow(round,2) - .010375_round + 9.282) \* #plys or GetConVar("nz_difficulty_zombie_amount_base"):GetFloat() ) \* GetConVar("nz_difficulty_zombie_amount_scale"):GetFloat())

thing is while mine is a basically closer to the actual zombie calculation it is not very good when 10+ people are on. so i spent a few hours getting a function that correctly reflects the original gamemode zombie count function in a way that allows any number of players to be on.

> ```
>   local plys = player.GetAll()
>     local numply = #plys
>     local numzomb = 10
>     if round <=0 then return 5 end
>     if round < 5 then
>     numzomb = (2.8*(1.9*(round%5)))*numply + (2.5 + 2*(round%5))
>     elseif round < 10 then
>     numzomb = (10.4*(1.32*(round%5)))*numply + (10.5 + .4*(round%5))
>     elseif round < 15 then
>     numzomb = (17*(2.36*(round%5)))*numply + (12.5 + -.2*(round%5))
>     elseif round <20 then
>     numzomb = (28.8*(3.05*(round%5)))*numply + (11.5)
>     else
>     local e1 = .0653 *math.exp( .4473 * numply ) 
>     local e2 = .0442*math.pow( numply,2) - .1804*numply + .0382
>     local e3 18.234*math.exp( .2414 * numply)       
>     numzomb = e1*math.pow(round, 2) + e2*round + e3
>     end
> ```

```
    return numzom
```

tell me what you think! (note, it is NOT fully tested. i could have made a mistake and all of the sudden their are 90000 zombies!)

**Comment by jaxjaxk** [comment]
in case you are wondering here is how i got the numbers.
i got all the data i needed form the calculator found here http://zombulator.com/ ( i located the calculation functions used)

there were 4 separate functions for when 1-4 players were on. on top of that wave 1-20 were not determined by functions but rather an array.

so i put the 4 arrays into excel and plotted to determine a fitting function where y is the number of zombies and x is the number of players. i did this for both the arrays and the function.

in the end this is what i got.

**Comment by jaxjaxk** [comment]
also if you would be so kind as to make a time limit for rounds. i also have data on how to calculate that accurately as well if you wish to implement that ( seeing as how bugs happen and people do not want to be stuck on the same wave forever)

**Comment by Zet0rz** [comment]
I am aware that we should probably change the calculation function to make it dependant on the amount of players, but these function seem excessive. I think I recall something like a base count, a scaling per-round count, and a scaling per-player count all added together to give the total. That'd probably work out better.

**Comment by Zet0rz** [comment]
This is what I'm referring to: https://youtu.be/nxOTwyPtzm4?t=4m18s

**Comment by Zet0rz** [comment]
Could make it `base + (scale * (#player.GetAllPlaying() - 1)) * round` where base would be 6 and scale could be something like 0.4, both of which are convars. All results rounded.

**Comment by jaxjaxk** [comment]
@Zet0rz  you are more than welcome to use that formula but i have yet to find a place that confirms that is the correct count. if i recall that is more of a rounded. keep in mind more than 4 players will be on so this will not be as accurate as what i have.

**Comment by Zet0rz** [comment]
Changed in update 1af80034dc69ff94c99ddd6c17ce85698ecb7f2b. **Make sure to update your convars so it doesn't scale extremely!** Scale should be something like 0.35, not 1.01!
