### ISSUE TITLE
inacurate tombstone perk

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#240]
according to http://callofduty.wikia.com/wiki/Tombstone_Soda
tombstone despawn 90 seconds AFTER the player who died respawns. as it is now the tombstone despawns 90 seconds after the player dies.

i do not have a lot of time in the next few days to fix this so let me give you the best suggestion i have for fixing it.

i recommend an array/table to house a list of tombstones to be placed that is filled during rounds. ( holds the player, position etc needed to spawn one in correctly in the right spot)

when the player suicides with tombstone it is added to the array mentioned above.

then at the start of every round the tombstones are spawned in and the array cleared.

sounds simple right?

**Comment by Zet0rz** [comment]
I just changed it to do this exact thing, but it may count spectating as respawning. Can you confirm this actually happens? The logic I use right now should be more efficient than a table and should also not rely on round respawning (e.g admin/cheat respawn).

**Comment by jaxjaxk** [comment]
@Zet0rz my version is about a week old and i can confirm several times that when you die it spawns in. have you changed it in the past week?

**Comment by Zet0rz** [comment]
I changed it to start the timer here one day ago in update 57c1952e155866fab8e2d750feccc3f7506ed1a8. It still spawns when you die, but it doesn't disappear until after 90 seconds and doesn't start counting those until its owner has respawned.
