### ISSUE TITLE
revive sign bug

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#242]
when a player is downed and they drop out then drop back in the sign above their head that says "revive" stays where they were downed and when the spawn back in the sign is always on them.

i am running a version that is 5 or so days older so it might have been fixed already.

**Comment by Zet0rz** [comment]
Good call, this is likely because it's not resetting on players dropping out. Will look into and fix :)

**Comment by Zet0rz** [comment]
Looking into this, it does in fact call RevivePlayer on players dropping out, making resetting their status. Do you mean on crashes/direct disconnects or via in-game drop out?

**Comment by Zet0rz** [comment]
I'd like more info, otherwise I will have to consider this an invalid report.
