### ISSUE TITLE
PAP price wrong

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#243]
for some reason the price to pap any of the weapons i have is 2000. the price says 5000 as it should but it only takes 2000 from players. any ideas?

**Comment by minin43** [comment]
This is true on my version as well. It says 5000 point but only uses 2000 points

**Comment by Zet0rz** [comment]
Could be a bug in the condition check on whether it's supposed to reroll attachments or not. I'll look into it. Does it happen with CW2/FAS2 (attachment) weapons, or normal ones?

**Comment by jaxjaxk** [comment]
@Zet0rz this happens to CW2, FAS2 and i think maybe just all weapons.

**Comment by Zet0rz** [comment]
Yeah likely a bug then. Will look into it!

**Comment by Zet0rz** [comment]
This has been fixed in a local copy I have - will be part of next update.

**Comment by Zet0rz** [comment]
Fixed in 1af80034dc69ff94c99ddd6c17ce85698ecb7f2b
