### ISSUE TITLE
Monkey bombs + Exploding Zombies...

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#245]
= Severe server lag (to such an extent that the client thinks it has lost connection)

it can take up to 10 to 15 seconds to reconnect.

**Comment by Zet0rz** [comment]
As in the moment it explodes and kills a lot of zombies? Have you tried with normal grenades? It might be specifically due to the targeting nature of Monkey Bombs, or it could be because of just a mass killing. Try killing just as big a group of zombies with another explosive weapon.

**Comment by minin43** [comment]
It only happened when the explosion of the monkey bombs would have killed an exploding zombie. I can provide footage if needed

**Comment by jaxjaxk** [comment]
i can not replicate this problem. do you have the server running on bad hardware or is your computer not the best?

**Comment by Zet0rz** [comment]
> exploding zombie

Fire zombie?

**Comment by minin43** [comment]
> Fire zombie?

Yes that is what I meant

**Comment by Zet0rz** [comment]
Can you confirm if it is the same as #247 ?

**Comment by minin43** [comment]
I will attempt to if I can remember to

**Comment by Zet0rz** [comment]
Fixed in b7d2afff09dcd9c753959f4893a7eae05943ee1d. Refer to #247 for explanation on fix.

**Comment by lolleko** [comment]
But wasn't this issue opened before you fixed invulnerability? 💁

**Comment by Zet0rz** [comment]
Yeah that was the cause. 
Edit: Read that wrong, no I don't think so. Disabling the line fixed it, so it had to be from then.

**Comment by minin43** [comment]
It was the cause.
