### ISSUE TITLE
Morphine

### ISSUE THREAD

**Issue by Lebofly** [Zet0rz/nzombies#249]
Sometimes when reviving a teammate you're stuck with morphine as your weapon and you can no longer pick up/switch to other guns. Solved by reviving another team mate but that isn't always possible.

**Comment by jaxjaxk** [comment]
for the time being i recommend in the primary attack function setting up a timer to switch the weapon back.

**Comment by Zet0rz** [comment]
Fixed in the special weapons rewrite.
