### ISSUE TITLE
Reloading Issues

### ISSUE THREAD

**Issue by ToroidalZer0** [Zet0rz/nzombies#255]
I have no clue what's causing the issue. Im using the nZombies workshop collection addons.

**Comment by minin43** [comment]
So what are you expecting someone to say...

**Comment by Zet0rz** [comment]
Umm what? What 'Reloading issues'?

**Comment by ToroidalZer0** [comment]
What I mean is when I ammo in my magazine for any weapon I can't reload my weapon

**Comment by Zet0rz** [comment]
Did you even read the FAQ on the Workshop page for the Content Pack?

**Comment by Zet0rz** [comment]
I'm gonna assume it was the 200+ weapons bug as the FAQ refers to. Give a reply if it isn't that and it's still broken, and then I'll reopen this and we can look more into it :)
