### ISSUE TITLE
HELP IT WONT RELOAD

### ISSUE THREAD

**Issue by the3picbrony** [Zet0rz/nzombies#260]
ok so when I'm in creative mode I can give myself a gun and reload but if I start playing the actual game it wont reload it will just make a clicking sound over and over again and wont stop HEKLLLP and we used weapons that cant reload and it will act like it fires but it dosent do damage IM SO CONFUSED

**Comment by Zet0rz** [comment]
Did you read the FAQ on the Workshop page for the content pack (The one that said "READ BEFORE ASKING!")?
![](http://i.imgur.com/kaER0bZ.png)

In all honestly though, I have absolutely _no clue_ why it works in Creative but not in Survival. Nothing weapon-based is handled differently :/

**Comment by func-octo** [comment]
Actually, the pac-a-punch may be the culprit with the "give all attachments" thing.

**Comment by the3picbrony** [comment]
oh and when I try to create a nav mesh it says no walkable seeds and I'm very confused cause I tried looking it up and couldn't find anything

**Comment by Zet0rz** [comment]
That is a different thing and not one we are going to be covering. If you looked it up you should've come across this site which has the answer to your question:
https://developer.valvesoftware.com/wiki/Navigation_Meshes
Also one of the top hits on google of "No walkable seeds found"
https://forums.newworldinteractive.com/printthread.php?tid=174
