### ISSUE TITLE
fire sale music

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#261]
even after the fire sale ends the music keeps playing forever.

**Comment by Zet0rz** [comment]
Not forever, just for the full duration of the file. sound.Add stopped working randomly after a Garry's Mod update which was required to be able to stop the sound again. Haven't really looked into it ever since other than changing it to a simple EmitSound (which can't be stopped)

**Comment by func-octo** [comment]
Have you tried stopping the sound on the prerelease branch? There always seems to be something happening there.

**Comment by minin43** [comment]
Alternatively, you could just cut the fire sale music down to the 30 seconds fire sale runs for.

**Comment by func-octo** [comment]
> Alternatively, you could just cut the fire sale music down to the 30 seconds fire sale runs for.

Although that's a good point, it is easy for people to set the fire sale to any length of time, and this would  make it sound bad after 30 seconds because the music would just cut-off.

**Comment by Roachdaripper** [comment]
local fsale = CreateSound("classname_of_mysterybox","path/to/sound.wav")
fsale:SetSoundLevel(SNDLVL_NONE)
if !fsale:IsPlaying() then 
fsale:PlayEx(1,100) 
end

What that does is it creates a CSoundPatch which can then be controlled via Play(), Stop() or FadeOut().
I used PlayEx() since it allows you to set the volume and the pitch (in that order) without the two extra lines

**Comment by Roachisserie** [comment]
local fsale = CreateSound("classname_of_mysterybox","path/to/sound.wav") -- Creates CSoundPatch
fsale:SetSoundLevel(SNDLVL_NONE) -- Makes it play everywhere
if !fsale:IsPlaying() then -- Are we currently playing?
fsale:PlayEx(1,100) -- If not then play the sound with max (1) volume and normal (100) pitch.
end

"fsale" can then be controlled via Play(), Stop() or FadeOut().

EDIT: Added comments to each line.

**Comment by Roachisserie** [comment]
You should probably only do this for one mystery box, as otherwise you'll probably play the sound multiple times.

**Comment by Zet0rz** [comment]
Tried it again with the latest update. `sound.Add` works just fine, but `entity:StopSound` does nothing at all. `CreateSound` also just doesn't play anything at all.
