### ISSUE TITLE
[Suggestion] Making jumping optional in nz_zombiebase

### ISSUE THREAD

**Issue by Roachisserie** [Zet0rz/nzombies#262]
I've talked with Zet0r about possibly making some -official- extensions for the gamemode, namely bosses since I've ported a handful of boss zombie models from CoD, although as they weren't originally intended for nZombies, they don't have jumping animations.

> For them to be official they need to be 100% compatible
> -Zet0r.

So is it possible to make jumping optional in the zombie base?

**Comment by lolleko** [comment]
Just set `ENT.JumpHeight` lower or equal then 22 (step height). This should disable all jumping (pathing logic, aswell as the actual jumping).

NOTE TO MYSELF: The 22 in the if statement should new replaced with self.StepHeight https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/entities/entities/nz_zombiebase.lua#L742

**Comment by Roachisserie** [comment]
Alright also lolle can you accept my friend request? I accidentally removed you while cleaning up said friendslist.

**Comment by lolleko** [comment]
Ohh yeah sure, I didn't even noticed that :D
