### ISSUE TITLE
revived while downed bug

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#263]
let's say you get downed. if the person reviving you gets downed while reviving you then you remain in the "being revived" state and never actually die. you just stay there until someone either revives you or everyone else gets downed and the game ends.

**Comment by Roachisserie** [comment]
I'm pretty sure a few IsValid()'s should sort that out. Don't quote me on that though since I haven't looked at the code.

**Comment by Zet0rz** [comment]
Yeah I think it's missing some checks, which would also be why #249 happens.
