### ISSUE TITLE
custom max ammo number

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#264]
maybe in weapons we should add a variable like "SWEP.maxammo = integer".
if the number exists then that is the number for the weapons max ammo, if not we use the default max ammo calculate function. the reason for this is that some weapons like snipers and mini guns should give more or less ammo then they do. naturally it should ignore the ceiling cut off ( i believe 500 or so)

**Comment by Roachisserie** [comment]
For that to work Zet0r would need to heavily restrict what weapons could be used, especially if someone who doesn't really know lua (at all) wants to play nZombies,, since it pretty much disallows players from using workshop guns.

**Comment by Zet0rz** [comment]
This already exists in the form of a function:
https://github.com/Zet0rz/nzombies/wiki/Weapon-Modifications-&-Attributes#max-ammo-function

> since it pretty much disallows players from using workshop guns.

I think you misunderstood, this would be an optional field. If it isn't there, it would assume normal behaviour (just like the max ammo function already does).
