### ISSUE TITLE
max clip size at 244

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#265]
OK so i KNOW that pretty much 0 normal weapons have a clip size over 100. thing is i have a minigun. the main issue is that the HUD will only display a clip size up to 244. it will decrease as normal but when it hits 0 it will jump back up to 244 until you actual run out of clip.

**Comment by Zet0rz** [comment]
I've come across this before. This is a bug I'd like to fix.

**Comment by func-octo** [comment]
You could get primaryammo count and then have a custom text "label" that displays the real number rather than a max of 244.

**Comment by func-octo** [comment]
Well here's some defeating evidence that the clip size isn't maxed to 244.
![gm_flatgrass0019](https://cloud.githubusercontent.com/assets/10675391/17215156/eceded1a-54a9-11e6-8719-a6019ffd6067.png)

**Comment by Zet0rz** [comment]
> Well here's some defeating evidence that the clip size isn't maxed to 244.

The ammo display is in no way limited (why would I add a limit?! xD), this is a bug seen on certain weapons. The ammo display directly uses wep:Clip1(), so the bug has to be in the weapon clip size handling of the game itself. Regardless, it's something I want to try and make a workaround for.

**Comment by minin43** [comment]
I can attest, I come across this bug myself.

**Comment by globalcringe** [comment]
This isn't a bug with the gamemode, it's a bug with how servers network the clipsize. It's maximum proper viewing size is 254, any higher and it'll overflow to -1, then 0, and so on. This doesn't effect the clip-size, however. This also won't happen in single player.

**Comment by Zet0rz** [comment]
Seems like we might not be able to fix it then.
