### ISSUE TITLE
ZE and objective map compatablity suggestion

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#266]
I'm sure we all know of the existence of zombie escape maps. thing is NZ is not compatible with pretty much any of these maps. 

so here is how i recommend we fix this. a simple option in the ZS map settings that says "zombie escape map".

now what that option does is that whenever a door is opened ONLY the spawners with that flag will spawn zombies. all other spawners are disabled.

**Comment by Roachisserie** [comment]
tl;dr add zombie escape option which disables spawner flags for all rooms except the one you're in.
I.E if you open up the first door disable flag 0.

**Comment by Zet0rz** [comment]
![](http://i.imgur.com/5lTKZLy.png)

**Comment by Zet0rz** [comment]
Although it is not finished, there are some entities missing. Refer to #189 for this feature. Discuss new potential entities and behaviours there.

**Comment by jaxjaxk** [comment]
for ZS compatibility whenever a door is opened it should also trigger the zombies to become a wave or two harder. just a thought as playing with zombies only on wave one would be easy to do.

**Comment by Zet0rz** [comment]
It is only for the objectives/map features, core gameplay will not change. You will still face limited zombies per round and rounds will still advance.
