### ISSUE TITLE
Entity Suggestion

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#270]
Suggestion: under the entities tab (the one with the fog and color correction), can you add in some form of player deterrent? Like radioactive shit (the sort of stuff that would set off a Geiger counter in the game) or fire damage or something.

I ask this because I have maps where an invisible deterrent (such as poisonous gas) would be fit the map better then a fence or rubble. Is this at all possible?

**Comment by Zet0rz** [comment]
Sounds like a good idea. I will look into it, but I can't guarantee it'll work properly or how much resource-intensive it would be. But I imagine I could make an edit_\* entity that allows you to set radius and it'll damage if you are inside of it.

**Comment by minin43** [comment]
That'd probably work. I've got some water area I don't want players in (but DO want zombies in) and something like I suggested would be perfect for it

**Comment by Zet0rz** [comment]
Check the new Damage Wall tool added in commit baf22e1d759e35640c110dee741f56b91b5a868e. You can set a few different types for different effects, delay and damage can also be set. I also have a spherical version that was scrapped in favor of this, if you feel that's better I can try working on that again.

**Comment by minin43** [comment]
I'll give it a shot, it sounds like it might be exactly what I need. Thanks!
