### ISSUE TITLE
Witcher Gates

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#271]
I saw this awesome addon http://steamcommunity.com/sharedfiles/filedetails/?id=727161410, and thought of bo3 zombies with the portals. If this were a part of nZombies, we could use them to allow players to enter other areas of the map much like bo3 does. It's also very light on resources.

https://www.youtube.com/watch?v=44HcsS1vGrk
Watch this video for a demo.

**Comment by minin43** [comment]
As far as I can tell, Zetor doesn't like ripping off other addons

**Comment by Zet0rz** [comment]
Well add it to your Entities tab in the spawnmenu. Entities from here get created via gmod's duplicator functions, so they are essentially completely recreated. Should work for other people as long as they also have the addon installed. If it doesn't, I'll try to make custom entities to work.

**Comment by func-octo** [comment]
How would I do that exactly? I don't know much about adding entities. Also the gates aren't entities, they are tools.

**Comment by func-octo** [comment]
But I guess they're entities after they are placed :P

**Comment by func-octo** [comment]
?

**Comment by Zet0rz** [comment]
https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/gamemode/q_menu/sh_populate.lua#L114-L120

Unless the tool does something special other than just spawning it, then this should work. If not, then you'll probably need the tool.

**Comment by func-octo** [comment]
I didn't see that earlier. Thanks for your help! I'll let you know if this works, because if it does, it'll be awesome.

**Comment by func-octo** [comment]
Yeah, I need the actual tool :/ Any way to grab it from sandbox and dump it into nZombies?

**Comment by Zet0rz** [comment]
You could script your own tool fairly simply, doing the same thing it does to the portals on spawn. However for now it won't save with the config (unless you make it spawn it and insert it to the Entities table from the QMenu which should actually be pretty easy), but we'll be adding custom save/load modules as well.

**Comment by func-octo** [comment]
Ok. As far as I'm concerned, It isn't a physgunnable entity unless it was spawned on a physics prop (yes that works!) and I also don't know how to find the entity name because it doesn't exist in the sandbox entity tab.

**Comment by func-octo** [comment]
Also just found that if you revive a player after a game ends, that player can walk around with a gun. So yeah...

EDIT: If that player is still walking around with the gun they had last game and players start readying up, they can use that gun in the next.

**Comment by func-octo** [comment]
And when a game ends any panzers in the map are not despawned

EDIT: Actually they are, but not for sevral seconds.

**Comment by func-octo** [comment]
Update on the gates: The latest update adds an entity to the addon! All I have to do is spawn two and link them up :)

**Comment by func-octo** [comment]
The entity spawn was a complete success; however, I need the color tool to make them something other than white...

**Comment by Zet0rz** [comment]
If you're using a custom tool, you can make those apply the color. If not, you might be able to use an EntityCreated hook or something like that to find all portals created and color them. Alternatively you could make it a tool.

**Comment by jaxjaxk** [comment]
@OctothorpeObelus can the zombies go through the portals too?

**Comment by func-octo** [comment]
Well, I have no idea, since, for some reason, they do not work in nZombies.

**Comment by Zet0rz** [comment]
> Well, I have no idea, since, for some reason, they do not work in nZombies.

It was coded for Sandbox, there'll likely always be errors when used in another gamemode. Also zombies might be able to teleport through them, but there is no way the navigation has any idea the portal even exists, so they'd never walk towards it.

**Comment by minin43** [comment]
> but there is no way the navigation has any idea the portal even exists, so they'd never walk towards it.

Not true, you can fool it into thinking so if the portal is down a corridor (as in, you can only reach it from one direction) and you edit the nav mesh to make a single little area under each portal connect to one another. It might be really janky, but it could work.

**Comment by Zet0rz** [comment]
Oh yeah with Navmesh editing anything can really be made, but nothing for dynamic spawning of them such as tools or a spawnmenu.

**Comment by minin43** [comment]
Oh and by the way, are we ever going to get nav mesh updates, for ladders and such? What's facepunch been up to?

**Comment by lolleko** [comment]
Idk what they are up to. But it doesnt look like they have done anything nextbot related in the past month. So really no idea.

**Comment by func-octo** [comment]
A shout out to facepunch (for the astronomically low chance ^ -2 that they see this), Update the navmesh system to be more resource efficient!!
