### ISSUE TITLE
whos who and tumbstone

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#276]
for some reason after a player uses tumbstone or whose who ( get downed and use perk) they are no longer able to use quick knife or grenades.

it should be noted that i use custom grenades and a custom quick knife. i doubt that is the issue after i have seen the code for whos who and tumbstone.

**Comment by func-octo** [comment]
I will test this on a "vanilla" state, and tell you if you custom stuff is the issue or not. :+1:

**Comment by func-octo** [comment]
No evidence of this happening on base version. I have tried just who's who (both crowbar and grenade worked), and Who's Who + Tombstone. Quickknife and Grenades still work. It could be your custom things.

**Comment by Zet0rz** [comment]
It _is_ custom things. Tombstone and Who's Who give back all the weapons stored from when the player dies, which is then given directly back like normal when picked up. If you didn't register your custom knives and grenades with the Special Weapon system properly, then they won't register as special weapons and the system will think "This guy isn't carrying any knife" and won't knife.

If you did in fact register it like normal, then I'd like to see your code for doing so.

**Comment by Zet0rz** [comment]
I will consider this a fault in your modifications and close this issue in a day or two if we don't hear from you. If we do after it has been closed and your claim is valid, I'll reopen the issue.

**Comment by jaxjaxk** [comment]
do i make them special weapons or something? because i changed the files to replace all the weapons names and everything.

**Comment by Zet0rz** [comment]
You need to register them as special weapons or the game won't know it's a knife you just picked up, since gmod doesn't have fancy weapon slot systems. I'm reworking the special weapons system to make it more simple and easy, don't bother too much with it now.
