### ISSUE TITLE
Cheats Not Working On Players With Spaces In Their Names

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#277]
As the title suggests, cheats can not be used on players with spaces in their names because it takes the player's name as separate strings (spaces being natural dividers) and then says [NZ] No valid [thing here] provided.

Example: Name = `Octothorpe Obelus (Team Heavy)` /giveperk Octothorpe Obelus (Team Heavy) dtap2 (or using the cheat menu) it thinks that the player is Octothorpe and the perk trying to be given is Obelus.

**Comment by Zet0rz** [comment]
Yeah it splits arguments with space. I'd like it to work with quotation marks for words with space, but it's something I'm not working on currently.

**Comment by lolleko** [comment]
Yes, I wanted to implement it with quoted strings. But Lua string.Split() doesn't support regex. So i was lazy and just didn't do it.

EDIT: Did it in #279 currently untested tho.
