### ISSUE TITLE
the noobie f1 issue

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#282]
Any reason not to add:

```
ply:ConCommand("nz_settings")
```

to:
https://github.com/Zet0rz/nzombies/blob/2341c9d712ad612d2c18e16821a71bc701b71115/gamemodes/nzombies/gamemode/chatcommand/sv_chatcommands.lua#L20

**Comment by Alig96** [comment]
https://github.com/Zet0rz/nzombies/issues/281

**Comment by lolleko** [comment]
Good idea!
Some more suggestions:
- Visible controls somewhere if the f1 menu is open
- A giant close button (X) somewhere.

**Comment by Alig96** [comment]
The gian close button wouldn't work because the game binds the user controls. IIRC. So they can't move to the X

**Comment by Zet0rz** [comment]
I added this though
![](http://i.imgur.com/DDTkhAn.png)
"Press F1 to toggle this menu" which when clicked also toggles it.

**Comment by Alig96** [comment]
Its not simple enough if there are people are still creating issues about it

**Comment by lolleko** [comment]
Isnt there a close button if you arent an admin anyway?
And i'm pretty sure that's as simple as it can be!
So if you are not admin you have a close button. And if someone is an admin (aka able to setup a server, someone should be smart enough to close a god damn window.

**Comment by Alig96** [comment]
But there's the issue; people are still making issues about it so something needs to be changed, what i said was merely a suggestion. Sometimes you gotta really hold their hand and do it for them

**Comment by Alig96** [comment]
It may seem simple to you and i, but it doesn't look like it is for other people

**Comment by Zet0rz** [comment]
> Isnt there a close button if you arent an admin anyway?

Yes there is

> And i'm pretty sure that's as simple as it can be!

Creative Mode is way more advanced than this, if they can't use this menu then the entire gamemode will be too complicated, even just to load a config.

**Comment by lolleko** [comment]
Also if "we do everything for them" they will never be able to use that menu ever (because they never learned it) :D
But i think there is nothing wrong with closing the menu after readying up.

**Comment by Alig96** [comment]
Its one additional line to the code; is it really this big of a change to discuss? I personally think it should be implemented, because even if you do know about the menu, you're going to press f1 to close it to play, if anything this is a win win for everyone

**Comment by lolleko** [comment]
I already said twice that we should implement your suggestion! I am just saying people will always be to stupid for something regardless what we do! :D

**Comment by Alig96** [comment]
Apologies; im retarded haha, so its settled?

**Comment by lolleko** [comment]
Sure, done in #283!
