### ISSUE TITLE
not getting tools in creative mode

### ISSUE THREAD

**Issue by Kraschamycket** [Zet0rz/nzombies#284]
im not getting the god damn tools in creative, i was going to make a map for it and play it for my channel, but it does not work, i dont get the tools for creative, how can i fix?

**Comment by func-octo** [comment]
Ok. Be sure you don't have two versions installed over-top of each other. I recommend deleting everything inside the nzombies addons folder and download the newest version, then install it.

**Comment by Zet0rz** [comment]
Suicide and respawn. Must be some addon that prevents the player class' Loadout function from running, which is what gives you your tools. For some reason the second time you spawn it works. Maybe it's because the player class is set after spawning (which is really wierd if so)?

**Comment by Kraschamycket** [comment]
i got it to work a while ago

**Comment by Zet0rz** [comment]
What did you do?

**Comment by Kraschamycket** [comment]
i disabled alot of my mods
