### ISSUE TITLE
Panzer's death plays HL2 explosion sound over panzer explosion sound

### ISSUE THREAD

**Issue by Roachisserie** [Zet0rz/nzombies#286]
Title says it all.

Fix: 
effectdata:SetFlags(4)

EDIT: (Zet0r already knows this but I'll put it here too so everyone else knows)
The reason I didn't submit this as a pull request is because I'm on a temporary laptop while my desktop is in need of repair, I don't have a branch of the git on this laptop nor do I have the github application.

**Comment by Zet0rz** [comment]
I'm not sure this is something to "fix". It isn't really a problem, is it? The panzer explosion sound's main thing is the buildup, after that the explosion sound doesn't really matter. I found the panzer explosion sound to not fit the default explosion from this effect, and it's also silent after a certain distance (whereas the gmod explosion echoes nicely). However when (and if) I completely replace the explosion effect with an actual custom one, it'll use a different sound obviously.

**Comment by Roachisserie** [comment]
Eh. It's more of a nitpick than an actual worrying/urgent issue. But I could always make the new effect.

**Comment by func-octo** [comment]
I also noticed that the panzer explodes then immediately disappears as if the corpse was teleported away. I feel as if there was supposed to be a smoke cloud to hide that...
