### ISSUE TITLE
Zombie Spawning is wank.

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#289]
I've already brought this issue up with Zetor, but for anyone else who might know a solution, the zombie spawning is extremely strange and only chooses specific spawns to use. You can have 1-8 spawns available for use and depending on other factors, none to ~3 of them might get used.

Notice how there are 4 spawners, but only 2 get used for every zombie spawn. https://youtu.be/m-8XQcOX3UM

**Comment by Zet0rz** [comment]
The odd thing is I did some quick testing today and everything worked 100% good. It seemingly happens randomly and not always.

**Comment by minin43** [comment]
It has happened 100% of the times I have played on the that map, and it's always the same spawns that spawn zombies. The one's that don't spawn zombies never do.

**Comment by Zet0rz** [comment]
Try changing the player spawnpoint to another room. Will zombies still spawn on those 3 or now new spawnpoints (but still only them)? It might be because it doesn't update properly but works fine initially.

**Comment by minin43** [comment]
Like, a different purchasable room, or just move the spawns around?

**Comment by Zet0rz** [comment]
Doesn't matter, you just wanna test if other spawnpoints can activate instead of your 3 ones so move the player spawns to other zombie spawnpoints instead (and remove the door link from those). If it is always a matter of only the spawnpoints during the first refresh, then we can figure it out.

**Comment by func-octo** [comment]
Although I'm a little late to the party, I did notice that as well, but in my case, I had 8 spawn points but only 6 of them were used because the other 2 were in really cramped spots where zombies probably wouldn't spawn because they'd get stuck.

**Comment by minin43** [comment]
Okay, tried moving the spawn and it changed nothing. The zombies still only spawned in the same spots.

**Comment by Zet0rz** [comment]
Give it a try in commit a4657b7deb167310e38ff017964daefbe344c776 on the development branch. It now distributes differently, you can read how with the comments in the code

**Comment by Zet0rz** [comment]
We have confirmed it working perfectly now in the dev branch. It was due to the global spawner still getting a cooldown even if the spawning failed (which happened more the more spawnpoints were blocked).
