### ISSUE TITLE
Development Version Zombie bug (2 players)

### ISSUE THREAD

**Issue by SarinaNubbs** [Zet0rz/nzombies#290]
When we played rounds most zombie spawners didn't work when you got close to them in closed area
in open didn't spawn at all,
this is what popped up for both of us when we killed a zombies 

[ERROR] addons/nzombies-development/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:58: attempt to call method 'SetUsingSpecialWeapon' (a nil value)
1. unknown - addons/nzombies-development/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:58

**Comment by func-octo** [comment]
Sounds like the Special Weapons System again... As far as I know, Zet0r is still rewriting this, so it may be like that for a bit longer :\

**Comment by Zet0rz** [comment]
The error is not related to spawning zombies, it's likely a bug with the function not existing on the player yet. The spawn issue is the same as #289, closing this to prevent duplicates.
