### ISSUE TITLE
Server's crashing...

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#293]
Got to round 15 and everyone died, once the map was supposed to reset itself, the server crashed shortly after console was spammed with this error:

CreateNoSpawn (entity_blocker): only works for CBaseEntitiesNot creating entity 
 'entity_blocker' - too many edicts! (8096 current, 8192 max)

**Comment by lolleko** [comment]
The game crashed because too many entities were alive at once. The edict_t(entity dictionary) struct only supports up to 8192 (in gmod). Either you did a shit ton of map editing (and/or the map is large) or the gamemode does not clean up some entities correctly.

**Comment by minin43** [comment]
8000 entities sounds wrong. There's no way that's an issue on my end.

**Comment by lolleko** [comment]
Keep in mind almost everything expect static world stuff, is an entity. The next time you play so many rounds `lua_run PrintTable(ents.getAll())` and post it to pastebin so we can have a look.

**Comment by minin43** [comment]
No console related to gmod supports 8000 lines... D:

**Comment by lolleko** [comment]
try -condebug as startup parameter, this should save a console.log file somewhere in your gmod directory with all the console lines of the game session.

**Comment by Zet0rz** [comment]
Or try `lua_run file.Write("entity_debug.txt", util.TableToKeyValues(ents.GetAll()))`. Not sure if that is readable with 8k entities though.

**Comment by minin43** [comment]
I haven't experienced this issue since it first happened so I'm assuming it's a one-time thing.
