### ISSUE TITLE
Letting a zombie spawn inside a wall or ceiling causes an infinite loop

### ISSUE THREAD

**Issue by globalcringe** [Zet0rz/nzombies#295]
Steps to reproduce:
1. Look at wall.
2. Spawn a zombie.
3. Once zombie tries to move, the server will enter an infinite loop, throwing the first core to 100% usage  forever until manually rebooted.

This might be the cause of some crashes people have been talking about.

**Comment by lolleko** [comment]
Like you said only happen if you spawn a zombie into a wall. This cannot happen during a normal game since there is no way for a zombie to get into a wall.

TL;DR don't spawn zombies in walls and you will be fine lol.

**Comment by Zet0rz** [comment]
I thought we fixed all short circuits? Anyway, I'll look into whether or not this happens and fix it if so. Did you spawn it using the test zombie tool or lua commands? Or a spawnpoint?

**Comment by Zet0rz** [comment]
Found and fixed it, it was if pathResult was "failed". There was a timeout commented out there, readded it and now it doesn't crash. Will be on dev branch soon and be part of the next update.

**Comment by Zet0rz** [comment]
Fixed in commit c627d15b81b2961ee3b118ed39cb8128f83caa56 on the development branch. The updates over there are soon complete and can be merged into the main branch.
