### ISSUE TITLE
Cannot Customize Attachments for CW Packs

### ISSUE THREAD

**Issue by NinjaWitaSniper** [Zet0rz/nzombies#297]
When I get a CW gun and press C it brings up the GUI for the attachments but i cannot select one.

Am I  the only one getting this?

**Comment by Zet0rz** [comment]
This is intentional. You need to Pack-a-Punch to get attachments, just like how it is in CoD.

**Comment by NinjaWitaSniper** [comment]
Thank you, sorry to take time out of your day for such a stupid question xP
