### ISSUE TITLE
Headshots

### ISSUE THREAD

**Issue by Lucius1202** [Zet0rz/nzombies#298]
Headshots do not seem to inflict considerable damage, compared to body shots.

COD headshots seem much more effective. It is just my impression?

**Comment by Alig96** [comment]
Zet0rz & Lolle will be able to provide a better answer, but from doing a bit of snooping, it would seem as though headshots don't actually deal more damage, it will only decapitate:

https://github.com/Zet0rz/nzombies/search?utf8=✓&q=head

https://github.com/Zet0rz/nzombies/blob/b773df4d26f47ff3eaa7b8b1d7da0bff5c77db26/gamemodes/nzombies/entities/entities/nz_zombiebase.lua#L609

The only thing that I saw that deals more damage is the pack-a-punch:

https://github.com/Zet0rz/nzombies/blob/b773df4d26f47ff3eaa7b8b1d7da0bff5c77db26/gamemodes/nzombies/gamemode/enemies/sv_hooks.lua#L66

So unless of the code is elsewhere, headshots do not deal more damage. I'm fairly sure it used to, maybe the lads forgot to re-implement it after refactoring the code.

Edit:
Found it, it seems as though it deals double dmg:
https://github.com/Zet0rz/nzombies/blob/2341c9d712ad612d2c18e16821a71bc701b71115/gamemodes/nzombies/gamemode/config/sh_constructor.lua#L35

Increase this value to do more dmg to your liking.

**Comment by lolleko** [comment]
The headshot are handled here https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/gamemode/enemies/sv_hooks.lua#L44
and here 
https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/gamemode/config/sh_constructor.lua#L33

I have no idea why it doesn't work. But you are right the code probably shouldn't be handled in a table/function in the config file. It should rather be handled on the zombie entity itself.

EDIT: 
Guess you found it yourself :D

**Comment by Lucius1202** [comment]
I played a lot these days, forgetting this addon Active:

http://steamcommunity.com/sharedfiles/filedetails/?id=110871780

So I could compare some locations and the respective damage, considering the number of hits and the impact zones. The gunshots inflict 20 damage, to the head occasionally add 5 points of damage.

In the first wave, three shots to the legs do not kill a zombie.
20x3 = 60

Shooting in the head, they serve still 3 shots.

25x2 = 75

Furthermore there is not always the +5 damage

They should well need 2, and should jump off a -40 to every headshots (20x2).

Perhaps I'm wrong and the addon mentioned above is not the best way to do a check.

it's just something I noticed.

**Comment by minin43** [comment]
I don't know if that addons is the best source of information. The CTakeDamageInfo class has multiple ways to get a weapon's "damage" and they aren't always the same. There might be additional damage done somewhere else in the gamemode's file that the addon doesn't see.

**Comment by Zet0rz** [comment]
Headshots are intended to do double damage. If they don't, I will find and fix it. I have plans on how to rewrite the table functions as well, but it will not be in the zombies themselves. Instead, it'll just be some table with valid zombie classes, and the functions will always all be run the same on all of them.

**Comment by Zet0rz** [comment]
Changed the way damage scaling is handled to always scale x2 on head regardless of the ValidEnemies table. Also removed the dependency on that table for damage-related events. Try and see if it changes anything, if not then it's likely something to do with the hitgroup registration.

**Comment by Lucius1202** [comment]
Thank you for your interest. To try the change we have to wait the code update here?

**Comment by Zet0rz** [comment]
Just change to the development branch and download that instead. It should be fairly smoothed out and errorless, although a few things have still yet to be tested.

**Comment by Lucius1202** [comment]
OK thanks. I take this opportunity to ask another question, in some matches in single player, during the wolf attack, the game freezes with repetitive sound. I have to "kill" gmod. The log file is empty. There is a boot command to get a debug file? Sorry for the wrong place.

**Comment by Zet0rz** [comment]
The launch option to create a console log is -condebug. Let me know if this is related to nZombies, and if so, open a new issue about it. It might also be a thing already fixed in the dev branch, so let us know what branch you found the bug in.

**Comment by Lucius1202** [comment]
I checked the development branch for a few minutes but I can say that the damage to the head seems to work properly. In the first wave the  zombies die with two hits to the head. Making everything fit.

**Comment by Zet0rz** [comment]
Did your damage number addon also show the correct numbers?

**Comment by lolleko** [comment]
I know that addon, i think headshots only worked for TTT. I could be wrong tho.

**Comment by Lucius1202** [comment]
I will check as soon as possible, I can already report a strange thing, the damage that "pop's" out when you hit with the crowbar decreases with the waves, the first inflicts 75, the second 64 and the third 59. I repeat that it is an addon that probably has no authority in showing the damage, only he has the merit of having attracted our attention on the possible issue.

**Comment by Lucius1202** [comment]
First of all I apologize for the previous tests that have been conducted with little attention. I had not noticed the cheats menu, and then I could not use the headshots daiquiri for the certainty of headshots.

So this time ...

I tried the development version again. The map that I tried gave me as a first weapon M1911 pistol, the impact marks 25 damage.
- I set nz_difficulty_zombie_health_scale to 1, so that each zombie has 75 hp in each wave.
- Via the cheats menu I acquired the perk Deadshot daiquiri, for the certainty of headshots.

During the game each shot in the head falls -25, with an occasional and additional -6, or -12, I have never seen a -50.

Zombies die with two or three shots. The calculations are wrong, regardless of the damage of the gun to his head and regardless of the number that jumps out, you should always have the same behavior, or two or three shots. The Deadshot Daiquiri should give a reasonable assurance that the shots are precise.

The worst thing is that the first wave of zombies die with a blow of a crowbar, which drop a -75 (right), in the second wave a hit of a crowbar drop -52 (or -56, now not remember) and NOT kill a zombie.

I will investigate further in the coming days and if someone could do a test to compare the results would be a great help.

**Comment by Zet0rz** [comment]
Deadshot doesn't guarantee headshots, it only makes your aim snap to the head (neck) bone when you aim down sight. Anything after that, you can move it anywhere else on the zombie. Sometimes headshots might not register properly, that could be it. It would probably need some debug messages when it's a headshot to see if it's a registration problem.

Crowbar behaves like it does for balancing reasons. Their health scale isn't the same linear one as in CoD, so the crowbar needs to actually fall in damage to not be too easy to get 130 points with within the first 10 rounds.

**Comment by Lucius1202** [comment]
Ok, then it is explained the mystery of the crowbar. For head shots investigate yet!
