### ISSUE TITLE
Deleting linked doors...

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#299]
So this has actually been an issue for quite awhile now, it's just I hardly ever ran into it.

When you give a map-spawned door lock information, I guess I don't know how the system works, but the door's information is saved somewhere in the config file. Having the door set to be removed fucks over the flag the door is set to (if it's set to one, and setting it to 0 bandages the issue). Right-clicking the door and selecting "unlock" on it does nothing, as far as I can tell, and if you attempt to purchase the "flag"/area the door was associated with, the system isn't smart enough to realize the door is no longer existent, and doesn't make an attempt to remove the door's lock-information before purchasing the area. If that makes sense.

This is the error that appears.
[ERROR] addons/nzombies/gamemodes/nzombies/gamemode/doors/sh_door_meta_accessors.lua:80: Tried to use a NULL entity!
1. CreatedByMap - [C]:-1
   1. DoorIndex - addons/nzombies/gamemodes/nzombies/gamemode/doors/sh_door_meta_accessors.lua:80
   2. GetDoorData - addons/nzombies/gamemodes/nzombies/gamemode/doors/sh_door_meta_accessors.lua:92
      1. OpenDoor - addons/nzombies/gamemodes/nzombies/gamemode/doors/sv_gameplay.lua:2
      2. OpenLinkedDoors - addons/nzombies/gamemodes/nzombies/gamemode/doors/sv_gameplay.lua:31
      3. BuyDoor - addons/nzombies/gamemodes/nzombies/gamemode/doors/sv_gameplay.lua:94
      4. v - addons/nzombies/gamemodes/nzombies/gamemode/doors/sv_gameplay.lua:119
         1. unknown - lua/includes/modules/hook.lua:84

The gamemode then proceeds to eat all your money and the door remains unopened. Can we get a fix for this?

**Comment by Zet0rz** [comment]
Right, so doors removed with the prop remover errors when they are attempted to open via links? And the unlock thing doesn't work?

**Comment by minin43** [comment]
Right

**Comment by minin43** [comment]
Update: right-clicking and selecting "remove lock" on the door DOES indeed remove the lock, but only after saving/re-opening the config. It still shows "Press C to purchase door for 1000 points" but it doesn't seem to retain that after a reload.

And I can't seem to find whatever door I'm seemingly deleting during gamestart that is causing the aforementioned error.

**Comment by Zet0rz** [comment]
It is likely due to not being networked upon being used with these commands. However the tool's right click should update client-side as well, at least it does in single player. Of course reloading the config will force update everything, so that will always work. I'll look into the networking of it and the removal of door links mid-game.

**Comment by Zet0rz** [comment]
Take a look with commit 950c4af285d733dc0dd19eea1b235706393b3821 which should fix those errors. Not sure about the unlock property not working, it works fine on my end.
