### ISSUE TITLE
Timer Error

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#30]
Whenever I type in "/ready" or click it. I wait for five seconds then I can see that the console gives me an error that the timer failed. (Line 16). What do I do?

**Comment by func-octo** [comment]
Can you give the entire error? (Highlight, Ctrl + C, Ctrl + V to paste here)

**Comment by lmao5677** [comment]
@ScriptnLua 
Here is the code

`[ERROR] gamemodes/nzombies3/gamemode/round/sv_round.lua:277: attempt to index global 'RandomBox' (a nil value)
1. SetupGame - gamemodes/nzombies3/gamemode/round/sv_round.lua:277
   1. unknown - gamemodes/nzombies3/gamemode/round/sv_round.lua:16

Timer Failed! [Simple][@gamemodes/nzombies3/gamemode/round/sv_round.lua (line 16)]
`

**Comment by Zet0rz** [comment]
Sounds like the random box module isn't loading in-game. Try putting this into the server console and tell us what it gives you:
lua_run PrintTabel(RandomBox)
In case this errors (table expected, got nil) try replacing RandomBox with nzRandomBox. Tell us if that worked or still errored. 

If it still errors, check your console higher up where it lists the files it loads and see if there's an error on launch.

**Comment by lmao5677** [comment]
@Zet0rz 

> Sounds like the random box module isn't loading in-game. Try putting this into the server console and tell us what it gives you:
> lua_run PrintTabel(RandomBox)
> In case this errors (table expected, got nil) try replacing RandomBox with nzRandomBox. Tell us if that worked or still errored.

It still gives me an error for RandomBox and nzRandomBox

> If it still errors, check your console higher up where it lists the files it loads and see if there's an error on launch.

I can't seem to find any errors when it launches. Have a look here
`nZombies 3.0 Loading...
 ** Client List **
Constructing: config
Including: config/sh_constructor.lua
Constructing: curves
Including: curves/sh_constructor.lua
Including: display/cl_contextmenu.lua
Including: display/cl_fonts.lua
Including: display/cl_gamemodehooks.lua
Including: display/cl_halos.lua
Including: display/cl_hud.lua
Including: display/cl_hudblock.lua
Including: display/cl_papnames.lua
Including: display/cl_scoreboard.lua
Including: display/cl_target.lua
Including: display/sh_properties.lua
Constructing: doors
Including: doors/sh_constructor.lua
Including: doors/sh_door_meta_accessors.lua
Including: doors/sh_sync.lua
Constructing: easter_eggs
Including: easter_eggs/sh_constructor.lua
Including: easter_eggs/cl_ee.lua
Constructing: effects
Including: effects/sh_constructor.lua
Constructing: electricity
Including: electricity/sh_constructor.lua
Including: electricity/sh_sync.lua
Constructing: enemies
Including: enemies/sh_constructor.lua
Constructing: fog
Including: fog/sh_constructor.lua
Including: fog/cl_fog.lua
Including: fog/sh_sync.lua
Including: function_override/sh_meta.lua
Constructing: interfaces
Including: interfaces/sh_constructor.lua
Including: interfaces/sh_int_configloader.lua
Including: interfaces/sh_int_configsaver.lua
Including: interfaces/sh_int_door.lua
Including: interfaces/sh_int_perkmachine.lua
Including: interfaces/sh_int_player_handler.lua
Including: interfaces/sh_int_rbox_handler.lua
Including: interfaces/sh_int_weps.lua
Including: interfaces/sh_int_zombielinks.lua
Including: interfaces/sh_sync.lua
Including: mainmenu/cl_vgui.lua
Constructing: mapping
Including: mapping/sh_constructor.lua
Including: mapping/cl_cleanup.lua
Constructing: misc
Including: misc/sh_constructor.lua
Including: misc/cl_precache.lua
Including: misc/sh_playerinit.lua
Including: misc/sh_weightedrandom.lua
Constructing: navigation
Including: navigation/sh_constructor.lua
Constructing: notifications
Including: notifications/sh_constructor.lua
Including: notifications/sh_sounds.lua
Including: notifications/sh_sync.lua
Constructing: perks
Including: perks/sh_constructor.lua
Including: perks/sh_meta.lua
Including: perks/sh_perks.lua
Including: perks/sh_sync.lua
Constructing: player_class
Including: player_class/sh_constructor.lua
Including: player_class/sh_player_create.lua
Including: player_class/sh_player_ingame.lua
Including: points/sh_points.lua
Constructing: powerups
Including: powerups/sh_constructor.lua
Including: powerups/sh_powerups.lua
Including: powerups/sh_sync.lua
Constructing: q_menu
Including: q_menu/sh_constructor.lua
Including: q_menu/cl_menu.lua
Including: q_menu/sh_net.lua
Including: q_menu/sh_populate.lua
Constructing: random_box
Including: random_box/sh_constructor.lua
Constructing: revive_system
Including: revive_system/sh_constructor.lua
Including: revive_system/cl_view.lua
Including: revive_system/sh_meta.lua
Including: revive_system/sh_playerdeath.lua
Including: revive_system/sh_revival.lua
Including: revive_system/sh_sync.lua
Constructing: round
Including: round/sh_constructor.lua
Including: round/cl_round.lua
Including: round/cl_round_meta.lua
Including: round/sh_player.lua
Including: round/sh_sync.lua
Constructing: special_weapons
Including: special_weapons/sh_constructor.lua
Including: special_weapons/sh_functions.lua
Including: special_weapons/sh_meta_functions.lua
Including: special_weapons/sh_specialweapons.lua
Including: special_weapons/sh_sync.lua
Constructing: spectator
Including: spectator/sh_constructor.lua
Constructing: tools
Including: tools/sh_constructor.lua
Including: tools/sh_meta.lua
Including: tools/sh_sync.lua
Including: tools/sh_tools.lua
Constructing: weapons
Including: weapons/sh_constructor.lua
Including: weapons/cl_wepswitch.lua
Including: weapons/sh_fas2.lua
Including: weapons/sh_wep_sync.lua
Including: weapons/sh_weps.lua
 ** End List **`

**Comment by func-octo** [comment]
Try Zet0rz' suggestion, except type Table instead of Tabel

@Zet0rz

> lua_run PrintTabel(RandomBox)

But instead do: lua_run PrintTable(RandomBox)

**Comment by lmao5677** [comment]
@ScriptnLua

I tried it now, but it gives me an even bigger error
` [ERROR] lua/includes/extensions/table.lua:711: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
   1. GetKeys - lua/includes/extensions/table.lua:711
   2. PrintTable - lua/includes/util.lua:42
      1. unknown - lua_run:1 `

**Comment by Zet0rz** [comment]
@ScriptnLua
Thanks for pointing out that typo :)

@lmao5677 
The list you gave me is the client side list but the error seems to be server side. Try and give me the server side list. There may be an error there. And are you running on a dedicated server or a listen server?

**Comment by lmao5677** [comment]
@Zet0rz I am hosting a listen server. How do you find the server side list? Is it on the console, or do I have to do something for it to be visible?

**Comment by Zet0rz** [comment]
@lmao5677 If you are on a listen server, it'd be the blue text in your console as long as you're hosting it.

**Comment by lmao5677** [comment]
@Zet0rz 
I have found the two errors

[AddCSLuaFile] Couldn't find 'function_override/sh_constructor.lua' (@gamemodes/nzombies3/gamemode/loader.lua (line 30))
Couldn't include file 'function_override\sh_constructor.lua' (File not found) (@gamemodes/nzombies3/gamemode/loader.lua (line 31))

[AddCSLuaFile] Couldn't find 'mainmenu/sh_constructor.lua' (@gamemodes/nzombies3/gamemode/loader.lua (line 30))
Couldn't include file 'mainmenu\sh_constructor.lua' (File not found) (@gamemodes/nzombies3/gamemode/loader.lua (line 31))

**Comment by Zet0rz** [comment]
@lmao5677 Those should just be because those files are empty. No other errors anywhere? Try the lua_run PrintTable(nzRandomBox). Also check your folders and look for nzombies/gamemodes/nzombies3/gamemode/random_box/sh_constructor.lua and see if the tables are even defined.

**Comment by lmao5677** [comment]
@Zet0rz 

> Try the lua_run PrintTable(nzRandomBox)

It gives me this

`[ERROR] lua/includes/extensions/table.lua:711: bad argument #1 to 'pairs' (table expected, got nil)`
  `1. pairs - [C]:-1`
   `2. GetKeys - lua/includes/extensions/table.lua:711`
    `3. PrintTable - lua/includes/util.lua:42`
    `4. unknown - lua_run:1`

> Also check your folders and look for nzombies/gamemodes/nzombies3/gamemode_random_box/sh_constructor.lua and see if the tables are even defined.

This is the code
 `//Main Tables`
 `nz.RandomBox = {}`
 `nz.RandomBox.Functions = {}`
 `nz.RandomBox.Data = {}`

 `//_ Variables`

**Comment by lmao5677** [comment]
Nevermind, I'm closing this issue because now the issue has been fixed. I didn't install the addon right.

**Comment by func-octo** [comment]
By the way, never do unbind all, its hard to reset it...

**Comment by Zet0rz** [comment]
You were running an older version of the gamemode, we are no longer using nz.Stuff.Functions tables for most modules, instead only a single table "nzStuff" (replace stuff with any modules identifier, eg RandomBox). Redownloading the latest version was what fixed it.
