### ISSUE TITLE
Can't earn points from zombies

### ISSUE THREAD

**Issue by superckool** [Zet0rz/nzombies#302]
Hey, I looked through every page of the issues and tried googling but found no luck. I assume I have a conflicting addon or something, because whenever I attack a zombie with anything I don't earn points, but I still earn them through barricades. Just looking for some input on this issue and where I should start looking for a conflict, I tried checking the hooks in the console but as far as I can see the only thing using those hooks are Nzombies. Haven't tried the newest developmental branch yet, I'm about to after I post this. I was using master-workshop, in case that helps.

**Comment by minin43** [comment]
Have you done any editting to the gamemode? Try redownloading the gamemode. If that still isn't the issue, play without any of your addons enabled. It may be conflicting addons. If it is, let us know what it is.

**Comment by superckool** [comment]
Haven't done any tampering, and once my internet stops shitting itself I'll try downloading the development branch and if that doesn't work I'll check the addons. I'll let you guys know how it goes so if anyone else has this issue they can easily fix it.

**Comment by minin43** [comment]
It won't be the differences in branches. If there's an addon that conflicts with nZombies Zet0r should know about it.

**Comment by Zet0rz** [comment]
Points are distributed in EntityTakeDamage hook. Check the hook table for hooks under that. Some addon is definitely conflicting. Maybe we should change the GM: functions instead of hooks.

**Comment by superckool** [comment]
Hey finally got my internet working today, and as it happens I figured out
what was causing the issue. I had an add on called damage numbers installed
that was conflicting with the takedamage hook. So I'm good to go and have
had no issues with gamemode since, keep up the good work guys.
