### ISSUE TITLE
Adding new entities?

### ISSUE THREAD

**Issue by superckool** [Zet0rz/nzombies#305]
I've ran into another problem, though this one isn't game breaking. I've added a few entities to the spawn menu for creative and they spawn in and function fine in creative mode, but they don't show up in game at all. Checked the config file for it and it shows no signs of any of the entities, is there something else I need to add besides adding the entities to sh_populate? Or is this just not fully supported yet?

**Comment by Zet0rz** [comment]
You don't add stuff to sh_populate anymore, a recent update changed the spawnmenu to work with a local .txt spawnlist file. If your spawnlist has the Save button in the top right corner, your game is updated to this version. In this case, you'll need to use the Search tab to find new models and add them by right-clicking. Refer to the screenshots in #213. Entities still need to be added to sh_populate atm.

Let me know if there's any other problem or you have trouble getting it to work!

**Comment by superckool** [comment]
I'm well aware of searching and saving for models, so is there a way I could get my nzombies to save my custom entities? For example, I have a landmine entity that players can activate and use against zombies, it shows up in the utilities tap of the spawn menu and can be placed, moved around, and even be activated and explode in create mode. So the problem here is that the gamemode isn't writing these entities to the config file, any where I can edit to make the system recognize these entities?

**Comment by Zet0rz** [comment]
It could be a bug. The game's supposed to save entities spawned with the entities tab using the duplicator library (saving a huge table containing all its information), but it could be the new spawnlist broke that. Do they disappear the moment you start the game or whenever you load the config?

**Comment by superckool** [comment]
If I load the config while directly after saving it and say I remove an entity, that entity will come back. But if I load up a map and then load the config, they don't show up at all. Also they always disappear the moment the game starts. Pretty odd bug.

**Comment by superckool** [comment]
By the way, I've noticed that if I'm above a zombie at all they don't attempt to pathfind towards me at all. Say I'm on a ledge that zombies can jump up to, the zombies will just stand still staring and won't do anything. It even happens if I walk up stairs, they just stand at the bottom doing nothing. Is this just on my end? Or is this just a normal bug?

**Comment by minin43** [comment]
The issue probably stems from your nav file. The zombies for nZombies are NEXTBOTs and thus require a .nav file for them to pathfind at all. If the aren't walking up a set of steps the auto-generation probably didn't do a good job getting everything and you'll have to add it on your own. Rarely is this an issue with the zombie AI itself

**Comment by superckool** [comment]
The navmesh is there on all of them because I added them myself. For stairs
I'd manually put areas on each stair and connect them, but on other maps
I've seen sloped areas. Any idea how to make those? Willing to bet that's
my problem. Also any update on the entities?

**Comment by lolleko** [comment]
> For stairs
> I'd manually put areas on each stair and connect them, but on other maps
> I've seen sloped areas.

Just create a nav area below the slope or staircase. and then look at the **corners** that are "in the ground" or under the stairs and run `nav_corner_place_on_ground` via console or the nav editor tool.

> I'd manually put areas on each stair

You can use this technique both for stairs and slopes, so you don't have to create an area for each stair.

**Comment by Zet0rz** [comment]
Simplest way to do it would be to make the areas at the top and bottom of the stairs, then splice them to create a sloped one between them. Splice is such a nice Nav editing command

**Comment by Zet0rz** [comment]
I think I may know what the bug here might be. It's possibly because game.CleanUpMap removes it, as custom entities aren't added to the exception. I can probably make it add all entities found in the player's (or server's) entities table.

**Comment by superckool** [comment]
That splice tool is a god-send haha. Yeah if you could take a look and see if you can get custom entities working that'd be amazing. Keep up the great work, and thanks for all the help guys!

**Comment by Zet0rz** [comment]
Okay new changes duplicates entities spawned with the special entities tab and recreates them after the cleanup. They will respawn with as much precision as gmod's own save system allows.
