### ISSUE TITLE
A small problem with sounds.

### ISSUE THREAD

**Issue by Lucius1202** [Zet0rz/nzombies#306]
A silly question! Every time the round start or end, no sound is played.

The console shows:

Create Stream Failed error 44
Failed to load sound "nz/round/round_start.mp3", file probably missing from disk/repository

Create Stream Failed error 44
Failed to load sound "nz/round/round_end.mp3", file probably missing from disk/repository

I found the files but wherever placed, do not play, what is the proper directory structure?

**Comment by Zet0rz** [comment]
[addon]/sound/nz/round/round_start.mp3

It's in the content pack, maybe it corrupted a bit?

**Comment by Lucius1202** [comment]
I'm finding out right now that this is a problem related to Garry's Mod on linux distributions, someone seems to have a workaround. If it works I'll post for reference.

**Comment by minin43** [comment]
I've had issues with sound on Linux before. Then I stopped using Linux and everything's better. I don't like Linux.

**Comment by Lucius1202** [comment]
Sorry but linux is my great love, I made the "jump" 15 years ago and I have never regretted. Until now. :-P LOL

**Comment by lolleko** [comment]
Linux is the best, but not for gaming!

**Comment by tylerpadgett** [comment]
Odd. My servers are running on linux, and it works fine for me.

**Comment by Lucius1202** [comment]
The game on Linux is very young, it takes years to set standards, even windows still has technical problems in some applications despite all its resources. Linux is an ethical and civil choise. Plus: no viruses, no drivers, apps repository and a great community. Ok, I'm factious. :-)

**Comment by Zet0rz** [comment]
I'd like to get it working on all platforms, but it sounds like more of a problem on your end than on the gamemode. Be sure to let me know if that is not the case.

**Comment by Lucius1202** [comment]
Yes, I confirm is my side problem and I resolve it merging some linux specific mp3 codecs folder from Half life 2, in my other linux computers no sound issue happen. I post my workaround if other linux user  need it.
