### ISSUE TITLE
Updating Currently Placed Config Objects Without Removing and Replacing Them

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#311]
Alright, here's a list of things that need to change for creative mode, then I'll explain what I mean by the title.
- [ ] 1. Make the hitbox of the spawns the size of the model spawned in (special spawns, player spawns, and zombie spawns so we can shoot it with the toolgun much easier rather than trying to find the dot on the ground)
- [ ] 2. Use the nzombies model as zombie spawn (t-pose)
- [ ] 3. Use the Hellhound model for the Special Spawn (ik it's not just the hounds, but it's the main thing that spawns there)

As you may have noticed, we cannot update current entities in nzombies except for doors.
- [ ] I was wondering if we could add an info updating system, much like Wiremod, so we don't have to remove and replace the entities to update their information. This would be extremely useful when updating configs and ,in general, for perfectionists who want to be sure everything is correct.
- [ ] There should also be, like Wiremod, a "3D GUI" that pops up stating information like:

ENT_DOOR
Use_Flags=true
Flag=1
Price=3500
Requires_Elec=true
Re-buyable=false
- [ ] This should be the same for #308 and #309 
  I feel like this would help a lot with config creation. Cheers! 👍

**Comment by Zet0rz** [comment]
I can change the model and hitbox size of spawnpoints (not sure if zombie models would be smart though, probably better to stick to red/green/blue). 

All entities' information is updateable without recreating them, simply shoot them with the toolgun with changed settings and they'll update (although that works by recreation). You can also hold C and right click them (as of dev branch) which will open the tool's interface specifically for this entity. 

3D gui could be cool, but not a priority atm. Not all information is retrievable clientside (might make though retrievable in the dev update though).

**Comment by func-octo** [comment]
Awesome :) The 3D would definitely help when you go back to be sure everything is right.
I just thought of something that'd be cool.
Set a color value for each flag number so we can see what zombie spawns fire with the same color as the door that we buy.

P.S. If you could message me on steam when you finish something on this list that'd be great so I could use this checklist above :)

**Comment by Zet0rz** [comment]
But I just said you already can? You mean you can shoot entities and their info should update? They already do that. Just try and use the wall buy tool, change the price and gun, shoot an already existing one.

3D Gui won't come now, so it's not a todo thing.

Spawnpoints will likely stay like they are. Changing their collisions mean they are prone to be flung away like the box spawnpoint can. Changing their model would make it look less clean (the current colored t-pose default models is very mapping-like).
