### ISSUE TITLE
Big Daddy's Despawn and Never Respawn

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#313]
If you receive a zombie blood drop and Big Daddy spawned that round (and you're in SP) the Big Daddy will de-spawn and won't ever respawn, even in future boss rounds.

**Comment by Zet0rz** [comment]
It's a problem with the death function not being called, thus not setting the next time he spawns. Which in turn is likely a problem with the NZBossType field not setting on the boss when spawned.

**Comment by Zet0rz** [comment]
Should be fixed in the latest dev branch update.
