### ISSUE TITLE
Insta-kill and burning zombies

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#317]
(First time posting here)    Hello!  Killing burning zombies while insta-kill is on causes them to explode multiple times all at once.  I've been killed by this more time than I can count because of the lag it causes and the massive damage it does.  Will do more play testing in the future to find more issues that may arise.

**Comment by minin43** [comment]
This is an older issue that was believed to be solved, do you have the latest version of nZombies downloaded?

**Comment by sh4d0w59** [comment]
I'll do some testing when i get home to check for any conflictions with the addons i have.  If i resolve the issue ill tell you and ill close this issue.

**Comment by sh4d0w59** [comment]
And yes i do have the latest version

**Comment by Zet0rz** [comment]
This is fixed on the dev branch.

**Comment by sh4d0w59** [comment]
Yes, I have fas 2.0, cw 2.0, and khris' cw 2.0 installed also.

I am using the gamemode and the content packs from the workshop also.

**Comment by sh4d0w59** [comment]
Is the devbranch available for download or is it only file transfer as it
says in the github description?  (I know its a dumb question but still)

**Comment by Zet0rz** [comment]
It is available to download and install exactly like the normal version, you just have to pick "development" instead of "master-workshop" in the drop down to the left. Although you need to make a clean install when you do (delete the old gamemode) as some files have been deleted, but would still load if they're left over from the old version (and cause errors).

**Comment by sh4d0w59** [comment]
Thank you for your help!  I was just wondering because the master workshop
version is a bit buggy, the developer branch says it's just for file
tansfer, and I'd like to help bugtest and whatnot.
