### ISSUE TITLE
Brutus? Support for gMod animation tool saving into configs for animated props?

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#318]
Any sign of him ever being ported to nZombies?

**Comment by Roachisserie** [comment]
Maybe. I'm going to re-port his model as well as others soon.

**Comment by func-octo** [comment]
Do you know if your models are already rigged? If not it'll take more time to re-rig the models for animation.

**Comment by Roachisserie** [comment]
Yes they are lol. How else did I make nextbots out of them.

**Comment by func-octo** [comment]
Lol, true. Unless the gMod Stiffy Squad is out again xD

**Comment by Zet0rz** [comment]
What do you mean by that title with animation tool?

And I thought of the ultimate tool for enabling and saving more (if not all) types of construction Garry's Mod has to offer, which would be support for loading _gmod saves_ along with configs, although it may not work practically.

**Comment by func-octo** [comment]
The animation "tool"\* example: https://www.youtube.com/watch?v=aM2MA6xOXzk

*A set of tools

This allows animation of normally still props, and could be used for ambient machinery like oil drigs, windmills, or power stations (also ragdolls, but that'sa little silly)

**Comment by func-octo** [comment]
~~But yeah, on the topic of Brutus. Would it be from WaW or BO3? Would we have the right animations for the BO3 one (if chosen)?~~ How much "health" does he have in the original game? Things like that.

EDIT: Apparantly in BO2, not WaW or BO3 😆  (I don't own these so yeah 😛 )

**Comment by func-octo** [comment]
And then there's his voice lines. That would add a lot of HDD/SDD space used to this if there are a lot.

**Comment by minin43** [comment]
But why is it gMod and not GMod?

**Comment by Roachisserie** [comment]
Uh. He was neither in BO3 or WaW. He was in BO2. The voicelines I have for him are also mp3s meaning they take up little to no space.

**Comment by Zet0rz** [comment]
> The animation "tool"\* example: https://www.youtube.com/watch?v=aM2MA6xOXzk

That looks like a tool that isn't for creating looping animated backgrounds but rather 1-time playbacks that you can use to record your own gmod animation. I doubt you could get it to work properly with something like this, but that being said, it does also look like it doesn't depend on sandbox. Try it in Creative Mode?

> But why is it gMod and not GMod?

I'd always call it gmod, I think most other ways look wierd although GMod kinda works too. Garry's Mod is the best way to go if in doubt.

**Comment by func-octo** [comment]
> But why is it gMod and not GMod?

Well it depends on what people like, so like Team Fortress 2 could've been TFT but people like TF2 better. Same case here, but I'm guessing general laziness, since Garry's Mod is sort of a mouthfull, especially if you type it twice every other sentence. The most likely reason for gMod is like iPhone, but I guess one less upper case is one less keystroke (SHIFT).

> it does also look like it doesn't depend on sandbox. Try it in Creative Mode?

I'll try that when I get home, which will be 10 P.M. on your time, 4 P.M. on my time. Also, which file contains which tools to give the player in creative mode, or is there a console to command to give the tool to a player?

**Comment by Zet0rz** [comment]
Is it an actual toolgun? nZombies doesn't support sandbox toolguns (although that would be cool, maybe by giving the normal sandbox toolgun next to the nZ one?)

**Comment by lolleko** [comment]
Maybe port all zombies tools to the sandbox tool gun format :D ? Just kidding that would be to much work now I guess.

Also I am not sure if the sandbox tool gun will work 100% since the game mode is not based of of sandbox.

**Comment by Zet0rz** [comment]
Yeah it might not work at all - hence why we didn't go with that system in the first place
