### ISSUE TITLE
The Replacements Approach...

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#32]
You've already seen two of them. Now the rest are coming...

**Comment by Zet0rz** [comment]
Are you talking about perk icons? If so, I noticed especially on the Who's Who icon that it was kinda rough. Still beats the blurry but try and see if you can smooth it out a bit more :P

**Comment by func-octo** [comment]
Yeah, the perk icons :). Also, thanks for the feedback! I'll see what I can do about that.

**Comment by func-octo** [comment]
https://drive.google.com/drive/u/1/folders/0B1xHaGAsFiwgSnJJeXUtaDVfSGc

This is where I'll be keeping the icons, so feel free to take the ones I have now so I don't have to open a pull request for all of them. I should have all of them in there by April 4. As always, tell me what needs fixing, and happy coding!

**Comment by func-octo** [comment]
P.S. Don't worry if some of them dont look right, I made them so that they look right at 25% magnification in photoshop, and have tested them in-game personally :) :+1: 

I also must improve my skills before being able to completely redo speed.png or revive.png because of the gradients.
