### ISSUE TITLE
Precision Tool Support

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#321]
Using the precision tool would allow us to more precisely place objects in configs by nudging them by hammer units. Please add the [Precision Tool](https://steamcommunity.com/sharedfiles/filedetails/?id=104482086) to Creative mode.

**Comment by Zet0rz** [comment]
You say add support, but out tool system is completely different from sandbox'. Tools aren't (as of now) cross-compatible. The way to make this tool compatible would be to completely remake it. Alternatively, I could try and work a "Sandbox Tool" that can pick from any sandbox toolgun from addons, but there is no guarantee it'll work, much less so if the interface and controls would work.
