### ISSUE TITLE
'Max Ammo' powerup Not Working.

### ISSUE THREAD

**Issue by Worset** [Zet0rz/nzombies#322]
[ERROR] addons/nzombies-development/gamemodes/nzombies/gamemode/powerups/sh_powerups.lua:178: attempt to call method 'GiveMaxAmmo' (a nil value)
  1. func - addons/nzombies-development/gamemodes/nzombies/gamemode/powerups/sh_powerups.lua:178
   2. Activate - addons/nzombies-development/gamemodes/nzombies/gamemode/powerups/sh_powerups.lua:56
    3. unknown - addons/nzombies-development/gamemodes/nzombies/entities/entities/drop_powerup/shared.lua:51

This error occurs every time I go to pick up a max ammo - both dropped from a normal zombie and at the end of a boss round. The pickup stays floating in the air no matter how many times I run through it and no ammo for either of my guns are refilled. 

FYI, I picked up a Fire Sale powerup in the same game and it worked fine.

**Comment by Zet0rz** [comment]
Thanks! Hotfixed in fa5cc0fa802d4043cc8ac09899be2bacf1566f1f!
(You can apply the fix to your own game by editing the code in that file on that line to what was changed if you don't want to redownload the whole thing)
