### ISSUE TITLE
objective and escape maps compatablity

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#323]
as good as i am at coding i feel that maybe you guys can do better than me. i suck at interfaces and other things that make live easier. i also would rather this gamemode have compatibility with objective/escape maps out of the box so i do not have to recode this stuff back in every update.

so here is what i have so far for making it compatible
1) when a door is opened we record the flag as such `latestdoor = data.link`
2) in the update valid spawns function for the spawner i use 
`		if string.find(mapname, "_obj_", 1, true) then
			if vspawn.link ~= latestdoor then
				vspawn:SetZombiesToSpawn(0)
			else
				vspawn:SetZombiesToSpawn(toSpawn)
			end
		else
			vspawn:SetZombiesToSpawn(toSpawn)
		end`
so that only the spawns that have the flag of the last door opened are used. 
3) finally the respawn function for when a round ends respawns the players to special spawns as if they got whos who. so they don't just go back to the start.
4) map starts on round 10

i would be happy to share this code as it does work as is however some work needs to be done to do some things
1) all random boxes should spawn in. not just one
2) a better respawn system for it because it might be wrong to do it wave based.
3) a way to prevent players from back tracking. maybe lock all doors that were open when the next one is opened. and if you press E on the locked door ( one that is already passed ) it will TP you to another player so you can not back track.
4) option in the map options config to enable this. right now it does it based off of name.
5) a way to despawn zombies that are too far behind.

**Comment by minin43** [comment]
> a way to prevent players from back tracking. maybe lock all doors that were open when the next one is opened. and if you press E on the locked door ( one that is already passed ) it will TP you to another player so you can not back track.

Why?

**Comment by Zet0rz** [comment]
I'm not changing how the core gamemode works (you do that, you do it in a map script or an autorun extension/addon). Something like this does sound interesting, but it's not something that is big and a main part of this mode; it'd almost be a completely different gamemode. Native objective support is planned ( #189 ), but not core-gamemode-altering.

**Comment by jaxjaxk** [comment]
@minin43 
because some people would rather stay at the spawn or find some place to camp.

**Comment by minin43** [comment]
That's not how Nazi Zombies was ever created. It is, quite simply, an extremely shitty idea. What about any perks in those areas? Mystery box? PaP? Easter Egg components?

You'd be denying players anything in that blocked off area. No.

**Comment by lolleko** [comment]
I don't get  why you are so angry lol :D I personally don't think it's a "shitty" idea, I could think of a few scenarios and maps where this would actually be a good thing to have. But like Zet said it is a bit to late now to add that functionality easily.

**Comment by minin43** [comment]
Just being blunt.

**Comment by Zet0rz** [comment]
While the ideas are cool and probably fun to play too, you can't just implement every spinoff you can think of into a gamemode. Some people have even suggested I add all features from CoD Ghosts' Extinction mode, which while sounds cool, just brings the gamemode away from being Nazi Zombies.

This idea is the same. It will not be implemented, but feel free to modify it on your end and host it like that if you want.
