### ISSUE TITLE
team error

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#329]
a while back i had a problem with a player that would not die. now i DID alter the gamemode a bit to add in a new team ( team = 4) HOWEVER, i am pretty sure i know what i am doing seeing as this never happened until i started using the dev branch. (workshop branch needs to be updated considering it has been months and so much has been improved BTW)

the player would not take damage form zombies however health generation worked fine on him. after running a quick diagnostics program i found that his team was 1002.

now 2 possible things apparently happened that could have lead to this (according to players, i was called when it happened)
1) the player used the mystery box.
2) the player was hit into a wall by zombies. ( and i do mean into the walls meaning they overlapped)

now this has happened one time however considering how much this affects game play it should be considered.

**Comment by Zet0rz** [comment]
1002 is TEAM_SPECTATOR (but not TEAM_SPECS which we use internally). An addon or modification of yours could've set the team to spectator? I don't think there's any logic to prevent damage from zombies on a spectating player, do you mean them not going for him at all or just him not taking damage from hits?
