### ISSUE TITLE
Points Bug

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#33]
I am currently experiencing a bug where I shoot the zombies, but they don't award me points? Is it something I have to edit in the config? I have checked the console to look for errors, but I find nothing that has anything to do with points.

**Comment by func-octo** [comment]
I would check the config, but if you don't see anything there about awarding 10 points on attack just comment that it's still broken and Zet0rz can help you (much more than I :) )

**Comment by lmao5677** [comment]
I've checked my config and I can see that it gives 10 points but I see that it isn't working

**Comment by func-octo** [comment]
What weapon(s) are you trying to use with this?

**Comment by func-octo** [comment]
Is it the weapons, or do all weapons do this?

**Comment by lmao5677** [comment]
I think all the weapons do this. I am using the WWII Weapons Pack and FAS2 guns aswell.

**Comment by func-octo** [comment]
Hmmm... Sounds like we'll have to wait for Zet0rz. :\

**Comment by Zet0rz** [comment]
Are you using custom zombie entities? And do you even damage them (will they die?)?

**Comment by lmao5677** [comment]
> Are you using custom zombie entities?
> Sorry if I sound silly, but could you state some examples please?
> 
> And do you even damage them?
> I do shoot them, but my points aren't changing

**Comment by Zet0rz** [comment]
You can code your own zombie entities or use other npcs (if you edit the code) other than what comes with the gamemode. But if you haven't touched it, that shouldn't be it. 
I know you can shoot them, but will they die? If they don't take damage, they don't give points. However if they do die, then that's not it. If so, try reinstalling the latest version. I get points when I play.

**Comment by lmao5677** [comment]
@Zet0rz 

> But will they die?

They do die. I have seen them die.
I have also tried reinstalling the latest version over and over, but nothing is working.

**Comment by lmao5677** [comment]
Also, I want to point out, if I kill myself or dropout, the game starts to freeze.

**Comment by Zet0rz** [comment]
It really sounds like you just have a really buggy installation, none of this happens for me or reportedly from any of my other playtesters. Try putting this in console:
`lua_run hook.Add("EntityTakeDamage", "Testhookthing", function(ent) print(ent, "taking damage") end)`
Then start shooting zombies again. Check if your console prints out the entity and "taking damage" every time or not. After that, try damaging yourself (fall damage or something) and see if it prints your player entity and "taking damage" to verify that it works.

**Comment by lmao5677** [comment]
@Zet0rz 
It just prints out

`hook.Add("EntityTakeDamage",Testhookthing", function(ent) print(ent, "taking damage") end)...`
When I shoot a zombie, nothing prints out in the console and it does the same thing when a zombie hits me.

**Comment by Zet0rz** [comment]
You must have an addon that then overrides EntityTakeDamage and returns a value (stopping the rest of the hooks from running). Disable all your addons that you think might do this and try again. If you find the culprit, let me know which one it is.

**Comment by lmao5677** [comment]
@Zet0rz 
Its now working. I just completely disabled all my addons and kept the fas2. Case Closed, thank you!
