### ISSUE TITLE
No Creative Mode Tools

### ISSUE THREAD

**Issue by NickWilde12** [Zet0rz/nzombies#330]
When I type "/create" it allows me to fly and open the "q" props menu however I have no tools such as doorlocker etc that I have seen in tutorial videos, why is this and is there a way to solve it or am I just doing something wrong?

**Comment by Zet0rz** [comment]
Try suicide and respawn

**Comment by NickWilde12** [comment]
I tried that but it didn't change anything

**Comment by Zet0rz** [comment]
What weapons do you have?

**Comment by NickWilde12** [comment]
Weapons in terms of creative mode tools, none
