### ISSUE TITLE
option to turn off RTV and votemap

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#333]
most servers use a different votemap system than what NZ uses by default.
not only that but maps like gm_construct and gm_flatgrass should not be on the list.

i ask, please have an option in the config so that you can turn off the votemap system or rtv system.

**Comment by jaxjaxk** [comment]
at the very least tell me what file has the code that starts the votemap

**Comment by lolleko** [comment]
If you type in vote in the repo search its the first file that comes up
https://github.com/Zet0rz/nzombies/blob/49407298f7e3838fe0cb98469042fe6c9f8d662a/gamemodes/nzombies/gamemode/interfaces/sh_int_configloader.lua

**Comment by Zet0rz** [comment]
Added nz_rtv_enabled which when set to 0 stops automatic rtv and prevents /rtv from doing anything.
