### ISSUE TITLE
Bug with the new traps?

### ISSUE THREAD

**Issue by Coract** [Zet0rz/nzombies#334]
After I place them and connect they seem fine. Then after hitting ready they just disappear...

**Comment by Zet0rz** [comment]
Right, noted. I think it's because they weren't registered to the cleanup exclusion. Added it to the todo list, will close this when it's done.

**Comment by Coract** [comment]
Alright, thanks

**Comment by Coract** [comment]
There's another problem, after upgrading sometimes the new skin will cover areas not on the gun.

**Comment by Zet0rz** [comment]
Updated, give it a test and let me know if it works for you.
