### ISSUE TITLE
[Off-Topic] How do you compile a model into .mdl?

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#336]
How do you compile a model into the .mdl format? I have tried multiple ways but to no avail. I use OBJtoSMD (I have a QC as well as the SMD) then from there try Crowbar, but always errors during compilation.
@Zet0rz what do you do to compile a model (personally, for what you did here)?

**Comment by lolleko** [comment]
I really don't think this is the right place to ask such questions. 😅

Anyways if you use Maya try [MESA](https://developer.valvesoftware.com/wiki/MESA) its super simple.

Some more useful links:
https://facepunch.com/forumdisplay.php?f=40
https://developer.valvesoftware.com/wiki/Compiling_a_model

You can find many more tutorials on google.

**Comment by func-octo** [comment]
Thanks @lolleko! I'll have to try that when I get home :)
