### ISSUE TITLE
Cannot load config scripts. ('Non-Existant Map Script'?)

### ISSUE THREAD

**Issue by Worset** [Zet0rz/nzombies#338]
![image](https://cloud.githubusercontent.com/assets/18449391/20990361/34f2e41a-bcd0-11e6-89d2-1c4d142c8a35.png)
This appears every time I attempt to load a map script - and it is not just with my own configs either.

I created a script for an upcoming config I am working on, but I cannot get it to work ingame whatsoever. I thought I had screwed something up, so I decided to test out the script for one of the official configs. Only...
![image](https://cloud.githubusercontent.com/assets/18449391/20990261/d5ab9330-bccf-11e6-94ab-de714f87c726.png)

I did not mess with the official config script AT ALL or move it anywhere else. And I made sure the path to my script always had /lua/mapscript/'Config Script' in it. I tried the base 'lua' folder in the standard gMod folder, in the 'nzombies-master-workshop' folder and in a brand new folder just for my map (nz_omen/lua/nzmapscripts/'Config Script'. As far as I can tell, there is no reason that neither official or my own scripts shouldn't be working. Any advice?

**Comment by Zet0rz** [comment]
In your own code, go to this https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/gamemode/mapping/sv_saveload.lua#L235

Try changing `configname` to just `name`. Let us know if that works for you. I think it's with the change for convinience in the /save interface, since mismatch needs the full file name.

**Comment by Worset** [comment]
Got the new update, it works now, but my console now shows:
[ERROR] 675138912'
  1. unknown - addons/nzombies-master-workshop/lua/nzmapscripts/nz_zs_southside;omen.lua:0


[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/mapping/sh_mapscripthandler.lua:34: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. LoadScript - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/mapping/sh_mapscripthandler.lua:34
    3. Correct - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/mapping/sh_mismatch.lua:491
     4. func - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/mapping/sh_mismatch.lua:15
      5. unknown - lua/includes/extensions/net.lua:32

And it has GOT to be something I screwed up on, considering I was just playing the Imprisoned config script and it worked perfectly.

**Comment by Zet0rz** [comment]
Return the map script table at the end of the file. If you don't have any, return an empty table. I should change it so that it'll warn if a table isn't returned.
