### ISSUE TITLE
Zombie heads are attacking me!

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#34]
No idea whether it's a fluke or a bug, but this has only happened once. No errors in the console to report.

So when one zombie was emerging, it got stuck in the ground so the head was showing, but it still came after me regardless. Anything in the zombies that could cause the model to be lower than the entity?

**Comment by lolleko** [comment]
Did you see the zombie emerging, or did you just see the head?

**Comment by func-octo** [comment]
It emerged as it should, then in a teleporting kind of manner, the model of it went into the ground leaving only the head showing.

**Comment by Zet0rz** [comment]
Seems like it might have been a 1-time bug. Even so, this is more engine-handled stuff so it's nothing we can fix without completely removing the underground animations. Reopen another issue if you get this again associated with a lua error.
