### ISSUE TITLE
I cant knife :(

### ISSUE THREAD

**Issue by Nyronix** [Zet0rz/nzombies#341]
I try pressing v. I tried different bind keys that have been given to me by my friends but still cant knife ?!? Is it because a addon please !! Help me ASAP I really like this gamemode :-( ?

**Comment by jaxjaxk** [comment]
i have had this issue before, are you able to knife at the beginning and later no longer able or just never able to? it should be the key you use for noclip. that may be why

**Comment by Zet0rz** [comment]
I really don't know what's causing this yet, but I've seen it myself. It is seemingly fixed by switching weapons if you have more than 1. 

Also it is no longer bound to noclip, it is bound to the `nz_key_knife` convar, same as all other special weapons.

**Comment by Nyronix** [comment]
Jaxjaxk yes i had access to the melee before but now i am unable to use it

**Comment by Nyronix** [comment]
Zet0rz Do you know the binding key for the melee or is this a problem you need to patch in future updates

**Comment by Zet0rz** [comment]
I just said the binding. It's bound by console commands (just enter it into console and the help text will tell you what numbers to use). I am aware of this bug, but try to play anyway, buy 1 more gun, switch between them, and then try to use melee or grenades again. Does it work then?

**Comment by Nyronix** [comment]
No it does not I tried swapping between different guns and then I try to melee and it still won't even work

**Comment by Nyronix** [comment]
It was an addon cause i resetted my gmod and erased all addons for the sake of this gamemode then i was able to knife again so it was probably an addon who knows ?

**Comment by jaxjaxk** [comment]
it is related to the special weapons bug.
