### ISSUE TITLE
round infinity question

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#344]
is it just me or are all the zombies the same health on round infinity?
it would not hurt to like increase the spawn health of every zombie by like 5 for every kill....

**Comment by Zet0rz** [comment]
You'd get a faster answer if you read the code instead of asking, it is all in there. To answer your question though, zombies spawn with random health and speeds within a certain range. The range is subject to balance, but round infinity is not a health-over-time-system.

**Comment by OctothorpeObelus** [comment]
There should be a 1 in 65 chance of a zombie to spawn with 2x health and 2x speed. Would make it more challenging I think.

**Comment by func-octo** [comment]
Whats the file with round infinity data in it?
