### ISSUE TITLE
Nothing in spawnlist!

### ISSUE THREAD

**Issue by Megapig123** [Zet0rz/nzombies#347]
When I hold (Q) while holding the phys gun there is nothing in the spawnlist menu. 
![image](https://cloud.githubusercontent.com/assets/24751331/21466319/547b2f88-c97b-11e6-82e6-ea0d5c6d6b58.png)

**Comment by Zet0rz** [comment]
Delete spawnlist.txt in data/nz/ and have it regenerate.
