### ISSUE TITLE
Speed Cola doesn't work and slows the reload of TFA Weapons

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#349]
When i buy speed cola while using a TFA Weapon it gives me a error and reloads without speed cola effect and slows the weapon reload.

**Comment by Zet0rz** [comment]
I think I fixed this a bit ago.

**Comment by DjNathann** [comment]
[TFA Base] addons/nzombies/gamemodes/nzombies/gamemode/weapons/sh_wep_modifiers.lua:117: attempt to call method 'SetReloadingEnd' (a nil value)
  1. Reload - addons/nzombies/gamemodes/nzombies/gamemode/weapons/sh_wep_modifiers.lua:117
   2. v - lua/tfa/modules/tfa_hooks.lua:128
    3. unknown - lua/includes/modules/hook.lua:84

**Comment by Zet0rz** [comment]
Noted down on my todo list
