### ISSUE TITLE
M9K Weapon bug.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#355]
When Holding a M9K Weapon and try to swap/buy an other weapon it swaps the 2nd weapon instead the gun im holding.

**Comment by Zet0rz** [comment]
Does not happen to me. Any other addon you can find that could be the culprit? Will it always work after disabling M9K? Try enabling M9K but disabling a bunch (if not all) other addons and see if that changes anything.

**Comment by DjNathann** [comment]
I dont use them anymore but thanks for the tip.
