### ISSUE TITLE
ammo types

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#358]
ok so im working with some strange guns. the guns display the ammo count on them however the problem is i can not for the life of me figure out the name of the ammo for the function weapon:GetAmmoCount([ammo name here]). i can see that the gamemode create new ammo types from all that were found however both the old and new do not work at all. sadly all i can get back is the ammo number and that can change from one day to another. it should also be noted that upon initialization it is one value and 1 second after another.

fact is i can not allow the ammo to be this unpredictable. further more it would seem that having two types of ammo is unheard of in this gamemode. the weapons that are epic have problems with showing the current ammo and with maxammo.

so what would be the ammo name if say the old one was "gasoline". and trust me, it is not "nz_weapon_ammo_gasoline".

it should also be noted that the function GetPrimaryAmmoType() can NOT be used as the function to display the ammo because it is run during initialization so it would keep the value of the initial ammo and there for be inaccurate. to put it simple, we need a way for some guns to not use the standard ammo system.

**Comment by Zet0rz** [comment]
The gamemode doesn't mess with other weapons' ammo type names, rather it switches what ammo type they use. Their ammo type becomes nz_weapon_ammo_1 for weapons in slot 1, nz_weapon_ammo_2 and nz_weapon_ammo_3. Well, at least that's what should happen. It simply replaces the GetPrimaryAmmoType function that checks the weapon slot. You can see it here:
https://github.com/Zet0rz/nzombies/blob/49407298f7e3838fe0cb98469042fe6c9f8d662a/gamemodes/nzombies/gamemode/weapons/sh_ammo.lua#L92-L107

**Comment by jaxjaxk** [comment]
well this will be fun to solve
