### ISSUE TITLE
Day of Infamy Weapons Bug *Max ammo*

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#359]
Using the DoI Weapon will create a bug that doesn't let you pick up max ammos but other drops you can.

[ERROR] addons/nzombies gamemode/gamemodes/nzombies/gamemode/weapons/sv_ammo.lua:55: attempt to index field 'Weapons' (a nil value)
  1. GiveMaxAmmo - addons/nzombies gamemode/gamemodes/nzombies/gamemode/weapons/sv_ammo.lua:55
   2. func - addons/nzombies gamemode/gamemodes/nzombies/gamemode/powerups/sh_powerups.lua:178
    3. Activate - addons/nzombies gamemode/gamemodes/nzombies/gamemode/powerups/sh_powerups.lua:56
     4. unknown - addons/nzombies gamemode/gamemodes/nzombies/entities/entities/drop_powerup/shared.lua:51

**Comment by Zet0rz** [comment]
This wasn't a bug with any particular weapon pack but one that came with the changes I made to the special weapons system. It has just been fixed.
