### ISSUE TITLE
Zombie Stiffy Pose

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#36]
It appears that the zombies have no idle/standing animation, as they go stiffy pose when standing still. All other animations work as said.

**Comment by Zet0rz** [comment]
Yep, I didn't compile an idle animation (kinda forgot in the rush) and I don't have my desktop with all my things with me. They'll be added when I come home along with some jumping and dropping ones :)

**Comment by func-octo** [comment]
Until then, it looks kinda funny. It's like they forgot what they were just doing xD
