### ISSUE TITLE
Should the Black ops Perk Machines models turn into Black ops 3?

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#360]
I mean like old models of perk machines are cool but yea they should get a upgrade and get the Black ops 3 model of the perks.

**Comment by Zet0rz** [comment]
I'm not sure if I will replace the models, maybe if they are just higher quality. Although I'm not replacing perk models or icons with the dirtier ones, I think the clean ones suit gmod more.

**Comment by DjNathann** [comment]
alright mate.

**Comment by func-octo** [comment]
There should be an option to choose the perk machine models between BO3 and WAW, if possible.

**Comment by minin43** [comment]
I disagree. It's more content clients have to download, and it takes work to implement such an insignificant feature.
