### ISSUE TITLE
turret traps

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#367]
turret traps will gladly shoot through walls if the target is close enough.
i recommend the function Entity1:Visible( Entity2 ) to see if the entity is able to be shot at

**Comment by Zet0rz** [comment]
Good call.

**Comment by lolleko** [comment]
Does it actually shoot through the wall or just at the wall if a zombie is behind it?

**Comment by minin43** [comment]
Visible is a function that checks to see if the eyebounds of an object (player or NPC, for example) meet with any part of the hitbox of the specified Entity2. According to the Wiki, it's done similarly to a trace call.

Semantically, it doesn't seem as if "Visible" will detect something behind a wall.

**Comment by lolleko** [comment]
Okay, but can you confirm that the bullets actually go through the wall or if it's just the turret trying to shoot through the wall, but not actually hitting the zombies.

**Comment by minin43** [comment]
http://wiki.garrysmod.com/page/Entity/Visible

**Comment by Zet0rz** [comment]
I imagine the bullets would just hit the wall, but it's definitely something I'll test when I get to this particular fix/change.

**Comment by Zet0rz** [comment]
It does indeed not take visibility into account. Updating so it will not attempt to shoot at a wall.

**Comment by func-octo** [comment]
If the bullet force is high enough (80+), the bullets would go through thin walls and props.
