### ISSUE TITLE
(Please tag with unrelated) USB 3.0 External Hard Drive

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#37]
I have a 300 GB usb 3.0 sata bridge external hard-drive. I have a motherboard with 3.0 enabled and ready, and have tried this with many computers, with and without 3.0 enabled.

When I transfer any sort of file/folder/zip, I get speeds of 311 KB/s. This is unacceptable. Do you know of a way to fix this issue? I haven't tried reformatting it yet.

**Comment by Zet0rz** [comment]
This is probably not the place to ask for this type of stuff lol
And no, I don't really know. Check your CPU usage I guess?

**Comment by func-octo** [comment]
Nevermind, just had to enable write-caching
