### ISSUE TITLE
Can't buy/open Doors

### ISSUE THREAD

**Issue by OOhSabre** [Zet0rz/nzombies#370]
Cant open Doors even if i have enough money

**Comment by DjNathann** [comment]
Did you put the price on the door/gate?

**Comment by minin43** [comment]
Gonna have to give a more in-depth error report if you want us to be able to help you. Any errors thrown?

**Comment by OOhSabre** [comment]
@DjNathann Yes the doors have a Price
@minin43 Alright, so when i try to buy for example a 750 Points Door i cant buy it even if i have for example 1000 Points. And no i dont get any Errors.

**Comment by Zet0rz** [comment]
Refrain from posting errors like this when they are already addressed in the FAQ on the workshop page; This is not a fault in the gamemode but a fault in one of your addons which blocks the PlayerUse hooks that door openings use. I have done what I can to prevent this from happening as much as possible, but it's random what order hooks are called and if any other is called before and it returns something, the rest are never ran.

If you happen to have Playable Piano, that is a known addon to cause this.
