### ISSUE TITLE
Things that should be visible in creative mode are invisible

### ISSUE THREAD

**Issue by ChrisCj8** [Zet0rz/nzombies#373]
Basically, everything that can only be seen in creative mode (zombie spawns, invisible walls, barricade positions (the fence is invisible, the planks are visible), etc.) except for player spawns, is invisible for me.

I'm pretty sure that this issue is not caused by another mod, because I tried disabling all mods (except for nzombies, of course) and stuff was still invisible.

**Comment by Zet0rz** [comment]
Do you have nz_creative_preview to 1?

**Comment by ChrisCj8** [comment]
Just tried setting it to 0 and that fixed the issue, but why was it set to 1 in the first place? I don't remember changing this variable.

**Comment by minin43** [comment]
When you have advanced mode checked on, and you select the invisible wall tool (or damage wall tool, I think both have it), there's a checkbox for "previewing" what the config will look like after you exit creative mode. Chances are, you selected it on the last time you created a config and forgot to turn it off.
