### ISSUE TITLE
sprint nil issue

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#376]
`[ERROR] addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61: attempt to compare two nil values
  1. fn - addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

ERROR Error: not enough memory

[ERROR] addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61: attempt to compare two nil values
  1. fn - addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

[ERROR] addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61: attempt to compare two nil values
  1. fn - addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

[ERROR] addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61: attempt to compare two nil values
  1. fn - addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

[ERROR] addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61: attempt to compare two nil values
  1. fn - addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

[ERROR] addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61: attempt to compare two nil values
  1. fn - addons/nzombies-master-workshop/gamemodes/nazizombies/gamemode/player_class/sv_sprint.lua:61
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

Lua Panic! Something went horribly wrong!

"not enough memory"`

so i have gotten this. naturally this crashes the server and it does not recover. i believe it is just me due to alterations to some parts of the gamemode however none the less i wanted to know if others have gotten this.

**Comment by minin43** [comment]
Unless there was some recent update altering the sprinting, you either have a conflicting addon or screwed something up yourself, as I've never run into this bug.

Also, for future reference, you don't have to paste the same error 5 times.

**Comment by Zet0rz** [comment]
`ply:GetStamina() < ply:GetMaxStamina()` is the only comparison on that line. Those values are set in the PlayerSpawn hook right above. You might have a PlayerSpawn hook that returns true as to block other hooks and/or a hook by the same name overwriting this. It could also be part of the Lua Panic you get at the end.

**Comment by jaxjaxk** [comment]
not enough memory linked to instance of when the game ends. i have no other information about this.
