### ISSUE TITLE
Console is flooded with errors

### ISSUE THREAD

**Issue by YJ101** [Zet0rz/nzombies#378]
Dunno if I installed this correctly, but for some reason the github download version gives me a flood of errors when playing the gamemode. I keep getting this error flooded into the console:
'[ERROR] gamemodes/nzombies/gamemode/special_weapons/sh_meta_functions.lua:5: attempt to index field 'Weapons' (a nil value)
  1. IsSpecial - gamemodes/nzombies/gamemode/special_weapons/sh_meta_functions.lua:5
   2. EquipPreviousWeapon - gamemodes/nzombies/gamemode/special_weapons/sh_meta_functions.lua:22
    3. unknown - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:83'

Any ideas?

**Comment by Zet0rz** [comment]
Did you recently update? You cannot update by merging the folder into your current installation and overwriting files as this will make you keep files that the update had deleted. `gamemodes/nzombies/gamemode/special_weapons/sh_meta_functions.lua:5` is one of such files. You will need to delete the old folder and install the new version fresh in every update that removes files.
