### ISSUE TITLE
(UNRELATED) Three Questions

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#38]
Since there isn't anywhere else to comment on, I would like to ask three questions.
1. Custom Names (Pack A Punch)
   When you pack a punch a gun, it changes the name. I'd like to add a few extra pack a punch names to other guns. Is there a way of doing this by editing a sort of file?
2. Zombies that attack.
   So I went and download the new nZombies. (With the one inch punch and monkey bombs) and I notice that the zombies push me when they attack me. This gets annoying because a zombie killed me by pushing me out of the map by falling down at the top area of the map.
3. Grenades
   I have no idea how you throw grenades/monkey bombs. Is it unbinded or do I have to press a key or type something?

**Comment by Zet0rz** [comment]
1) Yes, you can add your own custom Pack a Punch names without editing the files by calling the function in any lua file (e.g. one in autorun). It looks like this:
`AddPackAPunchName(class, papname)`
You can replace "class" with a display name (Like "Ray Gun") and it will apply to all guns with this display name, but names assigned to classes take priority. See more in gamemode/display/cl_papnames.lua

2) This was recently changed, it was usually tiny. I will make sure it gets either removed or very small.

3) Grenades are triggered with the key bound to +grenade1, and monkey bombs (and other future special grenades) are +grenade2. Bind a key to these if you haven't already (they are an original gmod bind, but not bound by default)

**Comment by lmao5677** [comment]
Ok, cheers for all of these questions. Closing...
