### ISSUE TITLE
file over ride

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#383]
well when you save now it no longer overrides the old file.

**Comment by minin43** [comment]
What

**Comment by Zet0rz** [comment]
Whut

**Comment by jaxjaxk** [comment]
when you use /save it no longer saves over the old file if you name it the same thing

**Comment by minin43** [comment]
Yes it does. There have been no updates out, and it still works 100% fine for me.

**Comment by Zet0rz** [comment]
This is likely your own modifications or your OS handling files differently.
