### ISSUE TITLE
SQL recomendation

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#386]
I think the option to have the map files save on a SQL database would be nice. if you would like i can cook something up and put it here.

**Comment by Zet0rz** [comment]
I have never used SQL so I have no idea how it works or how to use it. Probably isn't that complicated, but never really did anything to look into it. Is there are particular benefit to using SQL or just text files?

**Comment by jaxjaxk** [comment]
i see 2 main benefits and like you think they are not that big.

1) servers can share SQL so you do not have to sync the files manually across multiple servers.
2) in addiction to 1 you can update maps in SP and it will sync to MP. if you have several people making maps then they will always have the most updated data and you will not have to constantly resend files to eachother.

**Comment by minin43** [comment]
Well this requires Zet0r learn SQL if you want continued support for it. I don't see it as necessary myself.

**Comment by lolleko** [comment]
SQL is overkill, especially if you just want to share filedata (mapconfigs/-scripts if i understand you correctly).
If your servers run on the same hardware you should share your files with hardlinks.

If you want to share maps with your friends I suggest you use a git repo. everyone can commit their changes into the repo and other people will just have to pull, to receive updates which is one line in a terminal or a single click in a git GUI.

**Comment by Zet0rz** [comment]
It is also possible to use something like Dropbox with folder links to automatically sync if pushing/pulling on Github is problematic, although more prone to accidental overwrites.

**Comment by jaxjaxk** [comment]
the reason i want this is i have like 5 people in total that are working on maps some more frequent than others. having instant updates is also good for a server so that map errors can be fixed without having to get rid of everyone and go into creative as you can just switch to SP.

one way or another this week ill cook up something good. i have a functional version, you just would not like it very much.

**Comment by jaxjaxk** [comment]
TBH the part that requires sql is easy as pi and only requires one line to save and one line to load. it is about getting the order correct as query is not an instant thing so you have to use a callback to use the data correctly. at the end of the day the only hard part is getting the maps to load onto the load interface so you can select the ones form the database instead of from files.
