### ISSUE TITLE
reduce server spikes, space out load

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#387]
after some hard work i believe i found out what causes huge spikes in processing that occure every 1/2 seconds or so.

in our first photo we have a configuration for a map that has a ton of well, everything.
![gm_construct0015](https://cloud.githubusercontent.com/assets/18671500/23836764/599c0f4c-074b-11e7-8939-d2fc0fdaf334.jpg)

and in our second image the same configuration after saving it and then loading it.
![gm_construct0016](https://cloud.githubusercontent.com/assets/18671500/23836769/6a8fc136-074b-11e7-9ecf-6442b9d80808.jpg)

notice the huge change in the graph. this happens after you load any map. now what could be causing this? well here is my guess.

what is happening is we loaded all these entities at the same time. because of this all the timed functions run during the same tick ( or close to the same tick) rather than spread out like when we first created them. so now the server has to work hard for 1/2 a second while it calculates all this crap then is lazy for the next 1/2  second. 

the other possibility is that something is not saving or loading correctly. one way or another this is a huge issue as it causes huge spikes in lag that will not go away unless the load function is fixed.

**Comment by Zet0rz** [comment]
Does it persist with those spikes forever after loading or does it calm down eventually? I don't think the fact that they're all created at the same time cause any other lag than during loading itself. What happens if you leave/change map/restart, then load? Do the spikes get bigger if you load the config multiple times without shutting down?

**Comment by jaxjaxk** [comment]
the spikes stay forever. clients leaving and coming back does not change it. map restart does not change it ( naturally because load is run when you change map). this happens regardless of the map however clearly larger maps with more stuff have worse communication issues as well as FPS. var can spike at times in the 25-50 range and that is hell.

**Comment by jaxjaxk** [comment]
![gm_construct0018](https://cloud.githubusercontent.com/assets/18671500/23936451/4680a496-0920-11e7-80e0-41e22e78d79f.jpg)

this is what happens when you space out the loading a bit.
ill cook something up this week that will fix this all however this was something i cooked up in 5 min. it is not enough to load each element with a delay between, i had to load each spawn with a separate delay.

sadly my first attempt shown here required 10 seconds for the map to fully load. i will try to cut it down to 5 seconds though i doubt anyone can make it on the server quick enough to disrupt anything.

**Comment by minin43** [comment]
This might explain a lot. Fuckin'... I have a 1070 Founders Edition and a I5 quad core running at 3.4 GHz, and I average anywhere from 40-70 FPS. I know my comp isn't bottle-necking, there's just gotta be something going on we don't see. 

Have you tried placing everything and then actively playing? Then re-loading and re-playing? Maybe sitting in creative mode has nothing to do with the gameplay.

**Comment by jaxjaxk** [comment]
i defiantly fixed the issue however you will not like it at all. effectively i took all the load functions from all the items and copy pasted them to the load function under the loop that would normally calls them ( naturally i removed this loop). i then set up for loops with timers and a counter so that every .01 second an entity is loaded into the server thus spacing out the whole load method. so unless you have 500+ entities to load it will never cause a problem as everything will be loaded by the time players could ever hope to start.

We can do this method if you want, but it kind of is a step back in how we made it easier to save/load entities. perhaps we could load all core entities this way and then leave the loop for all custom entities.

one way or another i will gladly upload if you ask. else i will assume you do not want this messy way of fixing it.
