### ISSUE TITLE
about the zombie Shield/help

### ISSUE THREAD

**Issue by Dolhpin** [Zet0rz/nzombies#389]
i have a problem with the zombie sheld i dont know how to find it or the parts every map but i dont even dont know where i do i find the craft table i rly like the zombie sheld hope you help me.

-edited i did everything i search on creative mode i didn't find the parts or the craft table i tried weapon placer mabye i buy it but i didn't find it aigen and i searched the files i have found

nz_zombieshield i changed some of them like SWEP.Spawnable=True  but i didn't had it or the admin spawn

i found the buildable_table but i didn't change nothing idk i tried still idk but i can see ist on the game but why i can't find the parts i tried everything to find it hope you have good awnser for that..

**Comment by Worset** [comment]
Zombie Shield requires map scripting to accomplish, which in turn requires experience with LUA coding. (although its not too hard to figure it out yourself, like I did).

https://github.com/Zet0rz/nzombies/wiki/Map-Script-Reference-Snippets

**Comment by Zet0rz** [comment]
Worset is right, buildables require scripting. You can pretty easily add the shield alone into your configs if you want by following [this guide on how to add a map script](https://github.com/Zet0rz/nzombies/wiki/Map-Scripting#setting-up), then pasting [this code](https://github.com/Zet0rz/nzombies/wiki/Map-Script-Reference-Snippets#snippets-1) into it, but **remember to edit it like the comments say**.

If you're talking about where to find it in the official configs, it only currently exists in the Imprisoned config. The table is located down by Pack-a-Punch.

**Comment by Dolhpin** [comment]
oh god i am so bad at this idk what is going even i dont know what to do now or where/how to start you can tell me how to start from where to end bec. ist should be already in the game auto why we need to do the work, i hope when this gamemode will gone be added on workshop dont say we are gone need map scripting to add stuff or something else just thats not fair and many ppl will gone have question and in the maps Pack-a-Punch i have found but i didn't find the table/parts witch map if you can tell me to search aigen..

**Comment by minin43** [comment]
Whoa there - let's fix that giant block of text and add in some proper grammar. This is  nightmare to read.

**Comment by Dolhpin** [comment]
you can see ist not my first language dont need to be cool.

-or i am typing fast Derp

**Comment by minin43** [comment]
Just follow the links provided by Zet0rz. If that's not enough to help you figure out how to create a script for the gamemode, I'm afraid you're going to need to seek outside help.

**Comment by Dolhpin** [comment]
well thanks for that thats not helpful try the next time to help some ppl..

and i know some ppl have that problem

**Comment by minin43** [comment]
There was an effort to provide help. You were linked to a guide over how to create the script, and given several additional code snippets to help you along. If you don't understand the basics of object-oriented programming, or just programming in general, no one wants to walk you through all of it just so you can *maybe* create a script that *may* possibly go up on the Workshop. 

90% of us who frequent this Github page are all real nice people who want to help out, but if those guides Zet0rz linked aren't enough, then you don't know enough about Lua programming to be writing a script. Sorry not sorry.

**Comment by Zet0rz** [comment]
> well thanks for that thats not helpful try the next time to help some ppl..

I provided exact code you can just copy-paste. All you have to do is change the coordinates and angles of the locations you want to shield parts and the table to spawn in. And then call `shieldX:Reset()` inside your `mapscript.OnGameBegin` function (if you don't have one, make one).
