### ISSUE TITLE
Monkey Bomb models, sounds, complete

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#39]
Finish the Monkey Bomb weapon by giving it a model, viewmodel (with animations), sounds, and an HUD icon.

**Comment by minin43** [comment]
You could probably use this and just give credit to the creator, it might save a lot of time: http://steamcommunity.com/sharedfiles/filedetails/?id=207347505

EDIT: I see you've made a comment asking about it. Yea, you can use the addon. Just make sure you give proper credit to him when the workshop version of nZombies has been released and you'll be fine

**Comment by minin43** [comment]
What's the status on this? Are you going to use the one on the workshop? I feel it would be for the best to do so.

**Comment by Zet0rz** [comment]
No the one on the workshop really doesn't work, it just drops a nade modelled after the monkey bomb, no animation or anything. My plans was to take the model from WaW fully animated and a viewmodel animation with c_ hands like the perk bottle. And I was going to do that here after finishing the zombie models :)

**Comment by minin43** [comment]
Ah nice.

I understand you're aware of my sentiment, but I feel like you should port over either the marine models (from Nocht in WaW) or the 4 character's models to use as the _default_ playermodels. It'd really complete the picture. Not the _only_ player model, just the default.

**Comment by Zet0rz** [comment]
I'm sorry, but that is not going to happen in the gamemode itself. It's something people will have to go out and do themselves. I have plans for a trailer when this is done, and in that it's gonna be 4 typical gmod player model characters as well.

**Comment by minin43** [comment]
Well, I have searched extensively for the hero players models and could not find them absolutely anywhere. What currently are the default player models?

**Comment by Zet0rz** [comment]
In the gamemode? None, it's based on your sandbox setting.

**Comment by Zet0rz** [comment]
The monkeys are coming ... 910356d944dfc38c2ada73b42fd7250cffd39af2
