### ISSUE TITLE
Perk Bottle Camo Glitch?

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#394]
When drinking a perk bottle sometimes the weapon gets the perk bottle you drank into a camo.

![screenshot_1](https://cloud.githubusercontent.com/assets/24857329/24349119/589cb12a-12de-11e7-88f0-63f733d6310a.png)

**Comment by func-octo** [comment]
Fascinating... I have no idea what would cause that, but it doesn't look half bad...

**Comment by DjNathann** [comment]
It takes the Hands,scope,gun and everything to remove it you gotta pap

**Comment by DjNathann** [comment]
It doesn't let me reload when the camo bug appears.
