### ISSUE TITLE
Is my game file corrupted?

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#395]
Ive been getting very buggy stuff (for me) in-game like for example.
Dust becomes pixel ![screenshot_2](https://cloud.githubusercontent.com/assets/24857329/24349230/9da3df82-12de-11e7-85cd-2602cdfbc1e2.png)
Zombie as hellhound ![screenshot_3](https://cloud.githubusercontent.com/assets/24857329/24349236/a240e152-12de-11e7-82e9-08dcdfa01dd4.png)
Zombie has cube eyes ![screenshot_4](https://cloud.githubusercontent.com/assets/24857329/24349243/a743343e-12de-11e7-8239-0f0d12c32660.png)

**Comment by func-octo** [comment]
Try typing `mat_viewportscale 1` and see if it helps your pixel problems.

**Comment by DjNathann** [comment]
Doesn't work.

**Comment by YuRaNnNzZZ** [comment]
Can you stop making bug reports from my server yourself and leave them to me?
Especially when you don't know what i've modified in the gamemode's files.

**Comment by DjNathann** [comment]
Ay im sorry fam.

**Comment by DjNathann** [comment]
Nvm the l4d2 content folder was creating the particales bug.
