### ISSUE TITLE
Perk camo bug.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#396]
After buying a perk there is some chance to earn a Perk camo of the perk i drank.
![screenshot_1](https://cloud.githubusercontent.com/assets/24857329/24490191/d192eb04-1521-11e7-87a9-6fe830ac330d.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/24857329/24490199/d6befbd6-1521-11e7-9cb6-d582a058c9fc.png)

**Comment by DjNathann** [comment]
It block the scopes and doesn't let you drink other perks.

**Comment by DjNathann** [comment]
and can't buy other perks.

**Comment by Zet0rz** [comment]
The error you get is more important. Why close the old issues where you had a specific error?

**Comment by DjNathann** [comment]
I wasn't clear enough.

**Comment by DjNathann** [comment]
I found out how to get this bug.

The server thinks you drank 2 perks even doe you are only drinking one so basically it does the drinking sound effect 2 times and then you get the camo of the perk you drank.

**Comment by minin43** [comment]
Please leave the error message that appears in either the client console or server console.

**Comment by DjNathann** [comment]
It doesn't show any errors.

**Comment by DjNathann** [comment]
Ok this isn't the bug.

[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/weapons/sh_wep_modifiers.lua:217: attempt to index field 'NZModifiers' (a nil value)
  1. RevertNZModifier - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/weapons/sh_wep_modifiers.lua:217
   2. func - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/weapons/sh_wep_sync.lua:30
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by DjNathann** [comment]
Ok i found the error bug.

**Comment by DjNathann** [comment]
I found the bug.


[ERROR] addons/nzombies gamemode pack/gamemodes/nzombies/entities/entities/perk_machine/shared.lua:106: attempt to call method 'SetPerk' (a nil value)
  1. func - addons/nzombies gamemode pack/gamemodes/nzombies/entities/entities/perk_machine/shared.lua:106
   2. Buy - addons/nzombies gamemode pack/gamemodes/nzombies/gamemode/points/sh_points.lua:61
    3. unknown - addons/nzombies gamemode pack/gamemodes/nzombies/entities/entities/perk_machine/shared.lua:126

**Comment by Zet0rz** [comment]
The bug happens because you didn't get the weapon. You didn't get the weapon because some other addon messes with weapon handling. The gamemode just gives you the weapon.

**Comment by DjNathann** [comment]
It happens when im using TFA Weapons.

**Comment by minin43** [comment]
He's saying you have conflicting addons

**Comment by DjNathann** [comment]
Ok so the new patch is ok I still get the perk camo bug but at least I could buy perks.

**Comment by jaxjaxk** [comment]
@Zet0rz i do not think it has to do with conflicting addons as this can happen to any weapon at any time regardless of addon. every weapon i have ever used had this bug at some point however a majority of the time it does not happen.

**Comment by DjNathann** [comment]
Yea i just disabled all addons and i still get the textured perk.
