### ISSUE TITLE
Final Zombie Models

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#40]
Get the rest of the animations as well as fix the wierdly black bump maps (anyone good at texturing?)
Animations needed are:
- Idle
- Barricade jumping (just need to code these in)
- Jump and drop

Also use longer fadein and fadeout times to blend better.
Zombies also need hit groups to actually be headshot-able again.

**Comment by Zet0rz** [comment]
All animations done, they look really cool. Expect no more T-stance idle animations :D
Time to compile LODs. This is gonna take a while.

**Comment by minin43** [comment]
Noice!

**Comment by Zet0rz** [comment]
Man these LODs are going down low! http://i.imgur.com/Qbq2STc.png
I'm not sure what to put as the range, but this looks like it's gonna be optimized xD

**Comment by Zet0rz** [comment]
Uploaded and added in commit f825482d2c1ed24381b021c611e2aedb72c6ccea

**Comment by minin43** [comment]
So increased FPS when looking at a massive amount of zombies?

**Comment by minin43** [comment]
double noice
