### ISSUE TITLE
Panzersoldat Frozen bug (Yep its back)

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#400]
He freezes when he shoots his claw and gives this error.
[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/nz_panzer_claw.lua:133: attempt to call method 'Release' (a nil value)
  1. func - addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/nz_panzer_claw.lua:133
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by minin43** [comment]
It never went away?

**Comment by DjNathann** [comment]
Panzer always have a backup plan.

**Comment by minin43** [comment]
Zet0r already knows about this bug and it's been fixed, it just has yet to be released. Close the issue.
