### ISSUE TITLE
*IMPORTANT* Invisible Wall Causing Massive Performance Issues

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#401]
Mostly a just a note for Zet0r. I discovered that invisible walls, when used in large quantities, create huge performance issues for even the best computers. We are currently unsure as to why. This issue is currently leaving my map unplayable.

**Comment by jaxjaxk** [comment]
grab some results using FProfiler. that can help you detect what is the cause.

i will also investigate this claim.

**Comment by DjNathann** [comment]
i sometimes get stuck in the invisible wall when it creates spike lag if im near it.

**Comment by minin43** [comment]
>When i get near the invis wall i start to lag and then get stuck in the invis wall the only way to get out is you'r friends or players push you out of it.

Please remain on topic
