### ISSUE TITLE
bottlenecking

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#402]
i have done a bit of preliminary investigation into the bottle necking of how the server runs. the blame for bad FPS is in the amount of data it has to process in such a limited time.

here are some preliminary results of using FProfiler on a server run on my computer. (vieo about the tool found here :https://www.youtube.com/watch?v=vEbCrIjh26g)

![gm_construct0019](https://cloud.githubusercontent.com/assets/18671500/24590568/b7335984-17b4-11e7-853c-619962e8d6fd.jpg)
![gm_construct0020](https://cloud.githubusercontent.com/assets/18671500/24590571/c1e76f82-17b4-11e7-88f6-d30960ca4e50.jpg)

these photos were taken after playing for 2 rounds by my self on a decent map.

from these results we can conclude 2 things are mainly to blame for bad FPS.

1) the zombies think function. look, you can't have them run an expensive function every second with 20-50 zombies on the map and not see a problem. we need a better method of finding targets that is not have to go through an entire list of entities every second.

2) the zombie spawners. i hope we all know how the spawners work. it is also a very epensive function run every few seconds. while i love how it works it needs be fixed up a bit. we do not need them to be so accurate. maybe scrap the old way and put in a new method.

we should seriously focus on fixing these issues. if i have time in the next few weeks at the very least i will work on revamping the zombie find targets function.

**Comment by minin43** [comment]
How does the zombie think function work?

**Comment by Zet0rz** [comment]
I have already done some FProfiling a while back myself, and yes, the animation control and amount of zombies is the biggest resource consumer of the gamemode. I eventually want to rewrite the bot base more efficiently and more easy to use, a better targeting system should be doable. The zombie spawners' update rates can be changed with a convar. Do want to look into them but not sure if I'll end up changing them.

**Comment by jaxjaxk** [comment]
i have found a tactic that works. here are the changes i made.

1)  the function self:SetTarget(self:GetPriorityTarget()) only runs now when the zombie has no target OR it is not "distracted" ( sorry mate but we do not need a target priority system TBH)

2) a timer is set up so that every 1 second we search the area around HUMANS (within 80 units). to find zombies. every valid enemy has it's target set to the human. (unless the zombie is "distracted")

3) monkey bombs and any other entity like it works similar to above except it finds every zombie and not just the ones near it. it also sets the zombie to "distracted"

so let's explain this. 
#1 was done because that truly is bad coding. i can not have 10-50 entities run a large for loop with literally every entity and not expect some really bad processor lag. not to mention we do not need target priority or a function like "IsValidTarget" let alone funcitons to handle stuck when Nextbots already have that built in. so having this run when a zombie just can not find a target seems best.

#2 was done because we can either have 10-100 zombies searching for nearby humans or 1-20 humans search for near by zombies. this takes the processing load off of the zombies and puts it onto the players that there are not as many. 

#3 was done similar to #2. distracted zombies remain distracted until the entity is no longer valid. then naturally they run self:SetTarget(self:GetPriorityTarget()) as always.


i plan to continue making it better as i go. i HIGHLY recommend making these changes.

**Comment by minin43** [comment]
So what I'm getting out of this change is: if you don't have a monkey bomb, once spawned, the zombie will come after you until it dies.

**Comment by jaxjaxk** [comment]
@minin43 
Before the change the heavy taxing function "findprioeitytarget" would run every second. This reduces the number of times it has to run.

When a monkey bomb is thrown every zombie is considered "distracted" by the bomb. When distracted the distraction is the target and they ignore nearby players. When the bomb is gone the zombies locate their next target.

Look, everything works exactly as it did before, not it's just more efficient so shit does not hit the fan.

**Comment by minin43** [comment]
Can a zombie's targetting change w/out the use of a monkey bomb?

**Comment by Zet0rz** [comment]
> the function self:SetTarget(self:GetPriorityTarget()) only runs now when the zombie has no target OR it is not "distracted"

This sounds like it'll break Zombie Blood as well as general targeting. Zombies are supposed to retarget when another player gets closer to them than their current target, even if the range is more than 80 units. Although I completely agree that looping through `ents.GetAll()` is dumb. Here's what I propose:

1. Replace `ents.GetAll()` with `nzEnemies:GetHighestTargetPriorityGroup()` which returns only a table of entities who has a target priority, and only the ones in the highest group that is not empty. This'll make it loop only through targetable entities (props _can_ be targeted if scripted to do so).

2. Add a convar to control how often zombies retarget

Feel free to try implementing these yourself, it might be a bit before I get around to do it with my current schedule. I might throw something together over the course of the next week where I'm off uni.

**Comment by jaxjaxk** [comment]
@minin43 2) when a player gets within 80 of a zombie they become the target.

**Comment by jaxjaxk** [comment]
@Zet0rz does not break zombie blood.

**Comment by lolleko** [comment]
**Profiler**

The reason while most zombie functions are bottlenecking is that theprofiler records the time it takes to execute a function. Many of these functions include blocking timers the duration of those timers will be taken into account when caculating the total. So the profiler results are not accurate or representative, at least for the zombies.

**GetPriorityTarget**

Using a seperate table including only targetable ents, would reduce the iteration cost, but increase the general overhead becasue you would need to update that table 24/7. So im not sure that this will increase the performance, could even make it worse.

The only reason why we used `ents.GetAll()` in the first place was TARGET_PRIORITY_ALWAYS which basically made an entity targeted by all zombies no matter of the distance.
https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/entities/entities/nz_zombiebase.lua#L660
We should **disable** this feature, so we can use  `ents.FindInSphere()` over `ents.GetAll()` https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/entities/entities/nz_zombiebase.lua#L675
Internally  `ents.FindInSphere()` also iterates over every entity, but it should be faster since that iteration is handled in the C++ context.

EDIT: Out of 1:47 minutes this function only consumed 200ms processing time, which really isnt a big problem on modern multicores. The fact that one call takes 2ms avg is not great but really not the major reason of lags.

**Spawner**

The spawn system is indeed very inefficient. I will try to dig up a more efficient scheduling algorithm.

**Comment by Zet0rz** [comment]
> you would need to update that table 24/7

The table doesn't need to updated any other time than when `ent:SetTargetPriority()` is called on an entity or the entity is removed or killed. It should just do something simple like:
```Lua
function meta:SetTargetPriority( priority )
    targets[self.OldPriority][self] = nil
    targets[priority][self] = true
    -- More stuff ...
end
```

And then we can just add `nzEnemies:GetHighestActiveTargetPriority()` that returns the highest non-empty priority enum and `nzEnemies:GetTargetableEntities(priority)` that returns `table.GetKeys(targets[priority])`. Zombies can them by themselves define what priority to search for (such as hellhounds ignoring monkey bombs) by directly specifying what priority to look for.

**Comment by lolleko** [comment]
Okay right. But still not sure if that would be that much faster (all the table lookups) and you would still need to make the distance check in lua for every entity of that priority. Guess the only way to find out is implementing both and comparing.

But again i really dont think GetPriorityTarget is the major bottleneck. It doesnt perform ideal but it should not the reason for bad performance.

**Comment by Zet0rz** [comment]
> But again i really dont think GetPriorityTarget is the major bottleneck.

I agree on that. Also zombies should _always_ target regardless of distance. Distance should only ever be compared when comparing two targets of the same priority.

**Comment by jaxjaxk** [comment]
@Zet0rz
TBH we don't need to compare distances in my second method. And again. You really don't need priority. All you need is if the zombie is distracted by an object or not. If need by you can just reset the target to an object without setting it as distracted and the zombie will still target a player if they get too close or shoot at it enough.

**Comment by Zet0rz** [comment]
I am not going to make zombies target only 1 player for their entire lifespan. Zombies will _always_ retarget  to the nearest valid target. And looping through players instead of zombies is not a solid solution as it sets a hard-limit on the distance you have to go close to get a zombie after you instead.

**Comment by jaxjaxk** [comment]
@Zet0rz i do not think you fully understand my method as it works exactly how it did before but with less bottleneck ( as was the point). here are the ways the zombie will pick/ change targets.

1) when the zombie spawns or when it does not have a valid target it will call the original function self:SetTarget(self:GetPriorityTarget()) ( exact original code here. just not run as often)

2) when a player gets too close to a zombie, say 80 units the zombie will target them instead. ( as it did before)

3) when a new entity is introduced. say a monkey bomb. the zombie will target the bomb and ignore players as it did before. ( once the entity is gone it will run self:SetTarget(self:GetPriorityTarget()) as it no longer has a valid target)

if you seriously wish for zombies to target the closest player at all times then you can easily write a simpler method similar to 2 where instead of having 70+ zombies searching for the closest target you have the humans do it. the other option is retargeting based off of damage. essentially when a player does enough DPS to a zombie it will change targets. this could be a better method and cause less problems over all.  

the entire idea of what i did was to make it so zombies would not constantly search for monkey bombs when they are only going to find them 1/1,000 times. instead when a bomb spawns it does the searching for zombies every second so that the we only run the code in the 1/1 times.

 it also changes the method of zombies looking for humans near them to humans looking for zombies near them. you know. so instead of 70+ zombies running "find ents in sphere" every 1 second, 20 humans run the same function. so less processing needed.

understand again that this is just a better way to reduce the amount of code run and it does EXACTLY what it did before with no downside. if you truly desire you can implement priority targeting, i only threw that out as it seriously is not needed at all.


in the end once i run fproflier again the functions on finding humans were no longer foudn on teh bottleneck list. one way or another I'm going to mess around with this more. at the very least do 3 so that zombies are not always looking for priority targets that do not even exist 99% of the time.

**Comment by lolleko** [comment]
> it also changes the method of zombies looking for humans near them to humans looking for zombies near them. you know. so instead of 70+ zombies running "find ents in sphere" every 1 second, 20 humans run the same function. so less processing needed.

So how does a prop or somehting else with target priority signal a zombie its a target?

Can you provide the code for your solution and how much faster it actually is? I would be interested in a more effeiecnt approch but it should offer the same features we have right now and should be noticable faster.

**Comment by jaxjaxk** [comment]
for a monkey bomb i use this

`ENT.NextDistraction = 0
function ENT:Think()
	if SERVER then
		if self.NextCymbal and self.NextCymbal < CurTime() then
			self:EmitSound("nz/monkey/cymbals/monk_cymb_m.wav")
			self.NextCymbal = CurTime() + 0.2
		end
		if self.NextDistraction < CurTime() then
			
			for _, target in pairs(ents.GetAll()) do
				if nzConfig.ValidEnemies[target:GetClass()] then
					target:SetTarget(self)
					target.Distracted = self
					print("target distracted")
				end			
			end
			self.NextDistraction = CurTime() + 1
		end
	end
end`

**Comment by jaxjaxk** [comment]
@lolleko with respect to how much better my method works. it is no longer on the bottleneck list.
