### ISSUE TITLE
Latest update breaks many powerups

### ISSUE THREAD

**Issue by globalcringe** [Zet0rz/nzombies#408]
Max ammo gives no ammo, nukes do nothing but play "ka-boom", carpenter does nothing, death machine errors and so does zombie blood.

Error when getting zombie blood or death machine:
```
[ERROR] gamemodes/nzombies/gamemode/powerups/sh_powerups.lua:43: attempt to index a nil value
  1. Activate - gamemodes/nzombies/gamemode/powerups/sh_powerups.lua:43
   2. unknown - gamemodes/nzombies/entities/entities/drop_powerup/shared.lua:51
```
The others just do absolutely nothing, no errors or anything.

**Comment by minin43** [comment]
Prolly just a really simple oversight

**Comment by TheTrickyDonut** [comment]
Some power ups work like instakill and double points but other than that, a lot of the perks doesn't work too.

**Comment by Zet0rz** [comment]
I think I might know what's causing it. Thanks for pointing it out.
