### ISSUE TITLE
Hellhounds

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#41]
We'll need models, sounds, and the entity code itself.

**Comment by minin43** [comment]
Here's the "FETCH ME THEIR SOLES" sound that plays. The quality isn't the best, but for the life of me I couldn't find one that sounded any better. https://www.dropbox.com/s/4lu5hsejtlewd5s/fetchmetheirsoles.wav?dl=0

**Comment by minin43** [comment]
Here's a link to the announcer that screams "FETCH ME THEIR SOLES" during the round start. It isn't the best quality, but I couldn't find a better sounding one for the life of me. https://www.dropbox.com/s/4lu5hsejtlewd5s/fetchmetheirsoles.wav?dl=0

**Comment by Zet0rz** [comment]
I have a folder full of all the sounds from CoD WaW Zombies, that includes all Hellhound sound effects as well as the Announcer saying "Fetch me their souls!". I will add those in an upcoming update.

**Comment by minin43** [comment]
Awesome

**Comment by Zet0rz** [comment]
Status update: We now have the models. The NPC was already coded so we just have to implement it and assign the animations and sounds. We also need to integrate them into the general round system as well as add their Lightning spawn effect

**Comment by Zet0rz** [comment]
Sounds added in commit 87836001b1625746376e403a8cdf4c7e6c6daa70 It turns out Lolle already has the lightning effects, so they should be all done very soon!

**Comment by func-octo** [comment]
Yay! On the side note, should I make a map in hammer to test zombie behavior (i.e. jumping over barricades, normal doorway barricades, stairs (since they get stuck next to most stairs), corners)?

**Comment by Zet0rz** [comment]
Final stage of beta on commit 6173353a5efb2d3bf29cfcccb448d3261553f146. The next one will incorporate it into the main game with no convar to turn off (you'll have to disable special rounds and/or use the coming Map Setting to change what spawns)
