### ISSUE TITLE
Navmesh doesn't apply to all maps

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#413]
Clicking the Generate Navmesh will not force all maps to generate and gives out this error.
![screenshot_7](https://cloud.githubusercontent.com/assets/24857329/24857796/db18cbb4-1de9-11e7-81d6-7d60a552651f.png)

**Comment by minin43** [comment]
workaround: type nav_generate in console.

**Comment by DjNathann** [comment]
I have
didn't work.

**Comment by minin43** [comment]
Then there is a problem with your garry's mod client. If you can't open a map in sandbox and type nav_generate in console, that is not nZombies' problem.

**Comment by Alig96** [comment]
The reason for this error IIRC is because you're not spawned into the world.

Solution: Go into create mode land on the ground (as in don't be in no clip) then try generating the nav mesh.

**Comment by lolleko** [comment]
look at a surface and type nav_mark_wallkable then try nav_generate again. I also wrote this in a guide years ago. You might find more info there: http://steamcommunity.com/sharedfiles/filedetails/?id=485737805

**Comment by lolleko** [comment]
The error should be catched regardles. Maybe print something in chat that tells the player ro properly spawn in first or tell him how to manually generate the mesh.

**Comment by DjNathann** [comment]
Tryed all did not work..
