### ISSUE TITLE
Holding the Morphine while downed.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#414]
After attempt to revive a teammate and going down will still hold the morphine.
Also the revive bar will go off like [=====] to [=====]======= if you revive the ground instead the body.

No errors on console.

**Comment by Zet0rz** [comment]
It will go off the bar if it isn't stopped when it reaches the end. This means going down doesn't instantly cancel it which it should.

**Comment by jaxjaxk** [comment]
revive system is strange. i changed it so that the bounds of players change when they are downed so that it is easier to revive them. makes it a bit more fair considering how hard it is for people to revive others.

**Comment by DjNathann** [comment]
If someone is revive the player then leaves the player but he keeps holding the morphine and when someone else revive the downed player he gets insta revived but the player who was revive first keeps the morphine.

**Comment by DjNathann** [comment]
The revive box is still the same like the old update instead you can just run around with it and if a teammate revives the player you'r reviving you would be stuck with it unless a player goes down to revive him or die..
