### ISSUE TITLE
Speed Cola Rapid Fire TFA Weapons

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#415]
If you have speed cola and hold reload while using a TFA weapon, you can fire any TFA weapon as fast as you want.  This includes weapons that have bolt or pump such as sniper rifle or shotguns.

**Comment by globalcringe** [comment]
I thought it was just a server-specific issue, but guess not? #412

**Comment by Zet0rz** [comment]
I'll look into it. It might be on TFA's end, but it could also be a minor thing to just add/remove to the modifications.

**Comment by sh4d0w59** [comment]
Gonna close this issue down as there are many duplicates of it and it's a well known glitch.  Issue closed.
