### ISSUE TITLE
Can not interact with anything

### ISSUE THREAD

**Issue by TIH190** [Zet0rz/nzombies#416]
While in my short and simple map, I couldn't interact with anything and it would say that something is causing script errors. I spammed e, I tried switching the buttons to interact, and I even downloaded the latest files to see if anything was wrong, still the same problem. Please help.

**Comment by minin43** [comment]
It sounds like you have addon conflicts. Check [here](https://github.com/Zet0rz/nzombies/wiki/Finding-Conflicts-&-Known-Incompatibilities) and see if you have any of the shown addons installed on your client or server.

Please post whatever the error(s) are below so we can help diagnose the problem.

**Comment by TIH190** [comment]
I tried checking for the addons, which I didn't have installed, and I put the hook commands in the console, which when I did, it showed up as a script error.

**Comment by minin43** [comment]
_**Please post whatever the error(s) are below so we can help diagnose the problem.**_

**Comment by TIH190** [comment]
[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/special_weapons/sh_meta_functions.lua:5: attempt to index field 'Weapons' (a nil value)
  1. IsSpecial - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/special_weapons/sh_meta_functions.lua:5
   2. v - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/itemcarrying/sv_gameplay.lua:7
    3. unknown - lua/includes/modules/hook.lua:84
That is what shows up in the console.

**Comment by Zet0rz** [comment]
Oh look, it's the error you get if you updated the gamemode on top of an old installation :v 
Anyway, yeah don't update the gamemode on top of an old installation. If we delete files and you just overwrite, the deleted files are not there so they are not overwritten (by nothing), so you keep the old pre-update file which breaks stuff.

**Comment by TIH190** [comment]
Thanks, so don't replace the files and overwrite them, just delete the update files, then place the new ones in, correct?

**Comment by TIH190** [comment]
Never mind, it is, Thank you very much.
