### ISSUE TITLE
little by little better coding.

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#417]
I am working slowly to fix the small stuff little by little that uses up the processor so much when it is not needed. using FProfiler i'm targeting from top to bottom and doing whatever i can to reduce the load on the processor.

as always the main target is the zombie base class. this naturally takes time but in the meantime between hits i am working on some moderate stuff that hits the server about half as hard. so basic math, do 2 of these and it equals one of the big problems.

i will post the suggested changes here and encourage others to do the same. i am mostly targeting misuse of the 'think' function and hook as that is run every frame even when not needed. so here is my first huge reduction.

before we used this for the health regeneration for players.

```
hook.Add( "Think", "RegenHealth", function()
	for k,v in pairs( player.GetAll() ) do

		if v:Alive() and v:GetNotDowned() and v:Health() < v:GetMaxHealth() and (!v.lastregen or CurTime() > v.lastregen + HealthRegen.Rate) and (!v.lasthit or CurTime() > v.lasthit + HealthRegen.Delay) then
			v.lastregen = CurTime()
			v:SetHealth( math.Clamp(v:Health() + HealthRegen.Amount, 0, v:GetMaxHealth() ) )
		end
	end
end )
```

naturally this is what i am talking about when it comes to, not bad, just not perfect coding. we are using a loop in the think function when 95% of the time it is not needed! so how should we fix this?

well i used this instead

```
hook.Add( "EntityTakeDamage", "PlayerHealthRegen", function(ent, dmginfo)
	if ent:IsPlayer() and ent:GetNotDowned() then
	print("not down")
		if timer.Exists( (ent:EntIndex() ).."player healing" ) then
			timer.Destroy( (ent:EntIndex() ).."player healing" ) 
		end
		if timer.Exists( (ent:EntIndex() ).."player heal buffer" ) then
			timer.Start( (ent:EntIndex() ).."player heal buffer" )
			print("heal buffer reset")
		else
			timer.Create( (ent:EntIndex() ).."player heal buffer", HealthRegen.Delay, 1, function()
			print("starting heals")
				timer.Create((ent:EntIndex() ).."player healing", HealthRegen.Rate, 0, function ()
					if ent:Alive() and ent:GetNotDowned() and ent:Health() < ent:GetMaxHealth() then
						ent:SetHealth( math.Clamp(ent:Health() + HealthRegen.Amount, 0, ent:GetMaxHealth() ) )
						print("healing")
					else
						timer.Destroy( (ent:EntIndex() ).."player healing" )
						print("stopping heals")
					end
				end)
			
			end)
		end
		
	end
end)
```

looks complicated right? so let me break it down.
when a player that is not downed takes damage a timer is created ("player heal buffer") as well as a timer destroyed ("player healing"). when the timer "player heal buffer" is up a new timer is created called "player healing". this is the healing timer that heals the player every HealthRegen.Rate until they are fully healed, or the player is hit again. so why do this? well for one the timers do not exist unless the player does not have max health.

**Comment by Zet0rz** [comment]
I'm pretty sure constant timer creation and deletion is considered worse coding than a unified think hook. Also a think hook comparing numbers is the simplest think hook you'll get, and you _will_ need think hooks. I'd like to see the FProfiler results from this change though.

**Comment by minin43** [comment]
Why constantly create/delete them?  Create them all outright and edit them as needed.

**Comment by jaxjaxk** [comment]
@Zet0rz tested and it is not worse coding. uploading the FPprofiler results will not change much as the timers only work when players are hurt IE the result will be 0 unless players get hurt. creating timers does take more processing power than not (obviously) however keep in mind this runs only when players are hurt and only runs for players that are hurt (so no for loop needed) it also spaces out when it runs so players are not healed all at once. ( players damaged at different times so they heal at different times)

**Comment by lolleko** [comment]
Define bad coding? I mean good/bad coding is very subjective. I persoanly almost always prefer the shorter and cleaner solution unless there is really a huge performance impact with this approach.

For example here its 8 lines vs 25 and both versions basically do the same right?

**Comment by jaxjaxk** [comment]
@minin43 the reason for creating and deleting them was so that they do not exist 90% of the time so the code is not run for the 90% of the time when it is not needed. it also opens up the better coding method that it only runs for the players that are hurt and not all players. to put it simple when all players are at full health before the hook still ran, now it will not run. and this WAS  a medium bottleneck. it ranked about half as bad as the zombies locating targets ever second bottleneck.

understand my objective is to eliminate code that does not need to be run. in my opinion putting almost anything in the think function is a taboo. not even kidding at least 20 of the top 50 bottlenecks are because of the think function.

**Comment by jaxjaxk** [comment]
this brings me to my next fix. it is the zombie_base.lua file and naturally it is in the think function. now i have modified this file so too much and do not plan to release the whole thing until it is ready. so here is one that will save a lot of time.

```
		if self:ZombieWaterLevel() == 3 then
			self:RespawnZombie()
		end
```

This. this is VERY bad coding in so many ways. i do not care what you think this is just BAD. we are literally checking ever frame for every zombie to see if it is in water. for gods sake include it in the if statement here. because their is 0 reasons for why we need to run self:ZombieWaterLevel() every single frame. hell, i would recommend only running it every 5 seconds. in fact that is what i do.

```
		if self:GetLastTargetCheck() + 1 < CurTime() then
			self:SetTarget(self:GetPriorityTarget())
		end
```

@lolleko this is bad coding. this is a great example of bad coding. i can understand checking to see if a zombie is underwater but their is no reason why we need to check over 100 times a second on this.

**Comment by jaxjaxk** [comment]
@lolleko normally the shorter code is better i get it. i have taken classes in coding before and can do a rough calculation of what method is better however it is a huge pain in the ass to do it. so let me compare the two methods shown at the top. we will compare both when players are hurt and not hurt.first we have the before code.

the before code was run 100 times a second roughly. now we assume it already has a  list of players so that player.GetAll() is just an array. if 0 players are hurt we run the code

`if v:Alive() and v:GetNotDowned() and v:Health() < v:GetMaxHealth() and (!v.lastregen or CurTime() > v.lastregen + HealthRegen.Rate) and (!v.lasthit or CurTime() > v.lasthit + HealthRegen.Delay) then
`
to be nice we will say each function has a value of 1. so most of the time the player is alive, not downed and health is max. so it stops after that normally. with 20 players that is a value of 80. if players are hurt then 2 more functions above are run and the code in the if is run. with 20 players that is 240 in the worse case run every single frame.

now lets look at my code. if every player is healthy then 0 timers exist and so 0 code is run. the value is 0 ( keep in mind the timers are specific to each player so up to 20 times can exist in this example.) now here is where my method is a bit inferior. creating timers naturally takes more time than most functions and such. to be fair players will never get harmed all at once and if they do it will be a spike so small it will not be noticed. ( i tested and proved that myself) so we will assume the timers already exist. so if all players are harmed all timers exist. so 20 players and we have to check 1 timer each. and as we all know i pretty much used similar code to the before. so we get about 1+4 for each player giving us a value of 100 for all players hurt every frame. and naturally in the process of healing we created 40 timers, destroyed 40.


now here is the fun part. comparing them. lets say 1/2 players get hurt in a min ( that is pretty bad). in the before code the total count for 100FPS would be (100 times 60)times((80/2)+(240/2)) giving a total count of 96,000! in my code that would be 20 timers created would give you 40, 20 destroyed would give you another 40. and the code inside would give you 50 per frame. so the count for my method would be
100times60times50 + 40 + 40 giving us 30,080.

i know this is a rough count but seriously it shows how superior my code is. keep in mind that if 0 people are hurt the count for my code is 0 and the before code is 48,000. in order for my code to be inferior this rough count would have to be off by over 3 times. on top of that for the 90% of the time when a player is at full health my code is always superior.

**Comment by Zet0rz** [comment]
Multiple timers constantly created/destroyed is messy, and timers use think internally anyway. I'm not entirely sure if this really _is_ slightly more efficient, but this is **micro optimizations**. You're maybe cutting 1ms down to what, 0.5ms, which is no difference at all. Not worth the inconsistencies the timers will no doubt bring. Not implementing a timer solution.

> it also spaces out when it runs so players are not healed all at once.

I'm not sure if you understand the think hook properly, it already does this. Each player is independently checked if their own personal regen time has passed, and then begins to regen. Since it runs every frame you will not get "waves" of heals for all regenerating players.

> but their is no reason why we need to check over 100 times a second on this.

Sure, you can put it inside the retargeting function, that makes sense. Not sure if this is important though, don't think PointContents is that intense.

**Comment by jaxjaxk** [comment]
this is NOT a micro optimization. it is the 14th worst bottleneck on the server. in terms of how expensive it is, it is half as expensive as the zombie search function. and that is only run once a second. here is a before. this is with no one hurt IE the best case scenario for the function.

![zs_abandoned_mall_v6b0007](https://cloud.githubusercontent.com/assets/18671500/25066834/80d778be-21f7-11e7-84b3-460914f3a375.jpg)

now let's look at my method. well i would love to compare apples to apples by showing how expensive it is when no one is hurt however.... the timers do not exist so it cost nothing.

so lets see what it is like when i am hurt. in this example i am being kind to your cause by running the profiler only while i am hurt. i even got hurt consecutively so that that more code would have to be executed

![gm_construct0023](https://cloud.githubusercontent.com/assets/18671500/25066887/c4ec646e-21f8-11e7-842a-ee968dd19f80.jpg)

now the time to execute did go from .02 to .09. so yes, my function is more expensive HOWEVER it runs far fewer times than the old function. that was the point. so lets compare where they would cross. well in order for your function to be superior when players take damage ( because when they do not take damage mine never runs so my method always wins there) players would have to take damage around 20 times a second. so roughly  every player has to be attacked constantly with 20 players on the server. so basically unless players are taking damage literally every second my method is superior in every way. 

we went from 14 to 25 and that is comparing the best case for the old code and worst case for my code.
>  You're maybe cutting 1ms down to what, 0.5ms, which is no difference at all. 

it's EXACTLY that reason that the gamemode has lag issues. be a responsible programmer and do the right thing. i did the easy part by giving you the code that would reduce pressure on the processor. all you have to do is copy past now.

>  Not worth the inconsistencies the timers will no doubt bring. Not implementing a timer solution.

inconsistencies? do..... do you not know how timers work? they are checked 100 times a second. hell, the old code is basically another approach to timers. i mean hell explain this.
`(!v.lastregen or CurTime() > v.lastregen + HealthRegen.Rate)`

you look me in the eyes and tell me that is not a timer that runs every HealthRegen.Rate

> I'm not sure if you understand the think hook properly, it already does this. Each player is independently checked if their own personal regen time has passed, and then begins to regen. Since it runs every frame you will not get "waves" of heals for all regenerating players.

if you read over my code you would see that my method also does not work in waves. the max number of timers that can exist is equal to the number of players on the server. they are all independent and not working on the same timer.

> Sure, you can put it inside the retargeting function, that makes sense. Not sure if this is important though, don't think PointContents is that intense.

reducing anything from 100 times a second to 1 times a second is always an improvement no matter how small. careless coding causes issues that we are seeing in lag and small mistakes spread out make a big problem.

As i have said before the think function should be considered a taboo. before you EVER touch it always think "do i seriously need something that runs 100+ times a second or could i just create a timer that runs every 5-10 seconds" 99/100 times you do not need the think function. it makes me cry sometimes to see so much code in think functions that does not belong.

**Comment by Zet0rz** [comment]
You're telling me <0.1ms average methods is _not_ micro-optimizations?

Looking at the profiler screenshots, yours is literally more than twice as slow (8ms -> 18ms) in total time, and over 4 times slower on average (0.02 -> 0.09). Sure yours runs less times, but it's still slower in total (which takes the amount of times it is ran into account).

> would have to take damage around 20 times a second

Clearly your profiling shows yours is _twice as slow_ with just taking damage the amount of times that you did during your tests (I'm guessing way less than 20/sec)

> we went from 14 to 25

Uhm no? You can literally see the scroll bar on the side, you're _way_ further down than 14 on the first screenshot, it's like 30+. In the second screenshot you can also see the _real_ bottlenecks causing lag at **700+ ms**. This _is_ micro-optimizations (that in itself is not a problem though). 

> my method also does not work in waves

I never said yours doesn't, but you said/implied mine didn't. 

Finally, to clear misunderstandings, with inconsistencies, I mean those inexplainable bugs where some peoples' code just doesn't run. Using timers in a fire-and-forget way will surely bring lots of people where health regen either doesn't start or doesn't end, simply because the timers didn't start/destroy properly. 

I appreciate you helping giving ideas to optimize the gamemode, but you should move on to the 10+ ms bottlenecks.

**Comment by jaxjaxk** [comment]
@Zet0rz it's twice as slow because you are looking at the total time. also the sampling time was done twice as long for my method so ya, total time should be about twice. on top of that pay attention, we are comparing your best to my worst.

**Comment by jaxjaxk** [comment]
> I appreciate you helping giving ideas to optimize the gamemode, but you should move on to the 10+ ms bottlenecks.

mate, if it takes .01 ms and is run 100 times a second that is worse than taking .1 ms and running 1 time a second.

**Comment by jaxjaxk** [comment]
> Finally, to clear misunderstandings, with inconsistencies, I mean those inexplainable bugs where some peoples' code just doesn't run. Using timers in a fire-and-forget way will surely bring lots of people where health regen either doesn't start or doesn't end, simply because the timers didn't start/destroy properly.

Ive used timers to replace a whole lot. never had that problem.

**Comment by minin43** [comment]
What's currently the biggest bottleneck and why don't we address that instead?

**Comment by jaxjaxk** [comment]
@minin43 zombies code. i addressed this several times however my methods were not acceptable even though they work fine. also just because it takes a lot of processing power does not mean it can be changed to be better. obviously what i did here does work better.

**Comment by jaxjaxk** [comment]
look, this is well explained and proven. either used it or not. you are free to test it yourself, i will admit the tests were a bit different ( maps, players, time run) however unless you truly believe the error is over 400% we are done with that. on top of that my code ONLY runs when players are damaged an no other time. so 99% of the time nothing is running so honestly you would have to believe in 4000% error.

**Comment by minin43** [comment]
Sure, you've looked at the profiler at seen that at moments it's better and at moments it's worse.

But have you tried *just* playing with your code implemented vs. not, and seeing what the tangible framerate difference is? I'm wanting to say it's probably not a very big difference; 2-3 FPS, max. 

While your suggestions aren't for me, you write you comments like a prick. How about laying off the passive-aggressiveness.

**Comment by jaxjaxk** [comment]
> I'm wanting to say it's probably not a very big difference; 2-3 FPS, max. While these suggestions aren't for me, you write you comments like a prick. How about laying off the passive-aggressiveness.

fix something like this 10 times and you get what? 20-30 FPS difference. kind of a big difference. everyone apparently seems to get offended when i point out bad coding that fixing would help solve the worst problem this game has.

> But have you tried just playing with your code implemented vs. not, and seeing what the tangible framerate difference is?

yes. and naturally its not a huge change however it is very clear that a change exists. apparently the math checks out. who would have thought that math could accurately predict the outcome of a computer that runs on, well, math.

**Comment by minin43** [comment]
>fix something like this 10 times and you get what? 20-30 FPS difference. kind of a big difference.

Oh I'm sorry, can you name 9 other functions like this that need the micro-optimizations which will have a 2-3 FPS increase? This suggestion is *unneeded,* resources ought to be put towards other fixes and we have no idea what sort of effect this change might bring.

Leave it be and keep the issue closed.

**Comment by jaxjaxk** [comment]
so let us compare again with another quick test. here is before with focus on the function
![gm_construct0025](https://cloud.githubusercontent.com/assets/18671500/25069003/ce197d60-2239-11e7-80ba-04c5a00f4486.jpg)

and now after

![gm_construct0024](https://cloud.githubusercontent.com/assets/18671500/25069006/d339389e-2239-11e7-825c-79fe0ded5571.jpg)

now i know the time the test was run is different in terms of how long it was run so I'll do the math for you.

before is 4.655565 ms ever min.
after is .0044531835 ms every min.

so..... any doubt yet? i mean it now takes 1000 times less time on average. it's better than i thought.

**Comment by jaxjaxk** [comment]
@minin43 are you paying attention to the data? fixing one of these which took 5 min each was equal to revamping the worst bottleneck so it used no resources.

as i pointed out these micro-optimizations are needed because of bad coders. i mean seriously. it took me 5 min to revamp a small function that was one of the worst bottlenecks to nothing.

> Oh I'm sorry, can you name 9 other functions like this that need the micro-optimizations which will have a 2-3 FPS increase?

yes, yes i can. look at the list. and i guess i will not be bringing more here if it takes hours to explain a simple concept that was proven 3 times already in both theory and reality. if you honestly cast this much doubt on something so simple then you need help. i will not bring more if this is how you treat it. honestly, when you have to spend literally 20 times more time explaining than coding and testing something is wrong.

**Comment by Zet0rz** [comment]
> it's twice as slow because you're looking at the total time

Yes you are right, that completely went through my head. Anyway given that everything else on the list also ran for that much longer, they should scale up with it. And since yours jumped up the list, it suggests it's still slower. An accurate test would be the same situation the same time, both taking and not taking damage for both versions. 

Despite that, a timer solution is messy and with the aforementioned inconsistencies, I'm not making that jump for what is not really "one of the largest bottlenecks", no. Let's focus on the others on the list, starting from the top down yeah?

**Comment by jaxjaxk** [comment]
@Zet0rz your call. nice thing about my method is if the timer generates an error and fails somehow it is recreated the next time the player takes damage. so if you fear errors it kind of fixes itself. i have yet to generate an error and the server has been running for a week with it. also check out the last comment by me with the immages. i compared 1 to 1 with the same map and damage. although i slightly off on time but i spelled that out.
