### ISSUE TITLE
What textures pack is needed for this gamemode?

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#422]

**Comment by Zet0rz** [comment]
- http://steamcommunity.com/sharedfiles/filedetails/?id=675138912
- http://steamcommunity.com/workshop/filedetails/?id=777195612

**Comment by DjNathann** [comment]
Not that content pack i ment the texture content pack.

**Comment by minin43** [comment]
Those 2 links are the only resources used by the gamemode.

**Comment by lolleko** [comment]
CSS is probably also required by most addons included in the content pack.

**Comment by DjNathann** [comment]
Well you need CSS L4D2 And something else cause the workbench is error textured.

**Comment by Zet0rz** [comment]
The table is from CSS, I added the model directly from there into the nZombies content pack but I didn't think about the texture, you are right. Will probably fix when I eventually change the model completely if I do, otherwise next time I update content.

**Comment by Zet0rz** [comment]
The texture is added in today's Content Pack 2 update

**Comment by DjNathann** [comment]
Im talking about CSS Content L4D2 Content HL2 Content that stuff not the game textures. cause some of them are error to me.
