### ISSUE TITLE
Config Freezes

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#427]
After loading the config the configs just freezes and spits this error.

![screenshot_12](https://cloud.githubusercontent.com/assets/24857329/25292212/7aec3b00-26d5-11e7-891c-22c323c3a6bf.png)

**Comment by jaxjaxk** [comment]
it would seem this has to do with the map and or the config you set up. my bet is the config.

i am guessing you marked something as a door that is a button that you mistakenly marked as a door. simple fix, delete the door info from the config and redo the doors.

**Comment by DjNathann** [comment]
Yea just found out why it freezes.
