### ISSUE TITLE
Power Switch Activation Noise

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#43]
Please add in a sound to the power switch that plays upon activation. I couldn't find a great noise, but these one suffices. https://www.dropbox.com/s/opbqz0liurr4q44/electricity.wav?dl=0

**Comment by Zet0rz** [comment]
I have a lot of sounds, I can get ahold of them when I'm home :)

**Comment by Zet0rz** [comment]
Not yet coded in, but added in commit 87836001b1625746376e403a8cdf4c7e6c6daa70

**Comment by Zet0rz** [comment]
Coded in in commit 158e9c7e62acb44a6daccc0dfa42459f54624504
