### ISSUE TITLE
New power idea

### ISSUE THREAD

**Issue by conbubz** [Zet0rz/nzombies#431]
Could it be possible to add other power type entities like the generators from origins or the motd/shadow of evil power boxes (afterlife/beast mode included)?

**Comment by Kagutrenchi** [comment]
I had an idea like this for a month now, I think in basic options you should select power type, (generators, power box, switch, local switch) and powered things get a link if the type is anything but switch. Don't know how this works and I can't make it work. Not with the dev team, nor do I have experience with most languages.

**Comment by Zet0rz** [comment]
Power will remain global for the basic Creative Mode. If it will ever become a thing, it will be through a very complicated logic system where buttons and various activators can send inputs to other entities. However don't expect such a system, for now this is something that should be scripted in a map script (it's also specially scripted in CoD). Lua isn't hard to learn, setting up your own power logic will be fairly simple.
