### ISSUE TITLE
Any way I can use an STool in NZombies?

### ISSUE THREAD

**Issue by Coract** [Zet0rz/nzombies#433]
I just wanted to use the teleporter STool to add some "spice" to my map. *not sure how to mark as question

**Comment by minin43** [comment]
Provide a link to the addon? It can probably be done with a custom script for the map

**Comment by Coract** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=212709244

**Comment by minin43** [comment]
Can you do any scripting?

**Comment by Coract** [comment]
No, not very good at that stuff. Looks quite easy to learn though...

**Comment by Zet0rz** [comment]
I did want to look into a way to make gmod stools work with the toolgun, but, and it's a big but, I wouldn't save properly. Perhaps if the entities spawned by it are marked as special entities (saved and loaded like the duplicator tool) it would be possible. Don't expect this to become a thing though, if it is it will probably be way back after the rest of the gamemode is done.
