### ISSUE TITLE
No reload animations on CW 2.0 weapons bought off wall only on *my multiplayer server. sorry for being misleading

### ISSUE THREAD

**Issue by Coract** [Zet0rz/nzombies#435]
None of the CW 2.0 weapons in multiplayer have reload animations **unless it is the starting weapon.**

**Comment by Coract** [comment]
Reloads work in multiplayer sandbox too

**Comment by DjNathann** [comment]
Sandbox is different than nZombies..

**Comment by Coract** [comment]
Just pointing it out to show it is nzombies that was the problem.

**Comment by Coract** [comment]
Someone please, i'm literally dying...

**Comment by Zet0rz** [comment]
Does it matter whether you have speed cola? I can't really help you since the animations work fine on my end. The gamemode shouldn't modify anything about the weapon if you don't PaP it or get a perk that modifies weapons (speed and dtap), so if it's still broken there then I can only say conflicting addons :/

**Comment by Coract** [comment]
There isn't animations if I have speed cola or not the weapon just freezes in place and the mag refills.
Also the only addons I have are the official nzombies addons and CW 2.0. No errors in console either.
(also tried fresh install)

**Comment by Coract** [comment]
After fresh install when I click map settings I get this in console, 

> [ERROR] addons/nzombies/gamemodes/nzombies/gamemode/tools/sh_tools_settings.lua:61: attempt to index field 'BaseStartingWeapons' (a nil value)
  1. interface - addons/nzombies/gamemodes/nzombies/gamemode/tools/sh_tools_settings.lua:61
   2. RebuildToolInterface - addons/nzombies/gamemodes/nzombies/gamemode/q_menu/cl_menu.lua:598
    3. DoClick - addons/nzombies/gamemodes/nzombies/gamemode/q_menu/cl_menu.lua:666
     4. unknown - lua/vgui/dlabel.lua:232

**Comment by Coract** [comment]
Only thing I got left is to factory reset my pc and I already did that recently when I got a new motherboard and cpu.

**Comment by Coract** [comment]
I wasn't using dev branch, i switched and it is now working...

**Comment by Zet0rz** [comment]
If you are talking about the dev branch on nZombies in this github, that version is much older than master-workshop.

**Comment by Coract** [comment]
Well it works so I'll just use it for now

**Comment by Coract** [comment]
Reopened because I'm having other problems with the dev branch version and want to use Master-Workshop but still have the reload problem.

**Comment by Coract** [comment]
If it works with the old version but not the new one and it doesn't happen to others, what is the problem?

**Comment by Coract** [comment]
@lolleko *works in dev branch version but not master workshop

**Comment by jaxjaxk** [comment]
i use it on my server and it works fine. must be the most recent one that came out like a month ago
