### ISSUE TITLE
Rare crash.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#436]
![screenshot_2](https://cloud.githubusercontent.com/assets/24857329/25781122/56aef1da-3335-11e7-884d-ef9a413ca071.png)

**Comment by Zet0rz** [comment]
lolwot?

**Comment by DjNathann** [comment]
Everyone on the server got there game crashed and got this error.

**Comment by minin43** [comment]
This may be something to post on FacePunch for the game developer to see. Or maybe not, what do I know.

**Comment by DjNathann** [comment]
Who knows.
