### ISSUE TITLE
Vox Error.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#437]
[ERROR] addons/nzombies-master-workshop/lua/tfa_vox/modules/tfa_vox_nzombies.lua:102: attempt to call global 'TFAVOX_IsValid' (a nil value)
  1. b - addons/nzombies-master-workshop/lua/tfa_vox/modules/tfa_vox_nzombies.lua:102
   2. fn - RunString:8
    3. Call - lua/ulib/shared/hook.lua:109
     4. StateChange - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/round/cl_round.lua:18
      5. func - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/round/sh_sync.lua:77
       6. unknown - lua/includes/extensions/net.lua:32

**Comment by Zet0rz** [comment]
Sounds like an initialization error. That global function _does_ exist. Not a bug in the gamemode. Disable Vox if it keeps causing problems.

**Comment by DjNathann** [comment]
This disables the Round going to 6 12 18 24 etc. and Doesn't play the Special round theme and gives this error.

**Comment by DjNathann** [comment]
Talked with one of the TFA Vox creator he said its your bug.
