### ISSUE TITLE
Invisible Fence Bug

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#44]
https://youtu.be/D_S3c0dJkUs

Title/video description says all.

**Comment by Zet0rz** [comment]
With the latest update, the function door:IsLocked() will return false by default on entites that are not registered into the door system. This should prevent this error alltogether and will cause these entities to always render (like they should), but may not fix the underlying problem of them being reset to none on cleanup.

Are those fences registered as doors or just random props? And are actual door props also having this bug?

**Comment by minin43** [comment]
@Zet0rz They are NOT being considered doors, they are being considered a placed prop. All other placed props are invisible as well.

**Comment by Zet0rz** [comment]
Can you confirm this is still the case with the latest update? And is it only for that config (will saving a new config fix it?)

**Comment by Zet0rz** [comment]
No further reports, will assume fixed.

**Comment by minin43** [comment]
Not fixed. It happened again, but I didn't notice any errors in client console. I'll need to double check server console, but it happened again to me last night, @Zet0rz

**Comment by Zet0rz** [comment]
Still waiting to see what caused this. I don't get it any time on my installation, but that's probably because I'm on a listen server.

**Comment by minin43** [comment]
If I ever run into it again, I will let you know and update this thread.

**Comment by Zet0rz** [comment]
See commit 6173353a5efb2d3bf29cfcccb448d3261553f146
