### ISSUE TITLE
Monkey bomb is invisble from the box.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#440]
The monkey bomb doesn't appear from the box.

**Comment by DjNathann** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/24857329/25989262/ad393442-36fb-11e7-9b7f-72dc8230760e.png)

**Comment by jaxjaxk** [comment]
you are missing the texture.it is a client issue, rejoin the server.

**Comment by DjNathann** [comment]
i did that still invisble.

**Comment by Zet0rz** [comment]
Sometimes content just doesn't mount. Not much we can do about :/

**Comment by DjNathann** [comment]
It does appear when its scrolling thru the box but when choosed its not there.
