### ISSUE TITLE
Grenade icon replaces Monkey bomb icon.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#441]
The icon of the Grenades replaces the Monkey bomb icon.

**Comment by Zet0rz** [comment]
Screenshot?

**Comment by DjNathann** [comment]
I may have customize the grenades but it was like this when i didn't customized it.
![screenshot_3](https://cloud.githubusercontent.com/assets/24857329/25989223/9365b914-36fb-11e7-8ea1-39be2efc0e6a.png)

**Comment by Zet0rz** [comment]
Special grenade icons were always just red grenade icons.

**Comment by DjNathann** [comment]
But its not monkey bomb icon.?

**Comment by Zet0rz** [comment]
Not yet no. It will be when I get around to making a way to change up the icon; you can get more special grenades than just monkeys.
