### ISSUE TITLE
Gameplay footage of my nearly-finished maps.

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#45]
You may noticed lots of frame clipping and bad frame drop. Those are issues with the gamemode.

This map is mur_future_apt, or, Future Apartment. It uses CSS for some props and textures, although the map IS playable without CSS. Just not recommended. https://youtu.be/CrW1tgUJDhY

I'll upload some other gameplay footage here as well, to provide example gameplay for all of you to look at. You may notice I prefer to use CW2.0 weapons and not FA:S2 weapons, as CW2.0 is the currently supported pack and contains many more features.

**Comment by Zet0rz** [comment]
I see some frame drops, but I can't tell whether it's just the video footage or the gameplay. If you can, it'd help if you can specify when these frame drops happen. But the map looks good and the gameplay looks awesome :D

**Comment by minin43** [comment]
Whenever I look down the long hallway I experience notable frame drop. What's the thingy thing on gmod that shows your framerate?

Also: watch the very end of the video. This needs a fix and fast.

**Comment by Zet0rz** [comment]
Since I don't have any dedicated server setup and it seemingly only happens on that, could you help me out with debugging that crash? 

Take a clean config with only player and zombie spawn, play, die, see if it crashes. Then one by one with each entity, add that single entity and try again until we find out which one causes the crash. Then tell me which one that was. Try removing all by the crashing entity and try again. It might be a combination of entities.

**Comment by minin43** [comment]
The crashing happens on both single and multiplayer on these configs when you've purchased a new gun, either on the wall or through mystery box. I have tested it, the game DOES NOT crash if m-box/wall guns haven't been bought (as in: if everyone still has their starting pistol).

Isn't there some way to make the server print out it's errors into a notepad document to help with server crashing debugging?

Also, I will do some other testing with the guns on a fresh config.

**Comment by Zet0rz** [comment]
There should be a console command to start logging the console, but from my tests, this also gets cut off by a crash so I'm not sure you can use it.

**Comment by Zet0rz** [comment]
Closing this as I opened a dedicated issue about it.
