### ISSUE TITLE
Pack a Punch Error

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#453]
[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/display/cl_target.lua:62: attempt to call method 'HasNZModifier' (a nil value)
  1. unknown - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/display/cl_target.lua:62
   2. GetText - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/display/cl_target.lua:203
    3. Run - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/display/cl_target.lua:256
     4. unknown - gamemodes/base/gamemode/cl_init.lua:75

**Comment by Zet0rz** [comment]
I can see this error is clientsided, but for future reference, be sure to add whether the error is server- or clientsided.
