### ISSUE TITLE
Idea : Bonus Points Drop

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#457]
Zombies drop Bonus Points when the player picks it up and the players get 50-500points.

**Comment by Zet0rz** [comment]
https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/entities/entities/drop_bloodmoney/shared.lua

Just like in the game, these only drop on special occurences (using map scripts), and will not drop as a random drop.
