### ISSUE TITLE
"Release" Error

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#458]
[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/nz_panzer_claw.lua:133: attempt to call method 'Release' (a nil value)
  1. func - addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/nz_panzer_claw.lua:133
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by jaxjaxk** [comment]
release is the function to release the player if the claw caught a player. so if it is nil the player is either dead, disconnected or etc. does this happen every time with the panzer or just a few times?

**Comment by DjNathann** [comment]
Few times but he doesn't grab no one.
