### ISSUE TITLE
"Cant Load While playing"

### ISSUE THREAD

**Issue by MXBOY118** [Zet0rz/nzombies#459]
When trying to load a script, I get an error saying " You can't load while playing"

**Comment by DjNathann** [comment]
Are you on a server or singleplayer?

**Comment by MXBOY118** [comment]
Singleplayer

**Comment by Alig96** [comment]
Are you in create mode?

**Comment by Zet0rz** [comment]
You should be able to load from either waiting state or creative mode. You cannot load a new config mid-rounds or in game over state.

**Comment by MXBOY118** [comment]
I try to load when I first load the map

**Comment by Zet0rz** [comment]
Try to enter creative and load from there

**Comment by MXBOY118** [comment]
Ok I'll try

**Comment by MXBOY118** [comment]
Did not work

**Comment by Frenchytoast** [comment]
I know it's a bit late, but I found a fix for the issue. If you type nz_forceround into the console and wait, it'll let you go into creative.

**Comment by DjNathann** [comment]
Do you have ULX installed?

**Comment by MXBOY118** [comment]
I'll try that. If it doesn't work at least I bought Black Ops 3 for custom zombies.
