### ISSUE TITLE
Stuck with Morphine

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#467]
When you'r reviving someone and then one of the other teammates revive him instead you revived him you are stuck with a Morphine as a weapon.

The Only way to remove is to Die or Revive someone.

**Comment by jaxjaxk** [comment]
do what i do and modify the morphine swep with

``function SWEP:PrimaryAttack()
		timer.Simple(5, function()
		if !IsValid(self.WepOwner:GetActiveWeapon()) or !self.WepOwner:GetActiveWeapon():IsSpecial() then
			self.WepOwner:SetUsingSpecialWeapon(false)
		end
		self.WepOwner:SetActiveWeapon(nil)
		self.WepOwner:EquipPreviousWeapon()
	end)
end``

this will not fix the issue however if a player is stuck with the swep it will go back to their weapon after 5 seconds once they primary attack.

**Comment by DjNathann** [comment]
This doesn't fix anything this only make things worst and it eats the 2nd weapon
