### ISSUE TITLE
"IsSpecial" Error

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#468]
[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:359: attempt to call method 'IsSpecial' (a nil value)
  1. fn - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:359
   2. unknown - lua/ulib/shared/hook.lua:109

**Comment by minin43** [comment]
These error reports blow. You should provide more information. Just copying and pasting the error into an issue thread isn't super helpful.

**Comment by DjNathann** [comment]
should told me before.

**Comment by DjNathann** [comment]
Il close it until i find the bug.

**Comment by Zet0rz** [comment]
Post the following things along with your errors:
- Is it client or server sided?
- When does it happen?
- How frequently (always, sometimes, maybe a pattern)?
- Server or singleplayer? Try in the opposite and see if bug exists there too.

**Comment by DjNathann** [comment]
Server , sometimes , Idk , and Idk.
