### ISSUE TITLE
Idea : Replace Crowbar to knife?

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#477]
Crowbar is kinda ok but it knife can be useful cause the crowbar doesn't have the reach far stab but the knife can be more useful then the crowbar.

**Comment by Zet0rz** [comment]
Nope! Staying crowbar! (Also it's our own custom crowbar, we can change the range and damage on it as we please)

**Comment by DjNathann** [comment]
It can't hit zombies sometimes so can you fix it when you come back?

**Comment by minin43** [comment]
Can we mute someone to completely prevent them from making issues. Jesus.

>IT CAN'T HIT ZOMBIES FIX PLS.

Gee, what a wonderful bug report you have there, pal.

**Comment by DjNathann** [comment]
Calm down.

**Comment by minin43** [comment]
Oh look, I can edit my post to not sound like a dumbass too.

**Comment by DjNathann** [comment]
thanks

**Comment by DjNathann** [comment]
k

**Comment by DjNathann** [comment]
Its dumb to keep it unedited.

**Comment by DjNathann** [comment]
Melee only hurts zombies at the Head and stomach but not the arms or legs.
