### ISSUE TITLE
What ConVars/Console Commands do you want?

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#48]
So for the upcoming workshop release, which console commands do you want added? Currently we have these:
- nz_outlinedetail [0-4]
  Sets the amount of clone models that are created to generate the outline of a wall buy, lowering this may help reduce lag from stencils on lower end PCs. Max is 4, 0 disables the outline alltogether and uses the model itself instead.
- nz_bloodoverlay [0/1]
  Decides whether to use the blood overlay for health when damaged. Setting this to 0 disables it and re-enables the default HL2 health HUD.
- nz_forceround [Any number] [0/1]
  Forces the next round to begin. If the first argument is specified, the round will be set to this number. If the second argument is specified as 1, it will not kill the remaining zombies.
- nz_papattachments [0/1]
  Setting this to 1 will make all weapons integrated into the attachment system get randomized attachments on PaP. It will also strip the player of all their attachments on spawn. Setting this to 0 will make all players have all attachments at all times.

Discuss potential new console commands below here!

**Comment by minin43** [comment]
If you could make the on-map-join UI that lists off the ready button, workshop button, and the cog wheel/x-button more used, and add in an "options" button on it that sets these convars automatically, so you don't have to type it into console, that'd be awesome. 

I really like that UI whenever you first join a map, but it's currently kinda buggy and you only ever see it the once you join in. If it re-appeared on game end, that'd be great.

Including "general framerate improvement" options should be the first thing you work on. The general gmod playerbase has piss-poor computers, so make FPS-increasing options should be priority.

**Comment by lolleko** [comment]
Pretty much everything from the config file [(config)](https://github.com/Zet0rz/nzombies/blob/Master-Changes/gamemodes/nzombies3/gamemode/config/sh_constructor.lua), that does not have to be lua (all single values integers/bools/floats/strings) should be a cvar.

**Comment by minin43** [comment]
Can we get a list of commands for things like giving ourselves money, giving ourselves specific guns, turning on power, giving ourselves a specific perk, etc?

**Comment by Zet0rz** [comment]
@minin43 Should be fairly easy, I already do this all the time with lua_run code, so it's very simple. We can look into adding those, they're helpful for testing.
For now, you can do this in console:
`lua_run Entity(1):GivePoints(number)`
`lua_run Entity(1):GivePerk("perkid")` (list of IDs in the perk file)
`lua_run nz.Elec.Functions.Activate()`
`lua_run Entity(1):Give("weapon_class")`

**Comment by func-octo** [comment]
What we really need is a nz_removeRags or nz_removeRagdolls in case the ragdoll despawner fails. Also need to add zombie chances from the config in (command setup: nz_zombieChance "zombie name" {chance out of 100}). Example: nz_zombieChance nz_zombie_walker 100

Just in case one of those 'hardcore people' want to make all rounds extremely difficult with the special zombies. I realize you could just chanbge the config, but you'd have to reload the map to do that. I would just make it apply after the round that is current is over if one is going. If you decide not to implement this, could you make it check the config file after each round? Thanks!

**Comment by lolleko** [comment]
Cheats added in #69, those require some testing so it would be great if you check them out. We will also add some more cheats and functionality later. You can open the cheatpanel via the settings dropdown from the menu.

Thanks in advance & happy cheating :D

**Comment by minin43** [comment]
@lolleko How do you access the menu if you've already entered create mode?

**Comment by lolleko** [comment]
Still over the menu(f1) or via the "/cheats" chat command.

**Comment by Zet0rz** [comment]
Commit 9f86175c70f77f5ff6cc83ef85eb664749a826ec makes cheats able to be used in Creative mode, as well as adds a new cheat Target Priority, useful for making zombies not target you, or make them target an entity you're looking at. It also makes the Ready menu display "In Creative" for players in that.

**Comment by func-octo** [comment]
**Cheat Addon**: Add `All Perks` param to `Give {player} {PERK}`
**Cheat Addon**: Add `Random Gun` param to `Give {player} {GUN}`
**New Cheat**: `Give {player} (rand) <--(Not a visible parameter, just reference)` where rand = any perk or any gun or any amount of points using math.random() and possibly an if/else statement
**Cheat Addon**: Make {player} = to yourself by default instead of `Choose Player...`
**Cheat Addon**: Make `Number` in Points cheat remove after gaining focus and reappear after losing focus w/o any value.

**Comment by Zet0rz** [comment]
> Cheat Addon: Add All Perks param to Give {player} {PERK}

Permaperks are planned (basically you have all perks and they won't disappear when downed, to be used in easter eggs). A parameter to this cheat will likely be added for permaperks.

> Cheat Addon: Add Random Gun param to Give {player} {GUN}

Why would you want a random gun from a cheat? If you want it for fun'n'games, it'd be more fitting as a script rather than a cheat.

> New Cheat: Give {player} (rand) <--(Not a visible parameter, just reference) where rand = any perk or any gun or any amount of points using math.random() and possibly an if/else statement

A cheat that randomly gives a perk or a weapon or points or just anything? Refer to above.

> Cheat Addon: Make {player} = to yourself by default instead of Choose Player...

We can probably make the dropdown default to yourself fairly easily.

> Cheat Addon: Make Number in Points cheat remove after gaining focus and reappear after losing focus w/o any value.

That is rather pointless. I'm pretty sure default behaviour for all types of entries with a preset help text is to have it disappear when typing and not reappear later. That's for more fancy websites and such. We might make it just because why not, but it isn't because it's the most important feature.

**Comment by func-octo** [comment]
> That is rather pointless. I'm pretty sure default behaviour for all types of entries with a preset help text is to have it disappear when typing and not reappear later. That's for more fancy websites and such. We might make it just because why not, but it isn't because it's the most important feature.

The thing is is that if you are in a hurry to type the number you have to manually delete the `Number` from the box which takes enough time (When I say in a hurry, I mean from zombies).
