### ISSUE TITLE
Who's Who respawn function improvement

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#49]
Currently, it just picks a random navmesh within a certain range of your dead clone, but these can be both outside the playing area, as well as get you stuck in places. The way this works should be changed.

I'm thinking using the special spawn positions that we will later add for the Hellhounds.

**Comment by minin43** [comment]
Just have them respawn at a regular spawn position. Otherwise there's always a slight chance you'll spawn in an area you can't get to your body from. In the case your body is extremely far away from where you spawn, just increase the death timer of the body.

**Comment by Zet0rz** [comment]
I just added Special Spawnpoints along with its tool. This one is needed for Hellhounds anyway, but we can use the same ones with Who's Who respawning. It also has links like normal spawnpoints, meaning you won't respawn behind a closed door.
