### ISSUE TITLE
Everything is invisible even zombies

### ISSUE THREAD

**Issue by Innerdesert4346** [Zet0rz/nzombies#491]
When something is placed down in my server it is invisible perk machines, wall buys, and zombies when they spawn. I don't know how to fix this since i looked at one suggestion which was all i could find and it did nothing.

**Comment by DjNathann** [comment]
Do you have the content packs for nZombies??

**Comment by Innerdesert4346** [comment]
yes

**Comment by Innerdesert4346** [comment]
i just realized i was just playing zombies with you lol
