### ISSUE TITLE
Null entity OLD on line 56 of sh_weps.lua

### ISSUE THREAD

**Issue by Lewin225** [Zet0rz/nzombies#496]
[ERROR] addons/nzombies/gamemodes/nzombies/gamemode/weapons/sh_weps.lua:56: Tried to use a NULL entity!
  1. old - [C]:-1
   2. GetPrintName - addons/nzombies/gamemodes/nzombies/gamemode/weapons/sh_weps.lua:56
    3. fn - addons/nzombies/gamemodes/nzombies/gamemode/display/cl_hud.lua:114
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

This now occurs after the last update
Breaks most text on doors, pap, perks.  weapon hud ect.. 

As it is now 
local old = wepMeta.GetPrintName
function wepMeta:GetPrintName()
	local name = old(wep)
	if !name or name == "" then name = wep:GetClass() end
	if wep:HasNZModifier("pap") then
		name = wep.NZPaPName or nz.Display_PaPNames[wep:GetClass()] or nz.Display_PaPNames[name] or "Upgraded "..name
	end
	return name
end

As it was before the update 

local old = wepMeta.GetPrintName
function wepMeta:GetPrintName()
	local name = old(self)
	if !name or name == "" then name = self:GetClass() end
	if self:HasNZModifier("pap") then
		name = self.NZPaPName or nz.Display_PaPNames[self:GetClass()] or nz.Display_PaPNames[name] or "Upgraded "..name
	end
	return name
end

Pasting the old code into the new sh_weps fixes this but that's probbaly a duck tape fix

**Comment by Zet0rz** [comment]
I think you're looking at it the other way around, the code is right now as you said it was before the update:
```lua
local old = wepMeta.GetPrintName
function wepMeta:GetPrintName()
	local name = old(self)
	if !name or name == "" then name = self:GetClass() end
	if self:HasNZModifier("pap") then
		name = self.NZPaPName or nz.Display_PaPNames[self:GetClass()] or nz.Display_PaPNames[name] or "Upgraded "..name
	end
	return name
end
```
The differences being the "new" (according to you) has **wep** instead of **self**, but the current version has **self** as seen above.

Edit:
It was fixed in an update 2nd of March 2017:
https://github.com/Zet0rz/nzombies/commit/467521e3a06300ae950ffa4701a80b5302bb0a4f
