### ISSUE TITLE
Idea : Blue circle effect for Death machine and Zombie blood?

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#497]
Will the Death machine and Zombie blood have the blue circle effect like (EDITED) -> -black ops 3?

**Comment by Roachisserie** [comment]
Black Ops 2 doesn't have the death machine?

**Comment by DjNathann** [comment]
I meant Black ops 3. And its only in the Mystery box of Mob of the Dead.

**Comment by Roachisserie** [comment]
But it's not a powerup.

**Comment by DjNathann** [comment]
Nope its not.
