### ISSUE TITLE
Improved Movement on Random Box Weapons and Zombie Ragdolls

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#50]
Currently these use a timer that sets the position every 0.1 seconds or so. Instead, they should do what the PaP flying weapon entity does; by setting no gravity and setting a constant speed.

**Comment by Zet0rz** [comment]
Partially done, random box now has this improvement

**Comment by minin43** [comment]
If it helps with framerate, mystery box likes to cause frame stuttering, then freakin' sweet.

**Comment by Zet0rz** [comment]
The frame rate of the mysterbox is likely because of its model cycling; if it comes across a non-precached model, it might lag while precaching the model. This would only happen once per model, and only if it isn't precached. 

Should we make all guns precached at the beginning? This might cause a long lag when joining the game (it's the same lag, just at a different time).

**Comment by minin43** [comment]
Precaching it on spawn might work the best. But then I also noticed the it cycles through EVERY gun model on the server. Could you limit it to cycle only through the guns enabled for the mystery box?

**Comment by Zet0rz** [comment]
Yeah I was thinking that too. Will look into that.

**Comment by minin43** [comment]
It might limit it so that the lag isn't as nearly as bad, using only mystery-box-only models

**Comment by func-octo** [comment]
In the reaction to this reply, do thumbs up for precaching all _Random Box_ gun models and thumbs down for don't precache all gun models. More reactions gives a better perspective of what the people want!
And if your hyped for the workshop release do the party thing!
VVV

**Comment by minin43** [comment]
Why should we precache _every_ gun model? It should only be the gun models we use, not every gun available. Many servers, including my own, have other weapon packs on it for different gamemodes. If you use every gun model, regular players (who don't have the other gamemode stuff downloaded) will see errors, I run into this issue already.

**Comment by func-octo** [comment]
True. I have updated my comment to support this.

**Comment by Zet0rz** [comment]
When done, it will only precache models from guns in the random box list, as well as each model from the wallbuys.

**Comment by minin43** [comment]
@Zet0rz Fantastic

**Comment by func-octo** [comment]
> @Zet0rz Fantastic

Yes
