### ISSUE TITLE
Tombstone and Who's Who Bug

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#500]
[Tombstone] After Picking up my tombstone i can not use my Grenades nor my Melee and You don't get the Monkeys back from it.
[Who's Who] After Reviving myself or other people me and the players can not use Grenades nor can Melee.

**Comment by sh4d0w59** [comment]
What I've done to fix that is just switch weapons.  Though it would be nice to not have to switch weapons.
