### ISSUE TITLE
No Man's Land tool

### ISSUE THREAD

**Issue by Kagutrenchi** [Zet0rz/nzombies#508]
So, in Moon, you had Area 51/Groom Lake/Paradise Ranch/ No Man's Land. Infinite zombies spawned in this one area, increasing in numbers and strength as time, not rounds, went on. I was thinking of how creative you could get with such a tool in nZombies. Maybe a PaP room where a map config forces all people into the area, like in Moon. Or the entire map is No Man's Land, making a usually dull map a place where only the best survive. Maybe someone makes a script where the EE forces you into a No Man's Land to find something important.

**Comment by minin43** [comment]
So you want a script for a map to be implemented with this? Or a tool that creates such a function for you? I'm confused, you seem to change your mind on what you want halfway through writing this paragraph...

**Comment by Kagutrenchi** [comment]
I'm sorry if it came out as confusing, I'm talking about a tool an area tool, like the invisible or damage walls. I was just talking about map scripts as an example.

**Comment by minin43** [comment]
I don't think such a thing would be feasible. Specifically among uneven ground, any code would have a hard time knowing where a possible spawn spot would be without being very resource intensive (doing a lot of calculations), and they last thing we need is an ADDITIONAL resource-heavy tool/entity spawned in the maps.

Alternatively, it could be possible to manually alter the zombie spawn entities themselves. Some other unspoken issues revolve around the kill counter for rounds, and whether or not that would would/could be circumvented by created a second kind of zombie entity where kill count is kept track related to the round. At this point I'm talking out of my ass, we'll have to wait and see what Zet0r says.

**Comment by Kagutrenchi** [comment]
I can see the problem with my idea. Although, the area could be flagged, with similarly flagged zombie spawns, unless you thought of that and decided it would be resource-heavy. I can see another problem, as well: careless spots with multiple people. What would happen if half were outside and half were inside? I can't know. But hey, it's just an idea... An idea with a lot of holes...

**Comment by lolleko** [comment]
it's actually not very resource intensive to find valid spawnpoints via the navmesh. So i dont think that should be a concern in this disscussion.

**Comment by minin43** [comment]
Yea you can use the navmesh, but how dense will the zombie spawns be? What if nav-meshes are too close to a wall and any zombies spawning on the edge of the mesh will spawn *inside* the wall? What if the zombies spawn inside one another? What if the area isn't a perfect square? Am I going to need 2, maybe 3 or even 4 of these areas?

I don't think it's worth the time and the effort for Zet to try and make anything like this. But if you want to, be my guest. Personally, editing a regular zombie spawn to use different thinking seems like a much smarter option.

**Comment by Roachisserie** [comment]
I think that something like this can only be map-wide, and as a map config variable it completely removes rounds and adds time-based gameplay, like in WaW mods.

Alternatively, have it only accessible/usable via Hammer and brush tools.

**Comment by Zet0rz** [comment]
This is too specialized to become a tool unless I end up making a complete toolset for _all_ map script features (which has a very very low chance of happening), however I will make support for giving Spawnpoint entities custom Spawner objects. Actually I think you can already do that, that's how the normal round handling works (The gamemode automatically creates a Spawner and assigns it to all spawnpoints). I want these to have stuff like SetEnabled as well as custom curve/stat logic.
