### ISSUE TITLE
Weapons on TFA base

### ISSUE THREAD

**Issue by sasha12242** [Zet0rz/nzombies#509]
Hello i have a problem with weapons on tfa base. When i want to buy a weapon this thing shows up in console: [TFA Base] lua/weapons/tfa_gun_base/sh_utils.lua:231: attempt to call method 'GetOwner' (a nil value)
1. OwnerIsValid - lua/weapons/tfa_gun_base/sh_utils.lua:231
2. GetStat - lua/weapons/tfa_gun_base/sh_attachments.lua:150
3. GetPrimaryAmmoType - lua/weapons/tfa_gun_base/shared.lua:1473
4. unknown - gamemodes/nzombies/entities/entities/wall_buys/shared.lua:216
pls help

**Comment by minin43** [comment]
When *doesn't* TFA have a conflict with this gamemode.

**Comment by sasha12242** [comment]
and how i can fix it?

**Comment by globalcringe** [comment]
Have a TFA Base starting weapon, for some odd reason this also happens with CW and other popular bases

**Comment by sasha12242** [comment]
thank you!

**Comment by sasha12242** [comment]
you have been right

**Comment by sasha12242** [comment]
Solution: Pick a TFA starting weapon
