### ISSUE TITLE
Icon and Logo for Main Menu

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#51]
These need to be made. For the logo, I was thinking a bloody font saying "nZombies". The icon could fittingly be the same just with "nZ"

**Comment by minin43** [comment]
I have an artistic friend, I might be able to provide this for you. She's very skilled but doesn't really go logos, so only "might."

**Comment by Zet0rz** [comment]
I can also handle it myself when I'm home, but feel free to link some images here if you think we should use them (no promises though)

**Comment by minin43** [comment]
Will do

**Comment by minin43** [comment]
Update on this? Do you have the logo/icon down? My friend was thinking of attempting her hand but I don't want to tell her she's okay to, only for you to release ones you've made yourself.

**Comment by Zet0rz** [comment]
I still plan on making one myself, but it's probably the last thing I do before I upload to the workshop, so don't expect it very soon. Your friend can go ahead and try, but I can guarantee anything, especially since I have an image in my head of how it could look and she doesn't have that same image.

**Comment by minin43** [comment]
My friendo said she would have to wait until Summer time (I'm American, dunno how European country's school year work, but I get ~3 months off in the middle of Summer) to do it.

**Comment by Zet0rz** [comment]
That's probably too long, we'll have released the workshop version before then.

**Comment by minin43** [comment]
I understand, so do your own thing and don't expect anything from me

**Comment by func-octo** [comment]
Just a suggestion: take a look at the "Google Doodles" for ideas on how to sneak nzombies into a picture for the logo. I can get some neat screenshots and send them to you. Happy slaying!

**Comment by Zet0rz** [comment]
I think this is the logo we're going with:
![](http://i.imgur.com/juPNQgz.png)

**Comment by minin43** [comment]
I like it.

What about custom background pictures?

**Comment by Zet0rz** [comment]
We don't have any of them yet. It is a bit difficult posing since these aren't ragdolls but just NPCs xD

**Comment by minin43** [comment]
If you could disable HUD, you could probably get a few good screenshots of in-game play. Maybe a pic of drinking a cola, PaPing a weapon, shooting the zombie dogs, using the Bowie knife, etc.

**Comment by Zet0rz** [comment]
`cl_drawhud 0`. But that being said, backgrounds shouldn't be screenshots, they should be posed scenes.

**Comment by minin43** [comment]
Sure they can? They just need to be pictures. Yea  it isn't as "cinematic," but if the other option is NO background, I feel like gameplay pictures would suffice.

**Comment by func-octo** [comment]
I would add a little chunk to the right side of the S to make sure it doesn't look like it got cut off. Other than that awesome!

**Comment by Zet0rz** [comment]
The thumbnail for the workshop. If we change the S I'll update this one as well:
![](http://i.imgur.com/DRyG2K8.png)

**Comment by lolleko** [comment]
Still barely able to read the small text, might aswell remove the text i think people wil lget what this is about with out teh thumbnail text. Sounds like a cheap advertisement tbh :D

**Comment by func-octo** [comment]
What does the little text say? "Create and pay ni zies o ap"

**Comment by lolleko** [comment]
"CREATE AND PLAY NAZI ZOMBIES ON ANY MAP" I think ;D

**Comment by Zet0rz** [comment]
I need to redo that text tomorrow lol
Anyone got some ideas on what it could say? I want to promote the fact that it comes with a Creative mode, so people don't just think it's a small limited gamemode.

**Comment by minin43** [comment]
I feel a simple "A Nazi Zombies Recreation Gamemode" would work for now. It's hard to think of a catchy slogan

**Comment by Zet0rz** [comment]
It's not as much of a slogan, I just wanted to put focus on the whole create your own aspect that makes this gamemode so much better than a random other Nazi Zombies recreation. Without it, people would likely think it's just a recreation with a set few pre-made maps, or that they'd need to go through Hammer to get more maps. 

And holy schnitzel, that thumbnail is A LOT darker on my tablet than my desktop. I've gotta brighten that! I keep forgetting that my desktops monitor is so much more bright lol

**Comment by minin43** [comment]
It looks fine to me, why do you care if it's dark on your tablet? Gmod isn't on your tablet.

**Comment by func-octo** [comment]
Would this be classified as a De-make, or a Re-make?

**Comment by func-octo** [comment]
> "CREATE AND PLAY NAZI ZOMBIES ON ANY MAP" I think ;D

We must let the world know of this greatness!

**Comment by func-octo** [comment]
BTW I've got a background pack coming @Zet0rz ...
