### ISSUE TITLE
Zombie Blood glitch

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#512]
When you pick up the Zombie Blood when downed and when you get revived they still chase you while having zombie blood.

**Comment by jaxjaxk** [comment]
this has to do with how zombies ignore you when you are downed and when you are revived they no longer ignore you. i do not know why you picked up zombie blood when you were downed, seems kind of like a bad idea in the first place.

**Comment by DjNathann** [comment]
You can pick up Death Machine and Zombie blood while down they should like not be pickable unless you'r revived.
