### ISSUE TITLE
IDEA: Unused perk a colas

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#514]
In call of duty world at war and call of duty black ops, there are 4 unused perk a colas that never made it into the game.  These perks are as follows.  

- Amm-O-Matic:  This perk was taken out of Der Riese very late in development.  The only remaining files of the perk is in the form of an early texture.  It allowed you to get an instant max ammo for 10000 points but could only be used once.  An alternative could be regenerating ammo every couple of seconds.  Priced at 4500 - 5500 points.

- Candolier:  This perk is found in the PC files of black ops and would allow you to carry more ammo similar to the bandolier perk in multiplayer.  Priced at 3500 points.

- Tufbrew:  There is almost no other info other than the name for this perk so your guess as to what this perk does is as good as mine.  My guess is that it was an early version of juggernog.  My idea for it would be a temporary damage boost that last until the end of the round.  Priced between 2500 - 7500 points.

- Pronaid:  This perk would allow you to go prone faster...  Pretty useless.  Presumed to be the predecessor to PHD Flopper.  Ideas for this perk are HEAVILY welcome.

It would be nice to add these in either altered or kept the same when the gamemode itself is finished. 
 Feedback for these perks is welcome.

**Comment by sh4d0w59** [comment]
Btw, I have no idea how to put labels on these issues.  The enhancement label would be nice.

**Comment by DjNathann** [comment]
Zet0rz only created the perks that exist today not perks that they were scrapped.

**Comment by sh4d0w59** [comment]
Im just trying to bring some ideas to the table.  I don't expect him to add these in this early in development.  I just think that they would be a nice addition to the gamemode.

**Comment by DjNathann** [comment]
When he add Custom perks to the gamemode you can make them..

**Comment by Zet0rz** [comment]
These perk ideas were scrapped by Treyarch because they didn't work or play well, and I agree with the way the perks turned out in the end. I do not plan on adding any more perks than the official ones to the main gamemode. 

>When he add Custom perks to the gamemode you can make them..

Custom perks has been a thing since the perk module was first created; any external script can call the same functions as the original perks do, adding them to the perk drop down, save/load system and everything.
