### ISSUE TITLE
Idea : Equipments

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#515]
In the original cod you could buy Claymores,betties and trip mines on zombies but since the nZombies doesn't have that system there should be one.

**Comment by Zet0rz** [comment]
There is a system, it's the Special Weapons system. There aren't any actual weapons, but the special weapons system supports more slots (via strings, e.g. "grenade" "specialgrenade" and "shield") so we could easily add "equipment" if we actually get some weapons to fill those slots. That being said, I don't think that will happen.
