### ISSUE TITLE
IDEA: Setting default playermodels + pointshop integration.

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#518]
I don't know if this is the appropriate place to ask this but, would it be possible to add a setting within the map settings to select playermodels for all players within a map and if pointshop/pointshop 2 is installed, let the playermodels be overwritten if they have them equipped.  I'd like to restate that I don't know if this is the right place to ask this and if it isn't then I'll take this idea down.

**Comment by globalcringe** [comment]
This just sounds like a money sink for server owners.

**Comment by sh4d0w59** [comment]
@globalcringe   I think of that as a worst case scenario.  If you're even a halfway decent server owner you'll have a large amount of playermodels your clients can use for free and you'd set the defaults to something relatively nice (Rebels, combine, the original zombies crew, etc.).

**Comment by Punkinator7** [comment]
There is also the Idea that you can use whatever player models you want for free.  though it is pretty rare. I haven't seen more than 3 servers (Mine, FFGS, Eclipse Gaming Sandbox) do this tactic.
