### ISSUE TITLE
Quick revive + Who's Who.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#519]
[ERROR] addons/nzombies gamemode/gamemodes/nzombies/gamemode/revive_system/sh_revival.lua:52: attempt to perform arithmetic on field 'LastReviveTime' (a nil value)
  1. fn - addons/nzombies gamemode/gamemodes/nzombies/gamemode/revive_system/sh_revival.lua:52
   2. unknown - lua/ulib/shared/hook.lua:109

When you fed the zombies while having quick revive you get this error.

**Comment by Punkinator7** [comment]
wouldn't that be Quick Revive + Tombstone:?
