### ISSUE TITLE
IDEA:  Unstuck tool

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#521]
Players get stuck in walls quite often when they are downed in cramped hallways.  My idea is an integration into the current specials spawn tool that would teleport a stuck player to it within X seconds of getting stuck.  There should aslo be an "Unstuck Spawn" button to toggle whether or not the special spawn should be used as an unstuck spawn (Sometimes you have elevated dog spawns.  You dont want player spawning out of the map :P).

**Comment by Punkinator7** [comment]
This is a good Idea, but it depends on the map design and the map itself. like more open maps will use less of this, but this is a good idea overall.

**Comment by DjNathann** [comment]
Or he fix the downed body animation..

**Comment by Zet0rz** [comment]
I'd rather fix getting stuck than work on a tool to avoid it.
