### ISSUE TITLE
Idea: Interchangeable Perk Icons

### ISSUE THREAD

**Issue by Punkinator7** [Zet0rz/nzombies#524]
It would be really cool if there was a menu where you could change the perk Icons to fit the theme of the map, or if you really wanted to have a unique set of perk icons for your server.
And There could be like default perk icons like:
~The current Perk Icons
~WAW Themed
~BO 1 Themed
~BO 2 Themed
~BO 3 Themed - SoE and the Utlamus crews

**Comment by DjNathann** [comment]
You can just change them on you'r own if you know how to use you'r brain..

**Comment by Zet0rz** [comment]
I won't be including any more textures into the base gamemode myself, but any mod can just overwrite the hooks and draw their own icons instead.

**Comment by Punkinator7** [comment]
Thanks for letting me know.
