### ISSUE TITLE
Perk Limit  (Question)

### ISSUE THREAD

**Issue by OoziSuicide** [Zet0rz/nzombies#526]
Was wondering how to set the perk limit for players as the default for most maps is only 4. For most custom zombies maps created by individuals, I have seen the perk limit be increased but was curious as to how it was changed.

**Comment by DjNathann** [comment]
nz_perk_limit (number)

**Comment by Zet0rz** [comment]
It will never be possible to change the perk limit in your config, only on your server (or local game).
