### ISSUE TITLE
Can't buy TFA guns off wall

### ISSUE THREAD

**Issue by Punkinator7** [Zet0rz/nzombies#530]
I can't buy TFA wall weapons off the wall, here is an error.
[TFA Base] lua/weapons/tfa_gun_base/sh_utils.lua:231: attempt to call method 'GetOwner' (a nil value)
  1. OwnerIsValid - lua/weapons/tfa_gun_base/sh_utils.lua:231
   2. GetStat - lua/weapons/tfa_gun_base/sh_attachments.lua:150
    3. GetPrimaryAmmoType - lua/weapons/tfa_gun_base/shared.lua:1473
     4. unknown - addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua:216

Please fix and close.

**Comment by Punkinator7** [comment]
The weapon is from Ravens BO1 weapons.

**Comment by DjNathann** [comment]
That doesn't mean Zet0rz created the bug..

**Comment by Punkinator7** [comment]
It seems to happen with Fas2 weapons like the default starter the glock 20

**Comment by TheTrueGamerYT** [comment]
it dosent work when i play nZombies with my friend but works fine when i play it myself

**Comment by Punkinator7** [comment]
It's the opposite for me
it only happens when I play with myself.

**Comment by Punkinator7** [comment]
It seems to happen with CW2 as well.

**Comment by Zet0rz** [comment]
The gamemode is weird for half the people playing it ¯\_(ツ)_/¯

Anyway I am well aware of the TFA "GetOwner" error. A fix will come if it is fixable in the gamemode (which I think) when I come back to nZombies some time in early August.

**Comment by TheTrueGamerYT** [comment]
thanks man. If its fixable it should work fine for me and my friend as well. i didnt really check it but it was tfa base causing the problems so yeah. It should work if it is fixable. an addition it seems to also work when we sometimes buy the mystery box if that would help the fixing in any way

**Comment by Punkinator7** [comment]
another detail I found it only occurs before getting any TFA weapon, but disappears afterward, really weird.
I will close this because you say you fixed it.

**Comment by TheTrueGamerYT** [comment]
did u fix it?

**Comment by TheTrueGamerYT** [comment]
oh nevermind
