### ISSUE TITLE
Questions of mine!

### ISSUE THREAD

**Issue by SoMuchNope** [Zet0rz/nzombies#532]
So I have some questions as to the big plan with NZ... Let's get started.

1) So, is the teleporter ever going to be a thing? I know next to nothing about LUA, so I have no idea how hard that would be.

2) This is more of a suggestion than a question, but could you make a map option for what zombie model to use? (i.e. Nazi uniform, japanese uniform, hazmat suit, civilian clothes, hospital gown, etc.)

3) Are you going to add additional specials and bosses? (novas, jumping jacks, teleporting crawlers, brutus, moon man [the astronaut], avagadro, bo3 panzer, margwa, etc)

4) Will there eventually be a way to make a map ending easter egg and/or buyable ending?

5) Will we ever have a selection of PaP camos?

6) Original wonder weapons? I'd love to see what you can come up with!

7) Perk editor? (Think of the custom perks the community could make!)

8) Will everything be treyarch zombies only, or will we see AW and IW zombies content? (Goliath zombie would be pretty nifty.)

Thank you for taking my questions into consideration (and hopefully providing some answers). Have a nice day!

**Comment by Zet0rz** [comment]
1. Only in scripting. It'll take som lua knowledge, but it's mostly for just having a general idea of how to use it and how things work; the teleporter functions themselves wouldn't be too complicated.

2. That's coming!

3. I am personally not (maybe 1 custom boss, not from CoD), however the system is built to allow addons to add more.

4. There is! Through scripting though, it will never be available in Creative (unless someone else makes an addon that adds that tool, which they can).

5. Probably not.

6. Hard to come up with ideas, but I got a few that might see the light of day.

7. I can't imagine a good way to make an in-game perk editor lol. But like most other systems, addons can easily add additional perks (in fact, official perks are added the same way).

8. I'll let it be up to the community to add additional zombies, but it's totally possible if they have the models and animations for them.

**Comment by minin43** [comment]
I don't mean to toot my own horn here, so much, but all official maps, and some I'll release, will all have end-game EE objectives, and all official maps (last I knew) will actually have a semi-related "plot" of sorts to them. 

Aside from that, it's hard to find any maps that go the extra mile in terms of scripting and config "enhancing." Of course, you're more than welcome to contribute! Most of us will accept friend requests and will help out with problems you run into.

**Comment by DjNathann** [comment]
Is the Zombie models is gonna be a section in the tools / creative mode?

**Comment by minin43** [comment]
I would assume it would be in game settings, along with the other game options like starting weapon, EE song, and so on.

**Comment by ghost** [comment]
you know

I'd love to lend a hand in making official maps

scripting wise I can't do anything, but actually making the config and modifying the navmesh? Yeah, I can do that. Just get me a map that you guys want and I can work on it.

anyone I can talk to about this?

**Comment by minin43** [comment]
You'd want to talk to Zet about it, but he likes to make his own maps by himself, it seems. I tried to help with one of the official configs, and like, 2 edits I made were put into the map.

I only managed to get mine official because... in retrospect I'm not 100% sure. It has an long EE script though.

**Comment by ghost** [comment]
ye if I knew how to script well I'd probably have made a decent EE on one of my configs.

also what's your steam name? I'd like to talk.

**Comment by minin43** [comment]
It's just "Logan"

My profile picture is the pink gandalf one
