### ISSUE TITLE
Help...?

### ISSUE THREAD

**Issue by SoMuchNope** [Zet0rz/nzombies#534]
This may seem stupid, but could someone give an example of a PaP name script? I've been trying for the last couple of days, aaand... nothing. (New to LUA). I tried consulting the Wiki the whole time, and I just can't get it to work for the life of me.

**Comment by ghost** [comment]
SWEP.NZPaPName = "Meat Grinder"

put this in the shared.lua file of your gun.

replace meat grinder with your weapon name

**Comment by Zet0rz** [comment]
Or if you don't have access to the weapon file (e.g. you're using external addons, the weapons aren't yours), create any shared lua script (you could make an autorun script, just make sure the script is run) and in it call:
```Lua
AddPackAPunchName("class_name", "pap name")
```

**Comment by SoMuchNope** [comment]
Thank you so much my dudes! You are very helpful towards your community @Zet0rz  :-)

Also, I take it that I would put this within a function like the end of the round, the beginning of the round, or during the round?
