### ISSUE TITLE
Found incompatiabiltes with Hoff's Mystery Box Addon

### ISSUE THREAD

**Issue by Punkinator7** [Zet0rz/nzombies#539]
it makes the model a different direction or disappear completely.

**Comment by Punkinator7** [comment]
for, of course, the mystery box

**Comment by Punkinator7** [comment]
close when read

**Comment by DjNathann** [comment]
How about edit the comment instead going



BEEP






BOOP









BAAP

**Comment by Punkinator7** [comment]
I didn't know I was a robot. :D

**Comment by minin43** [comment]
I'm sorry, what's the problem now? I'm entirely confused.

**Comment by DjNathann** [comment]
He is saying that Hoff's Mystery box makes the box different directions or disappear.

**Comment by minin43** [comment]
What is Hoff's Mystery Box?

**Comment by DjNathann** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=256934412&searchtext=Mystery+box

**Comment by minin43** [comment]
Why are you trying to use that when the gamemode has it's own mystery box included...?

**Comment by DjNathann** [comment]
He probably uses it on sandbox..

**Comment by Zet0rz** [comment]
The thing is, the gamemode uses Hoff's model from back before I started working on it and it still does, which means the filenames are identical and the addon's will overwrite the gamemode's.

**Comment by minin43** [comment]
So the moral of the story: disable Hoff's addon before running nZombies..?
