### ISSUE TITLE
Faster Health Regeneration

### ISSUE THREAD

**Issue by ghost** [Zet0rz/nzombies#540]
I'm just going to be straight here:

The current health regeneration speed is too slow.

It takes nearly 10-15 seconds to regen from 1 to 250 HP, not counting the 2 second healing delay. At high rounds or in clutch moments, there's really no time for that.

I've modified it so that after 3 seconds of not taking damage, you regen 10 HP every 0.05 seconds, which is about how fast you regen HP when you're red-screened in zombies. (it's actually a 5 second delay though, but I feel 3 is better.)

The true health regen system from zombies is full health regen after 3 seconds unless critically injured, then it's a 5 sec delay with 10 HP every 0.05 seconds until you take damage or fully heal.

**Comment by lolleko** [comment]
Can you please open a PR to discuss code changes.

**Comment by DjNathann** [comment]
You can close this.

**Comment by lolleko** [comment]
Added in #602
