### ISSUE TITLE
"LastReviveTime" Error spam

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#541]
I don't know how it happened.
[ERROR] addons/nzombies gamemode/gamemodes/nzombies/gamemode/revive_system/sh_revival.lua:52: attempt to perform arithmetic on field 'LastReviveTime' (a nil value)
  1. v - addons/nzombies gamemode/gamemodes/nzombies/gamemode/revive_system/sh_revival.lua:52
   2. unknown - lua/includes/modules/hook.lua:84

**Comment by TheTrueGamerYT** [comment]
hmm. Maybe it might work if you re-install nZombies. Just thinking the most basic thing that i should've done

**Comment by DjNathann** [comment]
Yea no.

**Comment by Zet0rz** [comment]
This is a bug in the gamemode, have had it myself

**Comment by DjNathann** [comment]
Well i think if you press e on an object part of the map the error will be created and then You couldn't buy doors or guns.

**Comment by ChrisCj8** [comment]
Same thing happens to me and it's pretty annoying, I'd appreciate it if this was fixed as soon as possible, because it completely breaks all non-prop doors in solo.
