### ISSUE TITLE
Cant Buy Guns Off The Wall

### ISSUE THREAD

**Issue by TheTrueGamerYT** [Zet0rz/nzombies#543]
When me and my friend play nZombies i cant buy the wall weapons... but when i play by myself it works fine. Could you please fix this?

**Comment by DjNathann** [comment]
Any Errors in console?

**Comment by RickGrimesTM** [comment]
Replace the weapons in creative mode and it should work again. Don't know why this works but it does.

**Comment by TheTrueGamerYT** [comment]
thanks RickGrimesTM ill see if it works soon. if it works this will be closed

**Comment by TheTrueGamerYT** [comment]
DjNathann i didnt check the console. I should've huh

**Comment by TheTrueGamerYT** [comment]
RickGrimesTM sadly only the double barrel shotgun worked out of the 3 weapons

**Comment by TheTrueGamerYT** [comment]
DjNathann here is the error in console
[TFA Base] lua/weapons/tfa_gun_base/sh_utils.lua:231: attempt to call method 'GetOwner' (a nil value)
  1. OwnerIsValid - lua/weapons/tfa_gun_base/sh_utils.lua:231
   2. GetStat - lua/weapons/tfa_gun_base/sh_attachments.lua:150
    3. GetPrimaryAmmoType - lua/weapons/tfa_gun_base/shared.lua:1473
     4. unknown - addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua:216

**Comment by ghost** [comment]
oh yeah it's tfa's faulty base fucking everything up rip
wallbuy TFA weapons are broken if you try to buy them while holding a non TFA weapon, that means don't use 10 million weapon packs, only use one that you like for the gamemode

**Comment by TheTrueGamerYT** [comment]
yeah the solution rn is to not use TFA weapons. Wait for a fix

**Comment by DjNathann** [comment]
Idk what you guys are crying about TFA works fine

**Comment by func-octo** [comment]
The mysteries of code. Things break for nine tenths of the people then there's one guys who miraculously has no problems whatsoever. 10/10

**Comment by TheTrueGamerYT** [comment]
guys what i am doing is switching to m9k and CW so i dont have to make anymore issues about tfa. when a fix comes out then i will start using it again. Simple... I am just gonna close this now...
