### ISSUE TITLE
My mystery box is wrong

### ISSUE THREAD

**Issue by idksterlingopp** [Zet0rz/nzombies#545]
So after installing nZombies I made my own config and played it, When I spawned it I seen that the mystery 
box had parts of it going through the wall 
![screenshot_410](https://user-images.githubusercontent.com/30447852/28593741-044a25c4-7168-11e7-88b9-54222010fb3a.png)
If I am able to get a fix that would be amazing, wait, I forgot the other image
![screenshot_411](https://user-images.githubusercontent.com/30447852/28594857-08a657a6-716c-11e7-830c-dd5073a98327.png)

Please let me get a work around

**Comment by Zet0rz** [comment]
Do you have Hoffs mysterbox addon? If so, disable it while playing.

**Comment by idksterlingopp** [comment]
I indeed, Thank you for telling me about this fix! btw great gamemode
