### ISSUE TITLE
(IDEA) Connectable teleportation system

### ISSUE THREAD

**Issue by idksterlingopp** [Zet0rz/nzombies#546]
I enjoy nazi zombies original and the nZombies gamemode for garry's mod,
Something that bugged me was that there were no teleportation systems. (I really wanted to make a teleport to a pack-a-punch location) Making it for the gamemode would make me feel like im actually playing bo1 zombies or bo2 zombies which would be awesome, I am not dissing this gamemode in any way, I love making configs for this. But having a teleport system for PAP or any other place would be awesome.

**Comment by minin43** [comment]
I think I speak for the dev, Zet0r, when I say that something like this will probably never be officially supported in the gamemode (as in: there won't be a tool that creates such a thing). To expand on that statement, a teleportation system can already be created by the map creators themselves. Such a thing already exists in the config for ttt_kosovos (I think the config name is Escape or something of that nature). 

If you're talking about full-fledged Easter Eggs, with the soul collector or item creator, or any other thing you can think of, all *official* maps/configs will include an EE that "completes" the map, similar to many of the Nazi Zombies maps in BO2 and BO3.

**Comment by sh4d0w59** [comment]
I think that would be a great addition to the toolset we currently have.  The only issue I see with it other than taking time to code is zombies possibly getting stuck or taking up a massive amount resources to track you to the location you just teleported to.

**Comment by idksterlingopp** [comment]
I actually forgot to mention this, If any of you have made a super mario maker level, Your able to connect pipes to go to the area you want the next pipe to be, The way to tell them apart is by cards, That would be cool if we could link teleporters like that. That was the thing i was trying to explain.

**Comment by Zet0rz** [comment]
Teleporters will be a thing through mapscripts, but not a tool. It will have a negative impact on the diversity of configs (despite just adding more tools to use). If you have played BO3 custom zombies maps when people had just figured out how to add soul collectors and how to add Brutus, you would have noticed that pretty much _every single custom map_ always had Brutus and a full EE consisting of only various soul collectors, a door, a button, then more soul collecting.

That is something I want to avoid, so I will not be adding any "specialty" tools individually. I will only do that if I can do _all_ specialty tools into a full map logic system (which might be too much work to do).

Don't expect it.

**Comment by SoMuchNope** [comment]
I personally think that this is a great idea! I mean, why not? Wouldn't it be best to add all of the bo1/bo2/b03 features?

**Comment by idksterlingopp** [comment]
SoMuchNope I would like to disagree with one part of that statement, This developer can not add Everything from bo1-bo3, He is not a robot.

**Comment by minin43** [comment]
>I mean, why not?

We could stay here for the next 24 hours going over why expecting such a thing would be incredibly stupid, but instead, I'll just leave the remainder of the thread as evidence instead. Developer said no, so it's no.

**Comment by DjNathann** [comment]
"Dev says no"

"Others" LETS ADD THAT THING AND THAT AND THAT.

"Me" Blind wankers can't read.
