### ISSUE TITLE
1 weapon switching glitch

### ISSUE THREAD

**Issue by TheTrueGamerYT** [Zet0rz/nzombies#548]
This has been found on a couple of my nzombies maps. i have my starting pistol and another weapon... instead of swapping my pistol it swaps my other gun instead. I checked if i had gibmod install on gmod (how the issue was caused last time) it wasnt installed...

**Comment by DjNathann** [comment]
Well it was something else then and you would have found what mod does that instead creating the comment..

**Comment by TheTrueGamerYT** [comment]
ok then
