### ISSUE TITLE
Open Playtesting?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#55]
Anyone got any times of the day they'd be open for some playtesting? I live in central U.S., so I'm on CST time. I'm home by 3:20-ish (or 10:20-ish for you, Zet0rz).

**Comment by lmao5677** [comment]
I live in UK, so I do get alot of time. I don't really mind play testing because I work alot with making maps.

**Comment by minin43** [comment]
Feel free to add me on Steam (Steam name: Deathking15, IRL name: Logan) and I'll give you an invite whenever the server's up.

**Comment by lmao5677** [comment]
Alright, thanks.

**Comment by lmao5677** [comment]
Btw @minin43 

I have ttt_der_riese_b5 map if you would like to try it out. I can give you the config if you would like to take a test try.

Features:
Teleports that you can actually link! (They don't open the door to the pack a punch, it opens by spending it for 2500 points.)
Easter Egg (With the actual song!)
All the perks. (All of them, which includes black ops 1 and 2 perks)

[nz_ttt_der_riese_b5;AllPerksFinalRelease.txt](https://github.com/Zet0rz/nzombies/files/192454/nz_ttt_der_riese_b5.AllPerksFinalRelease.txt)

**Comment by minin43** [comment]
@lmao5677 Yea I'll give it a shot!

**Comment by Zet0rz** [comment]
I had plans on making an official config on ttt_der_riese with a map script that will make PaP actually open by using all three teleporters. Although I won't be making any official configs until release, so don't expect it for playtesting :P
I noticed though that the map is missing a whole lot of barricade windows. Does your config still work good despite this?

**Comment by lmao5677** [comment]
@Zet0rz 

I have no idea. Didn't the barricades already load? If they haven't then you can just replace them. Other than that, it works fine for me.

**Comment by Zet0rz** [comment]
Not barricades as in the plank fence walls, I meant as in actual map windows. There are several holes and even whole areas missing from the map itself where we could've placed zombie spawns, most of which would actually make a huge change in map balance.

**Comment by lmao5677** [comment]
@Zet0rz 
Oh, ok.

I know I've missed one area where the zombie is meant to spawn, I just replaced that with 2 perks, staminup and PHD. We might need to finish up those changes then.

**Comment by func-octo** [comment]
@lmao5677 

Map works great :)

**Comment by lmao5677** [comment]
@ScriptnLua

Thank you for your positive feedback :D

**Comment by func-octo** [comment]
On the other hand, none of the doors open : P
Must be time to install the updated version... xD

**Comment by lmao5677** [comment]
@ScriptnLua

Lol, thats weird.

**Comment by lolleko** [comment]
I wouldnt put to much work into the configs rightn now. As things **might** still be changing and configs could break, or become polluted by unused/changed stuff. Either way I would recommend to redo them completly once the workshop release is out. At least that's what I will/have todo with my configs.

**Comment by minin43** [comment]
That shouldn't be the case at all. What entities are you planning on removing/changing so drastically it requires re-placing? The only thing you'll need to worry about is new entities. For example, hell hound spawns, and that hopefully wouldn't require redoing the ENTIRE map.

**Comment by minin43** [comment]
Anyone open to some testing later today? 3:30 pm CST?

**Comment by lolleko** [comment]
Its probably not required, but configs get pretty messier with every change to them.

**Comment by func-octo** [comment]
Here's what I reccomend for configs is going here: https://developer.valvesoftware.com/wiki/Decompiling_Maps
then in hammer,  do top down view of the map and print it out/take a srceenshot. Then draw where everything is for nzombies on the map in some way so you can make it identical later when it needs to be redone.

**Comment by Zet0rz** [comment]
@ScriptnLua I'd rather just go in sandbox and fly straight up with a camera tool and take a screenshot than decompile
