### ISSUE TITLE
add teleport ?

### ISSUE THREAD

**Issue by bozoweed** [Zet0rz/nzombies#551]
hi every one some one have make the script for make teleport from one point to ohter with the good entitie model ? if yes can you leak it please ? or maybe just tell me how we can do and i will go try to make one

**Comment by minin43** [comment]
The map script for ttt_kosovos has teleport functionality inside of it (you are teleported outside of the PaP room in this script), go ahead and use the code in the script for reference to write your own.

**Comment by bozoweed** [comment]
oh yes it's very nice thanks my friend :)
