### ISSUE TITLE
Friendly Fire

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#554]
There seems to be an issue with any projectile based weapons.  Other than not being able to hit nextbots, the projectiles kill team mates.  This makes any explosive weapon non viable because of team mates running in front of you.  The specific packs I'm using are CS:O Nexus sweps and CS:O 2 sweps.  I've been told by the author on steam that it's an issue on the gamemode's side.

**Comment by sh4d0w59** [comment]
Could we change the collision group of all projectiles fired to one that doesnt collide with players?

**Comment by globalcringe** [comment]
[expfix.zip](https://github.com/Zet0rz/nzombies/files/1649397/expfix.zip)
Here, try this fix. Install to addons folder, the same way you installed nZombies.
This makes every explosive ignore player collisions.

**Comment by lolleko** [comment]
The Nextbot part is a god issue pretty sure at least it was one at the time.
The friendly fire part is a game mode issue.
