### ISSUE TITLE
Zombies Health per wave

### ISSUE THREAD

**Issue by JulesMerit** [Zet0rz/nzombies#556]
Hello, i am here to tell about minor problem in this gamemode - about health on zombies per wave. I think need to decrease the number of they health, like from 90 health to 60 (or just decrease to 2/3 from default), so this will be minor better for every who plays there.
Oh, and about his speed and damage - when zombies count reach 20-30 that cause minor lags, so then they can kill players easily, by this one i think need to decrease their damage or speed to 3/4 from default.

**Comment by ghost** [comment]
you can change the stats of the zombies by going into single player and clicking 2 player. There should be a more options button or something like that.

Also, you can limit the amount of zombies the same way. I have it set to 24, the default max from real Zombies. You can't change the speed without going into the game's code, however.
