### ISSUE TITLE
Stupid Zombies (solved! up to help people)

### ISSUE THREAD

**Issue by TheTrueGamerYT** [Zet0rz/nzombies#558]
When Inside a Building zombies do not follow the player if the player is outside. It's annoying as i have to reenter buildings and look around for zombies. Is there a way to get the zombies to chase you out of the buildings they spawn in?

**Comment by lolleko** [comment]
That is not a problem with the zombies. The zombies dont care if you are onside or outside.  

Your navmesh is probably broken. Check if the outside and inside are properly connected.

**Comment by TheTrueGamerYT** [comment]
i just click generate navmesh when the map is complete in the F1 menu

**Comment by TheTrueGamerYT** [comment]
well that helps my problem because i didnt mark them. thanks for the help. If it does work then i will close it. High Probability that its closed though

**Comment by TheTrueGamerYT** [comment]
there seems to be the issues with stairs i cant seem to connect the stairs fully. Is there any way i can fix that

**Comment by minin43** [comment]
You have to edit the navmesh to fix such problems. 

https://developer.valvesoftware.com/wiki/Navigation_Meshes

Above is a great resource that helped me first learn how to work with navmeshes.

**Comment by TheTrueGamerYT** [comment]
ok thanks ill have a look at it in my spare time

**Comment by TheTrueGamerYT** [comment]
thanks. It worked. The solution used for stairs didnt work. but the slope option worked for the stairs.. weird. I am gonna keep this up... Just incase someone is having this issue like me.

**Comment by TheTrueGamerYT** [comment]
how do i save the nav-mesh's afterwards? because i reopened the map and i have to redo it

**Comment by lolleko** [comment]
`nav_save` in console

**Comment by TheTrueGamerYT** [comment]
ok thanks
