### ISSUE TITLE
Invisible Perk Bottle

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#56]
So whenever I drink a perk a cola, the bottle is invisible. Any weird bug or was it just testing again? I restarted the server and saw it happen again.

**Comment by minin43** [comment]
It's an addon confliction. I don't know with what addon, but I experience the same issue on my main PC, and it was fixed on my laptop (which had pretty much no addons on it).

**Comment by lmao5677** [comment]
Ok, I'll see what addons to disable then.

**Comment by minin43** [comment]
Lemme know which one seemed to fix it so I can fix it myself.

**Comment by lmao5677** [comment]
Oh, I just disabled all the addons entireley, but kept the fas2 guns.
