### ISSUE TITLE
Suggestions if possible

### ISSUE THREAD

**Issue by TheTrueGamerYT** [Zet0rz/nzombies#560]
this is just some things that would make a more experement mind (me and others) to expand more on our maps. If you cant do it thats perfectly fine.

1. add audio clips for a story-line. Like in most zombies today in call of duty. The characters speak. Would that be possible to do on nZombies?

2. long easter eggs that lead to an ending cutscene. You can just put you win or something rather then a cutscene, an example of what kind of easter eggs i am talking about is Origins

3. a collectable to complete the game. If possible you could add collectables which players can place in creative mode. then in survival mode if all are collected then you would win in the map.

Lastly 4. a custom zombie creator. Maybe impossible but it would be nice to see if it is possible.

P.S. I have no coding knowledge so i am not forcing these ideas just merely suggestions if u want to put them in.

**Comment by minin43** [comment]
1. It's certainly possible and actually supported is various forms, but there's no official *dialogue.* While Zet0r does plan on having a somewhat-tangible story to the official maps, I don't know if/think there'll be dialogue along with it.

2. Already available. All official maps will have long and intricate Easter Eggs with an end-game. The only thing preventing new maps with such gameplay is map creator coding capability.

3. Is this not the same as question 2?

4. I don't think this will be added.

**Comment by TheTrueGamerYT** [comment]
ok thanks for letting me know about this. Apologies to question 3 being similar. and i sorta had a feeling 4 wasnt gonna be added. Thanks for the response man.
