### ISSUE TITLE
Players can't hear other players speaking.

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#563]
Players that joined a server and doesn't /ready will not hear other players talking thru the microphone.

**Comment by idksterlingopp** [comment]
I dont have this problem.

**Comment by ghost** [comment]
you do realize he could not have his sound on, right?

or doesn't understand english

**Comment by Zet0rz** [comment]
https://github.com/Zet0rz/nzombies/search?utf8=%E2%9C%93&q=PlayerCanHearPlayersVoice&type=

No hook for voice chat in this gamemode. It cannot be the cause of the gamemode.

**Comment by DjNathann** [comment]
okay.
