### ISSUE TITLE
tfa wall buys dont work

### ISSUE THREAD

**Issue by Wgairborne** [Zet0rz/nzombies#568]
[TFA Base] lua/weapons/tfa_gun_base/sh_utils.lua:231: attempt to call method 'GetOwner' (a nil value)
  1. OwnerIsValid - lua/weapons/tfa_gun_base/sh_utils.lua:231
   2. GetStat - lua/weapons/tfa_gun_base/sh_attachments.lua:150
    3. GetPrimaryAmmoType - lua/weapons/tfa_gun_base/shared.lua:1473
     4. unknown - addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua:216
(this error is not caused by addons)

**Comment by DjNathann** [comment]
Duplicate of #562 

Close it
