### ISSUE TITLE
PaP weapon names?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#57]
I remember reading somewhere that you can add in gun's PaP names outside of the cl_papnames file in the display folder, but I don't remember much else. Can I get clear, concise details about it, so there's no more guessing?

**Comment by lmao5677** [comment]
The code was `AddPackAPunchName(class, papname)`

The class was the name of the weapon. Example: fas2_glock20 then papname was the name that you would want it to change. (Of Course)

**Comment by minin43** [comment]
And does the file this code is in need to be in a specific folder? I remember mentions of the autorun folder.

**Comment by lmao5677** [comment]
I don't think so. Thats atleast all I could remember. I'm pretty sure you are able to just run the command and let it do its thing

**Comment by Zet0rz** [comment]
It can be any file (this is the case with any lua function). I only mentioned autorun because that is the go-to spot for scripts that auto-load in-game.
