### ISSUE TITLE
A way to put words on the screen without editing the map?

### ISSUE THREAD

**Issue by yourlocalfox** [Zet0rz/nzombies#572]
I want to make it so that when the players buy the final door, text appears on their screen. But I want to do it without editing the map itself. Is that possible with the game mode?

**Comment by minin43** [comment]
You'll have to create a script and enable it through the map editor. Do you know any Lua?

I don't know if you can AddCSLuaFile any client files, or if you have to send functions to the client as they need them, but function BroadcastLua and Player:SendLua may be of use.

**Comment by yourlocalfox** [comment]
I know no lua, but I do know there is a way to enable a map script which means it could happen, I just don't know how.

**Comment by minin43** [comment]
There are a lot of people who post "Issues" here that want code work done for them. Your request isn't any different so I'll repeat the reply I always give:

99% chance you won't find anyone here who wants to code your work for you for free. If this is something you want done, you'll have to figure it out yourself. There are plenty of resources available in this repository's [Wiki page](https://github.com/Zet0rz/nzombies/wiki), but no one will likely hand-feed you anything.

Additionally, utilizing Garry's Mod's own [Wiki](http://wiki.garrysmod.com/page/Main_Page) will provide you many classes, functions, and hook available to you from the get-go.

Unless of course you know absolutely no programming, in which case, good luck.

**Comment by yourlocalfox** [comment]
I didn’t know Garry’s mod had a wiki.., thanks for pointing me there. I know some programming so I’ll figure it out eventually. Thanks for letting me know that it can be done and giving me an idea.

**Comment by DjNathann** [comment]
Since when games do not have a wiki?
