### ISSUE TITLE
Modifying Clip Size and Ammo Pools (PaP and Normal)

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#576]
Is it possible to change the max ammo or clip size of specific weapons?  I'm asking because some weapons require multiple bullets to shoot and some weapons have VERY LOW ammo pools.  CS:O2 - Double Offence requires 2 shells to shoot when not PaP'd (not an issue).  When PaP'd it turns into the triple offence which takes 3 shells to shoot but has a clip size of 5 which leaves you with 2 shells you can't shoot.  This issue forces me to take them out of configs.  The low ammo pool issue is very apparent with double barrel shotguns (2/20 ammo pool) and single shot weapons (1/10 ammo pool).

**Comment by minin43** [comment]
Sure it's possible, but you're asking in the wrong place. That's not something that has to do with nZ.

**Comment by globalcringe** [comment]
Seems like a good place to start
You can't really edit the ammo variables as easily as, say, setting a gun to be a pap replacement.
I'd love to know how as well

**Comment by sh4d0w59** [comment]
@globalcringe Just out of curiosity, are you the same global that made the CS:O/CS:O2 sweps?

**Comment by DjNathann** [comment]
@sh4d0w59 yea he have created those weapons.

P.s he isn't gonna take requests.

**Comment by minin43** [comment]
http://wiki.garrysmod.com/page/weapons/GetStored

**Comment by sh4d0w59** [comment]
@DjNathann Nah, I'm not requesting anything.  I was just wondering if he was the same global.  Just a bit curiousity.

**Comment by sh4d0w59** [comment]
Found a fix for this issue after reading up on pap functions and max ammo functions.  Issue closed.
