### ISSUE TITLE
Morphine Fix

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#578]
#414  Fix *Hopefully*

 nzombies/gamemodes/nzombies/gamemode/special_weapons/sh_specialweapons.lua
1.
2. local function RegisterDefaultSpecialWeps()
3. nzSpecialWeapons:AddKnife( "nz_quickknife_crowbar", false, 0.65 )
4. nzSpecialWeapons:AddKnife( "nz_bowie_knife", true, 0.65, 2.5 )
5. nzSpecialWeapons:AddKnife( "nz_one_inch_punch", true, 0.75, 1.5 )
6.
7. nzSpecialWeapons:AddGrenade( "nz_grenade", 4, false, 0.85, false, 0.4 ) -- ALWAYS pass false instead of nil or it'll assume default value
8. nzSpecialWeapons:AddSpecialGrenade( "nz_monkey_bomb", 3, false, 3, false, 0.4 )
9.
10. nzSpecialWeapons:AddDisplay( "nz_revive_morphine", false, function(wep)
11.	 return !(IsValid(wep.Owner:GetPlayerReviving()) and wep.Owner:KeyDown(IN_USE))
12. end)
13.
14. nzSpecialWeapons:AddDisplay( "nz_perk_bottle", false, function(wep)
15.	return SERVER and CurTime() > wep.nzDeployTime + 3.1
16. end)
17.
18. nzSpecialWeapons:AddDisplay( "nz_packapunch_arms", false, function(wep)
19.	return SERVER and CurTime() > wep.nzDeployTime + 2.5
20. end)
21. end
22.
23. hook.Add("InitPostEntity", "nzRegisterSpecialWeps", RegisterDefaultSpecialWeps)
24. --hook.Add("OnReloaded", "nzRegisterSpecialWeps", RegisterDefaultSpecialWeps)

**Comment by DjNathann** [comment]
P.S I don't know how to pull request..

**Comment by lolleko** [comment]
How to make a pull request

[Github] Click the for button in the top right.
[Github->Local] Clone your fork.
[Local] Make your changes.
[Local->Github] Push your changes to your fork.
[Github] Click the Pullrequest Tab and make a new pull request, selecting zet0rz/master-workshop as base fork and your fork as head fork

https://help.github.com/articles/creating-a-pull-request/

**Comment by bozoweed** [comment]
morphine is allready fixed by me in laste comit #550

**Comment by DjNathann** [comment]
Its a good version.

**Comment by bozoweed** [comment]
why not but what your fix make for been better ?
