### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#579]
Edit: Forgot to add a description (It's 2 a.m. don't judge me).  On to my question.  Does Nzombies have an official discord where we can discuss the game mode and ask questions or is there alternative that already exists?

**Comment by Zet0rz** [comment]
I do have a discord server, but it is for my youtube channel community rather than my gmod stuff (but still a little bit of that too), and the server is also shared with a group of other youtubers/twitch streamers. No official nZombies dedicated server unless Alig had one way back before I started.

**Comment by minin43** [comment]
Discord wasn't quite a thing yet way back before you started working on the gamemode, so no, there is no official discord channel.

A steam group may be a better option in this case, though.

**Comment by sh4d0w59** [comment]
@Zet0rz Ok, I was just seeing what was available.  I might make a discord server dedicated to pointing people towards Nzombies and answering any questions they may have.  I'm gonna shut this thread down now.  Thank you for the info.

**Comment by cacohat** [comment]
Me and a couple of friends had an nZombies server before we got bored and
deleted it

**Comment by minin43** [comment]
If you could moderate posts on here like you can on actual forums...

>Me and a couple of friends had an nZombies server before we got bored and
deleted it

What's the point of posting this? Did you want a medal? A congratulation? You actually contribute *literally nothing* by responding with what you did. I don't really care how rude I come off sounding by saying that.

**Comment by Punkinator7** [comment]
What is the point of posting THIS?

> What's the point of posting this? Did you want a medal? A congratulations? You actually contribute _Literally nothing_ by responding with what you did. I don't really care how rude I sound by saying that.


 Did you want to contribute? a 100 pts? You also contribute **Literally nothing** by responding to it. 
Hypocrite.

**Comment by Alig96** [comment]
>What is the point of posting THIS?

>What's the point of posting this? Did you want a medal? A congratulations? You actually contribute Literally nothing by responding with what you did. I don't really care how rude I sound by saying that.

>Did you want to contribute? a 100 pts? You also contribute Literally nothing by responding to it.
Hypocrite.

What's the point of posting this? This also contributes nothing, something something something Double Hypocrite.

>I'm joking incase it wasn't obvious

**Comment by Alig96** [comment]
But seriously instead of getting annoyed at a response, maybe we should be looking at a way to turn it into a contribution;

> Me and a couple of friends had an nZombies server before we got bored and
deleted it

Why did you get bored of nZombies? What made you get bored?  Is there something that could be done that could help prevent you from getting bored?
