### ISSUE TITLE
GetMaxRunSpeed returns a nil value

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#58]
I experienced this bug being spammed into client console with the newest update.

**Comment by lolleko** [comment]
Client or serverside? Nvm found the issue.

**Comment by Zet0rz** [comment]
It might be different since I tested it in single player, but this value should always be set during gameplay? The value is set in the player classes as one spawns, but it may be because of a lack of networking. Was this client side errors?

**Comment by minin43** [comment]
@Zet0rz It was a clientside error running on a dedicated server.

**Comment by Zet0rz** [comment]
Did an experimental fix. It tries to get GetMaxRunSpeed if it exists, but if not, it goes to the player's current player class. But since this is in a move function which is predicted, I don't know if baseclass.Get and player_manager.GetPlayerClass are heavy functions to run multiple times. I may try further later.

**Comment by Zet0rz** [comment]
I can change it so that it stores the max speed in a local variable and then update it every time you spawn? Should make it only have to fetch the baseclass once at spawn. But I have no clue if this is more optimized, if the baseclass thing is nothing at all.

**Comment by Zet0rz** [comment]
After looking it up, it seems like it just gets a network ID of a player's class, gets the name via a table, then gets the class table from that. It's basically the same as this:
`baseclasses[stringtable[ply:GetClassID()]].RunSpeed`
(if the tables were called that)

**Comment by Zet0rz** [comment]
Before I close this, let me know if this fix works

**Comment by Zet0rz** [comment]
Seems to have been fixed (looking at the newest playtesting video).
