### ISSUE TITLE
Health Regen

### ISSUE THREAD

**Issue by ghost** [Zet0rz/nzombies#583]
Alright, so I wanted to make a PR to hopefully buff the rather slow HP regen, except I literally couldn't figure out how to make a PR for the life of me, even after looking at the tutorials.

but here's what I did in the code:

I changed the amount of HP you recover every 0.05 seconds to 10 instead of 1.
I changed the delay before you start regenerating HP to 3 seconds instead of 2.

These changes remove the 30~ second wait from going to very low HP to full HP with Juggernog, and make the game more enjoyable as a whole since you don't have to stay on critical health for 5-10 seconds.

**Comment by lolleko** [comment]
<img width="1047" alt="screen shot 2017-12-03 at 21 29 40" src="https://user-images.githubusercontent.com/4759511/33529440-3d14c8e4-d871-11e7-8351-28cdc5bea8fb.png">

You can literally press a button on this website to make a PR, If you don't understand how to do it locally with cloning, branching and pushing.

**Comment by ghost** [comment]
Sorry, I must have extreme retardism. Thanks.

**Comment by sh4d0w59** [comment]
You should prolly shut this issue down so we don't have any more congestion in the issues tab :P
