### ISSUE TITLE
Problem with weapon additions

### ISSUE THREAD

**Issue by arek751** [Zet0rz/nzombies#584]
Hello, recently I have a problem with adding the crosshairs to the CW2 weapon, could someone send me a configuration file how should it be done? I am completely green in these matters ...

**Comment by minin43** [comment]
I'm not certain what exactly it is you mean by "adding crosshairs" to the weapons, they come with the crosshairs on by default, you would have had to edit something to have them turned off.

**Comment by arek751** [comment]
I want to add optics to my weapon. Can be ?


[Picture .zip](https://github.com/Zet0rz/nzombies/files/1525027/Picture.zip)

**Comment by minin43** [comment]
You only get attachments on your weapon when you Pack-A-Punch them.

**Comment by arek751** [comment]
I do not understand very much, so nothing can be done?

**Comment by arek751** [comment]
If it works for you, could you send me your configuration file?

**Comment by minin43** [comment]
You don't get the weapon attachments (scopes, suppressors, grips, etc) by default. You have to upgrade your weapon using the Pack-A-Punch machine in the game, and only then will your weapon get the attachments on it. The video below showcases this.

https://youtu.be/CrW1tgUJDhY?t=11m29s

**Comment by arek751** [comment]
I did not even know about it. Thank you for your help: D

**Comment by arek751** [comment]
And yet it still does not work, My weapon is stronger, but still I can not put on a silencer or some crosshair :(

**Comment by arek751** [comment]
I will not be able to put them on even manually

**Comment by minin43** [comment]
There's a known bug with the game where the attachments sometimes will "ghost-attach." When this happens, the server recognizes the attachments have been attached to the weapons, but your client does not. You can remedy this by un-attaching and re-attaching the weapons (through the C menu).

**Comment by arek751** [comment]
Hmm, I will try

**Comment by arek751** [comment]
Works, great: D Thank you again for your help;)

**Comment by minin43** [comment]
When your issue has been resolved, please "close" the issue. And you're welcome.
