### ISSUE TITLE
New Gameplay Footage on Infected Facility

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#59]
It's a bit longer. It's a more open map so it makes it easier to survive.
https://youtu.be/EFsSPZMECxM

**Comment by Zet0rz** [comment]
Noticed a new crash, but this time it happened before you died, just when you got hit? Also we should keep this discussion in your older thread so we have it in a single issue.

**Comment by Zet0rz** [comment]
Closing this as I have created a dedicated issue to this crash.
