### ISSUE TITLE
Does not allow to start the "Survival" mode

### ISSUE THREAD

**Issue by Fucken19** [Zet0rz/nzombies#596]
I have read and done the installation correctly. When entering the game to verify that this mode, I continue with "Ready" but I get this message:
**Can not ready you up, because the map has not Navmesh loaded. Use the settings menu to generate a rough Navmesh or use tools in sandbox to make a proper one.**

Navmesh, if I'm not mistaken, must be "Navigation Mesh", as you must have already noticed, I'm a novice in this, so I ask for any suggestions or help please.

**Comment by DjNathann** [comment]
Open console type nav_mark_walkable (While staring at the ground).
Then type nav_generate
Then wait.
Then you can play.

**Comment by Zet0rz** [comment]
Navmeshes are needed for any gmod bot to be able to navigate. This isn't an nZombies issue, nZombies is just nice enough to let you know when you can't play without one. There are guides on how to make them on the wiki page, more in-depth guides on other sources.
