### ISSUE TITLE
Navmesh Editing

### ISSUE THREAD

**Issue by SILVERWAVE20** [Zet0rz/nzombies#599]
Can someone make a video on how to edit navmeshes? I have had many problems with my maps where the zombies get stuck or go where they shouldn't and i want someone to make a video showing most important things with navmeshes.

**Comment by lolleko** [comment]
There are several resources on that topic already:

http://steamcommunity.com/sharedfiles/filedetails/?id=485737805

https://www.youtube.com/watch?v=pSP9lY6YoFg

https://developer.valvesoftware.com/wiki/Navigation_Meshes
