### ISSUE TITLE
Crash on Killed

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#60]
Let's create a dedicated issue about this. I also just experienced this while testing myself on a single player listen server, so it is not a dedicated server only bug. I will continue to look into why, but let's discuss it fully here.

**Comment by Zet0rz** [comment]
Seems to in fact be related to wall buys if they have been bought (the models are rendering). Will need further testing to pinpoint the cause.

**Comment by Zet0rz** [comment]
It seems to require a random box on the map as well. I tried 16 wall buys all bought without a crash, but once I added the random box, I did. Later though, a random box alone did not crash, even if I bought it many times.

**Comment by minin43** [comment]
When it crashes on my dedicated server, I don't believe anything gets thrown into console. I will double check tonight, and I will also look into rcon logging. This all seems very strange.

**Comment by Zet0rz** [comment]
It seems to be one of those gmod-related crashes (no gamemode errors), but which happens when the gamemode does a certain thing. If we can figure out what exactly it is, we might be able to avoid it for now, but ultimately it's likely a bug in gmod itself.

**Comment by minin43** [comment]
Surely there's a webpage somewhere that describes in detail what you should do in gmod to avoid this? It seems awfully weird that doing some things in gmod will just insta-crash it.

**Comment by lolleko** [comment]
Is this still happening?

**Comment by minin43** [comment]
@lolleko Yes

**Comment by Zet0rz** [comment]
Does it happen consistently or randomly? When I tested it it crashed with a fair few wall guns when I got killed, but a few tests later it didn't. I don't know if it's a chance crash or a guaranteed one and I'm just missing something.

**Comment by minin43** [comment]
From my playing solo on my dedicated server last night: The first time I was downed (I purchased both the mystery box and a gun on the wall), the game ended normally and I was able to start another round. The second round, no matter what I did, it would crash. I tested this twice.

**Comment by Zet0rz** [comment]
It could be related to the outline entities since it's to do with wall buys. Try to do `nz_outlinedetail 0` and play for a bit, see if it still crashes. Although this is client side, so I don't see how this could cause a server crash.

It could be something to do with the map cleanup. Maybe something not cleaning correctly?

**Comment by Zet0rz** [comment]
Do you have a crash dump? If so, you can try using this site: http://dumps.metastruct.uk.to/ and examine the log from it. I don't seemingly have crash logs from these crashes

**Comment by minin43** [comment]
I can't seem to figure how to get server console to be saved. I didn't try your possible fix last night, I will try again tonight.

**Comment by minin43** [comment]
Also, tried the nz_outlinedetail 0 fix and it didn't work.

**Comment by Zet0rz** [comment]
I think it might be related to zombie pathfinding since it freezes very similarly as when you spawn them on no Navmesh (which has since been prevented by despawning). Since I don't crash but rather freeze, I'm not getting any crash dumps, but your server might (if it fully crashes), so look for a .mdmp file in the directories?

**Comment by Zet0rz** [comment]
Can now confirm it has nothing to do with random box or map cleanup. Crashed (froze) on a single launch with a fair few wall guns from CW2.

**Comment by Zet0rz** [comment]
Found the issue! I logged the console, and at the moment of dying, I found this in the log:
http://i.imgur.com/LghFqiu.png
Notice the scrollbar on the side. The rest of it down is the same print message, nothing else. I added a lot of debug prints (which run if `nz_zombie_debug` is 1), and got this:
http://i.imgur.com/whuAfRo.png
It seems like it's spamming the routine loop on a single zombie trying to retarget because it has no target, and unable to respawn, causing the loop to continue. I will continue to debug what line exactly it is on and try to prevent it. A coroutine.wait or path timeout might fix it.

**Comment by Zet0rz** [comment]
Yes fixed it! It was caused by an infinite loop with no delay that happened because the zombie ran OnNoTarget _just_ before the round was set to Game Over state. It is fixed by still doing this, but adding a 1 second timeout at the end, which will make it do only 1 loop and the next loop will be in Game Over state. See 1999ee386050abd1583190f078ec4fae60c93ca0

Needs testing now. Let me know if it works! Including on Navgroup changes!

**Comment by minin43** [comment]
WOOO!

**Comment by minin43** [comment]
Just finished a 16 round game on a new map I've been working on (map number 5 - it won't be the best but it'll be available). 

The fix DOES work (as well as the SP quick revive now being self-revive). Fantastic work!
