### ISSUE TITLE
Navmesh Editing

### ISSUE THREAD

**Issue by SILVERWAVE20** [Zet0rz/nzombies#601]
First of all, this is a repost. Don't come to me and my there are already sources of how to do this cause there aren't specifically for the one in nzombies. I want a tutorial on the nzombies one SPECIFICALLY. 

Can someone make a video on how to edit navmeshes? I have had many problems with my maps where the zombies get stuck or go where they shouldn't and i want someone to make a video showing most important things with navmeshes.

**Comment by lolleko** [comment]
Everything in theses guides mentioned in #599 also applies to nzombies.
I actually forgot to mention the nzombies specific guides in the wiki:

https://github.com/Zet0rz/nzombies/wiki/Basic-Navmesh-Editing
https://github.com/Zet0rz/nzombies/wiki/Advanced-Navmesh-Editing

For the sake of completeness again the guides mentioned in #599:

http://steamcommunity.com/sharedfiles/filedetails/?id=485737805
https://www.youtube.com/watch?v=pSP9lY6YoFg
https://developer.valvesoftware.com/wiki/Navigation_Meshes

There is no plan to create a official video for navmesh editing, maybe someone of the community will make one but we won't, so please stop asking.
