### ISSUE TITLE
Gameplay Footage

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#61]
This isn't meant to be a bug report or anything. This is purely for me to post gameplay footage. Reference this footage when you need to study gameplay. If you close this as well, I'll just assume you don't want this on the issues page, otherwise:

mur_future_apt - https://youtu.be/CrW1tgUJDhY
zs_infected_facility - https://youtu.be/EFsSPZMECxM
gm_scrapmetal - https://youtu.be/kjfA684k4Fs

**Comment by lolleko** [comment]
The apartment is a bit to linear in my opinion (still well edited tho), but i really like the facilty. Keep it up!

**Comment by minin43** [comment]
I agree with you on the apartment, but it's a good introductory map for players with CSS. A small and cramped map makes it very difficult to survive higher level rounds, but it also means it's less daunting for new players.

I have a third map (in reality its the second, but I had to skip it), but it has water placed in it, and when zombies hit water, they immediately respawn. So a tip to all other map makers, if a map has water in it, don't let zombies touch it

**Comment by lolleko** [comment]
Yeah zombies cant swim, I would love to add that but its not possible with gmod right now . So for now they just respawn to prevent them from not getting stuck underwater.

**Comment by minin43** [comment]
@lolleko I'm not suggesting they need to swim, their walking animation would be fine, but it just disallows me from using a specific map because of it

**Comment by lolleko** [comment]
It's not about the animation. The zombies/nextbots simply have no water physics. They will just walk on the ground (the bottom of whatever water pit they fell into), and are completly unable to ascend.

**Comment by Zet0rz** [comment]
Once gmod gets added ladder and water functionality to Nextbots (Lolle already created a request which Robotboy assigned himself to), we will add it in. For now, we'll have to avoid those maps :/

**Comment by minin43** [comment]
@lolleko I understand this. But for the specific map I'm talking about, it wouldn't matter. The water isn't steep enough for them to need a swim animation (Not only that, but in maps where the zombies WOULD just "emerge" out of the water, having them slowly walk out of it could be much more spooky then having them swim or anything).

**Comment by Zet0rz** [comment]
@minin43 We could probably achieve that with a server convar or a map setting. Something like `nz_zombiewaterrespawn [0/1]`

**Comment by lolleko** [comment]
I will change it so zombies only respawn if their head is underwater.

Edit: never mind it's already that way. So if you just delete all navmeshes that are too deep it should work. Could tell me if they despawn as soon as they touch water or just if their head is under water. And i get why it would be good for your map. But I tested it on maps (with pools for example), where zombies would just be stuck.

**Comment by minin43** [comment]
@lolleko It's as soon as they touch the water.

**Comment by minin43** [comment]
Updated with the newest footage.

**Comment by lolleko** [comment]
That's odd, I will make a workaround to only despawn them once they are fully submerged.

**Comment by minin43** [comment]
@lolleko Has the workaround been implemented?

**Comment by lolleko** [comment]
Sorry it took so long, I'm quite busy atm. But I think I got it working in 630cddb. Zombies now only despawn if their head is under water. It might be a little inaccurate depending on the map. Spawning under water should also work as long as the zombies are not spawned deeper than 64 units (player height). Please report back if that works for you aswell :cold_sweat:

**Comment by minin43** [comment]
@lolleko thanks!
