### ISSUE TITLE
Dog round fog overrides map fog.

### ISSUE THREAD

**Issue by Ethorbit** [Zet0rz/nzombies#612]
Not sure if it was intended, but maps can't have their own custom fog for nzombies.

**Comment by sh4d0w59** [comment]
Does the special round fog override the map fog all together or does it only override the map fog once the special round starts?

**Comment by Ethorbit** [comment]
It overrides the fog all together.

**Comment by sh4d0w59** [comment]
You could copy the map fog setting over to the nzombies fog editor as a workaround until it's fixed. idunno

**Comment by Ethorbit** [comment]
My bad. I had no idea there was a fog entity for the nzombies config. This is not an issue and I'm closing the topic now.
