### ISSUE TITLE
Red screen on hit.

### ISSUE THREAD

**Issue by Ethorbit** [Zet0rz/nzombies#616]
I know this issue has probably been around forever, but it's hard to play when your whole screen turns red every time you are hit.

**Comment by Zet0rz** [comment]
This is intentional.

**Comment by ghost** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=850350535&searchtext=Unreal+Enhancements
http://steamcommunity.com/sharedfiles/filedetails/?id=850977361&searchtext=Unreal+Enhancements

You can use those two addons together to replace the red screen effect with some chromatic aberration, or you can just turn off the effects in sandbox so you don't even get anything when you get hit.

**Comment by Ethorbit** [comment]
When you get hit it blinds your whole screen. Is that really what you wanted?

**Comment by sh4d0w59** [comment]
I’d like to see an overlay similar to call of duty’s in regards to long term aesthetics but in the mean time would it be possible to tone the red screen down?  Perhaps reduce the alpha across the board until we can get a cod overlay?

**Comment by TheFreshNewTaste** [comment]
Ive heard multiple peoples annoyance due to the blinding red mat color that appears everytime you get hit,  and in a zombie game its pretty frequent to get hit. I think it is time to do something about the ugly red.

**Comment by Ethorbit** [comment]
I just realized that it's not as bad in Singleplayer as it is on the TFA server. So it must be what they did, the red in Singleplayer is not blinding at all. Sorry for the inconvenience.

**Comment by Zet0rz** [comment]
It should look like this with the current code:
![](https://camo.githubusercontent.com/43856a707041c0f7c2699674e3ffc27b883d7a3c/687474703a2f2f692e696d6775722e636f6d2f434235645077682e6a7067)
If it looks more red than that, chances are the server you are playing on/your own client has some rendering conflicts. That, or gmod is just being unreasonable again. Either way, if the above is not what you think is a problem, then this issue isn't related to the gamemode.
