### ISSUE TITLE
Coroutine across C-call boundary error on Despawn

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#62]
This error happens whenever a zombie has been stuck for long enough to disappear. It will likely be fixed by adding a coroutine.yield somewhere before the entity being removed.

**Comment by lolleko** [comment]
Happens beause respawn is called from think not from runbehaviour. And since emerge on respawn aswell. PlaySequenceWait will be called without a courotine.

**Comment by lolleko** [comment]
Hotfixed in #63

**Comment by lolleko** [comment]
Looks like it's fixed.
