### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by ghost** [Zet0rz/nzombies#624]
Would it be possible to tell (or teach) the game mode to read .gif files, or any kind of animated file?

I just want to know since I saw some sweet looking animated perk icons and I want to put them into my game for personal use.

**Comment by minin43** [comment]
I think you meant the engine. Does the source engine support .gif files? I don't think so, but you can ask on forum.facepunch.com

**Comment by ghost** [comment]
okay, thanks

**Comment by lolleko** [comment]
Actually animated icons are possible, but you can't just use a gif you will have to use source's material system. A good place to start might be here: http://wiki.garrysmod.com/page/Category:Material
