### ISSUE TITLE
Every model is an error

### ISSUE THREAD

**Issue by rowan2104** [Zet0rz/nzombies#631]
i have the main mod put in addons, i have both content packs and subscribe to the full collection but all perks, zombies and hud elements are all errors and missing textures. plz help.

**Comment by DjNathann** [comment]
Uninstall everything (gamemode and content packs) and Re-download them.

**Comment by rowan2104** [comment]
Thanks, but I manage to get the models to work by downloading a bunch of the unofficial content packs, but I still have the problem of the mystery box being an error, it’s the only model I can’t fix.

**Comment by DjNathann** [comment]
Do you have Hoff's Mystery box? if so uninstall/disable it.

**Comment by rowan2104** [comment]
I’ve uninstalled it but it still comes up as an error.

**Comment by DjNathann** [comment]
Did you installed them while the game was still up?

Try downloading them without having the game up.

**Comment by rowan2104** [comment]
Thanks, that solve it.

**Comment by isaiahtronik** [comment]
@rowan2104 what content packs did you install to fix the error because I have the same errors

**Comment by rowan2104** [comment]
@isaiahtronik i just looked up nzombies and downloaded all the content pakcs, however i solved it by unistalling everything to do with the mod and just downloading the nessesary ones.

**Comment by isaiahtronik** [comment]
I tried deleting both content packs as well as the github addon and re-downloading them but it didn't work

**Comment by isaiahtronik** [comment]
So what "unofficial" content packs did you install?

**Comment by rowan2104** [comment]
I honestly couldnt tell you, its been so long. Just seach nzombies or nzombies content and download pretty much everything that comes up.
