### ISSUE TITLE
Can't reload with speed cola

### ISSUE THREAD

**Issue by Ezzocorbi** [Zet0rz/nzombies#637]
I found a bug that doesn't let me reload certain weapons when I buy Speed Cola.
Video: https://www.youtube.com/watch?v=ZcBSLpl-txY
Console Log: https://pastebin.com/wmC5N9X2
This happens with the Mustang and Sally addon too: https://steamcommunity.com/sharedfiles/filedetails/?id=758646160&searchtext=
TFA weapons aren't affected by this bug.

**Comment by DjNathann** [comment]
Speed cola only works with modded weapon base (TFA,CW and FAS) M9K and normal weapon base do not work so use TFA,CW or FAS atm.
