### ISSUE TITLE
Is there a way to get informations about a door?

### ISSUE THREAD

**Issue by Ezzocorbi** [Zet0rz/nzombies#638]
It would be useful because when I decide to edit a map I don't remember which flag I have set on each door when I created the map, so I have to take a look in the config every time and it is kinda messy in there.
Is there a way to get the info about a door without having to use the config file?

**Comment by DjNathann** [comment]
1. There is a Wiki near the Projects and Insights.
2. Hold C and hover your mouse to that door,right click it and there it will tell you to flag or remove the door.

**Comment by Punkinator7** [comment]
see, if you hold C and right click on the door and click edit lock, it will say the flag that you set on the door on the door flag in the menu.

**Comment by DjNathann** [comment]
Didn't i already said that?
