### ISSUE TITLE
M67 Grenade Conflict

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#64]
Not sure if you know this, but some weapons pack start conflicting with each other and may give me m67 grenades. Are these weapon packs just not compatible or what?

**Comment by minin43** [comment]
Do not use other pack's grenades. At all. Only use the placeholder one provided by Zet0rz. Other pack's grenades can break things, such as the mystery box.

**Comment by lmao5677** [comment]
Even if I don't use a pack with grenades, sometimes weapons will still break and give me m67 grenades

**Comment by minin43** [comment]
Explain this breaking? Are you talking about through mystery box? Because the mystery box, by default, has every weapon entity in it, including things such as weapon bases and, in your case, different grenades.

**Comment by lmao5677** [comment]
It happens when I buy a wall weapon or in the box. I was using black ops 2 remastered, cold war and modern warfare 2 weapons pack. First time I get a  gun it works. The second time it fails and gives me a m67 grenade.

**Comment by minin43** [comment]
If it prints an error, please post the error.

**Comment by lmao5677** [comment]
Ok, I will see if it does that.

@minin43 

No errors. But it still happens....

**Comment by Zet0rz** [comment]
Yeah let me know the errors. In most cases, I can prevent the use of grenades by blocking what causes the error if it occurs. But the way I made the special weapon system (weapons you can't equip from scrolling) makes it easy to add any weapon to it, and it will replace any previous weapon in that slot. The function to do this looks like this:
`SpecialWeapons:AddWeapon(weapon_class, category, usefunction, equipfunction)`
Weapon_class is the weapon you are registering.
Category is the type. Currently we have "knife", "grenade", "specialgrenade". You can add your own with `SpecialWeapons:CreateCategory(category, bind, createammotype)`
Usefunction is the function when the bind associated with its category is run (IN_ binds). Usually you would just make it equip the weapon, trigger wep:PrimaryAttack(), requip old weapon.
Equipfunction is when you get the weapon. Usually you would give starting ammo here, or for knives start a draw animation.
[_See /gamemode/special_weapons/sh_specialweapons.lua_](https://github.com/Zet0rz/nzombies/blob/Master-Changes/gamemodes/nzombies3/gamemode/special_weapons/sh_specialweapons.lua)

If you let me know which weapon packs this belongs to, I can look into adding them into the system by default, or prevent players from getting them alltogether (since we already have frags).

**Comment by lmao5677** [comment]
>  SpecialWeapons:AddWeapon(weapon_class, category, usefunction, equipfunction) 
> 
> SpecialWeapons:CreateCategory(category, bind, createammotype) 

How would I be able to run these commands?

The owner of the pack is Megadeath9811

**Comment by Zet0rz** [comment]
@lmao5677 Any .lua file run by the server with this function in it would add them. Put it in a simple lua script in autorun or add it to an extensive server setup lua file (where you also register all other things, like weapons to the Wonder Weapon system).

And may I ask, what kind of "conflict" does this create? Error spam? Unable to use these grenades? Unable to use NZ grenades?

**Comment by lmao5677** [comment]
> And may I ask, what kind of "conflict" does this create? Error spam? Unable to use these grenades? Unable to use NZ grenades?

It makes me unable to use these grenades. They appear as nothing. If I go back to the weapon, it just appears as my previous weapon.

**Comment by Zet0rz** [comment]
So you buy a gun, but it gives you grenades, and then it just gives you nothing?

**Comment by lmao5677** [comment]
Not exactly, when I buy a gun, it gives me grenades, but they don't appear as anything.

**Comment by Zet0rz** [comment]
Does it give you grenades **and** the gun? And the grenades, you do have them, they are just invisible and can't be used (taking up a spot in your weapon slots)?

**Comment by lmao5677** [comment]
It just gives me the grenades which are invisible and unusable. I don't get them because then it just becomes my weapon that I traded when I go back to that weapon slot.

**Comment by Zet0rz** [comment]
Alright. I will have to look into why this happens. From what you played, is the correct way this is supposed to be that you get the weapon without any grenades? I can probably prevent the equipping of weapons that other weapons give you in extension.

**Comment by lmao5677** [comment]
> You get the weapon without any grenades?

I do get grenades but the weapon that I buy/trade becomes grenades. Heres explanation in a deeper meaning.

M1911 + Buy Weapon = Success!
Buy New Weapon with M1911 on hands  = Fail, Grenades received
Buy New Weapon with New Weapon  on hands = Fail, Grenades received
Go back to weapon that I bought = Same weapon that I bought for the first time
Go back to M1911 = No new weapons.

If you can understand that.

EDIT: I'm going to post a video actually to make more sense

**Comment by Zet0rz** [comment]
Good call. But the outcome we want is that you just get the weapon you buy always, no grenades.

**Comment by lmao5677** [comment]
I've got the video. 

https://www.youtube.com/watch?v=vQsWl5AcPFY

**Comment by Zet0rz** [comment]
Alright I see what you mean, but there's something I want you to try. Make this happen again, then put this in console:
`lua_run print(Entity(1):GetActiveWeapon())` as well as `lua_run PrintTable(Entity(1):GetWeapons())`
Tell me what those output. Run the first one as your current weapon is that grenade (when the HUD says M67 Grenade). Finally, do this: `key_listboundkeys` and see which one is bound to "+grenade1". You can also try `key_findbinding +grenade1`

**Comment by lmao5677** [comment]
> print(Entity(1):GetActiveWeapon())...

OUTPUT: Weapon [268][nz_grenade]

> PrintTable(Entity(1):GetWeapons())...

Output: 1   =   Weapon [266][weapon_bo2_browninghp]
2   =   Weapon [267][nz_quickknife_crowbar]
3   =   Weapon [268][nz_grenade]
4   =   Weapon [270][weapon_bo2_galil]

> key_listboundkeys

Output: "g" = "+grenade1"

**Comment by Zet0rz** [comment]
Yep it actually equips the gamemode's grenades which is why it doesn't replace anything. This shouldn't have anything to do with the weapons then, does it happen with any other gun mod? It could be these guns trigger +grenade1 by themselves.

**Comment by lmao5677** [comment]
No, this does not happen with any gun pack.

**Comment by Zet0rz** [comment]
Fixed in commit b06aa358f37063bbdf362e344912e67bb75d50df. I'm gonna close this, but there's a chance this might happen again (if the weapon's weight is less than 1 and the auto-weight change didn't work), so let me know if it does and I'll reopen this.

**Comment by lmao5677** [comment]
I didn't seem to work. It replaced my weapons with grenades and I can't buy anything at all.

**Comment by Zet0rz** [comment]
It seemed to work for me, but I'll go through some more testing then. I think I may have a failsafe though, and is to set the player using special weapon variable to false (so it doesn't block you from switching weapons to non-special) if it wasn't changed to via the bind.

**Comment by Zet0rz** [comment]
Closing as it is being investigated in newer issue with  more info.
