### ISSUE TITLE
(Help) Disable TFA attachments

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#645]
Is there a way to completely disable tfa attachment rolling?

**Comment by ghost** [comment]
put nz_papattachments 0 in console.

keep in mind that this disables attachment rolling across the board.
If that's not the command, it's definitely an nz_ command, so look through them.

**Comment by sh4d0w59** [comment]
Thanks napalm/ducky boi.  You saved muh map configs.  Issue closed.
