### ISSUE TITLE
Player Respawning and Point System

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#65]
It has been reported that players respawning after dying out a previous round only spawn with 500 points. This is not intentional, players respawning should spawn with their previous points (but still no weapons or perks). 
The point system should also be updated to act like the real system with players dying:
- Getting downed (Lose 5% of points, given to revivor)
- Dying out subtracts 10% points from the remaining living players

**Comment by Alig96** [comment]
I wasnt even aware it did that in the actual game. Just a quick mention, remember to round to the nearest 10 dont want players running around with 506537.6444 points

**Comment by Zet0rz** [comment]
Yep, rounded to nearest 10. I don't think anything ever costs in the 10's unless you set it so in the tools.

**Comment by Zet0rz** [comment]
Added in commit f03909323cb6ad77bba1392ff746f9ed51ff8898. It would need some testing, so tell me the results of your playtesting!

**Comment by minin43** [comment]
I will test it!
