### ISSUE TITLE
Unable to Earn Points

### ISSUE THREAD

**Issue by WoomyKing** [Zet0rz/nzombies#653]
I ran into an issue where I don't have hit numbers in my addons and I didn't have an issue before until recently. I would love to play this game mode but I don't get points from killing or damaging zombies with any of my weapons.

**Comment by DjNathann** [comment]
If you have Life Mod: The All-In-One Ultility Tool or Hit Numbers (Maybe Both) they cause the game to conflict with them and the zombies will not give you points.
