### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by Innerdesert4346** [Zet0rz/nzombies#658]
What is the button for special grenades?

**Comment by DjNathann** [comment]
Really? You've made an issue to know what button for the specials grenades are without trying it yourself?
Its B btw, and don't create pointless issues like this.

**Comment by DjNathann** [comment]
G for Grenades.
B for Special Grenades.

**Comment by Innerdesert4346** [comment]
Well my friend has a mod that uses that button so i'll have to tell him to edit his controls as well as me edit mine. Sorry.
