### ISSUE TITLE
Solo Quick Revive

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#66]
In Black Ops and onwards, Quick Revive can be bought for 500 points and with no power requirement if playing alone. The perk also does something different; it instead causes the player with the perk to get revived after a few seconds of being downed. It can only be bought 3 times.
This can be made as a seperate perk ("solorevive") so it acts seperately.

**Comment by Zet0rz** [comment]
Added in commit 548260be20cb40bb9bce2e71d2a1ef243878eb75

**Comment by minin43** [comment]
Nice!
