### ISSUE TITLE
Can't find the nZombies gamemode on the Gamemode tab

### ISSUE THREAD

**Issue by BrandonPatNEGamerzz** [Zet0rz/nzombies#671]
Is this gamemode broken or something? I did everything it told me, subscribe to both parts of the gamemode, downloaded the .zip file and put them on my Addon folder. I went into Gmod, but I don't see them gamemode on my gamemode list. Did I do something wrong?

**Comment by lolleko** [comment]
Did you unzip the file?

**Comment by BrandonPatNEGamerzz** [comment]
>           Did you unzip the file?

No, all I did was download the .zip, put it on my addons folder, and (idk if this was needed) I extracted files in my addon folder

**Comment by BrandonPatNEGamerzz** [comment]
Oh nevermind, I found the problem, thx anyways :)
