### ISSUE TITLE
An option to automatically activate scripts

### ISSUE THREAD

**Issue by Chtidino** [Zet0rz/nzombies#676]
There would be the possibility to add an option to activate the map scripts automatically, without the need to go through a SuperAdmin that must accept on the window when loading the config to load the script of the map? pls

**Comment by Zet0rz** [comment]
If you are on a singleplayer or locally hosted server, you're already a super admin. If you're not a super admin, it means you're on another's server and you really shouldn't be allowed to accept scripts.

Remember scripts have the power to ban, promote to admins, and other malicious code.

**Comment by Chtidino** [comment]
This is for my server, and that the player does not need my intervention. In addition some scripts can unlock the pack a punch, which means that if the script is not active, there is no way to improve these weapons (config "imprisoned"). And the player complains about that. In the following for scripts, I watch that there is no bad intention. (I will try to make them myself if it is necessary)

**Comment by Chtidino** [comment]
In which file should we add or modify lines of code, and with what? please tell me
