### ISSUE TITLE
Doors with 0 Price not opening by themselves

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#68]
Doors with a price of 0 are supposed to open by themselves either on game start, or when electricity is turned on, depending on the setting. They currently do not do this. It is likely because of the migration to `entity:GetDoorData()` where the electricity and game start loop still use `entity.price` (stored directly on entity).

**Comment by Zet0rz** [comment]
Fixed with commit 51c4f203867a8597043821b7513956af1eadb2c8

**Comment by minin43** [comment]
yussssss

I wasn't going crazy
