### ISSUE TITLE
HUD is an Error and perk machines, box, and zombie models are errors. 

### ISSUE THREAD

**Issue by PerkaYT** [Zet0rz/nzombies#693]
Almost everything is an error. I've downloaded pretty much all the content packs and the complete collection. I'm just curious to why I'm still receiving errors. Here is what the console says to me.      Not loading addon 'addons/nzombies_content_pack_[part_2]_777195612.gma' - file doesn't exist
Couldn't mount addon file 'addons/nzombies_content_pack_[part_2]_777195612.gma' from 'nZombies Content Pack [Part 2]' (777195612)
Removing bad addon addons/nzombies_content_pack_[part_2]_777195612.gma

Not loading addon 'addons/nzombies_-_a_nazi_zombies_gamemode_[content_pack]_675138912.gma' - file doesn't exist
Couldn't mount addon file 'addons/nzombies_-_a_nazi_zombies_gamemode_[content_pack]_675138912.gma' from 'nZombies - A Nazi Zombies Gamemode [Content Pack]' (675138912)
Removing bad addon addons/nzombies_-_a_nazi_zombies_gamemode_[content_pack]_675138912.gma

Including: mainmenu/cl_vgui.lua
Couldn't find windows font 'PierSans-Regular', falling back to 'Tahoma'..
Couldn't find windows font 'PierSans-Regular', falling back to 'Tahoma'..
Couldn't find windows font 'PierSans-Regular', falling back to 'Tahoma'..

**Comment by minin43** [comment]
Your client isn't mounting the addons. That's not an nZombies issue.

**Comment by PerkaYT** [comment]
Why isn't my client mounting the addons?
Is it a PC problem?

**Comment by minin43** [comment]
This isn't a forum to ask for general gmod help.

**Comment by PerkaYT** [comment]
Nevermind, I figured out why, my lua files were corrupted by overuse. The mod works now.
