### ISSUE TITLE
Grenades and other special weapons erroring when not switched to

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#70]
Sometimes when reloading, you are blocked from switching away from the weapon until it's done. If this happens when you try to throw a nade, it will error because the :ThrowGrenade function doesn't exist on the weapon you then now keep. It can likely be fixed by checking if the weapon is special before doing anything, or by forcing weapon switch (no matter what).

**Comment by minin43** [comment]
Update on this? Got anything new related to it? Would you like to see the error it prints out?

**Comment by Zet0rz** [comment]
I have changed a lot of how the special weapons system works and I may have gotten around this while working on other things. Then again, maybe not. It's a later priority, probably only something that'll be fixed in the cleanup right before release.

**Comment by Zet0rz** [comment]
Fixed in the new way the special weapons system runs. Functions are now injected directly into the weapon's own Think function and will thus only run while the weapon is actually equipped.
