### ISSUE TITLE
Error with Setmaterial on wall weapons.

### ISSUE THREAD

**Issue by ValkyrWarframe** [Zet0rz/nzombies#700]
I've been having a lot of issues with the material of wall weapons not functioning properly as of the latest GMod patch. 

```
Full error message is:
[nzombies-master-workshop] addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua:85: bad argument #1 to 'SetMaterial' (string expected, got userdata)
  1. SetMaterial - [C]:-1
   2. RecalculateModelOutlines - addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua:85
    3. Draw - addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua:315
     4. unknown - gamemodes/base/entities/entities/base_anim.lua:49
```

I have no idea how to code or how lua works so is there any solution to this?  Weapons on walls don't render anymore.

**Comment by Lewin225** [comment]
Open addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua

Find and replace     :SetMaterial(chalkmaterial)

With       :SetMaterial("chalk.png")

**Comment by ValkyrWarframe** [comment]
> Open addons/nzombies-master-workshop/gamemodes/nzombies/entities/entities/wall_buys/shared.lua
> 
> Find and replace :SetMaterial(chalkmaterial)
> 
> With :SetMaterial("chalk.png")

Thank you
