### ISSUE TITLE
Barricade Jump Animation implementation

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#71]
Implement the zombies' barricade jump animations together with barricades that trigger this animation. Also make multiple types of barricades:
- Default, no animation
- With sandbags/generic prop, with animation
- With no props but still animation (place your own prop)
- With no props but still animation, no planks

**Comment by minin43** [comment]
If only I could animate D:

**Comment by Zet0rz** [comment]
The animations are already there, we just have to find the best way to blend, trigger, and handle them so that they continue to move from where they land.

**Comment by minin43** [comment]
Still don't know, lol
