### ISSUE TITLE
Model LODs and Bump Map

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#72]
Compile the Nazi Zombie models that we have now with their LOD meshes so that we can use those. This will greatly help performance when looking at many zombies. Also fix the bump maps causing wierd blackness on the zombies (if it is that).

**Comment by Zet0rz** [comment]
LODs finished and Bump Map problems improved (not completely gone) in commit f825482d2c1ed24381b021c611e2aedb72c6ccea

**Comment by minin43** [comment]
So increased FPS when looking at tons of zombies?
