### ISSUE TITLE
Some files are missing?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#73]
[AddCSLuaFile] Couldn't find 'function_override/sh_constructor.lua' (@addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/loader.lua (line 30))
Couldn't include file 'function_override\sh_constructor.lua' (File not found) (@addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/loader.lua (line 31))

**Comment by Zet0rz** [comment]
Yeah those are just because the files are empty. It doesn't change anything with the gamemode, we just haven't removed them in case we need them later.

**Comment by minin43** [comment]
Ah, ok. I was wondering if this was having some effect on the crashing or not. Guess it doesn't.
