### ISSUE TITLE
Random Box to only cycle available weapons and precache

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#74]
The Random Box should only cycle through guns added to its list (or the server's list, whichever it uses). On top of that, players should precache these models on join so that they won't get lag spikes when it's cycling through heavy models.

**Comment by func-octo** [comment]
Currently I get lag regardless every time it changes the model, but I have a 750 Ti, so I'm not really suprised xD

**Comment by Zet0rz** [comment]
750ti should easily be able to handle it

**Comment by func-octo** [comment]
Stats
RAM: 4 GB of RAM (GSKILL)
CPU: AMD A10 Black Series
GPU: EVGA NVIDIA 750 Ti SC
CPU Heatsink size: 6 inches wide and tall
CPU Fan Size: 6 inches wide and tall
Motherboard: BIOSTAR A36W (I think)

GPU has never gone above 35C
CPU has never gone above 40C

Yet I still go from 60 fps to 30fps on games like gmod, teamfortress 2, etc. It's more like couple minutes 60 fps, then a couple minutes of 30fps back and forth.

**Comment by minin43** [comment]
Who knows. Every different piece of hardware functions differently. Maybe it's a gmod thing.

**Comment by func-octo** [comment]
The only reason I complain about the fps is because the mouse sensitivity goes awol. Otherwise, our eyes percieve things as 14 fps, cameras at 24 fps, tvs at 40 fps, and games at 60 fps. Some can tell the difference between 30 and 60 fps, but after 60 fps, the eye can no longer tell the difference. This is why I dislike those who complain about low fps rates of 120 fps. The End.

**Comment by Zet0rz** [comment]
Done in commit 6764e46b3986cf0a01b0e60d7a7eed98ee273a2f

**Comment by Alig96** [comment]
Have you remembered precacheing the wall weapons too?

**Comment by Zet0rz** [comment]
@Alig96 Yup they do that on creation! (So it may lag in creative and on Round Start, but shouldn't on bought)

**Comment by minin43** [comment]
@ScriptnLua What.

What are you high on.

> but after 60 fps, the eye can no longer tell the difference

Do you just spout whatever bullshit crops up in the 'ol noggin?

You can tell the difference between 30 to 60 to 120 to 240 FPS. Sure, the higher the framerate, the more the law of diminishing returns applies, but you CAN tell the difference. It's a proven fact.

**Comment by Alig96** [comment]
It was a joke buddy, its the whole "consoles vs PC" debate

**Comment by minin43** [comment]
That most definitely doesn't look like a joke.
