### ISSUE TITLE
Special Weapons don't work on an empty mag

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#75]
Meleeing doesn't work if you don't have any ammo in your gun, at least for CW2.0. I will provide footage next chance I get.

**Comment by Zet0rz** [comment]
I think I've seen this bug being a gmod thing where you can't change weapons. I can probably find a workaround to avoid this.

**Comment by Zet0rz** [comment]
A possible workaround could be what TTT did:
https://github.com/garrynewman/garrysmod/blob/16f29636a3da81a0ff6fe3e5bf7f0aa787e86f8f/garrysmod/gamemodes/terrortown/gamemode/weaponry.lua#L179

**Comment by lolleko** [comment]
Might also be fixed if client side prediction an select weapon is used instead of server side select weapon.

**Comment by func-octo** [comment]
One thing, has the key for melee changed? It no longer does melee when I press V regardless. Is there an alias for it?

**Comment by Zet0rz** [comment]
@ScriptnLua It runs on the Noclip bind so whatever you bound noclip to.

**Comment by Zet0rz** [comment]
Gmod fixed this with one of its updates.
