### ISSUE TITLE
Texture errors.

### ISSUE THREAD

**Issue by lemonylink** [Zet0rz/nzombies#76]
Hello, I am hosting this gamemode and tweaking myself. Recently tho I started a fresh server with default files + this updated gamemode but sadly I have various pink and black errors all over the huds. zombies are giant errors aswell. 

Any help please?

**Comment by minin43** [comment]
You downloaded the incorrect version, most likely. Try this one: https://github.com/Zet0rz/nzombies/archive/Master-Changes.zip

**Comment by lemonylink** [comment]
That's the version I am using. Basically, I had the version from a few days ago and it was fine. Then I started a brand new SRCDS server with the updated files today and I get the pink and black texture errors on the hud and and zombies are giant errors. I have got other people to confirm this also, it was fine and now it's not. Not really sure what to do. I have tried alot of thing before coming here.

**Comment by minin43** [comment]
I just downloaded the latest version, let me test it and I will get back to you in a few minutes.

**Comment by minin43** [comment]
Alright, I just loaded up a map with the newest download and everything was working fine for me.

Try redownloading the gamemode and seeing if that fixes it, otherwise it might be an addon conflict (but that seems highly unlikely).

**Comment by lemonylink** [comment]
I am just reinstalling garry's mod aswell as a fresh server again to make 100 percent sure I am not doing anything wrong. Are you using a fast download to host the files?

**Comment by minin43** [comment]
The files are being download through github. Do you have the addon installed both on your client and on the server?

**Comment by lemonylink** [comment]
Yeah I do. I guess I should delete them. Would that make it conflict perhaps?

**Comment by lemonylink** [comment]
still not working on a fresh server with only the gamemode and other folders in latest master updated version from today. tried with FD and without. Still getting same errors. =c

**Comment by lemonylink** [comment]
Oh you mean the player has to manually download the addon from here before Joining my server???. I had it working with fast-download yesterday, but it just stopped for some reason  =/

**Comment by minin43** [comment]
It probably stopped because the code to fastDL the files was in the gamemode, which you overwrote when updating.

Yes, clients need the addon as well as the server. This gamemode will be going up onto the workshop within my prediction of 2-3 weeks. Wait then and then have them download the addon through steam.

**Comment by lemonylink** [comment]
Even doing that.

I fix the hud texture errors but..

I still can't see zombies and get this error.

[ERROR] lua/entities/nz_zombiebase.lua:449: attempt to index a nil value
  1. unknown - lua/entities/nz_zombiebase.lua:449


which is 

local leftEye = self:GetAttachment(self:LookupAttachment("lefteye")).Pos
		local rightEye = self:GetAttachment(self:LookupAttachment("righteye")).Pos
		cam.Start3D(EyePos(),EyeAngles())
			render.SetMaterial( eyeGlow )
			render.DrawSprite( leftEye, 4, 4, white)
			render.DrawSprite( rightEye, 4, 4, white)
		cam.End3D()
	end


rather weird.

**Comment by lemonylink** [comment]
Even doing it manually I still can not see the zombie models. It is failing to load them. Even on a LAN. I copied the files over to my garrys mod client root. But it seems like it will not read the zombies model location..

**Comment by minin43** [comment]
Either 1 of 2 things has happened: the files are corrupt, OR, you put them in the wrong place.

I'm betting on the latter.

**Comment by Zet0rz** [comment]
All clients need the addon installed as the models and textures are simply too big and too many to make them download on join. As long as you download the zip and extract the folder to addons it should work fine. You can verify it was done correctly by checking if this path exists:
`GarrysMod/garrysmod/addons/<any name>/models/nz_zombie/zombie_rerig_animated.mdl
`
This has to be in your client installation. The any name can be anything as Garry's Mod loads any addon folders inside addons, but you're only looking for the nzombies addon, so whatever you called.

**Comment by lemonylink** [comment]
Thank you for clearing that up for me, I have managed to get it working and just told people to manually download this and extract to the folder specified and it works. The only thing that's a problem now is that only admins can ready up. I did change this in the "Chat commands" Lua but for some reason it keeps reverting, Another problem is that when I make it available to anyone to join the game and not admin only they have access to /create /cheats etc etc. What part do I need to change to make it so anyone can join but not use /cheats or /create? Thanks.

**Comment by minin43** [comment]
It's currently a bug. There are 2 workarounds: 1) give those people superadmin status and they can ready up, OR 2) type this code into _server_ console: `lua_run for k,v in pairs(player.GetAll()) do v:ReadyUp() end`

**Comment by lemonylink** [comment]
I think I will use the code, Thank you :)

**Comment by Zet0rz** [comment]
The chat command error has been noted down in issue #81
