### ISSUE TITLE
Lag on RandomBox/WallBuys

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#78]
This issue has been around for the longest time, I think it is a pre-caching issue.

**Comment by Zet0rz** [comment]
It is. I have plans for it though. The random box should only cycle through weapons it can actually give, and when a player joins and this list is networked to him, he will precache all of them. I didn't think of the wall buys, that's a good call.

**Comment by Zet0rz** [comment]
Closing as there's already another issue about this.
