### ISSUE TITLE
Doors not networking correctly sometimes on Killed

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#79]
When getting killed and respawning the next round, there's a good chance of all doors reappearing to be locked for you (but you can still pass through them).

**Comment by minin43** [comment]
So happy to see the playtesting leading to all these bug fixes :D

**Comment by lemonylink** [comment]
Can also confirm I have had this bug

**Comment by Zet0rz** [comment]
A possible fix (since the visibility is the only thing messed up) would be to use a serverside SetNoDraw just like the serverside Collision Group. This would make it always look right (but may internally still be wrong). A sort of failsafe, should still be fixed in general.

**Comment by Zet0rz** [comment]
Seems to happen if another player joins, it resets the status for all other players.

**Comment by Zet0rz** [comment]
As of commit 6173353a5efb2d3bf29cfcccb448d3261553f146, this should be effectively fixed. It will still be wrong networking (clients still think they are locked), but the collision and visibility is controlled by the server, so they will still be walk-through and invisible.
