### ISSUE TITLE
Give me maps to configure.

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#82]
Just starting listing off any maps you think would make good maps for the gamemode.

Make sure they're off the workshop and I'll take a look at it.

**Comment by lemonylink** [comment]
What maps have already been done / in progress? I'm planning on doing a few myself. But don't want to conflict with maps already in progress. Currently I just set up messing around maps on the lifepunch cinema map and cs_office. - Planning on doing kino der toten later on and mwf2 terminal map.

**Comment by minin43** [comment]
check my gameplay footage post

**Comment by lemonylink** [comment]
Watching it now. Looks pretty good.

**Comment by Zet0rz** [comment]
For the official configs, I have plans of making all the original Zombies maps I can find on the workshop complete with map scripts that will make them like the original (like in Kino, a working teleporter that leads to PaP temporarily). On top of that, I wanted around 4 high-quality original configs. For those I have currently got `ttt_kosovos` and `ttt_rooftops_2016`

**Comment by minin43** [comment]
@Zet0rz You've played 2 of my maps so far, what are your thoughts on those 2?

**Comment by lolleko** [comment]
I did one for `dod_u471_b2`. You might want to try some zombie survival maps, see if you can use/convert them to nzombies. This one looks promissing for example: http://steamcommunity.com/sharedfiles/filedetails/?id=653898327

**Comment by Alig96** [comment]
If at all possible, I'd like the ones that were released previously:
- ttt_68thway_brownie_b
- ttt_forest_final
- cs_militia
- ttt_casino_b2
- de_corse
- de_crypt_cn_v1

Now you don't have to do them all, but they're the ones that I had previously had mapped. So if you're really wanting to do some, there we go :)

**Comment by minin43** [comment]
@Alig96 Yea, I'll take a look!

I may skip over the CSS maps. as I'm trying to avoid keeping things restricted to CSS owners, but myabe still.

Do you have workshop links for the rest of 'em?

**Comment by Zet0rz** [comment]
- [ttt_68thway_brownie_b](http://steamcommunity.com/sharedfiles/filedetails/?id=277354909&searchtext=ttt_68thway)
- [ttt_forest_final](http://steamcommunity.com/sharedfiles/filedetails/?id=147635981&searchtext=ttt_forest)
- [ttt_casino_b2](http://steamcommunity.com/sharedfiles/filedetails/?id=169342118&searchtext=ttt_casino)

Those are the ones I could find from that. I did make a config on Casino which was actually really cool, might use that in the official as well.

**Comment by minin43** [comment]
Thanks!

**Comment by minin43** [comment]
I've done some testing, these maps aren't very good :/

A lot of them have ladder-restricted areas, completely disallowing large sections of the map.

A lot of them also have very little "sectioned off" areas, where you'd want the zombies to spawn.

If you guys have more, post 'me here!

**Comment by Zet0rz** [comment]
I have a _great_ config on Casino, just need a good idea for what I can do with Pack-a-Punch. It needs some special objective or thing about it just like all real zombies maps, and just like what I plan to do with all official configs.

**Comment by func-octo** [comment]
Maps
zs_nacht_der_untoten
ttt_der_reise

**Comment by func-octo** [comment]
Did anyone make Die Rise yet?

**Comment by minin43** [comment]
@Zet0rz You'll have to explain what you mean with these special objectives or "map scripts," because I don't know what you mean by them and I feel like I'm missing out. Also, send me your config file for casino and I'll see if I can shoot you some ideas about it.

Also, a lot of the Nazi Zombie re-creation maps are unusable with the current nextbot zombies not being able to leap over barricades. They get stuck too easily.

**Comment by Zet0rz** [comment]
@minin43 Map Scripts essentially allows you to run code along with a single map config. You could then program anything in to make that config special. By Pack-a-Punch 'objective' I mean a special way to get to PaP. For an example, in Der Riese you need to link all teleporters. In Kino der Toten you can only teleport there temporarily. In Ascension you need to launch the rocket. In Call of the Dead it moves around with the lighthouse's light beam. And so on ...

**Comment by minin43** [comment]
So that makes logical sense, but how can someone such as myself set that up? Does it require hammer map editor, or something?

**Comment by Zet0rz** [comment]
No it requires Lua scripting skills. There'll be some handy functions, but generally it'd need you to know how to code something for gmod, like an addon or a gamemode. Another plan I had for a map with that was to make the special rounds make the lights in the map break and the map becomes fully dark.

**Comment by minin43** [comment]
I have a decent understanding of how code works. I understand most of the advanced concepts of coding, I just lack experience. But writing scripts that edit the map is new to me. Could you explain and/or write a tutorial?

**Comment by Zet0rz** [comment]
Probably will do when it gets fully released. For now, you'll probably want to look into the gamemodes own code to see what you can do. Particularly in `gamemodes/nzombies3/gamemode/mapping/sv_mapping.lua`

There's a template map script file in `lua/nzmapscripts`. Place any map script you make in there and name it the exact same as your config's .txt file, and be sure to tick Map Script in the Map Settings tool in your config. Then load the config, and the Mismatch window will ask you whether to load or not.

**Comment by minin43** [comment]
Will do

**Comment by Omnipotiontated** [comment]
@minin43 I'm currently working on a map sincere to this game mode, here's a few images so you'll get the Idea

![nzombies30005](https://cloud.githubusercontent.com/assets/18220400/14267250/3b79906c-fa94-11e5-9b62-826fb212f55d.jpg)
![nzombies30004](https://cloud.githubusercontent.com/assets/18220400/14267252/3eafef56-fa94-11e5-90f6-35d70167650c.jpg)
![nzombies30001](https://cloud.githubusercontent.com/assets/18220400/14267260/5565e5a2-fa94-11e5-8aad-685073e9e451.jpg)
That last photo was a picture of the spawn room, it's a little big atm. I plan on shrinking it down once I get the basic layout done.

**Comment by minin43** [comment]
sweet

**Comment by Zet0rz** [comment]
@minin43 Got the config I use for Casino. I really liked playing this one, maybe you can use it for playtesting as well? Just remember that you may need to edit the navlocks and navmeshes again since it requires a few areas under doors. You can use `/navflush` to clear the configs data, then redo them :P
[nz_ttt_casino_b2;High Stakes.txt](https://github.com/Zet0rz/nzombies/files/205883/nz_ttt_casino_b2.High.Stakes.txt)
It uses FAS2 weapons but you can use the mismatch system to set them to CW2 or whatever you want.

**Comment by minin43** [comment]
@Zet0rz I have the FA:S 2 weapons, it won't be a problem. I'll take a look, and maybe make a few changes :P

**Comment by Alig96** [comment]
@minin43 I never said the maps were good, they were just the ones that I did and released, and would be grateful if they were re-done.

**Comment by minin43** [comment]
@Alig96 Most of the maps would be best saved for when nexbot ladder functionality is added.
