### ISSUE TITLE
Prop Removal tool

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#84]
A new tool that allows you to mark props for removal on map cleanups. Allows you to permanently get rid of map-created props that may or may not hinder zombies and general movement.

**Comment by minin43** [comment]
sweet

**Comment by minin43** [comment]
Can this be increased in priority? Cause I've got some maps this'd be useful for and I can't work on maps without this.

**Comment by Zet0rz** [comment]
Alright, will look into this next. I am currently modelling the Hellhounds though, the models we got turned out to be not so good lol
