### ISSUE TITLE
Bowie Knife

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#86]
We'll need an upgraded melee weapons. Just like all the other original CoD weapons added, it needs to be with c_ arms and fully animated. The Bowie Knife is a one-hit kill up until round 11 (9 in BO1 and BO3).

**Comment by minin43** [comment]
Isn't this your "1-inch punch" weapon?

**Comment by Zet0rz** [comment]
http://callofduty.wikia.com/wiki/One_Inch_Punch

**Comment by minin43** [comment]
So yes?

**Comment by Zet0rz** [comment]
So no, One Inch Punch is much more powerul, waaaay too powerful to be put on a wall in any config (don't do it xD).

**Comment by minin43** [comment]
So it's supposed to be something earned through doing something on the map?

**Comment by Zet0rz** [comment]
Exactly. Pretty much map script exclusive.

**Comment by func-octo** [comment]
But if you're that one guy, you could put it on a wall buy?

**Comment by minin43** [comment]
It doesn't have a world model (unless you set one for it) so it'll show "E" on the wall. (for error, I believe)

**Comment by Zet0rz** [comment]
Actually the One Inch Punch has a world model, but it's rather weird. The "E" you're seeing isn't an E for error. It is literally _the E_ in the Error model (not anything I did, gmod itself picks the error model and the outlines just use whatever the main model is). Try holding the Weapon Buy took and pressing R on an error wall buy.

**Comment by Zet0rz** [comment]
Fully finished as of commit 6173353a5efb2d3bf29cfcccb448d3261553f146
