### ISSUE TITLE
Prediction in the Special Weapons system

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#87]
Right now the special weapons works purely on key binds and setting weapons and a bunch of timers. Using CurTime() and Think hooks it should be more predicted, as even though a player might press the button but not get the weapon instantly due to ping, CurTime() will stay synchronized and cause it to "catch up". This will require some experimentation, Move hooks might work better too.

See https://wiki.garrysmod.com/page/Prediction

**Comment by lolleko** [comment]
I am not sure we should to that right now, it's pretty much work and has very little impact. Maybe after Workshop Release?

**Comment by Zet0rz** [comment]
I have an idea of how I want to do it that could potentially also fix the grenade bug. But it's gonna be after getting the rest of the models, the content pack takes priority.

**Comment by Zet0rz** [comment]
Done in the development branch.
