### ISSUE TITLE
Zombie Animation speed thresholds to be dynamic

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#89]
Currently the zombies change ACT instantly if they cross a certain speed. For zombies set to this particular speed, they will often dip in and out causing them to constantly change animation.

The way it should be should be something more like this:
If a zombie has a speed threshold of 150 to change animation, it should only change up if the zombie goes over 170 (+20), and likewise should only change animation down if it falls below 130 (-20). The range (20) can be adjusted.

**Comment by func-octo** [comment]
Yes.

**Comment by Zet0rz** [comment]
This was done in commit 4e6b87dacfd227ac2e6bc4cb2a7dfe46d2ff3c54
