### ISSUE TITLE
Wall Buys trying to use NULL entity

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#90]
Seems to happen if it fails to create the Clientside Models. An IsValid check to see if they exist would probably work. If not, it'd either have to recreate the outlines, or cause the normal model to render (so it isn't invisible)

**Comment by Zet0rz** [comment]
This has been (hopefully) fixed in commit 6764e46b3986cf0a01b0e60d7a7eed98ee273a2f. Read its changelog to see what it does.

**Comment by minin43** [comment]
Yay! Time to test!

**Comment by Zet0rz** [comment]
Will assume fixed.
