### ISSUE TITLE
(Enhancement) Random Box Starting Location.

### ISSUE THREAD

**Issue by lmao5677** [Zet0rz/nzombies#91]
There should be a setting in the random box. The setting indicates that if the box location has been checked with the setting starting location, the box will always spawn there when someone starts a new game. Just like Der Riese, where the box is always where the power switch is.

**Comment by Zet0rz** [comment]
If we make this, it will probably be a setting of "Possible Start" so that you can have multiple. Putting this setting on only one box does what you mean, but you can also use it to make the box spawn randomly anywhere _but_ the first room.

**Comment by Zet0rz** [comment]
Commit 74fab22068764468b23fd6d1a108883365ef7051 adds this.
