### ISSUE TITLE
(Yes, Lag!) Monkey Bombs

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#92]
Very much lag happens when all zombies retarget at once. Could you maybe retarget one zombie every tick instead all at once to reduce cpu/gpu load? Thanks!

**Comment by lolleko** [comment]
Zombie targeting is completly asynchronous.

**Comment by Zet0rz** [comment]
I experimented with changing it to quickly retarget all zombies as otherwise they may ignore the monkey for up to 2 seconds (critical when in a corner), but I knew fully well it might cause lag on higher zombie counts. Looks like I should revert it.

**Comment by lolleko** [comment]
Oh lol, you did change that :D well it's about one second not 2 and idk if zombies have a instant reaction time anyways (since they are dead thinking shouldnt be taht easy for them).

**Comment by Zet0rz** [comment]
From the playtesting we had the other day we found it very unreliable. But I can definitely optimize the function by instead setting every zombie's target to this monkey (rather than running the priority enemy function), which will then later update as it would otherwise.

**Comment by Zet0rz** [comment]
Commit ea6e82dfe35ec9fb5b4cfe19622a44198a0a9732 should do this. Let me know of the results of this. In case the monkey isn't a valid target (or there's another closer by), they will just retarget back to their original valid target after those otherwise 2 seconds update time.

**Comment by func-octo** [comment]
What happens if it retargets, but then new zombies spawn?

**Comment by Zet0rz** [comment]
All Zombies run their retargeting function preriodically, so even if no zombies were hit with this retarget, they'd still target the monkey. The only thing this change really does is to cause all zombies to retarget instantly so we don't have to wait those 1-2 seconds until their next retarget. After being set to the monkey, they will continue to retarget (but just target the monkey again) as if it never happened.

**Comment by func-octo** [comment]
Cool.

**Comment by func-octo** [comment]
Do Hellhounds target the monkey, or no?

**Comment by Zet0rz** [comment]
Hellhounds are not affected by any sort of special targeting (although we should code them to target TARGET_PRIORITY_ALWAYS). And by extension, they also only ever target one player and never change until he gets downed or killed.

**Comment by minin43** [comment]
I'm fairly certain the dogs can switch targets to another player without either needing to be downed.

**Comment by Zet0rz** [comment]
Nope, they don't in the original games (maybe in some custom maps). The only time their target change is if their previous target becomes invalid for whatever reason (downing, teleporting, flying etc)

**Comment by minin43** [comment]
Probably just my imagination then

**Comment by Zet0rz** [comment]
Back to topic though, let me know the lag state of the new system and how well it is balanced. I'll close this if it's good, or keep it open to improve :P

**Comment by minin43** [comment]
Will test tonight
