### ISSUE TITLE
Improved Perk Icons

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#93]
(Pre-ShareX)
For Zet0rz

I have redone all perk icons to be cleaner. Have a look :)
https://drive.google.com/folderview?id=0B1xHaGAsFiwgSnJJeXUtaDVfSGc&usp=sharing

P.S. I haven't done speed.png or revive.png yet because of the gradients
P.S.S. Ignore the odd one out (You'll see what I mean)

**Comment by minin43** [comment]
Is the Deadshot Daquiri icon the one from CoD?

**Comment by func-octo** [comment]
Yes, I took all form the perk_icons folder and sharpened them up a LOT.

**Comment by minin43** [comment]
Ok

**Comment by Zet0rz** [comment]
I've seen them, but I'm not so sure whether to replace them in their current state. While the smudge/blur have been removed, the round parts are not really smooth. Particularly the bullet tip on Jugg, but also the guns on Mule Kick and all the rest. And I'm not even sure if the smudge/blur is actually better, since it smoothes out the texture when viewed as small as they are :/

**Comment by func-octo** [comment]
I'll see what I can do. I realized today that I forgot to smooth out jugg. :)

**Comment by func-octo** [comment]
As always, feel free to be pixel specific in your suggestions so I can do all i can to help!

**Comment by Zet0rz** [comment]
I'd say smooth out the tip of jugg, smooth out the circles around the radiation sign on PhD, smooth out the curves on the Mule Kick guns, and finally probably remake the DTap 1 icon :)
You also got the coloring of Deadshot wrong, it is green-ish grey, not black. Refer to the wiki for Zombies or the perk machine itself :P

**Comment by func-octo** [comment]
Thanks! Yeah, Photoshop bugged out and it kept using black instead of greenish gray. I must've had it set to grayscale for some reason :P

**Comment by func-octo** [comment]
Don't know if this is what you meant, but mulekickV2.png is now on drive. They are right next to each other so use arrow keys when previewing to do a comparison. Others coming sometime soon (All new ones will be labeled with a V2 since they are improvements. Also drive sorts them by name so they can be side by side.) since I have a job and school to worry about :)

**Comment by minin43** [comment]
@ScriptnLua Is the second one supposed to be worse looking? The first looks loads more sharp and nicer to look at.

**Comment by func-octo** [comment]
@minin43 Second one? Do you mean Mulekick? It looks bad when you zoom out all the way on chrome while the second one looks smooth from far away. they're meant to look nicer farther away rather than up close.

**Comment by minin43** [comment]
No, the second one looked crap from far away, imo

**Comment by Zet0rz** [comment]
Yeah the second Mule Kick icon didn't really work out as I intended lol. But no worries, we got time :P
The thing I suggest changing (from the V1 icon) is to smooth out the slightly jagged curves. Not something you would do with a blur tool, but rather zoom in a lot and use a smooth eraser. Try to make it look as clean as possible.

**Comment by func-octo** [comment]
Ok. So basically make circles become circles instead of those weird things in the trigger area. Among other things...

**Comment by func-octo** [comment]
V3 is now up. I realize that the trigger area is too far to the left. I'll have to fix that when I get home today (After 3PM). Just let me know if I am getting the right idea :)

**Comment by Zet0rz** [comment]
Yeah it's a bit better, but it became a bit blurry as well. Also Jugg is still jagged on the bullet tip. I think the best way to get a smooth perfect look would be to take an actual bullet with the same shape, give it a stroke, and use that outline as the outline (if it fits). Then erase all but the tip of that outline and merge them together. Could be an idea of how to work with it.

**Comment by func-octo** [comment]
I was using my School Issued Chromebook to draw that third mulekick just for concept. These things have bad resolution quality. I have tried that idea, but it doesn't fit. I'll make an oval for the tip and then clean it up to make it look natural. If that doesn't work, I'll find a picture of a bullet, trace it in illustrator, then give back the png. Also what does asignee do (On the right side), because you could assign me to this. Also, are you U.K. or U.S.? I am U.S.

**Comment by Zet0rz** [comment]
Central Europe. But you don't have to trace it in illustrator, you can just create a stroke of the bullet in Photoshop, create the layer based on the stroke, then mark the bullet and delete that selection from the new stroke layer. This is now an outline. Make it the same color and only take the tip. I don't know if you can find any bullets fitting the shape though.

**Comment by minin43** [comment]
@Zet0rz Mr. Zet0rz is Dutch, if I'm not mistaken. Though he doesn't sound like it.

Just a reminder these don't need to be perfect. Not very many people will look extremely closely at the icons. As long as they're there, the average gmod player won't give a rats ass.

**Comment by Zet0rz** [comment]
@minin43 I'm not Dutch, but Danish :P 

And true, the icons don't have to be perfect since they're viewed in small resolution. But maybe that will make the blurry ones we have now look more smooth? I'll have to compare them directly.

**Comment by minin43** [comment]
@Zet0rz Oh neat, my dad's side of the family is Danish.

**Comment by func-octo** [comment]
@minin43 I am 1/8 native American and 1/8 German :D

6/8 'Murica

**Comment by lolleko** [comment]
Germany (UTC + 2 / CEST) if anyone is interested lol. And we can't assign you, but it isn't that important tbh we know that you are working on this :)
