### ISSUE TITLE
What will be the default weapons?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#94]
If you look in any of my gameplay footage, or do any testing with me, you may notice I like to use CW2.0 weaponry for the guns. I just like them. But what will be the default weapon pack for the gamemode? What guns will players be using when they download the gamemode and play  by themselves, with no edits done to the gamemode? (Obviously it'd be based on what config they choose, but you still want to set a precedent).

I would suggest using CW2.0, as it's more up-to-date, it's still having features being added to it, and there's a large community of "3rd-party" creators behind it.

Otherwise there's:
-M9K
-FA:S 2.0
-GDCW
-One other I can't think of
-Some random base somebody made for 1 gun

**Comment by Zet0rz** [comment]
I definitely like CW2 the best, but the problem with it is that the default pack only has like 5 guns, and the rest you have to get individually 1 gun at a time. That can run up to become a significant amount of addons to subscribe to just you play the default. FAS2 seems better in that regard because it is only seperated into 5 packs with a good amount of weapons.

But perhaps just creating a collection and linking it would work around the problem of too many addons?

**Comment by minin43** [comment]
The base CW2.0 pack + the creator's "additional weapons" pack has almost 15 weapons, I believe. That, combined with the BO2 recreation pack for CW2.0 (which adds in 6 guns from BO2), account for most of the guns I use on my server, and that's 3 packs.

Now, I've added in a few more "flavor packs," which are mainly for me because I'm so used to the other guns that these new ones help spice things up, in a way.

I can do some more digging and maybe find some other _packs_ of CW2.0 weapons so that we can avoid a giant list of weapon downloads.

On a side note: if you add in `resource.AddWorkshop("workshop ID here")` to the shared.lua in the gamemode folder, you can set it so that it autodownloads those packs whenever you play the gamemode (for servers, you need `if SERVER then resource.AddWorkshop("*************") end` but I'm not sure about clients)

**Comment by Zet0rz** [comment]
I am not gonna AddWorkshop anything when it isn't required. You will be able to play all the default configs even without the default weapons by using the mismatch system. AddWorkshop'ing is much more for dedicated servers to do (which might by why you want to), but for addons for the general public, you never want to make them download stuff they may not need.

**Comment by minin43** [comment]
Fair enough. And "requiring" other addons for seperate configs uploaded to the workshop should work just fine.

What about the default weapons, though? There's gonna need to be one for the configs that come pre-included in the gamemode addon

**Comment by Zet0rz** [comment]
Probably CW2 if we can figure out a smart way of collecting them to make it easy. Else, FAS2.

**Comment by minin43** [comment]
You can upload the guns as a part of the game mode. Just give credit to the author, and you're protected by Steam.

**Comment by Omnipotiontated** [comment]
I was thinking the TFA CS:GO weapons. I use them and they work nicely, the wall buy outlines for them are gorgeous.

**Comment by minin43** [comment]
Are they customizable? Easy to work with? Link to the workshop page for testing?

**Comment by Zet0rz** [comment]
> You can upload the guns as a part of the game mode. Just give credit to the author, and you're protected by Steam.

Uhm no, that's not how copyright works? I can't upload anyone elses material without permission no matter what, even if I credit.

> **Do not reupload addons** - Reuploaded addons will be taken down. Search workshop before uploading. **Reuploading workshop addons is strictly forbidden, whatever the reupload reason is. ( Even if the original workshop addon was removed )**

Steam & Gmod Workshop rules. Even if I could, I wouldn't want to include any guns in this gamemode. I want to encourage as much freedom as possible. The only reason I have to chose a default pack is for my own configs in the official release lol.

**Comment by minin43** [comment]
> Uhm no, that's not how copyright works? I can't upload anyone else's material without permission no matter what, even if I credit.

The creator of CW2.0 did not and can not copyright the addon he uploaded, as it uses other people's resources. The CW2.0 pack and it's derivative addons are under no copyright protection (save packs that have files ripped from other ACTUAL copyrighted games, such as CoD- and even then not always). This means Steam will not, and I stress this because I've experienced this battle before, take down your gamemode if you have CW2.0 included in with it.

> Do not reupload addons - Reuploaded addons will be taken down. Search workshop before uploading. Reuploading workshop addons is strictly forbidden, whatever the reupload reason is. ( Even if the original workshop addon was removed )

This is only applicable to copy+paste re-uploads of addons. As long as you give due credit to the author and assume no credit of your own, as far as I can tell, Steam won't take your addon down, even if it gets reported (I had this happen to me before and I won).

Are you saying that there will be no default configuration files included in with the gamemode? Or you'll require addon subscribers to also subscribe to the CW2.0 guns as well? I'm confused as to what your whole plan as a whole is, as I'd like to remain consistent with what you're doing.

**Comment by Zet0rz** [comment]
> Or you'll require addon subscribers to also subscribe to the CW2.0 guns as well?

Do that :P

**Comment by Omnipotiontated** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=533104097

They aren't customizable if you're talking about adding sights, mags, etc. Although there are skin packs (which I don't use) and a few of the weapons allow you to add a suppressor.

They're nice and basic relieving a lot of lag if your someone with a "non to good" computer. Think of it as M9K but a lot less shittier and more optimized. They also all have their own world models.

**Comment by Zet0rz** [comment]
I am personally against using "remake" weapons as the official ones, with maybe the exception of CoD itself. So I will be much more likely to go with stuff like CW2 and FAS2.

**Comment by minin43** [comment]
While we're on the topic, you can open up the customization menu of any CW2.0 gun by pressing the default key of c, or, +context_menu. If this could somehow be disabled so players are unable to look at all of the attachments. There's also a bug about this, which I will post about soon.

**Comment by Zet0rz** [comment]
If you mean the bug of it causing you to change the weapon, then yeah, I do already know this. However as to removing it, I think I will keep it in, as when PaP'ing you actually get the attachments so that you can freely equip and unequip them. I know this isn't how CoD works, but I thought it would be nicer for players to pick which sight they want when they got them all, especially because in CoD it's pretty much only the sight changing, so you can easily re-PaP to get the one you want, but in this, it's incredibly rare to get the exact combo of attachments since there are multiple combinations. That's why I decided to "give" the attachments to players rather than just equipping them.

**Comment by minin43** [comment]
No, it's a bug with PaP where sometimes you're given the attachments after PaPing but they aren't equipped automatically.

**Comment by minin43** [comment]
I want to bump this. With the addon nearing workshop release, we need to figure out what the default weapons are. As far as I know, the official gun packs are:
- Customizable Weaponry 2.0 (base)
- Spy's Extra Customizable Weaponry 2.0 Pack
- \- Please fill in the rest @Zet0rz -

The other pack I'd suggest using is:
- Black Ops 2 Remastered Pack (for CW2.0)

We also need to find a raygun to use.

**Comment by Zet0rz** [comment]
There is now an official Weapon Pack collection here: http://steamcommunity.com/sharedfiles/filedetails/?id=673266588
These are subject to change while we're still in beta, so it is not final, but it will make it easier to get friends the necessary mods. I also need to edit the graphics (can't do that now), but I'm thinking I will go for a logo like that, but replace Nazi Zombies with nZombies.

**Comment by func-octo** [comment]
Yay! Now i don't have to deal with mismatch systems xD

**Comment by minin43** [comment]
@Zet0rz TOO MANY GUNS

OH GOD NO, TOO MANY GUNS

**Comment by Zet0rz** [comment]
I just made the pack quickly so I could play with some friends. But in my opinion, you can't have too many guns. Except the pistols ... god damn the pistols. lol

**Comment by lolleko** [comment]
I think we should add as much packs as possible, TFA would be a good addition, for example the [WW II Pack](http://steamcommunity.com/sharedfiles/filedetails/?id=434445556) is pretty good.

**Comment by func-octo** [comment]
Please minimize weapons since the more weapons the longer it takes to start gmod. Plus, it adds on to those people with 400 addons already.

**Comment by minin43** [comment]
please, Please, PLEASE.

Less is more! At this point, you've got almost 750 MB of PURELY guns be downloaded. You've got multiple packs that each have the SAME gun. Keep the guns small!!!!!!!!

**Comment by Zet0rz** [comment]
Which ones do you think are over-the-top? I just dropped all gun packs I had that I used with it in as I made it, I can definitely remove some. Already removed the pistols pack.

**Comment by minin43** [comment]
Out of the CW2.0 weapons: Keep the Khris guns (except pistols and Gauss rifle) and the base/Extra pack. The raygun is fine since that's a part of the original game, but the FA:S guns require ALL of the old FA:S packs and the rest of the guns either: aren't good/are unnecessary/don't fit.

I guess this is my opinion, but still, there's so much...

**Comment by lolleko** [comment]
I dont like FAS that much either, especially since most of the world models are broken.

**Comment by func-octo** [comment]
Yes, stick with CW as the main weapons of the gamemode.

**Comment by Omnipotiontated** [comment]
I've had this up for a while now, but it wasn't public. There seems to be a lot of tension anyways http://steamcommunity.com/sharedfiles/filedetails/?id=660636172

**Comment by func-octo** [comment]
@Omnipotiontated So many pistols xD
