### ISSUE TITLE
Delay Zombie spawning

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nzombies#97]
Even though we have the preparation phase, we'll want some more delay after the round actually sets in. A possible solution is to just delay zombie spawning, but another option is to make the Round Begin sound play earlier; making it look like a delay (and then extending the prep phase time). It may need to be further extended to make space for the "Fetch me their souls!" sound if it is a Hellhound round.

**Comment by func-octo** [comment]
I think you should extend the prep time the same amount of time as the wav sound for "Fetch me their souls" and play the begin round sound Before the extension (Ex. 10 seconds, play begin round sound, wait x amount of seconds until round begin sound is over, play FMTS sound, wait x amount of seconds until it is done playing that sound, THEN start the round.)

**Comment by minin43** [comment]
The zombies do start spawning extremely quickly. Faster than CoD does it.

**Comment by Zet0rz** [comment]
Now implemented into commit bd6b8085f66c8de93fd013b7a3ba8fd4eda218bf
It is delayed by 3 seconds, 7 if it is a Hellhound round (to give space for the sound effect). It also adds a function `Round:SetNextSpawnTime( time )` which you can use to delay whenever (used by Hellhounds to space out their spawning 2 seconds each).
